### PR TITLE
Set evm limited maximum gas

### PR DESCRIPTION
**Pull request by wangff15386**
math.MaxUint64 is too large to can not avoid an infinite loop

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/300)

### CODE REVIEW

**Comment by boqiu** [comment]
Reviewed 2 of 5 files at r3.
Review status: all files reviewed, 2 unresolved discussions (waiting on @wangff15386)

---

*[common/simple_decimal.go, line 18 at r3](https://reviewable.io/reviews/seeleteam/go-seele/300#-LFWt-2b-VOGY0ARxsbR:-LFWt-2b-VOGY0ARxsbS:b762uj7) ([raw file](https://github.com/seeleteam/go-seele/blob/e6878ad41c287b9f19c36055cb75740593ac6b02/common/simple_decimal.go#L18)):*
> ```Go
> 	SeeleToFan = big.NewInt(100000000)
> 	// MaxGasLimit evm limited maximum gas
> 	MaxGasLimit = uint64(10000000)
> ```

1) const
2) MaxTxGas or TxGasLimit

---

*[core/evm.go, line 72 at r3](https://reviewable.io/reviews/seeleteam/go-seele/300#-LFWtFbv6Lgkr78_i6jP:-LFWtFbv6Lgkr78_i6jQ:b-ohlrhr) ([raw file](https://github.com/seeleteam/go-seele/blob/e6878ad41c287b9f19c36055cb75740593ac6b02/core/evm.go#L72)):*
> ```Go
> 	receipt := &types.Receipt{TxHash: tx.Hash}
> 
> 	// Currently, use 10000000 gas to bypass ErrInsufficientBalance error and avoid overly complex contract creation or calculation.
> ```

do not expose the gas limit number in comment, since you may change it over time.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/300)*

**Comment by lucusfly** [comment]
Reviewed 2 of 5 files at r3.
Review status: all files reviewed, 2 unresolved discussions (waiting on @wangff15386 and @WTer)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/300)*

**Comment by wangff15386** [comment]
Review status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @boqiu, @lucusfly, and @WTer)

---

*[common/simple_decimal.go, line 18 at r3](https://reviewable.io/reviews/seeleteam/go-seele/300#-LFWt-2b-VOGY0ARxsbR:-LF_9WHC9Kq2xqD4y8ha:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e6878ad41c287b9f19c36055cb75740593ac6b02/common/simple_decimal.go#L18)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

1) const
2) MaxTxGas or TxGasLimit
</blockquote></details>

Done.

---

*[core/evm.go, line 72 at r3](https://reviewable.io/reviews/seeleteam/go-seele/300#-LFWtFbv6Lgkr78_i6jP:-LF_9XhfEkcmANuPRqwt:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e6878ad41c287b9f19c36055cb75740593ac6b02/core/evm.go#L72)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

do not expose the gas limit number in comment, since you may change it over time.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/300)*

**Comment by boqiu** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WTer)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/300)*

**Comment by WTer** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/300)*

**Pull request merged**
