### PR TITLE
Statedb opt: 1) record first db err; 2) add deleted flag for state obj to avoid unnecessary query from trie

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/194)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[core/state/statedb.go, line 86 at r1](https://reviewable.io/reviews/seeleteam/go-seele/194#-LD5sJOF2ZykCXHJ1vtB:-LD5sJOF2ZykCXHJ1vtC:b-a9tuey) ([raw file](https://github.com/seeleteam/go-seele/blob/6518ab68c2b0ffb8cb7f58d2c36c8692f108fa90/core/state/statedb.go#L86)):*
> ```
> setError only records the first error.
> ```
any background or purpose?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/194)*

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[core/state/stateobject.go, line 146 at r1](https://reviewable.io/reviews/seeleteam/go-seele/194#-LD5s_Yy9raJouTvF2i4:-LD5s_Yy9raJouTvF2i5:b19i1ct) ([raw file](https://github.com/seeleteam/go-seele/blob/6518ab68c2b0ffb8cb7f58d2c36c8692f108fa90/core/state/stateobject.go#L146)):*
> ```
> len(s.code) > 0
> ```
so you won't put empty code, but when will this code be empty?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/194)*

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[core/state/statedb.go, line 86 at r1](https://reviewable.io/reviews/seeleteam/go-seele/194#-LD5sJOF2ZykCXHJ1vtB:-LD5wrMxDCbnkNV1KIvJ:bcroz9t) ([raw file](https://github.com/seeleteam/go-seele/blob/6518ab68c2b0ffb8cb7f58d2c36c8692f108fa90/core/state/statedb.go#L86)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> setError only records the first error.
> ```
any background or purpose?
</blockquote></details>

This is to align the ETH EVM logic.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/194)*

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[core/state/stateobject.go, line 146 at r1](https://reviewable.io/reviews/seeleteam/go-seele/194#-LD5s_Yy9raJouTvF2i4:-LD5xVet-VCndGqNjQMR:b-gfysgm) ([raw file](https://github.com/seeleteam/go-seele/blob/6518ab68c2b0ffb8cb7f58d2c36c8692f108fa90/core/state/stateobject.go#L146)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> len(s.code) > 0
> ```
so you won't put empty code, but when will this code be empty?
</blockquote></details>

This is used by EVM interface and will never set code to nil. In other words, we don't support to delete the code of contract.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/194)*

**Comment by WTer** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/194)*

**Pull request merged**
