### PR TITLE
Fix out of range bug in downloader

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/189)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[seele/seeleprotocol.go, line 426 at r1](https://reviewable.io/reviews/seeleteam/go-seele/189#-LD05Y5ECOGg5xgeim8H:-LD05Y5F7am-iFC5cCw8:b-tu8982) ([raw file](https://github.com/seeleteam/go-seele/blob/c9df826ec5a94a2449212b8c1e3935747816c42b/seele/seeleprotocol.go#L426)):*
> ```
> if head, err = p.chain.GetStore().GetBlockHeader(hash); err != nil {
> ```
if no above code snippet you added, the hash will be invalid when something wrong.
However, this statement cannot get the correct the block header and will break,
so how you can fix the out of range bug?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/189)*

**Comment by lucusfly** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[seele/seeleprotocol.go, line 426 at r1](https://reviewable.io/reviews/seeleteam/go-seele/189#-LD05Y5ECOGg5xgeim8H:-LD0BlED0vNc1qJYJfBn:b-s5edp6) ([raw file](https://github.com/seeleteam/go-seele/blob/c9df826ec5a94a2449212b8c1e3935747816c42b/seele/seeleprotocol.go#L426)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> if head, err = p.chain.GetStore().GetBlockHeader(hash); err != nil {
> ```
if no above code snippet you added, the hash will be invalid when something wrong.
However, this statement cannot get the correct the block header and will break,
so how you can fix the out of range bug?
</blockquote></details>

before it "break handler" when got error, which stops message handler. But this error is supported in normal mode. so we should stop for loop here and keep running.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/189)*

**Comment by WTer** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/189)*

**Comment by boqiu** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/189)*

**Pull request merged**
