### PR TITLE
add http rpc

### PR DESCRIPTION
**Pull request by webbergao1**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/132)

### CODE REVIEW

**Comment by jessonzheng** [comment]
Reviewed 5 of 13 files at r1, 1 of 1 files at r2.
Review status: 6 of 13 files reviewed at latest revision, all discussions resolved.

---

*[rpc/httpserver.go, line 89 at r2](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBAM17c8lCOEnnNpIjM:-LBAM17c8lCOEnnNpIjN:b1pco4u) ([raw file](https://github.com/seeleteam/go-seele/blob/577056e01b552462acbb377716e99a5dab63fc16/rpc/httpserver.go#L89)):*
> ```Go
> }
> 
> func (h *hostFilter) ServeHTTP(w http.ResponseWriter, r *http.Request) {
> ```

better to add comments for public functions

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/132)*

**Comment by boqiu** [comment]
Review status: 6 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/node/cmd/config.go, line 44 at r2](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBAK3uW7PU1-wXM8mqH:-LBAK3uW7PU1-wXM8mqI:b7jg7qh) ([raw file](https://github.com/seeleteam/go-seele/blob/577056e01b552462acbb377716e99a5dab63fc16/cmd/node/cmd/config.go#L44)):*
> ```Go
> 
> 	// HTTPHostFilter is the whitelist of hostnames which are allowed on incoming requests.
> 	HTTPWhiteHost []string
> ```

duplicated definitions with node config, suggest to composite the node config here.

---

*[rpc/httpserver.go, line 20 at r2](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBALZqn2wc26DW-XTVS:-LBALZqn2wc26DW-XTVT:bvr43x) ([raw file](https://github.com/seeleteam/go-seele/blob/577056e01b552462acbb377716e99a5dab63fc16/rpc/httpserver.go#L20)):*
> ```Go
> 
> var (
> 	ErrInvalidHost = errors.New("Invalid host name.")
> ```

comment missed.

---

*[rpc/httpserver.go, line 56 at r2](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBAMc4N0sLT3TzS_uZw:-LBAMc4N0sLT3TzS_uZx:bxb36o8) ([raw file](https://github.com/seeleteam/go-seele/blob/577056e01b552462acbb377716e99a5dab63fc16/rpc/httpserver.go#L56)):*
> ```Go
> // CONNECT handles requests form other go rpc.Client
> func (server *HTTPServer) ServeHTTP(w http.ResponseWriter, req *http.Request) {
> 	if req.Method == "CONNECT" {
> ```

http.MethodConnect

---

*[rpc/httpserver.go, line 59 at r2](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBAMgC2331NBOgKcYaD:-LBAMgC2331NBOgKcYaE:b-kd9x6m) ([raw file](https://github.com/seeleteam/go-seele/blob/577056e01b552462acbb377716e99a5dab63fc16/rpc/httpserver.go#L59)):*
> ```Go
> 		server.Server.ServeHTTP(w, req)
> 
> 	} else if req.Method == "POST" {
> ```

http.MethodPost

---

*[rpc/httpserver.go, line 90 at r2](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBAN0Yy8o3exG5MErkX:-LBAN0Yy8o3exG5MErkY:b-bkdz36) ([raw file](https://github.com/seeleteam/go-seele/blob/577056e01b552462acbb377716e99a5dab63fc16/rpc/httpserver.go#L90)):*
> ```
> == true
> ```

redundant

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/132)*

**Comment by webbergao1** [comment]
Review status: 6 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[cmd/node/cmd/config.go, line 44 at r2](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBAK3uW7PU1-wXM8mqH:-LBAOb1K6oMCQHK0j5Pu:bc7a60u) ([raw file](https://github.com/seeleteam/go-seele/blob/577056e01b552462acbb377716e99a5dab63fc16/cmd/node/cmd/config.go#L44)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

duplicated definitions with node config, suggest to composite the node config here.
</blockquote></details>

good idea, I will do it later

---

*[rpc/httpserver.go, line 20 at r2](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBALZqn2wc26DW-XTVS:-LBAPgCu5kAQCr-l8UPt:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/577056e01b552462acbb377716e99a5dab63fc16/rpc/httpserver.go#L20)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

comment missed.
</blockquote></details>

Done.

---

*[rpc/httpserver.go, line 56 at r2](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBAMc4N0sLT3TzS_uZw:-LBAPrRR7SFfrJ3X_rju:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/577056e01b552462acbb377716e99a5dab63fc16/rpc/httpserver.go#L56)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

http.MethodConnect
</blockquote></details>

Done.

---

*[rpc/httpserver.go, line 59 at r2](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBAMgC2331NBOgKcYaD:-LBAPsAM2T4DIoxxfk7e:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/577056e01b552462acbb377716e99a5dab63fc16/rpc/httpserver.go#L59)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

http.MethodPost
</blockquote></details>

Done.

---

*[rpc/httpserver.go, line 89 at r2](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBAM17c8lCOEnnNpIjM:-LBAQVN0B1Gdr4nHv5L-:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/577056e01b552462acbb377716e99a5dab63fc16/rpc/httpserver.go#L89)):*
<details><summary><i>Previously, jessonzheng wrote…</i></summary><blockquote>

better to add comments for public functions
</blockquote></details>

Done.

---

*[rpc/httpserver.go, line 90 at r2](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBAN0Yy8o3exG5MErkX:-LBAQW-r2c4Dtkmswg8z:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/577056e01b552462acbb377716e99a5dab63fc16/rpc/httpserver.go#L90)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

> ```
> == true
> ```

redundant
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/132)*

**Comment by boqiu** [comment]
Review status: 6 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/node/cmd/config.go, line 44 at r2](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBAK3uW7PU1-wXM8mqH:-LBATedM28iGa6ziG6lH:b-9ykjn5) ([raw file](https://github.com/seeleteam/go-seele/blob/577056e01b552462acbb377716e99a5dab63fc16/cmd/node/cmd/config.go#L44)):*
<details><summary><i>Previously, webbergao1 wrote…</i></summary><blockquote>

good idea, I will do it later
</blockquote></details>

It's easy to change, suggest to refactor in this pull request.

---

*[rpc/httpserver.go, line 20 at r2](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBALZqn2wc26DW-XTVS:-LBAU8Mx0yExrjd8br8Q:b139rkd) ([raw file](https://github.com/seeleteam/go-seele/blob/577056e01b552462acbb377716e99a5dab63fc16/rpc/httpserver.go#L20)):*
<details><summary><i>Previously, webbergao1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please double check the syntax.

"is returned when the host is not in whitelist"

---

*[rpc/httpserver.go, line 59 at r3](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBAUd239wSVpZfAlFW5:-LBAUd239wSVpZfAlFW6:b-74uffd) ([raw file](https://github.com/seeleteam/go-seele/blob/a925544f26f0dc908ea097093900126a520eef03/rpc/httpserver.go#L59)):*
> ```Go
> 	if req.Method == http.MethodConnect {
> 		server.Server.ServeHTTP(w, req)
> ```

redundant blank line?

---

*[rpc/httpserver.go, line 65 at r3](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBAUnQ_0HMXIFRhKvsB:-LBAUnQ_0HMXIFRhKvsC:bu1yiil) ([raw file](https://github.com/seeleteam/go-seele/blob/a925544f26f0dc908ea097093900126a520eef03/rpc/httpserver.go#L65)):*
> ```Go
> 		server.ServeRequest(NewJsonCodec(conn))
> 
> 	} else {
> ```

switch is better than multiple if-else clauses. Anyway, it's OK to keep it as it is.

---

*[rpc/httpserver.go, line 97 at r3](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBAUsVd8Ata7itEhnSm:-LBAUsVd8Ata7itEhnSn:b-74uffu) ([raw file](https://github.com/seeleteam/go-seele/blob/a925544f26f0dc908ea097093900126a520eef03/rpc/httpserver.go#L97)):*
> ```Go
> 		http.Error(w, ErrInvalidHost.Error(), http.StatusForbidden)
> 	}
> ```

redundant blank line.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/132)*

**Comment by webbergao1** [comment]
Review status: 6 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[rpc/httpserver.go, line 20 at r2](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBALZqn2wc26DW-XTVS:-LBAaLPj3-6QdNFaBO2a:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/577056e01b552462acbb377716e99a5dab63fc16/rpc/httpserver.go#L20)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Please double check the syntax.

"is returned when the host is not in whitelist"
</blockquote></details>

Done.

---

*[rpc/httpserver.go, line 59 at r3](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBAUd239wSVpZfAlFW5:-LBA_VIwBKndbccFiRUj:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a925544f26f0dc908ea097093900126a520eef03/rpc/httpserver.go#L59)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

redundant blank line?
</blockquote></details>

Done.

---

*[rpc/httpserver.go, line 65 at r3](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBAUnQ_0HMXIFRhKvsB:-LBA_W3L8UTzr-NO2Qd_:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a925544f26f0dc908ea097093900126a520eef03/rpc/httpserver.go#L65)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

switch is better than multiple if-else clauses. Anyway, it's OK to keep it as it is.
</blockquote></details>

Done.

---

*[rpc/httpserver.go, line 97 at r3](https://reviewable.io/reviews/seeleteam/go-seele/132#-LBAUsVd8Ata7itEhnSm:-LBA_Ws_EwItmmQFDXxV:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a925544f26f0dc908ea097093900126a520eef03/rpc/httpserver.go#L97)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

redundant blank line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/132)*

**Comment by boqiu** [comment]
Reviewed 11 of 13 files at r1, 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/132)*

**Comment by boqiu** [comment]
CI failed.

---

Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/132#-:-LBTuEDk98mw_lSBb4SA:b-ref3vo)*

**Comment by jessonzheng** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/132)*

**Pull request merged**
