### PR TITLE
send different shard tx bug fix; known tx and known block should be thread safe

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/288)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @lucusfly, @WTer, @qiaozhigang, and @boqiu)

---

*[seele/peer.go, line 65 at r1](https://reviewable.io/reviews/seeleteam/go-seele/288#-LFL5ZQSDYeYuGoAZl01:-LFL5ZQSDYeYuGoAZl02:b-k9rbz4) ([raw file](https://github.com/seeleteam/go-seele/blob/a46105cb680e4b2921b9330896b6067d87a8da2f/seele/peer.go#L65)):*
> ```Go
> 
> func newPeer(version uint, p *p2p.Peer, rw p2p.MsgReadWriter, log *log.SeeleLog) (*peer, error) {
> 	knownTxsCache, err := lru.New(maxKnownTxs)
> ```

if the maxKnownTxs >0, you could panic on any error, so as to avoid handling the returned error.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/288)*

**Comment by lucusfly** [comment]
Review status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @boqiu, @WTer, and @qiaozhigang)

---

*[seele/peer.go, line 65 at r1](https://reviewable.io/reviews/seeleteam/go-seele/288#-LFL5ZQSDYeYuGoAZl01:-LFL8yVQ3OTz8-TyVRNJ:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a46105cb680e4b2921b9330896b6067d87a8da2f/seele/peer.go#L65)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

if the maxKnownTxs >0, you could panic on any error, so as to avoid handling the returned error.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/288)*

**Comment by boqiu** [comment]
Reviewed 1 of 5 files at r1, 2 of 4 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WTer and @qiaozhigang)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/288)*

**Comment by WTer** [comment]
Reviewed 5 of 5 files at r1, 2 of 4 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @qiaozhigang)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/288)*

**Pull request merged**
