### PR TITLE
Add downloader event

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/66)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[event/manager_instance.go, line 12 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/66#-L7SCrhi5uLSEOQvabao:-L7SCrhi5uLSEOQvabap:b-p1pdo7) ([raw file](https://github.com/seeleteam/go-seele/blob/6093d5f14cc2edc0961f879687464b513fc1e31d/event/manager_instance.go#L12)):*
> DownloaderStartEvent

do we need to add a InProgress event?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/66)*

**Comment by lucusfly** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[event/manager_instance.go, line 12 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/66#-L7SCrhi5uLSEOQvabao:-L7SDCA5i9OfWuO7k8Pu:btvcaiz) ([raw file](https://github.com/seeleteam/go-seele/blob/6093d5f14cc2edc0961f879687464b513fc1e31d/event/manager_instance.go#L12)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> DownloaderStartEvent

do we need to add a InProgress event?
</blockquote></details>

good suggestion, we will add it when needed later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/66)*

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[event/manager_instance.go, line 9 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/66#-L7SEMhgY2u2h-SdmgJS:-L7SEMhgY2u2h-SdmgJT:bd5ll8k) ([raw file](https://github.com/seeleteam/go-seele/blob/6093d5f14cc2edc0961f879687464b513fc1e31d/event/manager_instance.go#L9)):*
> ```Go
> 
> // BlockDownloaderEvent block download event
> var BlockDownloaderEventManager *EventManager = NewEventManager()
> ```

variable type *EventManager is unnecessary.

---

*[event/manager_instance.go, line 14 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/66#-L7SFUx2PADcLyC65DYp:-L7SFUx2PADcLyC65DYq:bsjdl22) ([raw file](https://github.com/seeleteam/go-seele/blob/6093d5f14cc2edc0961f879687464b513fc1e31d/event/manager_instance.go#L14)):*
> ```Go
> 	DownloaderStartEvent  = 0
> 	DownloaderDoneEvent   = 1
> 	DownloaderFailedEvent = 2
> ```

Better to add necessary comments that these events are used for BlockDownloaderEventManager

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/66)*

**Comment by lucusfly** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[event/manager_instance.go, line 9 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/66#-L7SEMhgY2u2h-SdmgJS:-L7SNOL5XM-zlsv0GgsH:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/6093d5f14cc2edc0961f879687464b513fc1e31d/event/manager_instance.go#L9)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

variable type *EventManager is unnecessary.
</blockquote></details>

Done.

---

*[event/manager_instance.go, line 14 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/66#-L7SFUx2PADcLyC65DYp:-L7SNQ5hbvdOEblbzCNJ:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/6093d5f14cc2edc0961f879687464b513fc1e31d/event/manager_instance.go#L14)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Better to add necessary comments that these events are used for BlockDownloaderEventManager
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/66)*

**Comment by boqiu** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/66)*

**Pull request merged**
