### PR TITLE
Add magic number for requesting blockheader and blocks while synchron…

### PR DESCRIPTION
**Pull request by qiaozhigang**
Magic number is to ensure that the sending and requesting messages are corresponding.

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/302)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @qiaozhigang, @WTer, @boqiu, and @lucusfly)

---

*[seele/define.go, line 44 at r1](https://reviewable.io/reviews/seeleteam/go-seele/302#-LFaJ8hO0hdN47gZQ-iD:-LFaJ8hO0hdN47gZQ-iE:b-op4x52) ([raw file](https://github.com/seeleteam/go-seele/blob/ea510278b8a9f7f81fa6176e981e8ea8ce02877e/seele/define.go#L44)):*
> ```
> uint32
> ```
is uint16 enough?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/302)*

**Comment by lucusfly** [comment]
Review status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @qiaozhigang, @WTer, @boqiu, and @lucusfly)

---

*[seele/download/peer.go, line 107 at r1](https://reviewable.io/reviews/seeleteam/go-seele/302#-LFaXOVF4JC1m4Z-sNC9:-LFaXOVF4JC1m4Z-sNCA:b-9jrpwi) ([raw file](https://github.com/seeleteam/go-seele/blob/ea510278b8a9f7f81fa6176e981e8ea8ce02877e/seele/download/peer.go#L107)):*
> ```Go
> func (p *peerConn) deliverMsg(msgCode uint16, msg *p2p.Message) {
> 	p.lockForWaiting.Lock()
> 	ch, ok := p.waitingMsgMap[msgCode]
> ```

why not use msgCode + magic number to deliver message?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/302)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @qiaozhigang, @WTer, @boqiu, and @lucusfly)

---

*[seele/define.go, line 44 at r1](https://reviewable.io/reviews/seeleteam/go-seele/302#-LFaJ8hO0hdN47gZQ-iD:-LFaYWKN28Suk0MTyU1R:b4uymsk) ([raw file](https://github.com/seeleteam/go-seele/blob/ea510278b8a9f7f81fa6176e981e8ea8ce02877e/seele/define.go#L44)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> uint32
> ```
is uint16 enough?
</blockquote></details>

maybe 16 bit is enough, but 32 bit is more safer

---

*[seele/download/peer.go, line 107 at r1](https://reviewable.io/reviews/seeleteam/go-seele/302#-LFaXOVF4JC1m4Z-sNC9:-LFaYrlG8X-sAX99aQKM:b-m48jc8) ([raw file](https://github.com/seeleteam/go-seele/blob/ea510278b8a9f7f81fa6176e981e8ea8ce02877e/seele/download/peer.go#L107)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

why not use msgCode + magic number to deliver message?
</blockquote></details>

maybe it's also ok, but I don't like to choose random number carefully to ignore overflow.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/302)*

**Comment by lucusfly** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @WTer and @boqiu)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/302)*

**Comment by qiaozhigang** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @WTer and @boqiu)

---

*[seele/define.go, line 44 at r1](https://reviewable.io/reviews/seeleteam/go-seele/302#-LFaJ8hO0hdN47gZQ-iD:-LFasgvc1u5HfcZYxTDY:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/d059a3303a6fa1e7fe7ac984f7a27623b035b71a/seele/define.go#L44)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

maybe 16 bit is enough, but 32 bit is more safer
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/302)*

**Comment by WTer** [comment]
Reviewed 6 of 6 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @boqiu)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/302)*

**Pull request merged**
