### PR TITLE
add rpc server

### PR DESCRIPTION
**Pull request by herove**
struct api for node
add new server

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/47)

### CODE REVIEW

**Comment by qiaozhigang** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[rpc/server.go, line 44 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/47#-L6dvN_OBAV8_p1sJst6:-L6dvN_OBAV8_p1sJst7:b-rgbb0r) ([raw file](https://github.com/seeleteam/go-seele/blob/afb2fade616e1e696427756b136564f2bed7a046/rpc/server.go#L44)):*
> ```Go
> 	rpcService := &RPCService{server}
> 	server.RegisterName(MetadataApi, rpcService)
> ```

Give some comments for this default service

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/47)*

**Comment by herove** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[rpc/server.go, line 44 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/47#-L6dvN_OBAV8_p1sJst6:-L6dzqigaKt8zl6PT0B1:bb7f2mf) ([raw file](https://github.com/seeleteam/go-seele/blob/afb2fade616e1e696427756b136564f2bed7a046/rpc/server.go#L44)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

Give some comments for this default service
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/47)*

**Comment by boqiu** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[rpc/server.go, line 12 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/47#-L6dyfDk7SgpaxhfwvFy:-L6dyfDk7SgpaxhfwvFz:b-8ulh1h) ([raw file](https://github.com/seeleteam/go-seele/blob/afb2fade616e1e696427756b136564f2bed7a046/rpc/server.go#L12)):*
> ```Go
> )
> 
> const MetadataApi = "rpc"
> ```

Comment missed for exported variable.

---

*[rpc/server_test.go, line 31 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/47#-L6e-2RY1JaKQdwneblP:-L6e-2RY1JaKQdwneblQ:bh0x2ez) ([raw file](https://github.com/seeleteam/go-seele/blob/afb2fade616e1e696427756b136564f2bed7a046/rpc/server_test.go#L31)):*
> ```Go
> }
> 
> func TestServerRegisterName(t *testing.T) {
> ```

golang recommended test method name is "Test_xxxx"

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/47)*

**Comment by lucusfly** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[rpc/server_test.go, line 31 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/47#-L6e-2RY1JaKQdwneblP:-L6e-sRmGMri4GnSatrZ:b-3o2j28) ([raw file](https://github.com/seeleteam/go-seele/blob/afb2fade616e1e696427756b136564f2bed7a046/rpc/server_test.go#L31)):*
> golang recommended test method name is "Test_xxxx"
I find golang recommended test method name is "Testxxx"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/47)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[rpc/server_test.go, line 31 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/47#-L6e-2RY1JaKQdwneblP:-L6e-hFQAWItjuuW24Qn:b-3iit8r) ([raw file](https://github.com/seeleteam/go-seele/blob/afb2fade616e1e696427756b136564f2bed7a046/rpc/server_test.go#L31)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

golang recommended test method name is "Test_xxxx"
</blockquote></details>

yes, like func Test_VBitVec_check(t *testing.T) 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/47)*

**Comment by lucusfly** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/47)*

**Comment by herove** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[rpc/server.go, line 12 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/47#-L6dyfDk7SgpaxhfwvFy:-L6e0eoPhxQl8Lkm1v7Q:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/afb2fade616e1e696427756b136564f2bed7a046/rpc/server.go#L12)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Comment missed for exported variable.
</blockquote></details>

Done.

---

*[rpc/server_test.go, line 31 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/47#-L6e-2RY1JaKQdwneblP:-L6e1Khi2kG-KuBoKvoQ:bsq2mhn) ([raw file](https://github.com/seeleteam/go-seele/blob/afb2fade616e1e696427756b136564f2bed7a046/rpc/server_test.go#L31)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

yes, like func Test_VBitVec_check(t *testing.T) 
</blockquote></details>

I found it in code style of seele. "Test cases of methods must use format Text_<Struct>_<Method>", I'll fix it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/47)*

**Comment by herove** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[rpc/server_test.go, line 31 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/47#-L6e-2RY1JaKQdwneblP:-L6e1Vx30M0fPpFcwJld:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/afb2fade616e1e696427756b136564f2bed7a046/rpc/server_test.go#L31)):*
<details><summary><i>Previously, herove (Leihao Zhou) wrote…</i></summary><blockquote>

I found it in code style of seele. "Test cases of methods must use format Text_<Struct>_<Method>", I'll fix it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/47)*

**Comment by qiaozhigang** [comment]
Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/47)*

**Comment by boqiu** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/47)*

**Comment by lucusfly** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/47)*

**Pull request merged**
