### PR TITLE
add shard id in PeerInfo

### PR DESCRIPTION
**Pull request by webbergao1**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/267)

### CODE REVIEW

**Comment by WTer** [comment]
nice to add/modify unit tests

---

Review status: 0 of 1 files reviewed, all discussions resolved (waiting on @wuliaodw88, @boqiu, and @lucusfly)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/267#-:-LEgxxYC9WW95H1RUwLp:bmq9ys6)*

**Comment by WTer** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wuliaodw88, @boqiu, and @lucusfly)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/267)*

**Comment by boqiu** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wuliaodw88 and @lucusfly)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/267)*

**Comment by WTer** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wuliaodw88 and @lucusfly)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/267)*

**Comment by WTer** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wuliaodw88 and @lucusfly)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/267)*

**Pull request merged**
