### PR TITLE
Change some methods to pointer type in common

### PR DESCRIPTION
**Pull request by WTer**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/351)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @WTer, @qqtou, @ypenghui6, @boqiu, @wangff15386, @yanllearnn, and @lucusfly)

---

*[common/hash.go, line 90 at r1](https://reviewable.io/reviews/seeleteam/go-seele/351#-LGUaAAcESJZeLkVdp9A:-LGUaAAcESJZeLkVdp9B:b-v27t2h) ([raw file](https://github.com/seeleteam/go-seele/blob/525a7d0c02ca7edfa9a68966a82b4fb7d0273de3/common/hash.go#L90)):*
> ```Go
> 
> // MarshalText marshals the Hash to HEX string.
> func (a *Hash) MarshalText() ([]byte, error) {
> ```

please make sure if it works for json marshal

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/351)*

**Comment by lucusfly** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @WTer, @qqtou, @ypenghui6, @boqiu, @wangff15386, and @yanllearnn)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/351)*

**Comment by WTer** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @WTer, @qqtou, @ypenghui6, @boqiu, @wangff15386, and @yanllearnn)

---

*[common/hash.go, line 90 at r1](https://reviewable.io/reviews/seeleteam/go-seele/351#-LGUaAAcESJZeLkVdp9A:-LGUitmE5vII_f_7sl4F:b-le8ttr) ([raw file](https://github.com/seeleteam/go-seele/blob/525a7d0c02ca7edfa9a68966a82b4fb7d0273de3/common/hash.go#L90)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

please make sure if it works for json marshal
</blockquote></details>

nice, added more unit tests, please  see the Test_MarshalAndUnmarshalText()

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/351)*

**Comment by WTer** [comment]
Review status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @lucusfly, @qqtou, @ypenghui6, @boqiu, @wangff15386, and @yanllearnn)

---

*[common/hash.go, line 90 at r1](https://reviewable.io/reviews/seeleteam/go-seele/351#-LGUaAAcESJZeLkVdp9A:-LGUk18GBaSTWX58vrj9:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/525a7d0c02ca7edfa9a68966a82b4fb7d0273de3/common/hash.go#L90)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

nice, added more unit tests, please  see the Test_MarshalAndUnmarshalText()
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/351)*

**Comment by lucusfly** [comment]
Review status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @lucusfly, @WTer, @qqtou, @ypenghui6, @boqiu, @wangff15386, and @yanllearnn)

---

*[common/hash_test.go, line 68 at r2](https://reviewable.io/reviews/seeleteam/go-seele/351#-LGY0SNdAd9iFDfsqodJ:-LGY0SNdAd9iFDfsqodK:bw67um6) ([raw file](https://github.com/seeleteam/go-seele/blob/f52e19643c6516bb0cdad1a9de185db00acf3d21/common/hash_test.go#L68)):*
> ```
> json.Marshal(hash.ToHex())
> ```

use json.Marshal(hash) instead, they should get the same result.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/351)*

**Comment by WTer** [comment]
Review status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @lucusfly, @qqtou, @ypenghui6, @boqiu, @wangff15386, and @yanllearnn)

---

*[common/hash_test.go, line 68 at r2](https://reviewable.io/reviews/seeleteam/go-seele/351#-LGY0SNdAd9iFDfsqodJ:-LGYs4dV22yasllVmDdo:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f52e19643c6516bb0cdad1a9de185db00acf3d21/common/hash_test.go#L68)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> json.Marshal(hash.ToHex())
> ```

use json.Marshal(hash) instead, they should get the same result.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/351)*

**Pull request merged**
