### PR TITLE
Task contract evm

### PR DESCRIPTION
**Pull request by boqiu**
Integrate EVM into Seele to support ETH Solidity on main chain. This is iteration 1 that porting the ETH VM to Seele and apply some underlying data structures of Seele (e.g. address, hash)

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/134)

### CODE REVIEW

**Comment by jessonzheng** [comment]
Reviewed 1 of 64 files at r1.
Review status: 1 of 64 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/134)*

**Comment by jessonzheng** [comment]
Reviewed 1 of 64 files at r1.
Review status: 2 of 64 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/134)*

**Comment by jessonzheng** [comment]
Reviewed 1 of 64 files at r1.
Review status: 3 of 64 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/134)*

**Comment by jessonzheng** [comment]
Reviewed 1 of 64 files at r1.
Review status: 4 of 64 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/134)*

**Comment by jessonzheng** [comment]
Reviewed 1 of 64 files at r1.
Review status: 5 of 64 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/134)*

**Comment by jessonzheng** [comment]
Reviewed 1 of 64 files at r1.
Review status: 6 of 64 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/134)*

**Comment by jessonzheng** [comment]
Reviewed 1 of 64 files at r1.
Review status: 7 of 64 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/134)*

**Comment by jessonzheng** [comment]
Reviewed 1 of 64 files at r1.
Review status: 8 of 64 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/134)*

**Comment by jessonzheng** [comment]
Reviewed 1 of 64 files at r1.
Review status: 9 of 64 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/134)*

**Comment by jessonzheng** [comment]
Reviewed 1 of 64 files at r1.
Review status: 10 of 64 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/134)*

**Comment by jessonzheng** [comment]
Reviewed 1 of 64 files at r1.
Review status: 11 of 64 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/134)*

**Comment by jessonzheng** [comment]
Reviewed 1 of 64 files at r1.
Review status: 12 of 64 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/134)*

**Comment by jessonzheng** [comment]
Reviewed 41 of 64 files at r1.
Review status: 53 of 64 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/134)*

**Comment by lucusfly** [comment]
could you copy EVM first and send your changes in another review? So we could see if it is compatible with EVM.

---

Review status: 62 of 64 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/134#-:-LBEnW8M202Lb2b8fnZK:b-gxqfwy)*

**Pull request closed without merging**
