### PR TITLE
add genesis config for initialize account balance

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/158)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[cmd/node/cmd/config.go, line 24 at r1](https://reviewable.io/reviews/seeleteam/go-seele/158#-LC86Xl55ZkNjYseRsNl:-LC85UW5-GvKLk30Mldo:b-zfiq5f) ([raw file](https://github.com/seeleteam/go-seele/blob/f44278b1c815e2f2b248edad5dd0244555719210/cmd/node/cmd/config.go#L24)):*
> ```Go
> // Note to add enough comments for every field
> type Config struct {
> 	// The name of the node	+	node.Config
> ```

copy error?

---

*[cmd/node/cmd/config.go, line 64 at r1](https://reviewable.io/reviews/seeleteam/go-seele/158#-LC86Zru-ptEFixma7Ic:-LC86Zru-ptEFixma7Id:b-5tn2z6) ([raw file](https://github.com/seeleteam/go-seele/blob/f44278b1c815e2f2b248edad5dd0244555719210/cmd/node/cmd/config.go#L64)):*
> ```Go
> }
> 
> type GenesisInfo struct {
> ```

comment missed for exported type?

---

*[cmd/node/cmd/config.go, line 95 at r1](https://reviewable.io/reviews/seeleteam/go-seele/158#-LC86jcS04vqIujQk6p9:-LC86jcS04vqIujQk6pA:bvr44e) ([raw file](https://github.com/seeleteam/go-seele/blob/f44278b1c815e2f2b248edad5dd0244555719210/cmd/node/cmd/config.go#L95)):*
> ```Go
> }
> 
> func GetGenesisInfoFromFile(filepath string) (GenesisInfo, error) {
> ```

comment missed?

---

*[core/genesis.go, line 37 at r1](https://reviewable.io/reviews/seeleteam/go-seele/158#-LC8AojwD3cCtRHsMdzR:-LC8AojwD3cCtRHsMdzS:bncumjh) ([raw file](https://github.com/seeleteam/go-seele/blob/f44278b1c815e2f2b248edad5dd0244555719210/core/genesis.go#L37)):*
> ```Go
> // DefaultGenesis returns the default genesis block in the blockchain.
> func GetGenesis(accounts map[common.Address]*big.Int) *Genesis {
> 	statedb, err := getStateDB(accounts)
> ```

how about move the panic together with NewStateDB?

---

*[core/genesis.go, line 98 at r1](https://reviewable.io/reviews/seeleteam/go-seele/158#-LC8BOMICGBbV-Gf4qIG:-LC8BOMICGBbV-Gf4qIH:b-omot8g) ([raw file](https://github.com/seeleteam/go-seele/blob/f44278b1c815e2f2b248edad5dd0244555719210/core/genesis.go#L98)):*
> ```Go
> func getStateDB(accounts map[common.Address]*big.Int) (*state.Statedb, error) {
> 	statedb, err := state.NewStatedb(common.EmptyHash, nil)
> 	if err != nil {
> ```

panic on err and remove the error in return list?

---

*[core/genesis.go, line 102 at r1](https://reviewable.io/reviews/seeleteam/go-seele/158#-LC8BWEx4WGAh4Jdm7nh:-LC8BWEx4WGAh4Jdm7ni:bt4wqcr) ([raw file](https://github.com/seeleteam/go-seele/blob/f44278b1c815e2f2b248edad5dd0244555719210/core/genesis.go#L102)):*
> ```Go
> 	}
> 
> 	if accounts != nil {
> ```

AFAIK, the nil check is unnecessary.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/158)*

**Comment by lucusfly** [comment]
Review status: 0 of 16 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[cmd/node/cmd/config.go, line 24 at r1](https://reviewable.io/reviews/seeleteam/go-seele/158#-LC86Xl55ZkNjYseRsNl:-LC8CaBXBqYpZ1XcARzu:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f44278b1c815e2f2b248edad5dd0244555719210/cmd/node/cmd/config.go#L24)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

copy error?
</blockquote></details>

Done.

---

*[cmd/node/cmd/config.go, line 64 at r1](https://reviewable.io/reviews/seeleteam/go-seele/158#-LC86Zru-ptEFixma7Ic:-LC8DvETExUA1NL87oQP:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f44278b1c815e2f2b248edad5dd0244555719210/cmd/node/cmd/config.go#L64)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

comment missed for exported type?
</blockquote></details>

Done.

---

*[cmd/node/cmd/config.go, line 95 at r1](https://reviewable.io/reviews/seeleteam/go-seele/158#-LC86jcS04vqIujQk6p9:-LC8DviK1aOB923k-sie:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f44278b1c815e2f2b248edad5dd0244555719210/cmd/node/cmd/config.go#L95)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

comment missed?
</blockquote></details>

Done.

---

*[core/genesis.go, line 102 at r1](https://reviewable.io/reviews/seeleteam/go-seele/158#-LC8BWEx4WGAh4Jdm7nh:-LC8F4RWCge4YSlw93ra:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f44278b1c815e2f2b248edad5dd0244555719210/core/genesis.go#L102)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

AFAIK, the nil check is unnecessary.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/158)*

**Comment by lucusfly** [comment]
Review status: 0 of 16 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[core/genesis.go, line 37 at r1](https://reviewable.io/reviews/seeleteam/go-seele/158#-LC8AojwD3cCtRHsMdzR:-LC8Fjgi18Dl8wN_03Hj:b-5w329t) ([raw file](https://github.com/seeleteam/go-seele/blob/f44278b1c815e2f2b248edad5dd0244555719210/core/genesis.go#L37)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

how about move the panic together with NewStateDB?
</blockquote></details>

will do it in another change

---

*[core/genesis.go, line 98 at r1](https://reviewable.io/reviews/seeleteam/go-seele/158#-LC8BOMICGBbV-Gf4qIG:-LC8Ff0TDfZDONaFsNXq:b-5w329t) ([raw file](https://github.com/seeleteam/go-seele/blob/f44278b1c815e2f2b248edad5dd0244555719210/core/genesis.go#L98)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

panic on err and remove the error in return list?
</blockquote></details>

will do it in another change

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/158)*

**Comment by boqiu** [comment]
Reviewed 14 of 16 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/158)*

**Comment by WTer** [comment]
Reviewed 14 of 16 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/158)*

**Pull request merged**
