### PR TITLE
Add log file support

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/77)

### CODE REVIEW

**Comment by WTer** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/77)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[common/constant.go, line 2 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/77#-L7bgJfqoVpFmqdUqqpU:-L7bgJfqoVpFmqdUqqpV:b9d735c) ([raw file](https://github.com/seeleteam/go-seele/blob/e679af285011102ba96da282c8837b3e26e03c49/common/constant.go#L2)):*
> ```Go
> /**
> *  @file
> ```

What is constant.go used for? In my mind, it's better to put GetTempFolder() in file.go, which contains all file related operations.

---

*[common/constant.go, line 18 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/77#-L7bgre1uIN6TiTGRfsv:-L7bgre1uIN6TiTGRfsw:bwnes9e) ([raw file](https://github.com/seeleteam/go-seele/blob/e679af285011102ba96da282c8837b3e26e03c49/common/constant.go#L18)):*
> ```Go
> 
> func init() {
> 	tempFolder = filepath.Join(os.TempDir(), "SeeleTemp")
> ```

could merge together with tempFolder declaration.

---

*[common/file.go, line 12 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/77#-L7bhL9VH0fSjapp0B23:-L7bhL9VH0fSjapp0B24:bvr43x) ([raw file](https://github.com/seeleteam/go-seele/blob/e679af285011102ba96da282c8837b3e26e03c49/common/file.go#L12)):*
> ```Go
> )
> 
> func IsFileOrFolderExist(fileOrFolder string) bool {
> ```

comment missed.

---

*[common/file.go, line 14 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/77#-L7bh3rb9DxmlnzwZnk_:-L7bh3rb9DxmlnzwZnka:bb67vcv) ([raw file](https://github.com/seeleteam/go-seele/blob/e679af285011102ba96da282c8837b3e26e03c49/common/file.go#L14)):*
> ```Go
> func IsFileOrFolderExist(fileOrFolder string) bool {
> 	if _, err := os.Stat(fileOrFolder); os.IsNotExist(err) {
> 		return false
> ```

return os.IsNotExist(err)

---

*[log/log.go, line 19 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/77#-L7biD6BN0xXyKQKcLTS:-L7biD6BN0xXyKQKcLTT:b-gd6l5h) ([raw file](https://github.com/seeleteam/go-seele/blob/e679af285011102ba96da282c8837b3e26e03c49/log/log.go#L19)):*
> ```Go
> 
> var (
> 	logFolder = filepath.Join(common.GetTempFolder(), "Log")
> ```

Just for test purpose at this moment? If so, suggest to add necessary comment.

Otherwise, temp folder is not the right place to put Seele logs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/77)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[common/constant.go, line 2 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/77#-L7bgJfqoVpFmqdUqqpU:-L7cO4qjkMpJ-H9_mf9P:b-8bkg5p) ([raw file](https://github.com/seeleteam/go-seele/blob/e679af285011102ba96da282c8837b3e26e03c49/common/constant.go#L2)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

What is constant.go used for? In my mind, it's better to put GetTempFolder() in file.go, which contains all file related operations.
</blockquote></details>

It is where we store constant parameters, keep them in a file is better to maintain.

---

*[common/constant.go, line 18 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/77#-L7bgre1uIN6TiTGRfsv:-L7cOKAG_ZoUw0siDXob:b-qeg77m) ([raw file](https://github.com/seeleteam/go-seele/blob/e679af285011102ba96da282c8837b3e26e03c49/common/constant.go#L18)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

could merge together with tempFolder declaration.
</blockquote></details>

I think they are the same:)

---

*[common/file.go, line 12 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/77#-L7bhL9VH0fSjapp0B23:-L7cOQv34s478AlEcL0j:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e679af285011102ba96da282c8837b3e26e03c49/common/file.go#L12)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

comment missed.
</blockquote></details>

Done.

---

*[common/file.go, line 14 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/77#-L7bh3rb9DxmlnzwZnk_:-L7cOklPZoCC-XRlaAqI:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e679af285011102ba96da282c8837b3e26e03c49/common/file.go#L14)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

return os.IsNotExist(err)
</blockquote></details>

Done.

---

*[log/log.go, line 19 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/77#-L7biD6BN0xXyKQKcLTS:-L7cOm0fDF39_E_4VSGW:b-9izud8) ([raw file](https://github.com/seeleteam/go-seele/blob/e679af285011102ba96da282c8837b3e26e03c49/log/log.go#L19)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Just for test purpose at this moment? If so, suggest to add necessary comment.

Otherwise, temp folder is not the right place to put Seele logs.
</blockquote></details>

It is not for test. It's the default folder for log. It may not be the right place, we could change it later if we find a better solution.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/77)*

**Comment by boqiu** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/constant.go, line 2 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/77#-L7bgJfqoVpFmqdUqqpU:-L7cQ70DeNbLp9o8azJ3:b-pmzinq) ([raw file](https://github.com/seeleteam/go-seele/blob/e679af285011102ba96da282c8837b3e26e03c49/common/constant.go#L2)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

It is where we store constant parameters, keep them in a file is better to maintain.
</blockquote></details>

In the manner of OO design, it is not a good practice to put many uncorrelated constants together. So still suggest to move the tempFolder variable to file.go

---

*[common/constant.go, line 18 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/77#-L7bgre1uIN6TiTGRfsv:-L7cQxVjfgWclb-H0zkk:b-x91krv) ([raw file](https://github.com/seeleteam/go-seele/blob/e679af285011102ba96da282c8837b3e26e03c49/common/constant.go#L18)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

I think they are the same:)
</blockquote></details>

Either is OK, but less code always better:)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/77)*

**Comment by lucusfly** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/constant.go, line 2 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/77#-L7bgJfqoVpFmqdUqqpU:-L7cat52keCQYUBdgFQk:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e679af285011102ba96da282c8837b3e26e03c49/common/constant.go#L2)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

In the manner of OO design, it is not a good practice to put many uncorrelated constants together. So still suggest to move the tempFolder variable to file.go
</blockquote></details>

Done.

---

*[common/constant.go, line 18 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/77#-L7bgre1uIN6TiTGRfsv:-L7catld7v33QmPXirf1:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e679af285011102ba96da282c8837b3e26e03c49/common/constant.go#L18)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Either is OK, but less code always better:)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/77)*

**Comment by boqiu** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/77)*

**Pull request merged**
