### PR TITLE
change staticNodes type

### PR DESCRIPTION
**Pull request by ypenghui6**
when first connect staticNodes, we don't know the staticNodes'ID； even,  we don't have to know.

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/271)

### CODE REVIEW

**Comment by boqiu** [comment]
Reviewed 10 of 12 files at r1, 2 of 2 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @boqiu, @WTer, and @lucusfly)

---

*[p2p/discovery/udp.go, line 305 at r1](https://reviewable.io/reviews/seeleteam/go-seele/271#-LEiJ5ra5aUu0a7HpTr3:-LEiUjcI3r6lEOpSiRAg:bspy5l3) ([raw file](https://github.com/seeleteam/go-seele/blob/d118ef9fd6f66c268a59d00dca85f4519060cb4a/p2p/discovery/udp.go#L305)):*
<details><summary><i>Previously, ypenghui6 (ypenghui6) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I can still see some dup codes in if..else.. body.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/271)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[p2p/discovery/udp.go, line 306 at r2](https://reviewable.io/reviews/seeleteam/go-seele/271#-LEjAp0S-2dhzNFEecB7:-LEjAp0S-2dhzNFEecB8:byrfg26) ([raw file](https://github.com/seeleteam/go-seele/blob/b5a1abf5e3b43bb9c21717afd64af62286b99b95/p2p/discovery/udp.go#L306)):*
> ```Go
> 						callback(p, r, el, pendingList)
> 						break
> 					} else if p.from.ID == r.fromId {
> ```

I think you could use udp address to distinguish all reply message.

---

*[p2p/discovery/udp.go, line 427 at r2](https://reviewable.io/reviews/seeleteam/go-seele/271#-LEjA3ir6asnZ0dWjBij:-LEjA3ir6asnZ0dWjBik:b-7q7oya) ([raw file](https://github.com/seeleteam/go-seele/blob/b5a1abf5e3b43bb9c21717afd64af62286b99b95/p2p/discovery/udp.go#L427)):*
> ```
> u.log.Debug("ping pong with id: %s, with address: %s", u.trustNodes[i].ID.ToHex(), u.trustNodes[i].IP)
> ```

1. the id info is useless.
2. you need print different messages for different case.
3. you missed the feature that keep add trust nodes when disconnecting.

---

*[p2p/discovery/udp.go, line 505 at r2](https://reviewable.io/reviews/seeleteam/go-seele/271#-LEjAcpP1lCbIfX_3Gi5:-LEjAcpP1lCbIfX_3Gi6:b5zuelt) ([raw file](https://github.com/seeleteam/go-seele/blob/b5a1abf5e3b43bb9c21717afd64af62286b99b95/p2p/discovery/udp.go#L505)):*
> ```Go
> 			continue
> 		}
> 		u.trustNodes = append(u.trustNodes, n)
> ```

they are not trust nodes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/271)*

**Comment by ypenghui6** [comment]
Review status: 10 of 12 files reviewed, 4 unresolved discussions (waiting on @boqiu, @lucusfly, and @WTer)

---

*[p2p/discovery/udp.go, line 305 at r1](https://reviewable.io/reviews/seeleteam/go-seele/271#-LEiJ5ra5aUu0a7HpTr3:-LElkbTt8Nnyd6aPLGso:b32w0x) ([raw file](https://github.com/seeleteam/go-seele/blob/d118ef9fd6f66c268a59d00dca85f4519060cb4a/p2p/discovery/udp.go#L305)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

I can still see some dup codes in if..else.. body.
</blockquote></details>

OK

---

*[p2p/discovery/udp.go, line 306 at r2](https://reviewable.io/reviews/seeleteam/go-seele/271#-LEjAp0S-2dhzNFEecB7:-LElh5qs8vy_6F6w0Cn2:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/b5a1abf5e3b43bb9c21717afd64af62286b99b95/p2p/discovery/udp.go#L306)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

I think you could use udp address to distinguish all reply message.
</blockquote></details>

Done.

---

*[p2p/discovery/udp.go, line 427 at r2](https://reviewable.io/reviews/seeleteam/go-seele/271#-LEjA3ir6asnZ0dWjBij:-LEljNwk5Snjj36oYsmy:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/b5a1abf5e3b43bb9c21717afd64af62286b99b95/p2p/discovery/udp.go#L427)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> u.log.Debug("ping pong with id: %s, with address: %s", u.trustNodes[i].ID.ToHex(), u.trustNodes[i].IP)
> ```

1. the id info is useless.
2. you need print different messages for different case.
3. you missed the feature that keep add trust nodes when disconnecting.
</blockquote></details>

Done.

---

*[p2p/discovery/udp.go, line 505 at r2](https://reviewable.io/reviews/seeleteam/go-seele/271#-LEjAcpP1lCbIfX_3Gi5:-LElmzOHEBO6E-q7Nox3:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/b5a1abf5e3b43bb9c21717afd64af62286b99b95/p2p/discovery/udp.go#L505)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

they are not trust nodes.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/271)*

**Comment by lucusfly** [comment]
Reviewed 8 of 12 files at r1, 1 of 2 files at r3, 2 of 3 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WTer)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/271)*

**Pull request merged**
