### PR TITLE
Fix panic bug in download module

### PR DESCRIPTION
**Pull request by qiaozhigang**
Fix panic bug in download module

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/324)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @qiaozhigang)

---

*[seele/seeleprotocol.go, line 525 at r1](https://reviewable.io/reviews/seeleteam/go-seele/324#-LFv6BFl6wmkBtjh_jnI:-LFv6BFl6wmkBtjh_jnJ:b9bcymf) ([raw file](https://github.com/seeleteam/go-seele/blob/6b93758b7ff8e5982b8bc0754c7162cac1e33fc7/seele/seeleprotocol.go#L525)):*
> ```Go
> 				hash, err := p.chain.GetStore().GetBlockHash(curNum)
> 				if err != nil {
> 					p.log.Error("get error when get block hash by height. err: %s, height:%d", err, curNum)
> ```

why did you delete this log?

---

*[seele/download/peer.go, line 79 at r1](https://reviewable.io/reviews/seeleteam/go-seele/324#-LFv6IME5kPf5sOIBjWE:-LFv6IME5kPf5sOIBjWF:b-m0ery0) ([raw file](https://github.com/seeleteam/go-seele/blob/189363d96bcebc083d4e454e3b9e17976a5f8ba6/seele/download/peer.go#L79)):*
> ```
>  msgCode
> ```

use codeToStr method.

---

*[seele/download/peer.go, line 89 at r1](https://reviewable.io/reviews/seeleteam/go-seele/324#-LFv6MhXD3QCthqc07Rr:-LFv6MhXD3QCthqc07Rs:bx0h6w) ([raw file](https://github.com/seeleteam/go-seele/blob/189363d96bcebc083d4e454e3b9e17976a5f8ba6/seele/download/peer.go#L89)):*
> ```
>  msgCode
> ```
use codeToStr method.

---

*[seele/download/peer.go, line 106 at r1](https://reviewable.io/reviews/seeleteam/go-seele/324#-LFv61dF21i2SrHSvKgv:-LFv61dF21i2SrHSvKgw:b-7cnbps) ([raw file](https://github.com/seeleteam/go-seele/blob/189363d96bcebc083d4e454e3b9e17976a5f8ba6/seele/download/peer.go#L106)):*
> ```
> p.log.Debug("peerConn.deliverMsg msgCode=%d pid=%s", msgCode, p.peerID)
> ```

this is explosion log. we should suppress it.

---

*[seele/download/peer.go, line 109 at r1](https://reviewable.io/reviews/seeleteam/go-seele/324#-LFv5z5-7B_iJVhhIQxW:-LFv5z5-7B_iJVhhIQxX:b-qgeqad) ([raw file](https://github.com/seeleteam/go-seele/blob/189363d96bcebc083d4e454e3b9e17976a5f8ba6/seele/download/peer.go#L109)):*
> ```
> Debug
> ```

Error?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/324)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @qiaozhigang and @lucusfly)

---

*[seele/seeleprotocol.go, line 525 at r1](https://reviewable.io/reviews/seeleteam/go-seele/324#-LFv6BFl6wmkBtjh_jnI:-LFv9HecDX_7PuYq9mVS:b-2hboom) ([raw file](https://github.com/seeleteam/go-seele/blob/6b93758b7ff8e5982b8bc0754c7162cac1e33fc7/seele/seeleprotocol.go#L525)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

why did you delete this log?
</blockquote></details>

it's not error, and prints so many logs sometimes.

---

*[seele/download/peer.go, line 106 at r1](https://reviewable.io/reviews/seeleteam/go-seele/324#-LFv61dF21i2SrHSvKgv:-LFv9kzn1VT818x-EIya:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/189363d96bcebc083d4e454e3b9e17976a5f8ba6/seele/download/peer.go#L106)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> p.log.Debug("peerConn.deliverMsg msgCode=%d pid=%s", msgCode, p.peerID)
> ```

this is explosion log. we should suppress it.
</blockquote></details>

ok

---

*[seele/download/peer.go, line 109 at r1](https://reviewable.io/reviews/seeleteam/go-seele/324#-LFv5z5-7B_iJVhhIQxW:-LFv9ng066Q9qfOlmYI9:b-fr9kdf) ([raw file](https://github.com/seeleteam/go-seele/blob/189363d96bcebc083d4e454e3b9e17976a5f8ba6/seele/download/peer.go#L109)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> Debug
> ```

Error?
</blockquote></details>

not error, can change to info

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/324)*

**Comment by lucusfly** [comment]
Review status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @lucusfly and @qiaozhigang)

---

*[seele/seeleprotocol.go, line 525 at r1](https://reviewable.io/reviews/seeleteam/go-seele/324#-LFv6BFl6wmkBtjh_jnI:-LFvKNyp1gT2aHlYPcsA:bm98xbf) ([raw file](https://github.com/seeleteam/go-seele/blob/6b93758b7ff8e5982b8bc0754c7162cac1e33fc7/seele/seeleprotocol.go#L525)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

it's not error, and prints so many logs sometimes.
</blockquote></details>

keep the error info

---

*[seele/seeleprotocol.go, line 516 at r2](https://reviewable.io/reviews/seeleteam/go-seele/324#-LFvKJd74PkjpvME4roY:-LFvKJd74PkjpvME4roZ:b-mii6pm) ([raw file](https://github.com/seeleteam/go-seele/blob/13cdb6d72e2ec96a8f107f5fabb6bd37c63f0694/seele/seeleprotocol.go#L516)):*
> ```
> query.Amount
> ```

maxHeight

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/324)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @lucusfly)

---

*[seele/seeleprotocol.go, line 525 at r1](https://reviewable.io/reviews/seeleteam/go-seele/324#-LFv6BFl6wmkBtjh_jnI:-LFvRbUIB5S0P6Ww1_H_:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/6b93758b7ff8e5982b8bc0754c7162cac1e33fc7/seele/seeleprotocol.go#L525)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

keep the error info
</blockquote></details>

ok

---

*[seele/seeleprotocol.go, line 516 at r2](https://reviewable.io/reviews/seeleteam/go-seele/324#-LFvKJd74PkjpvME4roY:-LFvQoCE8MLICSW6aidf:b3kre) ([raw file](https://github.com/seeleteam/go-seele/blob/13cdb6d72e2ec96a8f107f5fabb6bd37c63f0694/seele/seeleprotocol.go#L516)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> query.Amount
> ```

maxHeight
</blockquote></details>

?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/324)*

**Comment by lucusfly** [comment]
Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/324)*

**Pull request merged**
