### PR TITLE
When stop the miner, close chan instead of send msgs to chan according to thread num

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/294)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @boqiu, @WTer, and @lucusfly)

---

*[miner/miner.go, line 155 at r1](https://reviewable.io/reviews/seeleteam/go-seele/294#-LFSDhPR6NKc_W0wx0RQ:-LFSDhPR6NKc_W0wx0RR:b-52p0r2) ([raw file](https://github.com/seeleteam/go-seele/blob/0a5f81231eb4a20071e7ae1c4d023b5a908f4066/miner/miner.go#L155)):*
> ```Go
> func (miner *Miner) Close() {
> 	close(miner.stopChan)
> 	close(miner.recv)
> ```

keep this method. we need to close recv.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/294)*

**Comment by WTer** [comment]
Review status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @boqiu, @WTer, and @lucusfly)

---

*[miner/miner.go, line 95 at r1](https://reviewable.io/reviews/seeleteam/go-seele/294#-LFSWjPZ0W56hZpjdU_C:-LFSWjPZ0W56hZpjdU_D:bq54qlb) ([raw file](https://github.com/seeleteam/go-seele/blob/8bf571236bfbc8a13575dfc5d25841a7f4a11fda/miner/miner.go#L95)):*
> ```
> threads int
> ```
how about changing the int to uint?

---

*[miner/miner.go, line 126 at r1](https://reviewable.io/reviews/seeleteam/go-seele/294#-LFSYv1lB2JhgRI6Sbgj:-LFSYv1lB2JhgRI6Sbgk:b4toukl) ([raw file](https://github.com/seeleteam/go-seele/blob/8bf571236bfbc8a13575dfc5d25841a7f4a11fda/miner/miner.go#L126)):*
> ```
> miner.stopChan = make(chan struct{}, 1)
> ```
seems you can also initialize recv here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/294)*

**Comment by WTer** [comment]
Review status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @boqiu, @WTer, and @lucusfly)

---

*[miner/miner.go, line 159 at r1](https://reviewable.io/reviews/seeleteam/go-seele/294#-LFS_jAbA28WcieqgQqf:-LFS_jAbA28WcieqgQqg:b7fkre3) ([raw file](https://github.com/seeleteam/go-seele/blob/8bf571236bfbc8a13575dfc5d25841a7f4a11fda/miner/miner.go#L159)):*
> ```
> miner.wg.Wait()
> ```
Currently the stopChan's buffer size is 1, when threads > 1,  we send the stop request,  you closed the stopChan before any of miner threads recv the message, so wa.Wait will hang ever?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/294)*

**Comment by boqiu** [comment]
Review status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @lucusfly, @boqiu, and @WTer)

---

*[miner/miner.go, line 95 at r1](https://reviewable.io/reviews/seeleteam/go-seele/294#-LFSWjPZ0W56hZpjdU_C:-LFVFP3a0kZpgpUni1WZ:brs3ujh) ([raw file](https://github.com/seeleteam/go-seele/blob/8bf571236bfbc8a13575dfc5d25841a7f4a11fda/miner/miner.go#L95)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> threads int
> ```
how about changing the int to uint?
</blockquote></details>

Unnecessary, but we could improve the cmd usage in another PR.

---

*[miner/miner.go, line 126 at r1](https://reviewable.io/reviews/seeleteam/go-seele/294#-LFSYv1lB2JhgRI6Sbgj:-LFVFmlc8nEOHn0CV5UE:bcvr72k) ([raw file](https://github.com/seeleteam/go-seele/blob/8bf571236bfbc8a13575dfc5d25841a7f4a11fda/miner/miner.go#L126)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> miner.stopChan = make(chan struct{}, 1)
> ```
seems you can also initialize recv here.
</blockquote></details>

recv channel is not closed in Stop(), so do not init it here.

---

*[miner/miner.go, line 155 at r1](https://reviewable.io/reviews/seeleteam/go-seele/294#-LFSDhPR6NKc_W0wx0RQ:-LFVGKlg5SbbcoF5eiP6:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/0a5f81231eb4a20071e7ae1c4d023b5a908f4066/miner/miner.go#L155)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

keep this method. we need to close recv.
</blockquote></details>

Done.

---

*[miner/miner.go, line 159 at r1](https://reviewable.io/reviews/seeleteam/go-seele/294#-LFS_jAbA28WcieqgQqf:-LFVG-Lf5HG3-Q3rlK1l:bm33357) ([raw file](https://github.com/seeleteam/go-seele/blob/8bf571236bfbc8a13575dfc5d25841a7f4a11fda/miner/miner.go#L159)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> miner.wg.Wait()
> ```
Currently the stopChan's buffer size is 1, when threads > 1,  we send the stop request,  you closed the stopChan before any of miner threads recv the message, so wa.Wait will hang ever?
</blockquote></details>

close the stopChan will notify all related threads to break out of for loop, so here Wait() should just wait for a very short time. (e.g. < 1ms)

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/294)*

**Comment by WTer** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @lucusfly)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/294)*

**Comment by lucusfly** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/294)*

**Pull request merged**
