### PR TITLE
refine p2p part code to make it more clear and easier to use (will refine protocol part later)

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/87)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/node/cmd/test.go, line 55 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/87#-L81krWJVW8uSaQqMH6u:-L81krWJVW8uSaQqMH6v:b-jd4doo) ([raw file](https://github.com/seeleteam/go-seele/blob/42df9213af0096e114d255da00bd9d9f2d923313/cmd/node/cmd/test.go#L55)):*
> ```Go
> 			common.Deserialize(message.Payload, &msg)
> 			//fmt.Printf("myProtocol readmsg, code:%d, peer:%s, msg:%s\n", message.Code,
> 			//	message.CurPeer.Node.GetUDPAddr(), msg)
> ```

comment for temporal build pass, will refine it in another review

---

*[cmd/node/cmd/test.go, line 71 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/87#-L81l-Mx734cVIDxlwig:-L81l-Mx734cVIDxlwih:b-jd4doo) ([raw file](https://github.com/seeleteam/go-seele/blob/42df9213af0096e114d255da00bd9d9f2d923313/cmd/node/cmd/test.go#L71)):*
> ```Go
> 	//for peer := range p.peers {
> 	//	peer.SendMsg(&p.Protocol, 100, []string{"Hello", "world"})
> 	//}
> ```

comment for temporal build pass, will refine it in another review

---

*[p2p/peer.go, line 47 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/87#-L81l4e9K8cqKiLNbNKE:-L81l4e9K8cqKiLNbNKF:b-c6flxk) ([raw file](https://github.com/seeleteam/go-seele/blob/c7620afd072d05a74c7fbb8c5774743678331243/p2p/peer.go#L47)):*
> ```Go
> 	// add peer to protocols
> 	var (
> 		writeErr = make(chan error, 1)
> ```

remove it for not using,  will implement it later

---

*[p2p/protocol.go, line 36 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/87#-L81lL5frSBW8HsIV08i:-L81lL5frSBW8HsIV08j:ba1xewh) ([raw file](https://github.com/seeleteam/go-seele/blob/42df9213af0096e114d255da00bd9d9f2d923313/p2p/protocol.go#L36)):*
> ```Go
> 	// any protocol-level error (such as an I/O error) that is
> 	// encountered.
> 	run func(peer *Peer, rw MsgReadWriter) error
> ```

will implement run later

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/87)*

**Comment by boqiu** [comment]
Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[p2p/conn.go, line 47 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/87#-L81tLCCCiotjJ6NT-D2:-L81tLCCCiotjJ6NT-D3:bhgm2q6) ([raw file](https://github.com/seeleteam/go-seele/blob/42df9213af0096e114d255da00bd9d9f2d923313/p2p/conn.go#L47)):*
> Message

*Message to avoid value copy?

---

*[p2p/conn.go, line 51 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/87#-L81tRuQ05HfWeZ6ozv_:-L81tRuQ05HfWeZ6ozva:bl9v3ga) ([raw file](https://github.com/seeleteam/go-seele/blob/42df9213af0096e114d255da00bd9d9f2d923313/p2p/conn.go#L51)):*
> ```Go
> 	defer c.rmutux.Unlock()
> 
> 	headbuff := make([]byte, 6)
> ```

const variable instead of magic number?

---

*[p2p/conn.go, line 71 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/87#-L81u-OuhJZrPKTA42t1:-L81u-OuhJZrPKTA42t2:b-dh52ua) ([raw file](https://github.com/seeleteam/go-seele/blob/42df9213af0096e114d255da00bd9d9f2d923313/p2p/conn.go#L71)):*
> SendMsg

typo: WriteMsg

---

*[p2p/message.go, line 36 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/87#-L81uRRuyECsyKSeGmhj:-L81uRRuyECsyKSeGmhk:bxihrs0) ([raw file](https://github.com/seeleteam/go-seele/blob/42df9213af0096e114d255da00bd9d9f2d923313/p2p/message.go#L36)):*
> ```Go
> 
> type MsgReader interface {
> 	ReadMsg() (Message, error)
> ```

Necessary comment as the WriteMsg() below is preferred:)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/87)*

**Comment by WTer** [comment]
Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[p2p/conn.go, line 48 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/87#-L81v3oVD-y4Dj8DwpiK:-L81v3oVD-y4Dj8DwpiL:b-y3thhr) ([raw file](https://github.com/seeleteam/go-seele/blob/42df9213af0096e114d255da00bd9d9f2d923313/p2p/conn.go#L48)):*
> c.rmutux.Lock()

do we need to lock the whole func?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/87)*

**Comment by WTer** [comment]
Review status: 0 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[p2p/conn.go, line 48 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/87#-L81v3oVD-y4Dj8DwpiK:-L81vQazB6nLx8DIN2M9:b8nivlh) ([raw file](https://github.com/seeleteam/go-seele/blob/42df9213af0096e114d255da00bd9d9f2d923313/p2p/conn.go#L48)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> c.rmutux.Lock()

do we need to lock the whole func?
</blockquote></details>

I suppose you want to make sure the data to be read only once, right?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/87)*

**Comment by lucusfly** [comment]
Review status: 0 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[p2p/conn.go, line 47 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/87#-L81tLCCCiotjJ6NT-D2:-L85zwnw4YCLActqq767:b-3k74up) ([raw file](https://github.com/seeleteam/go-seele/blob/42df9213af0096e114d255da00bd9d9f2d923313/p2p/conn.go#L47)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

> Message

*Message to avoid value copy?
</blockquote></details>

Message should always be copied.

---

*[p2p/conn.go, line 48 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/87#-L81v3oVD-y4Dj8DwpiK:-L86-35wFAug-OOPniG3:ba1e5pt) ([raw file](https://github.com/seeleteam/go-seele/blob/42df9213af0096e114d255da00bd9d9f2d923313/p2p/conn.go#L48)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

I suppose you want to make sure the data to be read only once, right?
</blockquote></details>

the lock is for network tcp connection, not for any data

---

*[p2p/conn.go, line 51 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/87#-L81tRuQ05HfWeZ6ozv_:-L86-x8zA075N70QAphI:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/42df9213af0096e114d255da00bd9d9f2d923313/p2p/conn.go#L51)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

const variable instead of magic number?
</blockquote></details>

Done.

---

*[p2p/conn.go, line 71 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/87#-L81u-OuhJZrPKTA42t1:-L860-xd8ju6GiQ30k2M:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/42df9213af0096e114d255da00bd9d9f2d923313/p2p/conn.go#L71)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

> SendMsg

typo: WriteMsg
</blockquote></details>

Done.

---

*[p2p/message.go, line 36 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/87#-L81uRRuyECsyKSeGmhj:-L860PeZ_gtfRn6R6uIL:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/42df9213af0096e114d255da00bd9d9f2d923313/p2p/message.go#L36)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Necessary comment as the WriteMsg() below is preferred:)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/87)*

**Comment by WTer** [comment]
Reviewed 4 of 7 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/87)*

**Comment by boqiu** [comment]
Reviewed 4 of 7 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/87)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/node/cmd/test.go, line 55 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/87#-L81krWJVW8uSaQqMH6u:-L86Vh65NQcsx9MjEzMJ:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/42df9213af0096e114d255da00bd9d9f2d923313/cmd/node/cmd/test.go#L55)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

comment for temporal build pass, will refine it in another review
</blockquote></details>

Done.

---

*[cmd/node/cmd/test.go, line 71 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/87#-L81l-Mx734cVIDxlwig:-L86VhZBO0LOnGeXLCAl:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/42df9213af0096e114d255da00bd9d9f2d923313/cmd/node/cmd/test.go#L71)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

comment for temporal build pass, will refine it in another review
</blockquote></details>

Done.

---

*[p2p/peer.go, line 47 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/87#-L81l4e9K8cqKiLNbNKE:-L86ViDjqQqnlQ7LY03r:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/c7620afd072d05a74c7fbb8c5774743678331243/p2p/peer.go#L47)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

remove it for not using,  will implement it later
</blockquote></details>

Done.

---

*[p2p/protocol.go, line 36 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/87#-L81lL5frSBW8HsIV08i:-L86VieiYIKHPX-3QCjP:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/42df9213af0096e114d255da00bd9d9f2d923313/p2p/protocol.go#L36)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

will implement run later
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/87)*

**Pull request merged**
