### PR TITLE
add default account in genesis block

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/98)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---

*[core/blockchain_test.go, line 85 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/98#-L94AwRy526A80QTmL4e:-L94AwRy526A80QTmL4f:bpnxj3w) ([raw file](https://github.com/seeleteam/go-seele/blob/d51eec3fdd9f9cfa6030cb0b66b92d4a7d4e9557/core/blockchain_test.go#L85)):*
> ```
> assert.Equal(t, err, ErrBlockTxsHashMismatch)
> ```
I suppose no any tx in genesisBlock, right? 
if yes, you set txHash as empty:
newBlock.Header.TxHash = common.EmptyHash

would not affect the result.

---

*[core/genesis_test.go, line 34 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/98#-L948mVQ8dRo8DQ-MbQf:-L948mVQ8dRo8DQ-MbQg:b-qty77u) ([raw file](https://github.com/seeleteam/go-seele/blob/d51eec3fdd9f9cfa6030cb0b66b92d4a7d4e9557/core/genesis_test.go#L34)):*
> ```
> os.RemoveAll(dir)
> ```
do we need to make sure it always be executed? if errors happened in Close(),  it may be skipped.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/98)*

**Comment by WTer** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[core/blockchain_test.go, line 111 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/98#-L94CLJ61Gr5FEZEPVCw:-L94CLJ61Gr5FEZEPVCx:b-or16bi) ([raw file](https://github.com/seeleteam/go-seele/blob/d51eec3fdd9f9cfa6030cb0b66b92d4a7d4e9557/core/blockchain_test.go#L111)):*
> ```
> currentBlock
> ```
just curious, currentBlock is public member, so why its name starts with lowercase?

---

*[core/genesis.go, line 39 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/98#-L94D0LN4fgMQQDiU724:-L94D0LN4fgMQQDiU725:b-9a5i24) ([raw file](https://github.com/seeleteam/go-seele/blob/d51eec3fdd9f9cfa6030cb0b66b92d4a7d4e9557/core/genesis.go#L39)):*
> ```
> // TODO define default accounts in genesis block
> ```
you already added 3 default accounts, so remove it?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/98)*

**Comment by boqiu** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[core/blockchain_test.go, line 111 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/98#-L94CLJ61Gr5FEZEPVCw:-L94FmV88LW7Xh3GIkxO:b-awezeg) ([raw file](https://github.com/seeleteam/go-seele/blob/d51eec3fdd9f9cfa6030cb0b66b92d4a7d4e9557/core/blockchain_test.go#L111)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> currentBlock
> ```
just curious, currentBlock is public member, so why its name starts with lowercase?
</blockquote></details>

No, it's private member.

---

*[core/genesis.go, line 39 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/98#-L94D0LN4fgMQQDiU724:-L94FwS0EeZEh4wcrgoR:b-gxqt4p) ([raw file](https://github.com/seeleteam/go-seele/blob/d51eec3fdd9f9cfa6030cb0b66b92d4a7d4e9557/core/genesis.go#L39)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> // TODO define default accounts in genesis block
> ```
you already added 3 default accounts, so remove it?
</blockquote></details>

test data, not official accounts.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/98)*

**Comment by WTer** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/98)*

**Pull request merged**
