### PR TITLE
Add api for send tx; fix bugs;

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/120)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[cmd/client/cmd/getbalance.go, line 37 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/120#-L9sfV79D2kZd83GP1r2:-L9sfV79D2kZd83GP1r3:b-p7o5w8) ([raw file](https://github.com/seeleteam/go-seele/blob/3d705207cd94a0ea0f51da80fa16edbef2a99035/cmd/client/cmd/getbalance.go#L37)):*
> ```Go
> 		var address *common.Address
> 		if account == nil || *account == "" {
> 			address = nil
> ```

If the account is invalid, why not print error message and return?

---

*[cmd/client/cmd/getinfo.go, line 16 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/120#-L9sg2OU9fCvnkYsKD-l:-L9sg2OU9fCvnkYsKD-m:b-gjjc8n) ([raw file](https://github.com/seeleteam/go-seele/blob/3d705207cd94a0ea0f51da80fa16edbef2a99035/cmd/client/cmd/getinfo.go#L16)):*
> ```
> getcoinbase
> ```

getinfo command. Moreover, "getMinderInfo" is better to understand.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/120)*

**Comment by lucusfly** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cmd/client/cmd/getbalance.go, line 37 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/120#-L9sfV79D2kZd83GP1r2:-L9sr4s5ERnANS11KE93:b13dvco) ([raw file](https://github.com/seeleteam/go-seele/blob/3d705207cd94a0ea0f51da80fa16edbef2a99035/cmd/client/cmd/getbalance.go#L37)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

If the account is invalid, why not print error message and return?
</blockquote></details>

By default (don't specify account) it will get coinbase balance. And if the account is invalid, we will show error message.

---

*[cmd/client/cmd/getinfo.go, line 16 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/120#-L9sg2OU9fCvnkYsKD-l:-L9srXPw62EPZ0CQZuGB:b-wtvo5i) ([raw file](https://github.com/seeleteam/go-seele/blob/3d705207cd94a0ea0f51da80fa16edbef2a99035/cmd/client/cmd/getinfo.go#L16)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

> ```
> getcoinbase
> ```

getinfo command. Moreover, "getMinderInfo" is better to understand.
</blockquote></details>

I just want to keep it short :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/120)*

**Comment by boqiu** [comment]
Reviewed 8 of 11 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/120)*

**Comment by WTer** [comment]
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---

*[miner/miner.go, line 46 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/120#-L9t82Y2DwY3mxrrp11p:-L9t82Y2DwY3mxrrp11q:b-lx5pvw) ([raw file](https://github.com/seeleteam/go-seele/blob/3dcb5bcca56b614e10949dd03b032aacd844ef19/miner/miner.go#L46)):*
> ```
> isFirstDownloader
> ```
nice to add comments to explain why add this member

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/120)*

**Comment by WTer** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[miner/miner.go, line 104 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/120#-L9t9hnN0z08xHGEfqXP:-L9t9hnN0z08xHGEfqXQ:ba70vhq) ([raw file](https://github.com/seeleteam/go-seele/blob/3dcb5bcca56b614e10949dd03b032aacd844ef19/miner/miner.go#L104)):*
> ```
> atomic.StoreInt32(&miner.isFirstDownloader, 0)
> ```
for DownloaderFailedEvent, miner want to retry, however isFirstDownloader already be set to 0,  which means no choice to enter downloadEventCallback, 
since "if atomic.LoadInt32(&miner.isFirstDownloader) == 0 { return}",

so am i understand right?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/120)*

**Comment by lucusfly** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[miner/miner.go, line 46 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/120#-L9t82Y2DwY3mxrrp11p:-L9tFJlE7K3Qp2Z52piP:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/3dcb5bcca56b614e10949dd03b032aacd844ef19/miner/miner.go#L46)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> isFirstDownloader
> ```
nice to add comments to explain why add this member
</blockquote></details>

Done.

---

*[miner/miner.go, line 104 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/120#-L9t9hnN0z08xHGEfqXP:-L9tFKBZEDcfpuOpY-Fj:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/3dcb5bcca56b614e10949dd03b032aacd844ef19/miner/miner.go#L104)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> atomic.StoreInt32(&miner.isFirstDownloader, 0)
> ```
for DownloaderFailedEvent, miner want to retry, however isFirstDownloader already be set to 0,  which means no choice to enter downloadEventCallback, 
since "if atomic.LoadInt32(&miner.isFirstDownloader) == 0 { return}",

so am i understand right?

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/120)*

**Comment by WTer** [comment]
Reviewed 8 of 11 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/120)*

**Comment by boqiu** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/120)*

**Comment by herove** [comment]
Reviewed 8 of 11 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/120)*

**Pull request merged**
