### PR TITLE
metric add some points

### PR DESCRIPTION
**Pull request by ypenghui6**
1 add disk io points
2 add seele process cpu points
3 change transmission frequency

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/339)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 77 files reviewed, 1 unresolved discussion (waiting on @ypenghui6, @WTer, @boqiu, and @lucusfly)

---

*[metrics/runtimecpu.go, line 14 at r1](https://reviewable.io/reviews/seeleteam/go-seele/339#-LG6DaCk5m1B3T0bf-p1:-LG6DaCk5m1B3T0bf-p2:bh9z59d) ([raw file](https://github.com/seeleteam/go-seele/blob/804d4e7cc37a1b1198f8bc66e57fc46c094a8922/metrics/runtimecpu.go#L14)):*
> ```
> metricsSeeleCputGauge
> ```
what's difference between it and metricsCputGauge?

and Cput, what's meaning of this 't'?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/339)*

**Comment by WTer** [comment]
Review status: 0 of 77 files reviewed, 2 unresolved discussions (waiting on @ypenghui6, @WTer, @boqiu, and @lucusfly)

---

*[metrics/runtimecpu.go, line 30 at r1](https://reviewable.io/reviews/seeleteam/go-seele/339#-LG6Drz86RutWh__NB7B:-LG6Drz86RutWh__NB7C:b-cegabd) ([raw file](https://github.com/seeleteam/go-seele/blob/804d4e7cc37a1b1198f8bc66e57fc46c094a8922/metrics/runtimecpu.go#L30)):*
> ```
> // process.test
> ```
?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/339)*

**Comment by ypenghui6** [comment]
Review status: 0 of 78 files reviewed, 2 unresolved discussions (waiting on @WTer, @ypenghui6, @boqiu, and @lucusfly)

---

*[metrics/runtimecpu.go, line 14 at r1](https://reviewable.io/reviews/seeleteam/go-seele/339#-LG6DaCk5m1B3T0bf-p1:-LG8SqcV8kMazrN4yvOe:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/804d4e7cc37a1b1198f8bc66e57fc46c094a8922/metrics/runtimecpu.go#L14)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> metricsSeeleCputGauge
> ```
what's difference between it and metricsCputGauge?

and Cput, what's meaning of this 't'?
</blockquote></details>

Done.

---

*[metrics/runtimecpu.go, line 30 at r1](https://reviewable.io/reviews/seeleteam/go-seele/339#-LG6Drz86RutWh__NB7B:-LG8TGSeBl8b7QHyNSOl:b-zaw1lf) ([raw file](https://github.com/seeleteam/go-seele/blob/804d4e7cc37a1b1198f8bc66e57fc46c094a8922/metrics/runtimecpu.go#L30)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> // process.test
> ```
?
</blockquote></details>

It will cost a lot time , when add a UT; it will better to have a test in local, 

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/339)*

**Comment by lucusfly** [comment]
Reviewed 1 of 3 files at r3, 2 of 3 files at r7, 1 of 73 files at r10, 72 of 72 files at r11, 2 of 2 files at r12.
Review status: all files reviewed, 4 unresolved discussions (waiting on @WTer, @ypenghui6, and @boqiu)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/339)*

**Comment by ypenghui6** [comment]
Review status: 75 of 78 files reviewed, 4 unresolved discussions (waiting on @lucusfly, @WTer, @ypenghui6, and @boqiu)

---

*[metrics/runtimecpu.go, line 36 at r9](https://reviewable.io/reviews/seeleteam/go-seele/339#-LG9-bkXBfrBzkwX2RtZ:-LG91Kwp2ouLooGGP4-y:b-1907pc) ([raw file](https://github.com/seeleteam/go-seele/blob/37853a22584f93c469a8e47190ca8164e75315fd/metrics/runtimecpu.go#L36)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

what does the interval mean? I don't think it is refresh time.
</blockquote></details>

a duration time of  monitor cpu

---

*[metrics/runtimedisk.go, line 11 at r9](https://reviewable.io/reviews/seeleteam/go-seele/339#-LG8LOJT4isrXuTzTkcg:-LG91KE1EHdykOV4E3Tn:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/37853a22584f93c469a8e47190ca8164e75315fd/metrics/runtimedisk.go#L11)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

code style
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/339)*

**Comment by lucusfly** [comment]
Review status: 75 of 78 files reviewed, 4 unresolved discussions (waiting on @lucusfly, @WTer, @ypenghui6, and @boqiu)

---

*[common/constant.go, line 25 at r13](https://reviewable.io/reviews/seeleteam/go-seele/339#-LGKs-Pd3WAenlmbwrCT:-LGKs-Pe-Cv_GTvyiDDK:bzcoh5d) ([raw file](https://github.com/seeleteam/go-seele/blob/d4f0439d99899021246117071a79ce1ef43baebe/common/constant.go#L25)):*
> ```
> RefreshTime
> ```

rename to MetricsRefreshTime

---

*[common/constant.go, line 28 at r13](https://reviewable.io/reviews/seeleteam/go-seele/339#-LGKs7Fk6Y7nJorFa2Ms:-LGKs7Fk6Y7nJorFa2Mt:bxyeyyx) ([raw file](https://github.com/seeleteam/go-seele/blob/d4f0439d99899021246117071a79ce1ef43baebe/common/constant.go#L28)):*
> ```
> IntervalTime
> ```

rename to CPUMetricsIntervalTime

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/339)*

**Comment by ypenghui6** [comment]
Review status: 75 of 78 files reviewed, 4 unresolved discussions (waiting on @lucusfly, @WTer, and @boqiu)

---

*[common/constant.go, line 25 at r13](https://reviewable.io/reviews/seeleteam/go-seele/339#-LGKs-Pd3WAenlmbwrCT:-LGL42Fu9xeZYdgn58Sm:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/d4f0439d99899021246117071a79ce1ef43baebe/common/constant.go#L25)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> RefreshTime
> ```

rename to MetricsRefreshTime
</blockquote></details>

Done.

---

*[common/constant.go, line 28 at r13](https://reviewable.io/reviews/seeleteam/go-seele/339#-LGKs7Fk6Y7nJorFa2Ms:-LGL40dVEl9XYuu4tY8Y:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/d4f0439d99899021246117071a79ce1ef43baebe/common/constant.go#L28)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> IntervalTime
> ```

rename to CPUMetricsIntervalTime
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/339)*

**Comment by ypenghui6** [comment]
Review status: 75 of 78 files reviewed, 4 unresolved discussions (waiting on @lucusfly, @WTer, @ypenghui6, and @boqiu)

---

*[metrics/runtimecpu.go, line 30 at r1](https://reviewable.io/reviews/seeleteam/go-seele/339#-LG6Drz86RutWh__NB7B:-LGL4SZp6moioUAUON1E:b-vbpgqo) ([raw file](https://github.com/seeleteam/go-seele/blob/804d4e7cc37a1b1198f8bc66e57fc46c094a8922/metrics/runtimecpu.go#L30)):*
<details><summary><i>Previously, ypenghui6 (ypenghui6) wrote…</i></summary><blockquote>

It will cost a lot time , when add a UT; it will better to have a test in local, 
</blockquote></details>

It will work hard but get little result Refer to the go native CPU monitoring method。

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/339)*

**Comment by lucusfly** [comment]
Reviewed 1 of 3 files at r13, 2 of 2 files at r14, 1 of 1 files at r15.
Review status: all files reviewed, 2 unresolved discussions (waiting on @WTer and @boqiu)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/339)*

**Pull request closed without merging**
