### PR TITLE
many code improvements. see descriptions

### PR DESCRIPTION
**Pull request by lucusfly**
add handler for rpc client
move account info to a separate file
use private key instead of keystore for tools
add more detail info for get tps
fix multi thread bug
change block transaction number and tx pool limit

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/259)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---

*[cmd/client/cmd/cmdconfig.go, line 21 at r1](https://reviewable.io/reviews/seeleteam/go-seele/259#-LEU-3PvD6fGm5SiCq5B:-LEU-3PvD6fGm5SiCq5C:b-kfx2v8) ([raw file](https://github.com/seeleteam/go-seele/blob/8973fdf959f2d33303b9bdffe3ee1d1d162bde58/cmd/client/cmd/cmdconfig.go#L21)):*
> ```
> Handler
> ```

OnComplete?

---

*[core/blockchain.go, line 28 at r1](https://reviewable.io/reviews/seeleteam/go-seele/259#-LEU10PTBUiWUfREor7O:-LEU0TW-Buuf7CMBQ9wu:b2xrgm6) ([raw file](https://github.com/seeleteam/go-seele/blob/8973fdf959f2d33303b9bdffe3ee1d1d162bde58/core/blockchain.go#L28)):*
> ```Go
> 	futureBlockLimit int64 = 10
> 
> 	// block transaction number limit, 1000 transaction is about 1.28MB
> ```

1) 1000 transactions are ...
2) 1.28 Mb

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/259)*

**Comment by WTer** [comment]
nice.

---

Review status: 0 of 25 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/259#-:-LEV0N0k-ozLhUcoSzJg:b-7m74ok)*

**Comment by WTer** [comment]
Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/259)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/client/cmd/cmdconfig.go, line 21 at r1](https://reviewable.io/reviews/seeleteam/go-seele/259#-LEU-3PvD6fGm5SiCq5B:-LEXHVe-2Uydfy2JDRfY:b-hu9txu) ([raw file](https://github.com/seeleteam/go-seele/blob/8973fdf959f2d33303b9bdffe3ee1d1d162bde58/cmd/client/cmd/cmdconfig.go#L21)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> Handler
> ```

OnComplete?
</blockquote></details>

This function is used to handle result value. I think handler is better.

---

*[core/blockchain.go, line 28 at r1](https://reviewable.io/reviews/seeleteam/go-seele/259#-LEU10PTBUiWUfREor7O:-LEXI63-ED1KLnTQ-S0R:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/8973fdf959f2d33303b9bdffe3ee1d1d162bde58/core/blockchain.go#L28)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

1) 1000 transactions are ...
2) 1.28 Mb
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/259)*

**Comment by boqiu** [comment]
Reviewed 24 of 25 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/259)*

**Pull request merged**
