### PR TITLE
add get tps api; get tps tool support; fix some bugs

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/256)

### CODE REVIEW

**Comment by WTer** [comment]
Reviewed 9 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/256)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[cmd/tool/cmd/gettps.go, line 39 at r1](https://reviewable.io/reviews/seeleteam/go-seele/256#-LESDHimAVqrLkHxxi8Y:-LESDHimAVqrLkHxxi8Z:b-sutvih) ([raw file](https://github.com/seeleteam/go-seele/blob/bed3645bbc5d07a120c79a944866584a95245b37/cmd/tool/cmd/gettps.go#L39)):*
> ```Go
> 
> 			fmt.Printf("sum tps is %d, real tps is %d\n", sum, sum/600)
> 			time.Sleep(10 * time.Second)
> ```

allow user to specify the sleep interval?

---

*[cmd/tool/cmd/root.go, line 41 at r1](https://reviewable.io/reviews/seeleteam/go-seele/256#-LESEbQo0jIqnEBk1jm7:-LESEbQp63pi4iccAMyL:b-ecltwc) ([raw file](https://github.com/seeleteam/go-seele/blob/bed3645bbc5d07a120c79a944866584a95245b37/cmd/tool/cmd/root.go#L41)):*
> ```Go
> 
> func init() {
> 	rootCmd.PersistentFlags().StringVarP(&serveList, "server", "s", "127.0.0.1:55027", "server list for requesting and submit, split by ;")
> ```

better to figure out that only monitor the last server if multiple servers in the same shard specified.

---

*[cmd/tool/cmd/sendtx.go, line 93 at r1](https://reviewable.io/reviews/seeleteam/go-seele/256#-LESF0I18L4Dw1MJeKRU:-LESF0I18L4Dw1MJeKRV:brwd1kw) ([raw file](https://github.com/seeleteam/go-seele/blob/bed3645bbc5d07a120c79a944866584a95245b37/cmd/tool/cmd/sendtx.go#L93)):*
> ```Go
> 			}
> 
> 			time.Sleep(time.Microsecond * 50)
> ```

allow user to specify the sleep interval will help to test.

---

*[seele/api_debug.go, line 78 at r1](https://reviewable.io/reviews/seeleteam/go-seele/256#-LESGK4V96QoIodDlyB9:-LESGK4V96QoIodDlyBA:btjfmk4) ([raw file](https://github.com/seeleteam/go-seele/blob/bed3645bbc5d07a120c79a944866584a95245b37/seele/api_debug.go#L78)):*
> ```Go
> }
> 
> func (api *PrivateDebugAPI) GetTPS(input interface{}, result *uint64) error {
> ```

Cache the data will improve the query perf, even though it's a debug API.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/256)*

**Comment by boqiu** [comment]
Reviewed 9 of 10 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/256)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/tool/cmd/gettps.go, line 39 at r1](https://reviewable.io/reviews/seeleteam/go-seele/256#-LESDHimAVqrLkHxxi8Y:-LESIC5wAJW0a4ybusz2:b-qx5a8d) ([raw file](https://github.com/seeleteam/go-seele/blob/bed3645bbc5d07a120c79a944866584a95245b37/cmd/tool/cmd/gettps.go#L39)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

allow user to specify the sleep interval?
</blockquote></details>

It is related with block generate time. And I didn't see the necessary, so just keep it.

---

*[cmd/tool/cmd/root.go, line 41 at r1](https://reviewable.io/reviews/seeleteam/go-seele/256#-LESEbQo0jIqnEBk1jm7:-LESIec98LfsX9_Kwsvp:b-vvoegz) ([raw file](https://github.com/seeleteam/go-seele/blob/bed3645bbc5d07a120c79a944866584a95245b37/cmd/tool/cmd/root.go#L41)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

better to figure out that only monitor the last server if multiple servers in the same shard specified.
</blockquote></details>

that is what I do now :)

---

*[cmd/tool/cmd/sendtx.go, line 93 at r1](https://reviewable.io/reviews/seeleteam/go-seele/256#-LESF0I18L4Dw1MJeKRU:-LESLxmB1auy1ODNZcaQ:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/bed3645bbc5d07a120c79a944866584a95245b37/cmd/tool/cmd/sendtx.go#L93)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

allow user to specify the sleep interval will help to test.
</blockquote></details>

Done.

---

*[seele/api_debug.go, line 78 at r1](https://reviewable.io/reviews/seeleteam/go-seele/256#-LESGK4V96QoIodDlyB9:-LESKNuv1DysBs1sJPyv:b-mei9s0) ([raw file](https://github.com/seeleteam/go-seele/blob/bed3645bbc5d07a120c79a944866584a95245b37/seele/api_debug.go#L78)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Cache the data will improve the query perf, even though it's a debug API.
</blockquote></details>

actually we need to do the cache in blockchain store. And I think leveldb already do something about it. We could add it if we found that's not enough.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/256)*

**Comment by boqiu** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/tool/cmd/root.go, line 41 at r1](https://reviewable.io/reviews/seeleteam/go-seele/256#-LESEbQo0jIqnEBk1jm7:-LETdTyd8sMYD0UkrYip:b-8snbfh) ([raw file](https://github.com/seeleteam/go-seele/blob/bed3645bbc5d07a120c79a944866584a95245b37/cmd/tool/cmd/root.go#L41)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

that is what I do now :)
</blockquote></details>

I mean figure out in the usage of parameter "server"

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/256)*

**Comment by lucusfly** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/tool/cmd/root.go, line 41 at r1](https://reviewable.io/reviews/seeleteam/go-seele/256#-LESEbQo0jIqnEBk1jm7:-LETigrJ9jvOpmnkMmka:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/bed3645bbc5d07a120c79a944866584a95245b37/cmd/tool/cmd/root.go#L41)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

I mean figure out in the usage of parameter "server"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/256)*

**Comment by boqiu** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/256)*

**Pull request merged**
