### PR TITLE
Add p2p test cmd

### PR DESCRIPTION
**Pull request by gongliaoan**
p2p test cmd move the code in p2p/simulations to cmd/p2p.
use command "go run main.go start" to start  a p2p server.

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/63)

### CODE REVIEW

**Comment by lucusfly** [comment]
There are so many unnecessary commits in your PR, because you use the same branch working on many different developments. Please use a different branch to start new PR.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/p2p/cmd/start.go, line 29 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/63#-L72OHrPRC-4qzh8a7KZ:-L72OHrPRC-4qzh8a7K_:bng9gmi) ([raw file](https://github.com/seeleteam/go-seele/blob/9a5f267f3512c0135034438d0be5feec3eff15cd/cmd/p2p/cmd/start.go#L29)):*
> ```Go
> // 3. In function Run, handle three channel
> // 4. Append SubProtocols to p2p.server.Protocols
> ```

Is this duplicated with p2p simulations? If so, please remove one.

---

*[cmd/p2p/cmd/start.go, line 29 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/63#-L72OZt7DScbKraHq9ob:-L72OZt7DScbKraHq9oc:bswbfhv) ([raw file](https://github.com/seeleteam/go-seele/blob/9a5f267f3512c0135034438d0be5feec3eff15cd/cmd/p2p/cmd/start.go#L29)):*
> ```Go
> // 3. In function Run, handle three channel
> // 4. Append SubProtocols to p2p.server.Protocols
> ```

Please add it to Makefile and enable ci test in .travis.yaml

---

*[cmd/p2p/cmd/start.go, line 163 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/63#-L72P-xOC5w5vp0P9Abt:-L72P-xOC5w5vp0P9Abu:b7n6pnk) ([raw file](https://github.com/seeleteam/go-seele/blob/9a5f267f3512c0135034438d0be5feec3eff15cd/cmd/p2p/cmd/start.go#L163)):*
> ```Go
> 		for {
> 			time.Sleep(10 * time.Second)
> 		}
> ```

use WaitGroup instead of sleep

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/63#-:-L72NAfVsm-ersruFbK5:bthwcsx)*

**Comment by lucusfly** [comment]
For this time, we could just use this PR. Please be careful next time.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/63#-:-L72PEAr5iXd9pxJNJcX:b-kmosqm)*

**Comment by gongliaoan** [comment]
ok

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/p2p/cmd/start.go, line 29 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/63#-L72OHrPRC-4qzh8a7KZ:-L72rzXp4p1Ou4zosFiE:b-qzg0c9) ([raw file](https://github.com/seeleteam/go-seele/blob/9a5f267f3512c0135034438d0be5feec3eff15cd/cmd/p2p/cmd/start.go#L29)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

Is this duplicated with p2p simulations? If so, please remove one.
</blockquote></details>

ok，i will remove it later.

---

*[cmd/p2p/cmd/start.go, line 29 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/63#-L72OZt7DScbKraHq9ob:-L7NFNkM9gbTpzk9V4nw:b57fg4k) ([raw file](https://github.com/seeleteam/go-seele/blob/9a5f267f3512c0135034438d0be5feec3eff15cd/cmd/p2p/cmd/start.go#L29)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

Please add it to Makefile and enable ci test in .travis.yaml
</blockquote></details>

There is another PR about Makefile, i will do it after the PR pushed.

---

*[cmd/p2p/cmd/start.go, line 163 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/63#-L72P-xOC5w5vp0P9Abt:-L7NA1Ss0XS0bs5xbhvM:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/9a5f267f3512c0135034438d0be5feec3eff15cd/cmd/p2p/cmd/start.go#L163)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

use WaitGroup instead of sleep
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/63#-:-L72eLov-UWhZz5YBHW7:b32wtd)*

**Comment by gongliaoan** [comment]
done

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/63#-:-L7NIW2F07wczo7HH27N:bb7f2mf)*

**Comment by lucusfly** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/node/cmd/p2pstart.go, line 163 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/63#-L72P-xOC5w5vp0P9Abt:-L7Nu-Q7FXWYxPMpHrvM:bg9ou6u) ([raw file](https://github.com/seeleteam/go-seele/blob/9a5f267f3512c0135034438d0be5feec3eff15cd/cmd/node/cmd/p2pstart.go#L163)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is not the right way to use WaitGroup

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/63)*

**Comment by gongliaoan** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/node/cmd/p2pstart.go, line 163 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/63#-L72P-xOC5w5vp0P9Abt:-L7O8AKJ2QHbbrh1p7EB:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/9a5f267f3512c0135034438d0be5feec3eff15cd/cmd/node/cmd/p2pstart.go#L163)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

This is not the right way to use WaitGroup
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/63)*

**Comment by gongliaoan** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/node/cmd/p2pstart.go, line 163 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/63#-L72P-xOC5w5vp0P9Abt:-L7O8J-LDYdFyK9_eZTZ:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/9a5f267f3512c0135034438d0be5feec3eff15cd/cmd/node/cmd/p2pstart.go#L163)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/63)*

**Comment by lucusfly** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[p2p/server.go, line 112 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/63#-L7OB91I-sXtRy3DUkRC:-L7OB91I-sXtRy3DUkRD:b-8tqioz) ([raw file](https://github.com/seeleteam/go-seele/blob/42871327db1db4f93d8dd8959bc06f2ca28b7df5/p2p/server.go#L112)):*
> ```Go
> func (srv *Server) Wait() (err error) {
> 	srv.loopWG.Wait()
> 	return nil
> ```

why do u return an error?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/63)*

**Pull request closed without merging**
