### PR TITLE
add miner start and stop apis

### PR DESCRIPTION
**Pull request by gongliaoan**
add miner start and stop apis

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/148)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/client/cmd/miner.go, line 23 at r1](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe-44M8R5pdRvCwqBD:-LBe-44M8R5pdRvCwqBE:b6jfjrt) ([raw file](https://github.com/seeleteam/go-seele/blob/33e34e4a122a66fe440360aa497c9401638bf711/cmd/client/cmd/miner.go#L23)):*
> ```Go
> 	Short: "miner actions",
> 	Long: `For example:
> 	 client.exe miner -a start
> ```

1) it's "-o", not "-a"
2) what about -t as defined below?

---

*[cmd/client/cmd/miner.go, line 35 at r1](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe-Iw9EjwFmJM4v-nU:-LBe-Iw9EjwFmJM4v-nV:b-afmi4s) ([raw file](https://github.com/seeleteam/go-seele/blob/33e34e4a122a66fe440360aa497c9401638bf711/cmd/client/cmd/miner.go#L35)):*
> ```Go
> 		var result string
> 		var input string
> 		switch *operation {
> ```

case sensitive?

---

*[cmd/client/cmd/miner.go, line 54 at r1](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe-X1K4_eTzqfJNDVQ:-LBe-X1K4_eTzqfJNDVR:b-akht10) ([raw file](https://github.com/seeleteam/go-seele/blob/33e34e4a122a66fe440360aa497c9401638bf711/cmd/client/cmd/miner.go#L54)):*
> ```Go
> 		default:
> 			fmt.Println("operation is not defined.")
> 			return
> ```

all the returns are redundant in switch body.

---

*[miner/miner.go, line 24 at r1](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe0NKg7psW2YafNwig:-LBe0NKg7psW2YafNwih:bx67svw) ([raw file](https://github.com/seeleteam/go-seele/blob/33e34e4a122a66fe440360aa497c9401638bf711/miner/miner.go#L24)):*
> ```Go
> 
> var (
> 	ErrMinerIsRunning = errors.New("Miner is running")
> ```

1) Comment missed for exported variable.
2) I think you do not apply the golint plugin tool, which will force the error message format.

---

*[miner/miner.go, line 25 at r1](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe0Zu-0TO2jjlYW2xf:-LBe0Zu-0TO2jjlYW2xg:b9q50fv) ([raw file](https://github.com/seeleteam/go-seele/blob/33e34e4a122a66fe440360aa497c9401638bf711/miner/miner.go#L25)):*
> ```
> stop
> ```

stopped?

---

*[miner/miner.go, line 108 at r1](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe1P4m1Ah-GgRhx_w_:-LBe1P4m1Ah-GgRhx_wa:bbpla85) ([raw file](https://github.com/seeleteam/go-seele/blob/33e34e4a122a66fe440360aa497c9401638bf711/miner/miner.go#L108)):*
> ```
> stoped
> ```

stopped

---

*[miner/miner.go, line 250 at r2](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe1GQ1EsZscxJTLcKY:-LBe1rSPAkY3T0aPmgXl:bqsjx5s) ([raw file](https://github.com/seeleteam/go-seele/blob/40fb49d23ed46001a54fca5f9a77a1b1a926bf59/miner/miner.go#L250)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

mining can't be multiple thread.
</blockquote></details>

it's a waste to mine in multiple threads with random start index, it's better to mine in different partition/shard.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/148)*

**Comment by gongliaoan** [comment]
Review status: 0 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[cmd/client/cmd/miner.go, line 23 at r1](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe-44M8R5pdRvCwqBD:-LBehTLl9th-KVY8bc6R:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/33e34e4a122a66fe440360aa497c9401638bf711/cmd/client/cmd/miner.go#L23)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

1) it's "-o", not "-a"
2) what about -t as defined below?
</blockquote></details>

Done.

---

*[cmd/client/cmd/miner.go, line 35 at r1](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe-Iw9EjwFmJM4v-nU:-LBek-iT52I6saZm_qs9:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/33e34e4a122a66fe440360aa497c9401638bf711/cmd/client/cmd/miner.go#L35)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

case sensitive?
</blockquote></details>

Done.

---

*[cmd/client/cmd/miner.go, line 54 at r1](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe-X1K4_eTzqfJNDVQ:-LBehQk459gIcaJvhkjS:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/33e34e4a122a66fe440360aa497c9401638bf711/cmd/client/cmd/miner.go#L54)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

all the returns are redundant in switch body.
</blockquote></details>

Done.

---

*[miner/miner.go, line 24 at r1](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe0NKg7psW2YafNwig:-LBehX8T5zYpiW3MmhEM:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/33e34e4a122a66fe440360aa497c9401638bf711/miner/miner.go#L24)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

1) Comment missed for exported variable.
2) I think you do not apply the golint plugin tool, which will force the error message format.
</blockquote></details>

Done.

---

*[miner/miner.go, line 25 at r1](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe0Zu-0TO2jjlYW2xf:-LBehb7HCPNGz6GT1HfR:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/33e34e4a122a66fe440360aa497c9401638bf711/miner/miner.go#L25)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> stop
> ```

stopped?
</blockquote></details>

Done.

---

*[miner/miner.go, line 108 at r1](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe1P4m1Ah-GgRhx_w_:-LBehkr-8MapKLj-UuSz:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/33e34e4a122a66fe440360aa497c9401638bf711/miner/miner.go#L108)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> stoped
> ```

stopped
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/148)*

**Comment by sufay** [comment]
Review status: 0 of 11 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[miner/miner.go, line 36 at r3](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBgIYiM2FQt9yPqbEHS:-LBgIYiM2FQt9yPqbEHT:b73tkpk) ([raw file](https://github.com/seeleteam/go-seele/blob/3e1c94c910098f150edd0ac1b85b94451c69c48d/miner/miner.go#L36)):*
> ```Go
> 
> // SeeleService wraps all methods required for minier.
> type SeeleService interface {
> ```

suggested to change SeeleService to SeeleBackend,  avoiding confusion with seeleservice.SeeleService

---

*[miner/miner.go, line 100 at r3](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBgKLWW65NCgg4n1Lxk:-LBgKLWW65NCgg4n1Lxl:b-eoalkw) ([raw file](https://github.com/seeleteam/go-seele/blob/3e1c94c910098f150edd0ac1b85b94451c69c48d/miner/miner.go#L100)):*
> ```Go
> 
> 	go miner.waitBlock()
> 	if atomic.LoadInt32(&miner.isFirstBlockPrepared) == 0 {
> ```

the state flag seems to be unnecessary. with prepareNewBlock not exported, invocation to it  outside miner can be initiated only by miner.Start . in this case, check can be ignored

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/148)*

**Comment by gongliaoan** [comment]
Review status: 0 of 12 files reviewed at latest revision, 9 unresolved discussions.

---

*[miner/miner.go, line 250 at r2](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe1GQ1EsZscxJTLcKY:-LBsK22y6-I0Ed8w9WPI:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/40fb49d23ed46001a54fca5f9a77a1b1a926bf59/miner/miner.go#L250)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

it's a waste to mine in multiple threads with random start index, it's better to mine in different partition/shard.
</blockquote></details>

Done.

---

*[miner/miner.go, line 36 at r3](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBgIYiM2FQt9yPqbEHS:-LBsG0e1DSF40sQGw9Be:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/3e1c94c910098f150edd0ac1b85b94451c69c48d/miner/miner.go#L36)):*
<details><summary><i>Previously, sufay wrote…</i></summary><blockquote>

suggested to change SeeleService to SeeleBackend,  avoiding confusion with seeleservice.SeeleService
</blockquote></details>

Done.

---

*[miner/miner.go, line 100 at r3](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBgKLWW65NCgg4n1Lxk:-LBsGjBq0Qv_72uyWRaA:b-5o4ypq) ([raw file](https://github.com/seeleteam/go-seele/blob/3e1c94c910098f150edd0ac1b85b94451c69c48d/miner/miner.go#L100)):*
<details><summary><i>Previously, sufay wrote…</i></summary><blockquote>

the state flag seems to be unnecessary. with prepareNewBlock not exported, invocation to it  outside miner can be initiated only by miner.Start . in this case, check can be ignored
</blockquote></details>

the flag is necessary, because the block state hash will mismatch when start miner after the  invocation of miner.Stop. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/148)*

**Comment by boqiu** [comment]
Review status: 0 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmd/client/cmd/miner.go, line 23 at r1](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe-44M8R5pdRvCwqBD:-LBtvxCLElA40LACbs4t:bcj9mtu) ([raw file](https://github.com/seeleteam/go-seele/blob/33e34e4a122a66fe440360aa497c9401638bf711/cmd/client/cmd/miner.go#L23)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

Done.
</blockquote></details>

-t flag missed in command "Long" property, is it as expected?

---

*[miner/miner.go, line 24 at r1](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe0NKg7psW2YafNwig:-LBtx6qp4Ij0Su30rkLa:b-ydliqg) ([raw file](https://github.com/seeleteam/go-seele/blob/33e34e4a122a66fe440360aa497c9401638bf711/miner/miner.go#L24)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

Done.
</blockquote></details>

As far as I know, the golint plugin require lowercase error message. Strongly recommend to  keep consistence.

---

*[miner/miner.go, line 57 at r4](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBtxXTSEyyRCxs9WoRg:-LBtxXTSEyyRCxs9WoRh:b-xysjnc) ([raw file](https://github.com/seeleteam/go-seele/blob/26f8186ddeaac7d314f910e4cee7b8f37a35616f/miner/miner.go#L57)):*
> ```
> int
> ```

uint or uint8?

---

*[miner/miner.go, line 255 at r4](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBtxnWh0uMGmfRrV_fz:-LBtxnWh0uMGmfRrV_g-:b43f6yg) ([raw file](https://github.com/seeleteam/go-seele/blob/26f8186ddeaac7d314f910e4cee7b8f37a35616f/miner/miner.go#L255)):*
> ```Go
> 	}
> 	if threads < 0 {
> 		threads = 0
> ```

1 as default?

---

*[miner/miner.go, line 260 at r4](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBty0rnBfrdlsbHhIZh:-LBty0rnBfrdlsbHhIZi:b-7bsr5n) ([raw file](https://github.com/seeleteam/go-seele/blob/26f8186ddeaac7d314f910e4cee7b8f37a35616f/miner/miner.go#L260)):*
> ```Go
> 
> 	var step uint64
> 	seed := uint64(rand.Int63())
> ```

Nonce value [0, seed) missed during mining. I think the right mining logic is [seed, uint64.Max] and [0, seed - 1)

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/148)*

**Comment by gongliaoan** [comment]
Review status: 0 of 12 files reviewed at latest revision, 8 unresolved discussions.

---

*[cmd/client/cmd/miner.go, line 23 at r1](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe-44M8R5pdRvCwqBD:-LBuA5WlAYpCUzhL5kNu:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/33e34e4a122a66fe440360aa497c9401638bf711/cmd/client/cmd/miner.go#L23)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

-t flag missed in command "Long" property, is it as expected?
</blockquote></details>

Done.

---

*[miner/miner.go, line 24 at r1](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBe0NKg7psW2YafNwig:-LBuA4ae04TMzACn5elc:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/33e34e4a122a66fe440360aa497c9401638bf711/miner/miner.go#L24)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

As far as I know, the golint plugin require lowercase error message. Strongly recommend to  keep consistence.
</blockquote></details>

Done.

---

*[miner/miner.go, line 57 at r4](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBtxXTSEyyRCxs9WoRg:-LBuCSZJ5HJuUym4sMs9:bfm1l62) ([raw file](https://github.com/seeleteam/go-seele/blob/26f8186ddeaac7d314f910e4cee7b8f37a35616f/miner/miner.go#L57)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> int
> ```

uint or uint8?
</blockquote></details>

when threads num is negative, the miner will not start.

---

*[miner/miner.go, line 255 at r4](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBtxnWh0uMGmfRrV_fz:-LBuE4bTBOJo6IiEfAF_:br5k87c) ([raw file](https://github.com/seeleteam/go-seele/blob/26f8186ddeaac7d314f910e4cee7b8f37a35616f/miner/miner.go#L255)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

1 as default?
</blockquote></details>

the default thread num is the number of logical cups.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/148)*

**Comment by gongliaoan** [comment]
Review status: 0 of 12 files reviewed at latest revision, 8 unresolved discussions.

---

*[miner/miner.go, line 260 at r4](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBty0rnBfrdlsbHhIZh:-LBxZa_BBForFMBXYdNy:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/26f8186ddeaac7d314f910e4cee7b8f37a35616f/miner/miner.go#L260)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Nonce value [0, seed) missed during mining. I think the right mining logic is [seed, uint64.Max] and [0, seed - 1)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/148)*

**Comment by sufay** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[miner/miner.go, line 100 at r3](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBgKLWW65NCgg4n1Lxk:-LByKYDCEQnHeEtGs1-O:b-4fccpz) ([raw file](https://github.com/seeleteam/go-seele/blob/3e1c94c910098f150edd0ac1b85b94451c69c48d/miner/miner.go#L100)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

the flag is necessary, because the block state hash will mismatch when start miner after the  invocation of miner.Stop. 
</blockquote></details>

yes, you are right

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/148)*

**Comment by gongliaoan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[miner/miner.go, line 100 at r3](https://reviewable.io/reviews/seeleteam/go-seele/148#-LBgKLWW65NCgg4n1Lxk:-LByekby7yM0Rr39uS3c:b-pldjj8) ([raw file](https://github.com/seeleteam/go-seele/blob/3e1c94c910098f150edd0ac1b85b94451c69c48d/miner/miner.go#L100)):*
<details><summary><i>Previously, sufay wrote…</i></summary><blockquote>

yes, you are right
</blockquote></details>

Please acknowledge this comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/148)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/client/cmd/miner.go, line 43 at r5](https://reviewable.io/reviews/seeleteam/go-seele/148#-LByf98O7cD-4Zn4S06X:-LByf98O7cD-4Zn4S06Y:b-l8yzb3) ([raw file](https://github.com/seeleteam/go-seele/blob/38eaa29608ab9620d09dc400ad958ab4edf4cc59/cmd/client/cmd/miner.go#L43)):*
> ```
> miner start
> ```

miner start succeed

---

*[cmd/client/cmd/miner.go, line 50 at r5](https://reviewable.io/reviews/seeleteam/go-seele/148#-LByfETf5koohY-Lp4EF:-LByfETf5koohY-Lp4EG:b-22iii9) ([raw file](https://github.com/seeleteam/go-seele/blob/38eaa29608ab9620d09dc400ad958ab4edf4cc59/cmd/client/cmd/miner.go#L50)):*
> ```
> miner stop
> ```

miner stop succeed

---

*[miner/core.go, line 20 at r5](https://reviewable.io/reviews/seeleteam/go-seele/148#-LByhNRFAFdkev4_pf94:-LByhNRFAFdkev4_pf95:b-astwe3) ([raw file](https://github.com/seeleteam/go-seele/blob/38eaa29608ab9620d09dc400ad958ab4edf4cc59/miner/core.go#L20)):*
> ```Go
> // result represents the founded nonce will be set in the result block
> // abort is a channel by closing which you can stop mining
> func StartMining(task *Task, seed uint64, min uint64, max uint64, result chan<- *Result, abort <-chan struct{}, isNonceFound *int32, log *log.SeeleLog) {
> ```

change comments to align with parameters

---

*[miner/core.go, line 35 at r5](https://reviewable.io/reviews/seeleteam/go-seele/148#-LByuaBa6d26pKRWZdA0:-LByuaBa6d26pKRWZdA1:b-2xhsz9) ([raw file](https://github.com/seeleteam/go-seele/blob/38eaa29608ab9620d09dc400ad958ab4edf4cc59/miner/core.go#L35)):*
> ```Go
> 
> 		default:
> 			if *isNonceFound != 0 {
> ```

use atomic.load

---

*[miner/core.go, line 63 at r5](https://reviewable.io/reviews/seeleteam/go-seele/148#-LByhnh0DBrzaT05F5cO:-LByhnh0DBrzaT05F5cP:b-t7ct32) ([raw file](https://github.com/seeleteam/go-seele/blob/38eaa29608ab9620d09dc400ad958ab4edf4cc59/miner/core.go#L63)):*
> ```Go
> 
> 			// outage
> 			if nonce == max {
> ```

change comments to align with your change

---

*[miner/miner.go, line 255 at r5](https://reviewable.io/reviews/seeleteam/go-seele/148#-LByjzir-ZDNnCthtRWj:-LByjzir-ZDNnCthtRWk:b-vlb35w) ([raw file](https://github.com/seeleteam/go-seele/blob/38eaa29608ab9620d09dc400ad958ab4edf4cc59/miner/miner.go#L255)):*
> ```Go
> 	}
> 	if threads < 0 {
> 		threads = 0
> ```

threads is 0 means miner stop. I suggest reset threads to cpu number when threads is smaller than 0

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/148)*

**Comment by gongliaoan** [comment]
Review status: 9 of 12 files reviewed at latest revision, 7 unresolved discussions.

---

*[cmd/client/cmd/miner.go, line 43 at r5](https://reviewable.io/reviews/seeleteam/go-seele/148#-LByf98O7cD-4Zn4S06X:-LBz1MO_8KC6qy6_sbgA:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/38eaa29608ab9620d09dc400ad958ab4edf4cc59/cmd/client/cmd/miner.go#L43)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> miner start
> ```

miner start succeed
</blockquote></details>

Done.

---

*[cmd/client/cmd/miner.go, line 50 at r5](https://reviewable.io/reviews/seeleteam/go-seele/148#-LByfETf5koohY-Lp4EF:-LBz1NM8DCZ-uqHYl--6:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/38eaa29608ab9620d09dc400ad958ab4edf4cc59/cmd/client/cmd/miner.go#L50)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> miner stop
> ```

miner stop succeed
</blockquote></details>

Done.

---

*[miner/core.go, line 20 at r5](https://reviewable.io/reviews/seeleteam/go-seele/148#-LByhNRFAFdkev4_pf94:-LBz3qX45Zdw2_ml4wWr:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/38eaa29608ab9620d09dc400ad958ab4edf4cc59/miner/core.go#L20)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

change comments to align with parameters
</blockquote></details>

Done.

---

*[miner/core.go, line 35 at r5](https://reviewable.io/reviews/seeleteam/go-seele/148#-LByuaBa6d26pKRWZdA0:-LBzA_kh9Cnp4zRndDTo:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/38eaa29608ab9620d09dc400ad958ab4edf4cc59/miner/core.go#L35)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

use atomic.load
</blockquote></details>

Done.

---

*[miner/core.go, line 63 at r5](https://reviewable.io/reviews/seeleteam/go-seele/148#-LByhnh0DBrzaT05F5cO:-LBz36IA6jpKbGiLLD1i:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/38eaa29608ab9620d09dc400ad958ab4edf4cc59/miner/core.go#L63)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

change comments to align with your change
</blockquote></details>

Done.

---

*[miner/miner.go, line 255 at r5](https://reviewable.io/reviews/seeleteam/go-seele/148#-LByjzir-ZDNnCthtRWj:-LBz42X2CC5j89xR6kl0:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/38eaa29608ab9620d09dc400ad958ab4edf4cc59/miner/miner.go#L255)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

threads is 0 means miner stop. I suggest reset threads to cpu number when threads is smaller than 0
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/148)*

**Pull request merged**
