### PR TITLE
Use LRU in state db

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/139)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[core/state/statedb.go, line 55 at r1](https://reviewable.io/reviews/seeleteam/go-seele/139#-LBXDk4d1enkmxHDTDOu:-LBXDk4d1enkmxHDTDOv:b-dfw72p) ([raw file](https://github.com/seeleteam/go-seele/blob/ecb36da738a8a6deb35ffa8e96125f1b5d9f08e9/core/state/statedb.go#L55)):*
> ```
> for _, k := range s.stateObjects.Keys()
> ```
do we need to add lock for this iteration operation?

---

*[core/state/statedb.go, line 146 at r1](https://reviewable.io/reviews/seeleteam/go-seele/139#-LBXEI7K5KVFCMMlQGWO:-LBXEI7K5KVFCMMlQGWP:b-urwzja) ([raw file](https://github.com/seeleteam/go-seele/blob/ecb36da738a8a6deb35ffa8e96125f1b5d9f08e9/core/state/statedb.go#L146)):*
> ```
> a quarter
> ```
just curious, why 1/4 instead of other values, any background for this number?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/139)*

**Comment by lucusfly** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[core/state/statedb.go, line 55 at r1](https://reviewable.io/reviews/seeleteam/go-seele/139#-LBXDk4d1enkmxHDTDOu:-LBYi8j77w8nUsq5K8Ne:b-eo3j0) ([raw file](https://github.com/seeleteam/go-seele/blob/ecb36da738a8a6deb35ffa8e96125f1b5d9f08e9/core/state/statedb.go#L55)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> for _, k := range s.stateObjects.Keys()
> ```
do we need to add lock for this iteration operation?

</blockquote></details>

Statedb is not declared thread safe.

---

*[core/state/statedb.go, line 146 at r1](https://reviewable.io/reviews/seeleteam/go-seele/139#-LBXEI7K5KVFCMMlQGWO:-LBYiZj_5j-HnWOLNS_f:b5s9jh5) ([raw file](https://github.com/seeleteam/go-seele/blob/ecb36da738a8a6deb35ffa8e96125f1b5d9f08e9/core/state/statedb.go#L146)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> a quarter
> ```
just curious, why 1/4 instead of other values, any background for this number?
</blockquote></details>

no background, just experience dependence.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/139)*

**Comment by boqiu** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[core/state/statedb.go, line 18 at r1](https://reviewable.io/reviews/seeleteam/go-seele/139#-LBYiAy3CaKQyPP18c8i:-LBYiAy3CaKQyPP18c8j:bnlv7h7) ([raw file](https://github.com/seeleteam/go-seele/blob/ecb36da738a8a6deb35ffa8e96125f1b5d9f08e9/core/state/statedb.go#L18)):*
> ```Go
> )
> 
> const StateCacheCapacity = 1000
> ```

comment missed for exported variable.

---

*[core/state/statedb.go, line 52 at r1](https://reviewable.io/reviews/seeleteam/go-seele/139#-LBYiOss44ab8Pb7BioL:-LBYiOss44ab8Pb7BioM:brm0kqp) ([raw file](https://github.com/seeleteam/go-seele/blob/ecb36da738a8a6deb35ffa8e96125f1b5d9f08e9/core/state/statedb.go#L52)):*
> ```Go
> 	copies, err := lru.New(StateCacheCapacity)
> 	if err != nil {
> 		panic(err) // only get err when StateCacheCapacity is negative, if so panic
> ```

Better to use log.panic to track unexpected error.

---

*[core/state/statedb.go, line 137 at r1](https://reviewable.io/reviews/seeleteam/go-seele/139#-LBYj6Od61hILKmPfVYs:-LBYj6Od61hILKmPfVYt:b6welk) ([raw file](https://github.com/seeleteam/go-seele/blob/ecb36da738a8a6deb35ffa8e96125f1b5d9f08e9/core/state/statedb.go#L137)):*
> ```Go
> 	data, err := rlp.EncodeToBytes(obj.account)
> 	if err != nil {
> 		panic(err) // must encode because object account is a deterministic struct
> ```

log.panic

---

*[core/state/statedb.go, line 144 at r1](https://reviewable.io/reviews/seeleteam/go-seele/139#-LBYjOJz7bugTX-bTNOu:-LBYjOJz7bugTX-bTNOv:bb5nink) ([raw file](https://github.com/seeleteam/go-seele/blob/ecb36da738a8a6deb35ffa8e96125f1b5d9f08e9/core/state/statedb.go#L144)):*
> ```Go
> func (s *Statedb) cache(addr common.Address, obj *StateObject) {
> 	if s.stateObjects.Len() == StateCacheCapacity {
> 		s.Commit(nil)
> ```

any purpose of calculating root hash here?

---

*[core/state/statedb_test.go, line 170 at r1](https://reviewable.io/reviews/seeleteam/go-seele/139#-LBYkNJq33lPKPa3fNdC:-LBYkNJq33lPKPa3fNdD:b-2eib38) ([raw file](https://github.com/seeleteam/go-seele/blob/ecb36da738a8a6deb35ffa8e96125f1b5d9f08e9/core/state/statedb_test.go#L170)):*
> ```Go
> 
> func getAddr(a int) common.Address {
> 	return BytesToAddressForTest([]byte(strconv.Itoa(a)))
> ```

bytesToAddress is available in common pkg.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/139)*

**Comment by lucusfly** [comment]
Review status: 0 of 12 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[core/state/statedb.go, line 18 at r1](https://reviewable.io/reviews/seeleteam/go-seele/139#-LBYiAy3CaKQyPP18c8i:-LBYo4Ob2dD91rRRIzxS:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/ecb36da738a8a6deb35ffa8e96125f1b5d9f08e9/core/state/statedb.go#L18)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

comment missed for exported variable.
</blockquote></details>

Done.

---

*[core/state/statedb.go, line 52 at r1](https://reviewable.io/reviews/seeleteam/go-seele/139#-LBYiOss44ab8Pb7BioL:-LBYpBlPAdONi_ZtCnIE:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/ecb36da738a8a6deb35ffa8e96125f1b5d9f08e9/core/state/statedb.go#L52)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Better to use log.panic to track unexpected error.
</blockquote></details>

Done.

---

*[core/state/statedb.go, line 137 at r1](https://reviewable.io/reviews/seeleteam/go-seele/139#-LBYj6Od61hILKmPfVYs:-LBYpCca8T7jjDivOlEf:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/ecb36da738a8a6deb35ffa8e96125f1b5d9f08e9/core/state/statedb.go#L137)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

log.panic
</blockquote></details>

Done.

---

*[core/state/statedb.go, line 144 at r1](https://reviewable.io/reviews/seeleteam/go-seele/139#-LBYjOJz7bugTX-bTNOu:-LBYn94uEAHqEafwI2yE:bcb4ik3) ([raw file](https://github.com/seeleteam/go-seele/blob/ecb36da738a8a6deb35ffa8e96125f1b5d9f08e9/core/state/statedb.go#L144)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

any purpose of calculating root hash here?
</blockquote></details>

this is not for calculate root hash. it is for flush the dirty objects to trie.

---

*[core/state/statedb_test.go, line 170 at r1](https://reviewable.io/reviews/seeleteam/go-seele/139#-LBYkNJq33lPKPa3fNdC:-LBYp4es3DtbHjgYBNkm:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/ecb36da738a8a6deb35ffa8e96125f1b5d9f08e9/core/state/statedb_test.go#L170)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

bytesToAddress is available in common pkg.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/139)*

**Comment by boqiu** [comment]
Reviewed 10 of 12 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/139)*

**Comment by WTer** [comment]
Reviewed 10 of 12 files at r1, 8 of 8 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/139)*

**Pull request merged**
