### PR TITLE
Task change address from 64 bytes to 32 bytes

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/231)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---

*[common/Address.go, line 64 at r1](https://reviewable.io/reviews/seeleteam/go-seele/231#-LDz3CwdD5BU3zN95EI-:-LDz3Cwl4VOuvL7OCRTe:bd4d27i) ([raw file](https://github.com/seeleteam/go-seele/blob/3de3dcd0cd14015deacb795c963940c3230d87eb/common/Address.go#L64)):*
> ```
> PubKeyToAddress
> ```
no any error happened in this func?

---

*[common/Address.go, line 73 at r1](https://reviewable.io/reviews/seeleteam/go-seele/231#-LDz3OIP2QCupzZLy8IY:-LDz3OIS7NkPnGmw1Rix:b-50i185) ([raw file](https://github.com/seeleteam/go-seele/blob/3de3dcd0cd14015deacb795c963940c3230d87eb/common/Address.go#L73)):*
> ```
> 	copy(addr[2:22], hash[12:])
> 	copy(addr[22:], hash[:10])
> ```
nice to add comments for this numbers

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/231)*

**Comment by boqiu** [comment]
Review status: 0 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/Address.go, line 64 at r1](https://reviewable.io/reviews/seeleteam/go-seele/231#-LDz3CwdD5BU3zN95EI-:-LDz4cZ00KEY-hrS2-8a:biw7b5g) ([raw file](https://github.com/seeleteam/go-seele/blob/3de3dcd0cd14015deacb795c963940c3230d87eb/common/Address.go#L64)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> PubKeyToAddress
> ```
no any error happened in this func?
</blockquote></details>

Unnecessary, only 2 cases that need to return error: 1) parse from hex string 2) parse from bytes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/231)*

**Comment by WTer** [comment]
Review status: 0 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/Address.go, line 27 at r1](https://reviewable.io/reviews/seeleteam/go-seele/231#-LDz4bcMA5TX-6dHHuWt:-LDz4bcPDzb8VZpTqDx6:bi0clrc) ([raw file](https://github.com/seeleteam/go-seele/blob/3de3dcd0cd14015deacb795c963940c3230d87eb/common/Address.go#L27)):*
> ```
> shardMod(2)
> ```
2 bytes for shard number?

And I suppose non-contract account also contains this field.

how can get the 8/10 bytes hash string from normal hash string?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/231)*

**Comment by WTer** [comment]
Review status: 0 of 23 files reviewed at latest revision, 3 unresolved discussions.

---

*[common/Address.go, line 45 at r1](https://reviewable.io/reviews/seeleteam/go-seele/231#-LDz64W98qce4Dyice0v:-LDz64WC2j7iu7PNgb6q:bon4iji) ([raw file](https://github.com/seeleteam/go-seele/blob/3de3dcd0cd14015deacb795c963940c3230d87eb/common/Address.go#L45)):*
> ```
> if b[0] != addressVersion1
> ```
how to do version back-compatible? we cannot guarantee all nodes upgrade at the same time.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/231)*

**Comment by WTer** [comment]
Review status: 0 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

*[common/Address.go, line 52 at r1](https://reviewable.io/reviews/seeleteam/go-seele/231#-LDz6cle-uO41X6lhGyT:-LDz6clf0SI4a4QbW2IO:b-vz5t9a) ([raw file](https://github.com/seeleteam/go-seele/blob/3de3dcd0cd14015deacb795c963940c3230d87eb/common/Address.go#L52)):*
> ```
> 	switch b[1] {
> 	case addressTypeExternal:
> 	case addressTypeContract:
> ```

the definition of addressTypeContract:
addressTypeContract = byte(2)

so the comparison will be ok? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/231)*

**Comment by WTer** [comment]
Review status: 0 of 23 files reviewed at latest revision, 5 unresolved discussions.

---

*[common/Address.go, line 157 at r1](https://reviewable.io/reviews/seeleteam/go-seele/231#-LDz7eVPBB5VnrL9BmyH:-LDz7eVPBB5VnrL9BmyI:bovkf6d) ([raw file](https://github.com/seeleteam/go-seele/blob/3de3dcd0cd14015deacb795c963940c3230d87eb/common/Address.go#L157)):*
> ```
> if IsShardDisabled {
> ```
you should modify the comments in common/shard.go:

// IsShardDisabled indicates if the shard is disabled.
// THIS IS FOR UNIT TEST PURPOSE ONLY!!!

---

*[common/Address.go, line 158 at r1](https://reviewable.io/reviews/seeleteam/go-seele/231#-LDz7mtn30p3BhGKDoWK:-LDz7mto1_oL4eOByPoc:bv7z86t) ([raw file](https://github.com/seeleteam/go-seele/blob/3de3dcd0cd14015deacb795c963940c3230d87eb/common/Address.go#L158)):*
> ```
> 0
> ```
using defaultShardNumber as instead.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/231)*

**Comment by boqiu** [comment]
Review status: 0 of 23 files reviewed at latest revision, 7 unresolved discussions.

---

*[common/Address.go, line 27 at r1](https://reviewable.io/reviews/seeleteam/go-seele/231#-LDz4bcMA5TX-6dHHuWt:-LDz7lydEqb-fu1Kojoy:b3rsmls) ([raw file](https://github.com/seeleteam/go-seele/blob/3de3dcd0cd14015deacb795c963940c3230d87eb/common/Address.go#L27)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> shardMod(2)
> ```
2 bytes for shard number?

And I suppose non-contract account also contains this field.

how can get the 8/10 bytes hash string from normal hash string?
</blockquote></details>

1) 2 bytes are enough, which allow to support 65536 shards.
2) 2 bytes shardMod is not the shard number, but used to ensure the contract address shard number is the same with the creator's address shard. Addionally, please refer to Shard() for shard number calculation.

---

*[common/Address.go, line 45 at r1](https://reviewable.io/reviews/seeleteam/go-seele/231#-LDz64W98qce4Dyice0v:-LDz8hbe-UQsKfU6EZth:b-xxhzij) ([raw file](https://github.com/seeleteam/go-seele/blob/3de3dcd0cd14015deacb795c963940c3230d87eb/common/Address.go#L45)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> if b[0] != addressVersion1
> ```
how to do version back-compatible? we cannot guarantee all nodes upgrade at the same time.
</blockquote></details>

This is the logic of version 1 only. Once we upgrade to version 2, then the code change need to compatible with the verion 1.

---

*[common/Address.go, line 52 at r1](https://reviewable.io/reviews/seeleteam/go-seele/231#-LDz6cle-uO41X6lhGyT:-LDzAZI78R8M2XL7rXAP:bvlq7mt) ([raw file](https://github.com/seeleteam/go-seele/blob/3de3dcd0cd14015deacb795c963940c3230d87eb/common/Address.go#L52)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> 	switch b[1] {
> 	case addressTypeExternal:
> 	case addressTypeContract:
> ```

the definition of addressTypeContract:
addressTypeContract = byte(2)

so the comparison will be ok? 
</blockquote></details>

byte(2) means that the addressTypeContract is 2 in byte type, not 2 bytes.

---

*[common/Address.go, line 73 at r1](https://reviewable.io/reviews/seeleteam/go-seele/231#-LDz3OIP2QCupzZLy8IY:-LDzB0gi5AZIyqUMSjZ4:bb7f2mf) ([raw file](https://github.com/seeleteam/go-seele/blob/3de3dcd0cd14015deacb795c963940c3230d87eb/common/Address.go#L73)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> 	copy(addr[2:22], hash[12:])
> 	copy(addr[22:], hash[:10])
> ```
nice to add comments for this numbers
</blockquote></details>

done

---

*[common/Address.go, line 157 at r1](https://reviewable.io/reviews/seeleteam/go-seele/231#-LDz7eVPBB5VnrL9BmyH:-LDz9L4M2tcL1Rbw3cZc:b-foqqwf) ([raw file](https://github.com/seeleteam/go-seele/blob/3de3dcd0cd14015deacb795c963940c3230d87eb/common/Address.go#L157)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> if IsShardDisabled {
> ```
you should modify the comments in common/shard.go:

// IsShardDisabled indicates if the shard is disabled.
// THIS IS FOR UNIT TEST PURPOSE ONLY!!!
</blockquote></details>

The logic is not changed, why need to change the comment?

---

*[common/Address.go, line 158 at r1](https://reviewable.io/reviews/seeleteam/go-seele/231#-LDz7mtn30p3BhGKDoWK:-LDzB2d2-QPl_YpMyXF2:bb7f2mf) ([raw file](https://github.com/seeleteam/go-seele/blob/3de3dcd0cd14015deacb795c963940c3230d87eb/common/Address.go#L158)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> 0
> ```
using defaultShardNumber as instead.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/231)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/231)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[crypto/crypto.go, line 132 at r2](https://reviewable.io/reviews/seeleteam/go-seele/231#-LDzjbAH6Oh2dmb71vqY:-LDzjbAH6Oh2dmb71vqZ:bcu3ni6) ([raw file](https://github.com/seeleteam/go-seele/blob/5c79cdf5da8eec2b5fd0174d6d418ae76e12d7f8/crypto/crypto.go#L132)):*
> ```Go
> 
> // GenerateRandomAddress generates and returns a random address.
> func GenerateRandomAddress() (*common.Address, error) {
> ```

why not use GenerateKeyPair?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/231)*

**Comment by boqiu** [comment]
Review status: 22 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

*[crypto/crypto.go, line 132 at r2](https://reviewable.io/reviews/seeleteam/go-seele/231#-LDzjbAH6Oh2dmb71vqY:-LDztoay3KUCaNkp7GnG:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/5c79cdf5da8eec2b5fd0174d6d418ae76e12d7f8/crypto/crypto.go#L132)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

why not use GenerateKeyPair?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/231)*

**Pull request merged**
