### PR TITLE
validate block nonce and reward amount

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/115)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[miner/pow/engine.go, line 37 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/115#-L9ihwIT-ANdc4OUY_af:-L9ihwIT-ANdc4OUY_ag:b-5tybqg) ([raw file](https://github.com/seeleteam/go-seele/blob/dc4fb7d6ce8f5cf23fa4898477827186b54f5f64/miner/pow/engine.go#L37)):*
> ```
> new(big.Int).Div(maxUint256, blockHeader.Difficulty)
> ```
use GetMiningTarget()

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/115)*

**Comment by lucusfly** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/115)*

**Comment by boqiu** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[miner/pow/engine.go, line 37 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/115#-L9ihwIT-ANdc4OUY_af:-L9ip-eNDcy2pvA5nYQn:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/dc4fb7d6ce8f5cf23fa4898477827186b54f5f64/miner/pow/engine.go#L37)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> new(big.Int).Div(maxUint256, blockHeader.Difficulty)
> ```
use GetMiningTarget()
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/115)*

**Comment by lucusfly** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/115)*

**Pull request merged**
