### PR TITLE
load nodes

### PR DESCRIPTION
**Pull request by ypenghui6**
load nodes from the nodes backup file, avoid to discoery the nodes again when restart

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/255)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[p2p/discovery/udp.go, line 14 at r1](https://reviewable.io/reviews/seeleteam/go-seele/255#-LEOnD3b3wHmgHkEoGlQ:-LEOnD3b3wHmgHkEoGlR:b-527fzi) ([raw file](https://github.com/seeleteam/go-seele/blob/94f5a00ec28652b090f0f503d3dc2611adbaf56e/p2p/discovery/udp.go#L14)):*
> ```Go
> 	"net"
> 	"time"
> ```

remove this empty line

---

*[p2p/discovery/udp.go, line 485 at r1](https://reviewable.io/reviews/seeleteam/go-seele/255#-LEOnRgQ3sfC1a_MgpnV:-LEOnRgQ3sfC1a_MgpnW:bgqq28u) ([raw file](https://github.com/seeleteam/go-seele/blob/94f5a00ec28652b090f0f503d3dc2611adbaf56e/p2p/discovery/udp.go#L485)):*
> ```
> u.log.Error("nodes info backup file analysis failed for:[%s]", err.Error())
> ```

u.log.Error("read nodes info backup file failed for:[%s]", err)

---

*[p2p/discovery/udp_test.go, line 13 at r1](https://reviewable.io/reviews/seeleteam/go-seele/255#-LEOnvj9C8nDxQddvybP:-LEOnvj9C8nDxQddvybQ:bykhm1q) ([raw file](https://github.com/seeleteam/go-seele/blob/94f5a00ec28652b090f0f503d3dc2611adbaf56e/p2p/discovery/udp_test.go#L13)):*
> ```
> log := log.GetLogger("discovery", common.LogConfig.PrintLog)
> ```

for test, you don't need store error in log. you could panic to make test failed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/255)*

**Comment by ypenghui6** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[p2p/discovery/udp.go, line 14 at r1](https://reviewable.io/reviews/seeleteam/go-seele/255#-LEOnD3b3wHmgHkEoGlQ:-LEOqbkW6Fqu2Ff-xOCj:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/94f5a00ec28652b090f0f503d3dc2611adbaf56e/p2p/discovery/udp.go#L14)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

remove this empty line
</blockquote></details>

Done.

---

*[p2p/discovery/udp.go, line 485 at r1](https://reviewable.io/reviews/seeleteam/go-seele/255#-LEOnRgQ3sfC1a_MgpnV:-LEOqfFOD9rvZnCwzFXE:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/94f5a00ec28652b090f0f503d3dc2611adbaf56e/p2p/discovery/udp.go#L485)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> u.log.Error("nodes info backup file analysis failed for:[%s]", err.Error())
> ```

u.log.Error("read nodes info backup file failed for:[%s]", err)
</blockquote></details>

Done.

---

*[p2p/discovery/udp_test.go, line 13 at r1](https://reviewable.io/reviews/seeleteam/go-seele/255#-LEOnvj9C8nDxQddvybP:-LEOq_N9-LgJmvWYkrpk:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/94f5a00ec28652b090f0f503d3dc2611adbaf56e/p2p/discovery/udp_test.go#L13)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> log := log.GetLogger("discovery", common.LogConfig.PrintLog)
> ```

for test, you don't need store error in log. you could panic to make test failed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/255)*

**Comment by lucusfly** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[p2p/discovery/udp.go, line 485 at r1](https://reviewable.io/reviews/seeleteam/go-seele/255#-LEOnRgQ3sfC1a_MgpnV:-LEPb-jF9Pl-R4vZvd7A:bxmw0bv) ([raw file](https://github.com/seeleteam/go-seele/blob/94f5a00ec28652b090f0f503d3dc2611adbaf56e/p2p/discovery/udp.go#L485)):*
<details><summary><i>Previously, ypenghui6 (ypenghui6) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

didn't see the change

---

*[p2p/discovery/udp_test.go, line 16 at r2](https://reviewable.io/reviews/seeleteam/go-seele/255#-LEPasw387IWJkMxNiCm:-LEPasw44y2_zf15KSXI:bmnhp9f) ([raw file](https://github.com/seeleteam/go-seele/blob/a5ae87d67b5fc487087a3dc89d1ce5f84a3e1155/p2p/discovery/udp_test.go#L16)):*
> ```
> faild
> ```

failed, better print out the error message

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/255)*

**Comment by ypenghui6** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[p2p/discovery/udp.go, line 485 at r1](https://reviewable.io/reviews/seeleteam/go-seele/255#-LEOnRgQ3sfC1a_MgpnV:-LES43qn9QEoNSL-uid1:b32w0x) ([raw file](https://github.com/seeleteam/go-seele/blob/94f5a00ec28652b090f0f503d3dc2611adbaf56e/p2p/discovery/udp.go#L485)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

didn't see the change
</blockquote></details>

OK

---

*[p2p/discovery/udp_test.go, line 16 at r2](https://reviewable.io/reviews/seeleteam/go-seele/255#-LEPasw387IWJkMxNiCm:-LES41Fm3QWrROfpae5K:b32w0x) ([raw file](https://github.com/seeleteam/go-seele/blob/a5ae87d67b5fc487087a3dc89d1ce5f84a3e1155/p2p/discovery/udp_test.go#L16)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> faild
> ```

failed, better print out the error message
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/255)*

**Comment by WTer** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/255)*

**Comment by lucusfly** [comment]
Reviewed 1 of 3 files at r1, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/255)*

**Pull request merged**
