### PR TITLE
create contract by solidity file and save the funcHash data in DB

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/279)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @boqiu and @wangff15386)

---

*[cmd/vm/cmd/create.go, line 55 at r1](https://reviewable.io/reviews/seeleteam/go-seele/279#-LEsgZyt86okFcoAkzgn:-LEsgZyuAm9W8NPTNS-q:b3b6u1i) ([raw file](https://github.com/seeleteam/go-seele/blob/2fb4c64109070b6348ef50bf9c9c528bba5e88dc/cmd/vm/cmd/create.go#L55)):*
> ```
> return nil, nil, nil
> ```
nice to return meaningful error message, such as "solidity file cannot be nil"

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/279)*

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @boqiu and @wangff15386)

---

*[cmd/vm/cmd/create.go, line 55 at r1](https://reviewable.io/reviews/seeleteam/go-seele/279#-LEsgZyt86okFcoAkzgn:-LEw3RYbB1oi4rnoL_T3:blcixt4) ([raw file](https://github.com/seeleteam/go-seele/blob/2fb4c64109070b6348ef50bf9c9c528bba5e88dc/cmd/vm/cmd/create.go#L55)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> return nil, nil, nil
> ```
nice to return meaningful error message, such as "solidity file cannot be nil"
</blockquote></details>

1) when solidity file not specified, this method just return nil result, and the program will use specified bytecodes to create contract.
2) In this case, return a empty func for dispose.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/279)*

**Comment by WTer** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @boqiu and @wangff15386)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/279)*

**Comment by boqiu** [comment]
Review status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @WTer and @wangff15386)

---

*[cmd/vm/cmd/create.go, line 101 at r1](https://reviewable.io/reviews/seeleteam/go-seele/279#-LEw4tA58n0OeOMgZo56:-LEwAm3DBLU358bmf7RN:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2fb4c64109070b6348ef50bf9c9c528bba5e88dc/cmd/vm/cmd/create.go#L101)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> "0x" + string(content)
> ```
do we need to check whether the content already starts with "0x"?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/279)*

**Comment by WTer** [comment]
Reviewed 3 of 3 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangff15386)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/279)*

**Pull request merged**
