### PR TITLE
refine log

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/185)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---

*[p2p/peer.go, line 121 at r1](https://reviewable.io/reviews/seeleteam/go-seele/185#-LClm-r32dLBN9jT4kmB:-LClm-r32dLBN9jT4kmC:b-qvk0ug) ([raw file](https://github.com/seeleteam/go-seele/blob/2b04cdd9476a63a7697fc7704892f29f6460f1f4/p2p/peer.go#L121)):*
> ```
> Info
> ```

Debug? otherwise there may be massive of such logs.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/185)*

**Comment by WTer** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[p2p/server.go, line 158 at r1](https://reviewable.io/reviews/seeleteam/go-seele/185#-LClo-1o2GaIgCzX7xb1:-LClo-1o2GaIgCzX7xb2:bit568t) ([raw file](https://github.com/seeleteam/go-seele/blob/2b04cdd9476a63a7697fc7704892f29f6460f1f4/p2p/server.go#L158)):*
> ```
> "got discovery a new node event"
> ```
add node info "node.String()" into log for better debugging?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/185)*

**Comment by lucusfly** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[p2p/peer.go, line 121 at r1](https://reviewable.io/reviews/seeleteam/go-seele/185#-LClm-r32dLBN9jT4kmB:-LCltzpw188iAzOcPWuv:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2b04cdd9476a63a7697fc7704892f29f6460f1f4/p2p/peer.go#L121)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> Info
> ```

Debug? otherwise there may be massive of such logs.
</blockquote></details>

Done.

---

*[p2p/server.go, line 158 at r1](https://reviewable.io/reviews/seeleteam/go-seele/185#-LClo-1o2GaIgCzX7xb1:-LCluWzS5W5whEMFFLAQ:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2b04cdd9476a63a7697fc7704892f29f6460f1f4/p2p/server.go#L158)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> "got discovery a new node event"
> ```
add node info "node.String()" into log for better debugging?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/185)*

**Comment by WTer** [comment]
Reviewed 7 of 9 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/185)*

**Comment by boqiu** [comment]
Reviewed 7 of 9 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/185)*

**Pull request merged**
