### PR TITLE
add p2p test

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/76)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/node/cmd/test.go, line 27 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/76#-L7YtUxwXg2iOg6pzgpO:-L7YtUxwXg2iOg6pzgpP:b860clo) ([raw file](https://github.com/seeleteam/go-seele/blob/d187af9249446365396d3581afba68d1c2f9327e/cmd/node/cmd/test.go#L27)):*
> channel

channels

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/76)*

**Comment by WTer** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/76)*

**Comment by lucusfly** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/node/cmd/test.go, line 27 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/76#-L7YtUxwXg2iOg6pzgpO:-L7YwiWuyCV8E1yaY3MV:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/d187af9249446365396d3581afba68d1c2f9327e/cmd/node/cmd/test.go#L27)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> channel

channels
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/76)*

**Comment by WTer** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/76)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[cmd/node/cmd/test.go, line 27 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/76#-L7YtUxwXg2iOg6pzgpO:-L7Yvuc1kUVZPDYm1bAN:bfkf2yb) ([raw file](https://github.com/seeleteam/go-seele/blob/d187af9249446365396d3581afba68d1c2f9327e/cmd/node/cmd/test.go#L27)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> channel

channels
</blockquote></details>

pkg comment appears before package declaration.

---

*[p2p/peer.go, line 157 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/76#-L7YxGPrTNLQwdYaNUVy:-L7YxGPrTNLQwdYaNUVz:b9telfm) ([raw file](https://github.com/seeleteam/go-seele/blob/d187af9249446365396d3581afba68d1c2f9327e/p2p/peer.go#L157)):*
> ```Go
> 		go p.sendCtlMsg(ctlMsgPongCode)
> 	case msgRecv.msgCode == ctlMsgPongCode:
> 		//p.log.Debug("peer handle Ping msg.")
> ```

delete unnecessary debug log? Also note for similar unused debug log.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/76)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/node/cmd/test.go, line 27 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/76#-L7YtUxwXg2iOg6pzgpO:-L7Yz7SfgjmHyl4SxTX3:b-h5xtoo) ([raw file](https://github.com/seeleteam/go-seele/blob/d187af9249446365396d3581afba68d1c2f9327e/cmd/node/cmd/test.go#L27)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

pkg comment appears before package declaration.
</blockquote></details>

actually it is not pkg level comments, change it to file.

---

*[p2p/peer.go, line 157 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/76#-L7YxGPrTNLQwdYaNUVy:-L7YyWaSm_a-gsFzHD0h:bphc7nw) ([raw file](https://github.com/seeleteam/go-seele/blob/d187af9249446365396d3581afba68d1c2f9327e/p2p/peer.go#L157)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

delete unnecessary debug log? Also note for similar unused debug log.
</blockquote></details>

This is for temporary suppress the info, we may need to open it later. so just keep it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/76)*

**Comment by boqiu** [comment]
Reviewed 11 of 12 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/76)*

**Comment by herove** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/node/cmd/test.go, line 27 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/76#-L7YtUxwXg2iOg6pzgpO:-L7_41BAUDT4W99aJLk4:bc1yq0m) ([raw file](https://github.com/seeleteam/go-seele/blob/d187af9249446365396d3581afba68d1c2f9327e/cmd/node/cmd/test.go#L27)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

actually it is not pkg level comments, change it to file.
</blockquote></details>

The comment walks on the edge of the code style.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/76)*

**Comment by WTer** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/76)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/node/cmd/test.go, line 27 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/76#-L7YtUxwXg2iOg6pzgpO:-L7bgD10g92AB80lQ78F:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/d187af9249446365396d3581afba68d1c2f9327e/cmd/node/cmd/test.go#L27)):*
<details><summary><i>Previously, herove (Leihao Zhou) wrote…</i></summary><blockquote>

The comment walks on the edge of the code style.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/76)*

**Pull request merged**
