### PR TITLE
add miner reward

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/111)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[core/blockchain.go, line 181 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/111#-L9df7o7DoW2ST31JiXF:-L9df7o7DoW2ST31JiXG:bcc854e) ([raw file](https://github.com/seeleteam/go-seele/blob/87eb99158d1836701cb8f32a6d968171c1c0c0b8/core/blockchain.go#L181)):*
> ```
> *tx.Data.To
> ```
how can we ensure this account is block miner?

---

*[miner/task.go, line 38 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/111#-L9dfhAq3ecJKVO0LmsH:-L9dfhAq3ecJKVO0LmsI:b-v7aao9) ([raw file](https://github.com/seeleteam/go-seele/blob/87eb99158d1836701cb8f32a6d968171c1c0c0b8/miner/task.go#L38)):*
> ```
> common.Address{}
> ```
common.EmptyHash?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/111)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[core/blockchain.go, line 181 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/111#-L9df7o7DoW2ST31JiXF:-L9diAeE7xQUq_5U0vYx:b1x2iur) ([raw file](https://github.com/seeleteam/go-seele/blob/87eb99158d1836701cb8f32a6d968171c1c0c0b8/core/blockchain.go#L181)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> *tx.Data.To
> ```
how can we ensure this account is block miner?
</blockquote></details>

should verify the amount to prevent malicious reward?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/111)*

**Comment by lucusfly** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[miner/task.go, line 38 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/111#-L9dfhAq3ecJKVO0LmsH:-L9djDxC25qmrSyIwsv8:bldgveh) ([raw file](https://github.com/seeleteam/go-seele/blob/87eb99158d1836701cb8f32a6d968171c1c0c0b8/miner/task.go#L38)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> common.Address{}
> ```
common.EmptyHash?
</blockquote></details>

This is Address, not hash. we don't have EmptyAddress

---

*[core/blockchain.go, line 181 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/111#-L9df7o7DoW2ST31JiXF:-L9djtfw4_gcIop_bGvi:bygid3d) ([raw file](https://github.com/seeleteam/go-seele/blob/87eb99158d1836701cb8f32a6d968171c1c0c0b8/core/blockchain.go#L181)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

should verify the amount to prevent malicious reward?
</blockquote></details>

Remove this part as Bo will do it later.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/111)*

**Comment by qiaozhigang** [comment]
Reviewed 7 of 9 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/111)*

**Pull request merged**
