### PR TITLE
fix a panic bug

### PR DESCRIPTION
**Pull request by webbergao1**
panic when 'conn' is nil

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/258)

### CODE REVIEW

**Comment by boqiu** [comment]
did not see any code change for panic logic, please double confirm.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/258#-:-LETch_y6DOTQ3qOCRGV:blnbhag)*

**Comment by boqiu** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/258)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[p2p/server.go, line 179 at r1](https://reviewable.io/reviews/seeleteam/go-seele/258#-LETipxe0RVqw4j4PLQc:-LETipxg8RRJvqlTEnbm:b-sekzgb) ([raw file](https://github.com/seeleteam/go-seele/blob/a3eea3239ca66263a16efc6bd888df5a5a5e3d68/p2p/server.go#L179)):*
> ```Go
> 		return
> 	}
> 	srv.log.Info("connect to a node with %s -> %s", conn.LocalAddr(), conn.RemoteAddr())
> ```

I already fix it in the review https://reviewable.io/reviews/seeleteam/go-seele/256

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/258)*

**Comment by webbergao1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[p2p/server.go, line 179 at r1](https://reviewable.io/reviews/seeleteam/go-seele/258#-LETipxe0RVqw4j4PLQc:-LETjKj00vEAxOzlsyog:bpos9pi) ([raw file](https://github.com/seeleteam/go-seele/blob/a3eea3239ca66263a16efc6bd888df5a5a5e3d68/p2p/server.go#L179)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

I already fix it in the review https://reviewable.io/reviews/seeleteam/go-seele/256
</blockquote></details>

ok  , I close this review

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/258)*

**Comment by webbergao1** [comment]
already fixed by other

**Pull request closed without merging**
