### PR TITLE
 use encrypted key file

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/149)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---

*[common/stdin.go, line 29 at r1](https://reviewable.io/reviews/seeleteam/go-seele/149#-LBtBv8UBOxtfVbvz9pG:-LBtBv8UBOxtfVbvz9pH:bhk4mhe) ([raw file](https://github.com/seeleteam/go-seele/blob/c79c667e3c5573323aabee5176d2defc921ec7d0/common/stdin.go#L29)):*
> ```
> gopass.GetPasswd()
> ```
need to ensure its security.

---

*[common/stdin.go, line 44 at r1](https://reviewable.io/reviews/seeleteam/go-seele/149#-LBtCBvt2dM59PyVOGPd:-LBtCBvt2dM59PyVOGPe:b7b8czx) ([raw file](https://github.com/seeleteam/go-seele/blob/c79c667e3c5573323aabee5176d2defc921ec7d0/common/stdin.go#L44)):*
> ```
> string(pass)
> ```
I suppose string(pass) is still secure and encrypted string, right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/149)*

**Comment by WTer** [comment]
Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/client/cmd/savekey.go, line 41 at r1](https://reviewable.io/reviews/seeleteam/go-seele/149#-LBtCQfi4GaWYVv0oxGb:-LBtCQfi4GaWYVv0oxGc:bn2r62t) ([raw file](https://github.com/seeleteam/go-seele/blob/c79c667e3c5573323aabee5176d2defc921ec7d0/cmd/client/cmd/savekey.go#L41)):*
> ```
> err.Error()
> ```
to make sure no any info leak related to user password.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/149)*

**Comment by boqiu** [comment]
Review status: 0 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[common/stdin.go, line 16 at r2](https://reviewable.io/reviews/seeleteam/go-seele/149#-LBu-jo40quK23bN53HM:-LBu-jo40quK23bN53HN:bnq98xr) ([raw file](https://github.com/seeleteam/go-seele/blob/1b9698d3778e16676bc5881fdd0630b1a7cf0ed2/common/stdin.go#L16)):*
> ```Go
> 
> // GetPassword ask user for password interactively
> func GetPassword() (string, error) {
> ```

Suggest to return a []byte instead of unsafe string type for password, and reset the []byte in memory once used. Maybe we can introduce a SecureString struct as .NET provided.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/149)*

**Comment by lucusfly** [comment]
Review status: 0 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/client/cmd/savekey.go, line 41 at r1](https://reviewable.io/reviews/seeleteam/go-seele/149#-LBtCQfi4GaWYVv0oxGb:-LBu6w-W5d6FqcIwVb6F:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/c79c667e3c5573323aabee5176d2defc921ec7d0/cmd/client/cmd/savekey.go#L41)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> err.Error()
> ```
to make sure no any info leak related to user password.
</blockquote></details>

Done.

---

*[common/stdin.go, line 29 at r1](https://reviewable.io/reviews/seeleteam/go-seele/149#-LBtBv8UBOxtfVbvz9pG:-LBuBduiAgFDBzor6cJc:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/c79c667e3c5573323aabee5176d2defc921ec7d0/common/stdin.go#L29)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> gopass.GetPasswd()
> ```
need to ensure its security.
</blockquote></details>

Done.

---

*[common/stdin.go, line 44 at r1](https://reviewable.io/reviews/seeleteam/go-seele/149#-LBtCBvt2dM59PyVOGPd:-LBu8jfq4e8d3fRz_Z5I:b-d9xeni) ([raw file](https://github.com/seeleteam/go-seele/blob/c79c667e3c5573323aabee5176d2defc921ec7d0/common/stdin.go#L44)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> string(pass)
> ```
I suppose string(pass) is still secure and encrypted string, right?
</blockquote></details>

no. This is user's password. GC will destroy it after used.

---

*[common/stdin.go, line 16 at r2](https://reviewable.io/reviews/seeleteam/go-seele/149#-LBu-jo40quK23bN53HM:-LBuBf8G9M43i79MxMve:b-twap7e) ([raw file](https://github.com/seeleteam/go-seele/blob/1b9698d3778e16676bc5881fdd0630b1a7cf0ed2/common/stdin.go#L16)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Suggest to return a []byte instead of unsafe string type for password, and reset the []byte in memory once used. Maybe we can introduce a SecureString struct as .NET provided.
</blockquote></details>

there is no good way to clear an array in go.  the string password will be cleared by GC. it is temporally exist in memory. I think it is OK for security.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/149)*

**Comment by WTer** [comment]
Reviewed 13 of 16 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/149)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/stdin.go, line 16 at r2](https://reviewable.io/reviews/seeleteam/go-seele/149#-LBu-jo40quK23bN53HM:-LBxjMqZDtCimXaqyh2H:bi4hpj6) ([raw file](https://github.com/seeleteam/go-seele/blob/1b9698d3778e16676bc5881fdd0630b1a7cf0ed2/common/stdin.go#L16)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

there is no good way to clear an array in go.  the string password will be cleared by GC. it is temporally exist in memory. I think it is OK for security.
</blockquote></details>

At least, we can reset each byte to 0 immediately after using password. Anyway, I know it's used in command and nothing serious, but we can do it better:)

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/149)*

**Pull request merged**
