### PR TITLE
Add node rpc server service and add test rpc cmd

### PR DESCRIPTION
**Pull request by gongliaoan**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/82)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---

*[cmd/node/cmd/rpcClient.go, line 19 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/82#-L7iFJ411BT1_z2UTHen:-L7iFJ411BT1_z2UTHeo:bns01ia) ([raw file](https://github.com/seeleteam/go-seele/blob/c9b2c13ceb8390d28dbb657cb6e72835547bd52f/cmd/node/cmd/rpcClient.go#L19)):*
> //

add meaningful comments, or remove it.

---

*[node/node.go, line 119 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/82#-L7iFZOP8gb3J_KF-scP:-L7iFZOP8gb3J_KF-scQ:b560pkn) ([raw file](https://github.com/seeleteam/go-seele/blob/c9b2c13ceb8390d28dbb657cb6e72835547bd52f/node/node.go#L119)):*
> return err

do we need to implement this logic as a transaction?  which means all opened, or all closed. no intermediate status, since some RPCs already opened when errors happened.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/82)*

**Comment by gongliaoan** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/node/cmd/rpcClient.go, line 19 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/82#-L7iFJ411BT1_z2UTHen:-L7iGaAsN36ho8TjvIW4:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/c9b2c13ceb8390d28dbb657cb6e72835547bd52f/cmd/node/cmd/rpcClient.go#L19)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> //

add meaningful comments, or remove it.
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/82)*

**Comment by gongliaoan** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[node/node.go, line 119 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/82#-L7iFZOP8gb3J_KF-scP:-L7iIeCfWKjM8dVnSrEq:bjdlmy0) ([raw file](https://github.com/seeleteam/go-seele/blob/c9b2c13ceb8390d28dbb657cb6e72835547bd52f/node/node.go#L119)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> return err

do we need to implement this logic as a transaction?  which means all opened, or all closed. no intermediate status, since some RPCs already opened when errors happened.
</blockquote></details>

yes, i will add stop func when we have more than one rpc server, and stop the started rpc server when one rpc server failed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/82)*

**Comment by boqiu** [comment]
Review status: 0 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[cmd/node/cmd/rpcClient.go, line 17 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/82#-L7vtYv-oMjyqb5PLKuL:-L7vtYv-oMjyqb5PLKuM:b4a7aru) ([raw file](https://github.com/seeleteam/go-seele/blob/a93699c09ea577ea1742b7f466d443afc197c150/cmd/node/cmd/rpcClient.go#L17)):*
> *string

*string or string?

---

*[cmd/node/cmd/start.go, line 22 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/82#-L7vuTBeyE99-LLn26tR:-L7vuTBeyE99-LLn26tS:bh4keu2) ([raw file](https://github.com/seeleteam/go-seele/blob/a93699c09ea577ea1742b7f466d443afc197c150/cmd/node/cmd/start.go#L22)):*
> ```Go
> 
> var (
> 	seeleNodeKey, _     = crypto.GenerateKey()
> ```

What if error happened?

---

*[cmd/node/cmd/start.go, line 70 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/82#-L7vvBtvi94hUNI2Raad:-L7vvBtvi94hUNI2Raae:b-1um1bd) ([raw file](https://github.com/seeleteam/go-seele/blob/a93699c09ea577ea1742b7f466d443afc197c150/cmd/node/cmd/start.go#L70)):*
> ```Go
> 			return
> 		}
> 		slog := log.GetLogger("seele", true)
> ```

If it is a common use log, how about move to constants.go under common pkg.

---

*[cmd/node/cmd/start.go, line 72 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/82#-L7vv4ULHcslhq82lu-e:-L7vv4ULHcslhq82lu-f:b1btxt9) ([raw file](https://github.com/seeleteam/go-seele/blob/a93699c09ea577ea1742b7f466d443afc197c150/cmd/node/cmd/start.go#L72)):*
> ```Go
> 		slog := log.GetLogger("seele", true)
> 
> 		seeleService, _ := seele.NewSeeleService(0, slog)
> ```

error handling?

---

*[node/node.go, line 142 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/82#-L7vwITho3E63meZhjHL:-L7vwITho3E63meZhjHM:b-czp0yo) ([raw file](https://github.com/seeleteam/go-seele/blob/a93699c09ea577ea1742b7f466d443afc197c150/node/node.go#L142)):*
> ```Go
> 
> 	if listerner, err = net.Listen("tcp", n.config.RPCAddr); err != nil {
> 		n.log.Error("Listen failed", "err", err)
> ```

once error occurred, is it necessary to unregister the RPC services above?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/82)*

**Comment by lucusfly** [comment]
Review status: 0 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[cmd/node/cmd/rpcClient.go, line 65 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/82#-L7vyKwD9FkGlq6auV6U:-L7vyKwD9FkGlq6auV6V:bh3o6fy) ([raw file](https://github.com/seeleteam/go-seele/blob/a93699c09ea577ea1742b7f466d443afc197c150/cmd/node/cmd/rpcClient.go#L65)):*
> ```Go
> 	clientConfigFile = rpcClientCmd.Flags().StringP("config", "c", "", "seele node config file (required)")
> 	rpcClientCmd.MarkFlagRequired("config")
> ```

remove empty line

---

*[cmd/node/cmd/rpcClient.toml, line 1 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/82#-L7vy8kgCRrqmR8ATeX5:-L7vy8kgCRrqmR8ATeX6:b-gijzip) ([raw file](https://github.com/seeleteam/go-seele/blob/a93699c09ea577ea1742b7f466d443afc197c150/cmd/node/cmd/rpcClient.toml#L1)):*
> ```TOML
> RPCAddr="127.0.0.1:55027"
> ```

no need to use it as a file, just pass it in the command line

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/82)*

**Comment by gongliaoan** [comment]
Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[cmd/node/cmd/rpcClient.go, line 17 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/82#-L7vtYv-oMjyqb5PLKuL:-L7vzkwL7xFe_1d-rkBQ:b-212k8a) ([raw file](https://github.com/seeleteam/go-seele/blob/a93699c09ea577ea1742b7f466d443afc197c150/cmd/node/cmd/rpcClient.go#L17)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

> *string

*string or string?
</blockquote></details>

*string

---

*[cmd/node/cmd/rpcClient.go, line 65 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/82#-L7vyKwD9FkGlq6auV6U:-L7w0ZnVEHviqsGx-6Er:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a93699c09ea577ea1742b7f466d443afc197c150/cmd/node/cmd/rpcClient.go#L65)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.

---

*[cmd/node/cmd/start.go, line 22 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/82#-L7vuTBeyE99-LLn26tR:-L7w4h91D2eAmTGnTplA:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a93699c09ea577ea1742b7f466d443afc197c150/cmd/node/cmd/start.go#L22)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

What if error happened?
</blockquote></details>

Done.

---

*[cmd/node/cmd/start.go, line 70 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/82#-L7vvBtvi94hUNI2Raad:-L7w6NOR8aj3P388aKhH:b-q5zq4v) ([raw file](https://github.com/seeleteam/go-seele/blob/a93699c09ea577ea1742b7f466d443afc197c150/cmd/node/cmd/start.go#L70)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

If it is a common use log, how about move to constants.go under common pkg.
</blockquote></details>

This log is not common use log, it is only use to test node start, i will add it in constants.go after we finished the seele node start.

---

*[cmd/node/cmd/start.go, line 72 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/82#-L7vv4ULHcslhq82lu-e:-L7w5_k296zFUNk53qWV:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a93699c09ea577ea1742b7f466d443afc197c150/cmd/node/cmd/start.go#L72)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

error handling?
</blockquote></details>

Done.

---

*[node/node.go, line 142 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/82#-L7vwITho3E63meZhjHL:-L7wAG3i9QgC_72P1jfp:bfko3bo) ([raw file](https://github.com/seeleteam/go-seele/blob/a93699c09ea577ea1742b7f466d443afc197c150/node/node.go#L142)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

once error occurred, is it necessary to unregister the RPC services above?
</blockquote></details>

it is not necessary to unregister RPC services and need to stop opened RPCs, there is only one RPC, so not need stop opened RPCs. 

---

*[cmd/node/cmd/rpcClient.toml, line 1 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/82#-L7vy8kgCRrqmR8ATeX5:-L7w0bDW0LDDPMOpHhAn:b-4fwilw) ([raw file](https://github.com/seeleteam/go-seele/blob/a93699c09ea577ea1742b7f466d443afc197c150/cmd/node/cmd/rpcClient.toml#L1)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

no need to use it as a file, just pass it in the command line
</blockquote></details>

good suggestion.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/82)*

**Comment by boqiu** [comment]
Reviewed 5 of 8 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/82)*

**Comment by gongliaoan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/node/cmd/rpcClient.toml, line 1 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/82#-L7vy8kgCRrqmR8ATeX5:-L7wjh9nvpoIakHua_Ou:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a93699c09ea577ea1742b7f466d443afc197c150/cmd/node/cmd/rpcClient.toml#L1)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

good suggestion.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/82)*

**Comment by WTer** [comment]
Reviewed 3 of 8 files at r1, 2 of 3 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/82)*

**Comment by WTer** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/82)*

**Comment by lucusfly** [comment]
Reviewed 1 of 8 files at r1, 2 of 3 files at r3, 1 of 3 files at r4, 2 of 2 files at r5, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/82)*

**Comment by gongliaoan** [comment]
Review status: 7 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/node/cmd/start.go, line 31 at r6](https://reviewable.io:443/reviews/seeleteam/go-seele/82#-L8WAaUvU5UjKsCQOzec:-L8WV4x5PQU7t-n4QLDE:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/bf831ece575d0b465f0e71f1cdb0356c2d238870/cmd/node/cmd/start.go#L31)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

SeeleNodeConfig shoule be node.config?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/82)*

**Comment by WTer** [comment]
Reviewed 3 of 5 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/82)*

**Comment by WTer** [comment]
Reviewed 5 of 5 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/82)*

**Comment by qiaozhigang** [comment]
Reviewed 1 of 3 files at r3, 1 of 3 files at r4, 2 of 2 files at r5, 1 of 3 files at r7, 5 of 5 files at r8.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/82)*

**Pull request merged**
