### PR TITLE
add critical bench mark for core module

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/336)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @boqiu, @WTer, and @lucusfly)

---

*[core/types/transaction.go, line 297 at r1](https://reviewable.io/reviews/seeleteam/go-seele/336#-LG3zPHS2zZMalgqxVC0:-LG3zPHTD-9f7fHlShCG:blmt3j6) ([raw file](https://github.com/seeleteam/go-seele/blob/f27567796f3343ffe0fd7f4a578acec49f57015f/core/types/transaction.go#L297)):*
> ```
> 4
> ```
2?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/336)*

**Comment by WTer** [comment]
Review status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @boqiu, @WTer, and @lucusfly)

---

*[core/types/transaction.go, line 325 at r1](https://reviewable.io/reviews/seeleteam/go-seele/336#-LG4-xJ2Er-SdRKJUI8g:-LG4-xJ2Er-SdRKJUI8h:bq8zf39) ([raw file](https://github.com/seeleteam/go-seele/blob/f27567796f3343ffe0fd7f4a578acec49f57015f/core/types/transaction.go#L325)):*
> ```
> break
> ```
when any one thread exited with error, it should notify other threads to terminate.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/336)*

**Comment by boqiu** [comment]
Review status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @boqiu, @WTer, and @lucusfly)

---

*[core/types/transaction.go, line 297 at r1](https://reviewable.io/reviews/seeleteam/go-seele/336#-LG3zPHS2zZMalgqxVC0:-LG44nd05M7Lo3S2jcRt:b-57ruy9) ([raw file](https://github.com/seeleteam/go-seele/blob/f27567796f3343ffe0fd7f4a578acec49f57015f/core/types/transaction.go#L297)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> 4
> ```
2?
</blockquote></details>

On windows, the NumCPU returns logic processor (e.g. 8 in my desktop), but kernel number is 4. Additionally, we must avoid CPU 100%, so 2 threads are enough.

---

*[core/types/transaction.go, line 325 at r1](https://reviewable.io/reviews/seeleteam/go-seele/336#-LG4-xJ2Er-SdRKJUI8g:-LG47UTd3rFhl7YLvGpK:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f27567796f3343ffe0fd7f4a578acec49f57015f/core/types/transaction.go#L325)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> break
> ```
when any one thread exited with error, it should notify other threads to terminate.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/336)*

**Comment by WTer** [comment]
Reviewed 2 of 4 files at r1, 13 of 13 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lucusfly)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/336)*

**Pull request merged**
