### PR TITLE
add get transaction by hash

### PR DESCRIPTION
**Pull request by gongliaoan**
1、add GetTransactionByHash api

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/192)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[core/tx_pool.go, line 39 at r1](https://reviewable.io/reviews/seeleteam/go-seele/192#-LD14buD6OWg5za7pqZC:-LD14buD6OWg5za7pqZD:b-8jgtyg) ([raw file](https://github.com/seeleteam/go-seele/blob/5b0c02703924e0b1ef303279d97a18f49c77a40d/core/tx_pool.go#L39)):*
> ```Go
> 	chain             blockchain
> 	hashToTxMap       map[common.Hash]*types.Transaction
> 	lookupHashToTxMap map[common.Hash]*types.Transaction // Transactions map for lookup
> ```

Why not reuse the "hashToTxMap"? What you need is just add a flag, and RPC client could aware the tx status (queued, processing, processed)

---

*[core/store/db_store.go, line 170 at r1](https://reviewable.io/reviews/seeleteam/go-seele/192#-LD1-dQK2kEbav6qOqvg:-LD1-dQK2kEbav6qOqvh:b-3vsql1) ([raw file](https://github.com/seeleteam/go-seele/blob/5b0c02703924e0b1ef303279d97a18f49c77a40d/core/store/db_store.go#L170)):*
> ```Go
> 			idx := types.TxIndex{
> 				BlockHash: hash,
> 				Index:     uint(i),
> ```

Once new field added in txindex, someone may forget to init here. So, suggest to use the original way to force creating tx index with all field initialized.

---

*[seele/api_txpool.go, line 17 at r1](https://reviewable.io/reviews/seeleteam/go-seele/192#-LD10JJ88tQSLivhuMKG:-LD10JJ88tQSLivhuMKH:btkd7if) ([raw file](https://github.com/seeleteam/go-seele/blob/5b0c02703924e0b1ef303279d97a18f49c77a40d/seele/api_txpool.go#L17)):*
> ```Go
> 
> var (
> 	errIndexOutRange       = errors.New("index out of block transaction list range, the max index is ")
> ```

missed the max index info

---

*[seele/api_txpool.go, line 96 at r1](https://reviewable.io/reviews/seeleteam/go-seele/192#-LD10SJdBgoN6zFsn23d:-LD10SJdBgoN6zFsn23e:b58f5jp) ([raw file](https://github.com/seeleteam/go-seele/blob/5b0c02703924e0b1ef303279d97a18f49c77a40d/seele/api_txpool.go#L96)):*
> ```
> griven
> ```

given

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/192)*

**Comment by boqiu** [comment]
Reviewed 6 of 8 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/192)*

**Comment by gongliaoan** [comment]
Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[core/tx_pool.go, line 39 at r1](https://reviewable.io/reviews/seeleteam/go-seele/192#-LD14buD6OWg5za7pqZC:-LD5JZQlBvflMWNjSo0-:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/5b0c02703924e0b1ef303279d97a18f49c77a40d/core/tx_pool.go#L39)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not reuse the "hashToTxMap"? What you need is just add a flag, and RPC client could aware the tx status (queued, processing, processed)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/192)*

**Comment by gongliaoan** [comment]
Reviewed 1 of 8 files at r1.
Review status: 5 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/192)*

**Comment by gongliaoan** [comment]
Reviewed 4 of 8 files at r1, 1 of 3 files at r2, 4 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/192)*

**Pull request merged**
