### PR TITLE
enable mining in command line

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/97)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---

*[cmd/node/cmd/start.go, line 89 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/97#-L8f6IUQ0HXScnX5QjlR:-L8f6IUQ0HXScnX5QjlS:biy6ico) ([raw file](https://github.com/seeleteam/go-seele/blob/3f62c2b5b3cff07cddcfabf36d3f6c717ea959a5/cmd/node/cmd/start.go#L89)):*
> startMiner

firstly should start node, and then start to mine, so this call should be after "seeleNode.Start()"?

---

*[core/tx_pool.go, line 69 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/97#-L8f75OEBnEb3fZER7wi:-L8f75OEBnEb3fZER7wj:bg3czi1) ([raw file](https://github.com/seeleteam/go-seele/blob/3f62c2b5b3cff07cddcfabf36d3f6c717ea959a5/core/tx_pool.go#L69)):*
> //fire

add one blank between '//' and 'fire'

---

*[miner/core.go, line 45 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/97#-L8f9wbr4YO4itrp1_dK:-L8f9wbr4YO4itrp1_dL:bc0t6mw) ([raw file](https://github.com/seeleteam/go-seele/blob/3f62c2b5b3cff07cddcfabf36d3f6c717ea959a5/miner/core.go#L45)):*
> block.HeaderHash = hash

I suppose the header hash is unrelated to miner, why do you set it here?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/97)*

**Comment by WTer** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[miner/miner.go, line 169 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/97#-L8fBFcS3320vnFFJ9u_:-L8fBFcS3320vnFFJ9ua:b-4xty8z) ([raw file](https://github.com/seeleteam/go-seele/blob/3f62c2b5b3cff07cddcfabf36d3f6c717ea959a5/miner/miner.go#L169)):*
> atomic.StoreInt32(&miner.mining, 0)

actually the miner.mining should also be reset to 0 when applyTransactions() done, so we need to move this statement out of if{} block.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/97)*

**Comment by lucusfly** [comment]
Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/node/cmd/start.go, line 89 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/97#-L8f6IUQ0HXScnX5QjlR:-L8fGQAY0kk6i42mwiz8:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/3f62c2b5b3cff07cddcfabf36d3f6c717ea959a5/cmd/node/cmd/start.go#L89)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> startMiner

firstly should start node, and then start to mine, so this call should be after "seeleNode.Start()"?
</blockquote></details>

Done.

---

*[core/tx_pool.go, line 69 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/97#-L8f75OEBnEb3fZER7wi:-L8fGUMS1VQ8-LfoKUdO:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/3f62c2b5b3cff07cddcfabf36d3f6c717ea959a5/core/tx_pool.go#L69)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> //fire

add one blank between '//' and 'fire'
</blockquote></details>

Done.

---

*[miner/core.go, line 45 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/97#-L8f9wbr4YO4itrp1_dK:-L8fGV74EuaNrFze8j9J:b3z89yw) ([raw file](https://github.com/seeleteam/go-seele/blob/3f62c2b5b3cff07cddcfabf36d3f6c717ea959a5/miner/core.go#L45)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> block.HeaderHash = hash

I suppose the header hash is unrelated to miner, why do you set it here?
</blockquote></details>

this block will be returned as result. so need to set its hash when get the right value.

---

*[miner/miner.go, line 169 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/97#-L8fBFcS3320vnFFJ9u_:-L8fGe6F5P9dq469hten:bsv04cd) ([raw file](https://github.com/seeleteam/go-seele/blob/3f62c2b5b3cff07cddcfabf36d3f6c717ea959a5/miner/miner.go#L169)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> atomic.StoreInt32(&miner.mining, 0)

actually the miner.mining should also be reset to 0 when applyTransactions() done, so we need to move this statement out of if{} block.
</blockquote></details>

normally mining should be reset to 0 when we find the right nonce and get a new block. here we get errors when generating block, so break the task and reset mining to 0.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/97)*

**Comment by WTer** [comment]
Reviewed 12 of 14 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/97)*

**Comment by WTer** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/97)*

**Pull request merged**
