### PR TITLE
add miner module, it's just a rough framework without implement of so…

### PR DESCRIPTION
**Pull request by tianlao**
…me interface

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/73)

### CODE REVIEW

**Comment by herove** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[core/tx_pool.go, line 66 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/73#-L7XDlYw-r-57MHSSaTB:-L7XDlYw-r-57MHSSaTC:bw0wpjl) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/core/tx_pool.go#L66)):*
> ```Go
> 	// TODO
> 	return nil,nil
> }
> ```

no new line at the end

---

*[event/manager_instance.go, line 19 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/73#-L7XEOjQTC1IaM7f3oiQ:-L7XEOjQTC1IaM7f3oiR:b-liq0ar) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/event/manager_instance.go#L19)):*
> ```Go
> 
> // event of new mined block
> var BlockMinedEventManager = NewEventManager()
> ```

comment should be start with BlockMinedEventManager

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/73)*

**Comment by boqiu** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[event/manager_instance.go, line 19 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XEOjQTC1IaM7f3oiQ:-L7XFqmP0GSf3hTBLAaM:b-v56c3f) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/event/manager_instance.go#L19)):*
<details><summary><i>Previously, herove (Leihao Zhou) wrote…</i></summary><blockquote>

comment should be start with BlockMinedEventManager
</blockquote></details>

We use VS code and the go plugins (e.g. golint or goreturns) will help to format the code, including the comment style.

---

*[miner/engine.go, line 15 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XGJ187Ph6ZuZe3q_E:-L7XGJ187Ph6ZuZe3q_F:bggzx9j) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/engine.go#L15)):*
> ```Go
> )
> 
> type CPUEngine struct {
> ```

Comment missed. Again, please ensure your IDE use go plugins properly. Tool will help to format the code and prompt the missed necessary comments.

---

*[miner/engine.go, line 47 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XIekg9_j86lrslIai:-L7XIekg9_j86lrslIaj:b7e4r90) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/engine.go#L47)):*
> ```Go
> 
> func (eng *CPUEngine) Start() {
> 	if atomic.LoadInt32(&eng.mining) == 1 {
> ```

Do you want to design Start() as thread-safe? If so, it is not thread-safe in this manner, please use CompareAndSwap or mutex or sync.Once instead.

---

*[miner/engine.go, line 56 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XJqHz6XGg3FOQJ9Ly:-L7XJqHz6XGg3FOQJ9Lz:btboeid) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/engine.go#L56)):*
> ```Go
> 
> func (eng *CPUEngine) Stop() {
> 	if atomic.LoadInt32(&eng.mining) == 0 {
> ```

when to set the mining to 0?

---

*[miner/engine.go, line 64 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XKkQIEvmufky88WAE:-L7XKkQJ9U44ZFw-L7-j:b-cukq86) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/engine.go#L64)):*
> ```Go
> 	// clear all work in taskChan
> out:
> 	for {
> ```

1) It seems for loop is unnecessary, why not read from taskChan directly?
2) All the channels are not closed in current implementation. Is it as expected or will add other API to close the resources?

---

*[miner/engine.go, line 83 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XM36627Wisck8r00R:-L7XM36627Wisck8r00S:bsimv0t) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/engine.go#L83)):*
> ```Go
> 			}
> 			eng.currentChan = make(chan struct{})
> 			go eng.mine(work, eng.currentChan) // start mining
> ```

according to the min() declaration, the 2nd parameter is stop chan. please double confirm

---

*[miner/engine.go, line 92 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XLLr_3wFPjrrIErWX:-L7XLLr_3wFPjrrIErWY:b-79m5n9) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/engine.go#L92)):*
> break out
return?

---

*[miner/miner.go, line 83 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XNHDFD97we8FpqI0e:-L7XNHDFD97we8FpqI0f:b6yr20z) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/miner.go#L83)):*
> ```Go
> 	defer miner.mutex.Unlock()
> 
> 	if atomic.LoadInt32(&miner.mining) == 1 {
> ```

Pay attention to the thread-safe manner, Load & Store in 2 steps cannot guarantee once purpose.

---

*[seele/seelebackend.go, line 27 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XMRcl7umUJJtACMFa:-L7XMRcl7umUJJtACMFb:bh0lxh1) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/seele/seelebackend.go#L27)):*
> ```Go
> // fake impl of SeeleBackend
> type SeeleBackendImpl struct {
> 	txPool 		*core.TransactionPool
> ```

whitespaces alignment. Go plugins will help to format the code automatically:)

---

*[seele/seelebackend.go, line 38 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XMe9y1Qw43cN3xzAC:-L7XMe9y1Qw43cN3xzAD:bw3t0on) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/seele/seelebackend.go#L38)):*
> ```Go
> 	db, err := leveldb.NewLevelDB(dbPath)
> 	if err != nil {
> 		fmt.Println("New leveldb instance failed")
> ```

Use log instead?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/73)*

**Comment by lucusfly** [comment]
Review status: 0 of 6 files reviewed at latest revision, 12 unresolved discussions.

---

*[miner/engine.go, line 25 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/73#-L7XOLkEZGHQ5P90WWIs:-L7XOLkEZGHQ5P90WWIt:b-nodi3y) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/engine.go#L25)):*
> int32
bool?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/73)*

**Comment by WTer** [comment]
Review status: 0 of 6 files reviewed at latest revision, 16 unresolved discussions.

---

*[core/tx_pool.go, line 61 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/73#-L7XYAK56SXh1MRLIS8b:-L7XYAK56SXh1MRLIS8c:b4s68qt) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/core/tx_pool.go#L61)):*
> Pending()

Nice to add comments for this function.

---

*[event/manager_instance.go, line 25 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/73#-L7XYIHzGySmGEknL5v-:-L7XYIHzGySmGEknL5v0:b-jsz1b1) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/event/manager_instance.go#L25)):*
> ```Go
> 
> // event of new block inserted into blockchain
> var BlockInsertedEventManager = NewEventManager()
> ```

Take care this warn.
there are some same warns in other source files.

---

*[miner/miner.go, line 84 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/73#-L7XxVKsOqP_JYZzr72r:-L7XxVKsOqP_JYZzr72s:b-kchx31) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/miner.go#L84)):*
> fmt.Printf("Miner is running")

change to log

---

*[miner/miner.go, line 113 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/73#-L7XyJDjo1MIto_26rQ7:-L7XyJDkj31KkCja5tRf:b-g8f0x2) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/miner.go#L113)):*
> engine.Stop()

Will this procedure be terminated when one of engines failed to stop?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/73)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 6 files reviewed at latest revision, 17 unresolved discussions.

---

*[seele/seelebackend.go, line 24 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/73#-L7Y0hlv-8RoEWzZd0rA:-L7Y0hlv-8RoEWzZd0rB:b7zxupy) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/seele/seelebackend.go#L24)):*
> ```Go
> 	ApplyTransaction(coinbase common.Address, tx *types.Transaction) error
> }
> ```

seelebackend.go should be replaced by seeleservice.go, and the function used by miner has been added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/73)*

**Comment by WTer** [comment]
Review status: 0 of 6 files reviewed at latest revision, 19 unresolved discussions.

---

*[miner/miner.go, line 193 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/73#-L7Y04S-wdNkyF-cRHL5:-L7Y04S-wdNkyF-cRHL6:b-2mdb1g) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/miner.go#L193)):*
> saveBlock(result.Block, result.Task)

seems you can refine the definition of this function to merge 2 parameters into one result.

---

*[miner/miner.go, line 253 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/73#-L7Y-PhDCdjYR-kRzTVV:-L7Y-PhDCdjYR-kRzTVW:bny5mzo) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/miner.go#L253)):*
> task *Task

Currently this parameter is not used, can be removed? or you just keep it for the future purpose?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/73)*

**Comment by tianlao** [comment]
Review status: 0 of 6 files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[core/tx_pool.go, line 61 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XYAK56SXh1MRLIS8b:-L7rQ2-f8k7kKxR2Y8Ub:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/core/tx_pool.go#L61)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> Pending()

Nice to add comments for this function.
</blockquote></details>

ok

---

*[core/tx_pool.go, line 66 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XDlYw-r-57MHSSaTB:-L7rQ3MLCMsf8wF3aEY4:b-q8jzb0) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/core/tx_pool.go#L66)):*
<details><summary><i>Previously, herove (Leihao Zhou) wrote…</i></summary><blockquote>

no new line at the end
</blockquote></details>

got it

---

*[event/manager_instance.go, line 19 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XEOjQTC1IaM7f3oiQ:-L7rIC6_EtqYmLCu2gYE:b-1uofme) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/event/manager_instance.go#L19)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

We use VS code and the go plugins (e.g. golint or goreturns) will help to format the code, including the comment style.
</blockquote></details>

Thanks, I will install vs code and go plugins to format our code

---

*[event/manager_instance.go, line 25 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XYIHzGySmGEknL5v-:-L7rIe0-1CGzcDN1IS_e:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/event/manager_instance.go#L25)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

Take care this warn.
there are some same warns in other source files.
</blockquote></details>

ok

---

*[miner/engine.go, line 15 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XGJ187Ph6ZuZe3q_E:-L7rPylS-lAGxzy1R0HP:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/engine.go#L15)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Comment missed. Again, please ensure your IDE use go plugins properly. Tool will help to format the code and prompt the missed necessary comments.
</blockquote></details>

ok

---

*[miner/engine.go, line 25 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XOLkEZGHQ5P90WWIs:-L7rJDQi-P7CMF-HRjKe:bvhgt9n) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/engine.go#L25)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> int32
bool?
</blockquote></details>

any int32 or bool is ok here, but I will use int32 for scalability

---

*[miner/engine.go, line 47 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XIekg9_j86lrslIai:-L7rJasZ4lw3YdxzboZS:bgvcn3m) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/engine.go#L47)):*
>u r right,  CompareAndSwap is needed

---

*[miner/engine.go, line 56 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XJqHz6XGg3FOQJ9Ly:-L7rK3Qk8ddsVOmcXOj7:ba6lqe6) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/engine.go#L56)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

when to set the mining to 0?
</blockquote></details>

I will use CompareAndSwap  to set it

---

*[miner/engine.go, line 64 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XKkQIEvmufky88WAE:-L7rPMaQ60GuXjwRiPfG:b-axg1q) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/engine.go#L64)):*
> It seems for loop is unnecessary, why not read from taskChan directly?
use loop to clear all the task blocked in chan
> All the channels are not closed in current implementation. Is it as expected or will add other API to close the resources?
no need to close

---

*[miner/engine.go, line 83 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XM36627Wisck8r00R:-L7rLpow1e8H776Cz4PF:b-230c3z) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/engine.go#L83)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

according to the min() declaration, the 2nd parameter is stop chan. please double confirm
</blockquote></details>

stop chan is used to stop engine but the 2nd param here is used to stop the out-of-date mining work to start new work

---

*[miner/engine.go, line 92 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XLLr_3wFPjrrIErWX:-L7rMIQ6DCepoVoQyAXN:b-95krks) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/engine.go#L92)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

> break out
return?
</blockquote></details>

break out here,  cause the current mining work is closed by currentChan. What we should do is just stop accept any more task

---

*[miner/miner.go, line 83 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XNHDFD97we8FpqI0e:-L7rNAQi4-yNSGGziSHX:bi5qxdx) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/miner.go#L83)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Pay attention to the thread-safe manner, Load & Store in 2 steps cannot guarantee once purpose.
</blockquote></details>

the mutex is used to guarantee

---

*[miner/miner.go, line 84 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XxVKsOqP_JYZzr72r:-L7rQ-Bj2aUPFjuHrZON:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/miner.go#L84)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> fmt.Printf("Miner is running")

change to log
</blockquote></details>

ok

---

*[miner/miner.go, line 113 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XyJDjo1MIto_26rQ7:-L7rORpHDlb41DKomh4Y:b-usea65) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/miner.go#L113)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> engine.Stop()

Will this procedure be terminated when one of engines failed to stop?
</blockquote></details>

You are right,  we shoud send stop msg to miner.stopChan before stop engine

---

*[miner/miner.go, line 193 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7Y04S-wdNkyF-cRHL5:-L7rOeoy-ZYp3pcU9R1K:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/miner.go#L193)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> saveBlock(result.Block, result.Task)

seems you can refine the definition of this function to merge 2 parameters into one result.
</blockquote></details>

ok

---

*[miner/miner.go, line 253 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7Y-PhDCdjYR-kRzTVV:-L7rOiqxC2wcKgGeKeNt:b-4wfslc) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/miner/miner.go#L253)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> task *Task

Currently this parameter is not used, can be removed? or you just keep it for the future purpose?
</blockquote></details>

use Result as parameter

---

*[seele/seelebackend.go, line 24 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7Y0hlv-8RoEWzZd0rA:-L7rOsqk1IoitN5cktAC:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/seele/seelebackend.go#L24)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

seelebackend.go should be replaced by seeleservice.go, and the function used by miner has been added.
</blockquote></details>

ok

---

*[seele/seelebackend.go, line 27 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XMRcl7umUJJtACMFa:-L7rQ0Qc3Tks2fCd0SCu:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/seele/seelebackend.go#L27)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

whitespaces alignment. Go plugins will help to format the code automatically:)
</blockquote></details>

ok

---

*[seele/seelebackend.go, line 38 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/73#-L7XMe9y1Qw43cN3xzAC:-L7rOxeI0vlUKkyQSUho:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/ecebb887f82a9431825a777adcd59ffe3305c886/seele/seelebackend.go#L38)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Use log instead?
</blockquote></details>

ok

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/73)*

**Pull request closed without merging**
