### PR TITLE
Some bugs fix

### PR DESCRIPTION
**Pull request by WTer**
#1000495, #1000450

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/304)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @WTer, @qqtou, @ypenghui6, @boqiu, and @lucusfly)

---

*[cmd/client/cmd/savekey.go, line 51 at r1](https://reviewable.io/reviews/seeleteam/go-seele/304#-LFaLCNk2res_4V5-CXV:-LFaLCNk2res_4V5-CXW:b-yc1iht) ([raw file](https://github.com/seeleteam/go-seele/blob/3f84661c736b6dbd5df63fb18f2e699d2f39b367/cmd/client/cmd/savekey.go#L51)):*
> ```Go
> 
> 		keystore.StoreKey(*keyFile, pass, &key)
> 		if err != nil {
> ```

which error?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/304)*

**Comment by WTer** [comment]
Review status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @WTer, @qqtou, @ypenghui6, @boqiu, and @lucusfly)

---

*[cmd/client/cmd/savekey.go, line 51 at r1](https://reviewable.io/reviews/seeleteam/go-seele/304#-LFaLCNk2res_4V5-CXV:-LFb2yDu3ZmeYdR59nnd:b-t1jfmv) ([raw file](https://github.com/seeleteam/go-seele/blob/3f84661c736b6dbd5df63fb18f2e699d2f39b367/cmd/client/cmd/savekey.go#L51)):*
> ```
> StoreKey
> ```
it will call writeKeyFile(), in which will return some system errors, such as mkdir fail,  open file and write permission errors, etc.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/304)*

**Comment by lucusfly** [comment]
Review status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @lucusfly, @qqtou, @ypenghui6, and @boqiu)

---

*[cmd/client/cmd/savekey.go, line 51 at r1](https://reviewable.io/reviews/seeleteam/go-seele/304#-LFaLCNk2res_4V5-CXV:-LFb5UvzAj6KWfJ97kjb:bnsxcy1) ([raw file](https://github.com/seeleteam/go-seele/blob/3f84661c736b6dbd5df63fb18f2e699d2f39b367/cmd/client/cmd/savekey.go#L51)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> StoreKey
> ```
it will call writeKeyFile(), in which will return some system errors, such as mkdir fail,  open file and write permission errors, etc.
</blockquote></details>

I didn't see where you set your err.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/304)*

**Comment by WTer** [comment]
Review status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @lucusfly, @qqtou, @ypenghui6, and @boqiu)

---

*[cmd/client/cmd/savekey.go, line 51 at r1](https://reviewable.io/reviews/seeleteam/go-seele/304#-LFaLCNk2res_4V5-CXV:-LFogxQ60SFbGAOyMmHj:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/3f84661c736b6dbd5df63fb18f2e699d2f39b367/cmd/client/cmd/savekey.go#L51)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

I didn't see where you set your err.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/304)*

**Comment by lucusfly** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @qqtou, @ypenghui6, and @boqiu)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/304)*

**Pull request merged**
