### PR TITLE
add node.service

### PR DESCRIPTION
**Pull request by herove**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/42)

### CODE REVIEW

**Comment by reedhong** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[node/service.go, line 12 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/42#-L6UT9-I3I_MVABvixu7:-L6UT9-I3I_MVABvixu8:biwq278) ([raw file](https://github.com/seeleteam/go-seele/blob/3b21b55d4658176e4f4485d65e1091fbb31f35cd/node/service.go#L12)):*
> ```Go
> // Service registers to node after node starts.
> type Service interface {
> 	Protocols() []p2p.Protocol
> ```

you shoud add a comment

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/42)*

**Comment by herove** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[node/service.go, line 12 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/42#-L6UT9-I3I_MVABvixu7:-L6UUEKWuehLiSCRwRl5:b-7rl0kd) ([raw file](https://github.com/seeleteam/go-seele/blob/3b21b55d4658176e4f4485d65e1091fbb31f35cd/node/service.go#L12)):*
<details><summary><i>Previously, reedhong (reedhong) wrote…</i></summary><blockquote>

you shoud add a comment
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/42)*

**Comment by reedhong** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/42)*

**Comment by reedhong** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/42)*

**Pull request merged**
