### PR TITLE
create contract address in the same shard with account address

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/205)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---

*[common/shard.go, line 17 at r1](https://reviewable.io/reviews/seeleteam/go-seele/205#-LDF55ttCqy6S3N74QPV:-LDF55tuBgBpFo62t_gk:bnak8jt) ([raw file](https://github.com/seeleteam/go-seele/blob/4d77d6aa81e9f62029081fd23f35b2ac1505872e/common/shard.go#L17)):*
> ```Go
> 
> // IsShardDisabled indicates if the shard is disabled.
> // THIS IS FOR TEST PURPOSE ONLY!!!
> ```

UNIT TEST

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/205)*

**Comment by lucusfly** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/205)*

**Comment by boqiu** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/shard.go, line 17 at r1](https://reviewable.io/reviews/seeleteam/go-seele/205#-LDF55ttCqy6S3N74QPV:-LDFEn1n3BhfPLY2knpz:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/4d77d6aa81e9f62029081fd23f35b2ac1505872e/common/shard.go#L17)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

UNIT TEST
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/205)*

**Comment by lucusfly** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/205)*

**Pull request merged**
