### PR TITLE
remove tx from tx pool after mining

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/121)

### CODE REVIEW

**Comment by WTer** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/121)*

**Comment by boqiu** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[core/tx_pool.go, line 110 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/121#-L9tQWwl1ppgEWzWFTDk:-L9tQWwl1ppgEWzWFTDl:bavz2oz) ([raw file](https://github.com/seeleteam/go-seele/blob/f7398840692f08af91eae456c52939b3ddee484b/core/tx_pool.go#L110)):*
> ```
> return
> ```
unnecessary

---

*[seele/download/downloader.go, line 186 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/121#-L9tQusq3fpHuB99p8pl:-L9tQusq3fpHuB99p8pm:b5pqqgb) ([raw file](https://github.com/seeleteam/go-seele/blob/d786de26a70aed4a3f5f06e8965d2d68e24bad64/seele/download/downloader.go#L186)):*
> ```Go
> 	block, _ := d.chain.CurrentBlock()
> 	localHeight := block.Header.Height
> 	if localHeight == 0 {
> ```

Not latest code?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/121)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[core/tx_pool.go, line 110 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/121#-L9tQWwl1ppgEWzWFTDk:-L9tRyo_-92YuK5zYHUM:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f7398840692f08af91eae456c52939b3ddee484b/core/tx_pool.go#L110)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

> ```
> return
> ```
unnecessary
</blockquote></details>

Done.

---

*[seele/download/downloader.go, line 186 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/121#-L9tQusq3fpHuB99p8pl:-L9tSAXe1ZrUMy_JZ0Lc:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/d786de26a70aed4a3f5f06e8965d2d68e24bad64/seele/download/downloader.go#L186)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Not latest code?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/121)*

**Comment by boqiu** [comment]
Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/121)*

**Pull request merged**
