### PR TITLE
add getblock rpc api & cmd

### PR DESCRIPTION
**Pull request by wuliaodw88**
add getblockheight getblockbyheight getblockbyhash rpc api & cmd

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/140)

### CODE REVIEW

**Comment by webbergao1** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[seele/api.go, line 113 at r1](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBZeim-2x1B_ev-bSKk:-LBZgxQC5ZJJp8_ktZID:b-312hgh) ([raw file](https://github.com/seeleteam/go-seele/blob/362feab771dfb4bb1f2714b5dfb613074cfeeb81/seele/api.go#L113)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

fullTx missing
</blockquote></details>

Should we return all the information to the user? For example 'TxHash' or 'StateHash'

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/140)*

**Comment by webbergao1** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[seele/api.go, line 126 at r1](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBZiClk7HFBLnxwLT6c:-LBZiClk7HFBLnxwLT6d:b-312hgh) ([raw file](https://github.com/seeleteam/go-seele/blob/362feab771dfb4bb1f2714b5dfb613074cfeeb81/seele/api.go#L126)):*
> ```Go
> 		return err
> 	}
> 	*block = *pBlock
> ```

Should we return all the information to the user? For example 'TxHash' or 'StateHash'

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/140)*

**Comment by wuliaodw88** [comment]
*[cmd/client/cmd/getblockbyhash.go, line 63 at r1](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBZcqUBASYrXWXZPcN2:-LBcthj70QjfxkXJe-Kv:b-1x5o3n) ([raw file](https://github.com/seeleteam/go-seele/blob/362feab771dfb4bb1f2714b5dfb613074cfeeb81/cmd/client/cmd/getblockbyhash.go#L63)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

use s as short don't make sense
</blockquote></details>

h is uesd,i use k to express the meaning of key,or i will not use short for this flag

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/140)*

**Comment by wuliaodw88** [comment]
*[cmd/client/cmd/getblockbynumber.go, line 49 at r1](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBZdAah54Ul99Jg-OSM:-LBcv1eFAgWiq6ssFwEG:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/362feab771dfb4bb1f2714b5dfb613074cfeeb81/cmd/client/cmd/getblockbynumber.go#L49)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> 		fmt.Printf("block hash: %s\n", block.HeaderHash.ToHex())
> 		fmt.Printf("block height: %d\n", block.Header.Height)
> 		fmt.Printf("block creator: %s\n", block.Header.Creator.ToHex())
> 		fmt.Printf("block previousBlockHash: %s\n", block.Header.PreviousBlockHash.ToHex())
> 		fmt.Printf("block stateHash: %s\n", block.Header.StateHash.ToHex())
> 		fmt.Printf("block txHash: %s\n", block.Header.TxHash.ToHex())
> 		fmt.Printf("block nonce: %d\n", block.Header.Nonce)
> 		fmt.Printf("block difficulty: %d\n", block.Header.Difficulty)
> 		fmt.Printf("block createTimestamp: %d\n", block.Header.CreateTimestamp)
> 		for index, transaction := range block.Transactions {
> 			fmt.Printf("block transaction %d hash: %s\n", index, transaction.Hash.ToHex())
> 			fmt.Printf("block transaction %d from: %s\n", index, transaction.Data.From.ToHex())
> 			fmt.Printf("block transaction %d to: %s\n", index, transaction.Data.To.ToHex())
> 			fmt.Printf("block transaction %d amount: %d\n", index, transaction.Data.Amount)
> 			fmt.Printf("block transaction %d payload: %d\n", index, transaction.Data.Payload)
> 			fmt.Printf("block transaction %d nonce: %d\n", index, transaction.Data.AccountNonce)
> 			fmt.Printf("block transaction %d timestamp: %d\n", index, transaction.Data.Timestamp)
> 		}
> ```


duplicate code
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/140)*

**Comment by wuliaodw88** [comment]
*[seele/api.go, line 89 at r1](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBZdhSKDO20ZnKkuDLX:-LBcv7c6CyDgxAOdypEq:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/362feab771dfb4bb1f2714b5dfb613074cfeeb81/seele/api.go#L89)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

where is fullTx? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/140)*

**Comment by wuliaodw88** [comment]
*[seele/api.go, line 90 at r1](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBZdkjh71XlYow6u2LO:-LBcv9ZGAPsQGOlhw5gl:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/362feab771dfb4bb1f2714b5dfb613074cfeeb81/seele/api.go#L90)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> numberStr string
> ```

use uint64 instead of string
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/140)*

**Comment by wuliaodw88** [comment]
*[seele/api.go, line 113 at r1](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBZeim-2x1B_ev-bSKk:-LBcvXNF6gHgPBxY-rpX:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/362feab771dfb4bb1f2714b5dfb613074cfeeb81/seele/api.go#L113)):*
<details><summary><i>Previously, webbergao1 (weibogao) wrote…</i></summary><blockquote>

Should we return all the information to the user? For example 'TxHash' or 'StateHash'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/140)*

**Comment by wuliaodw88** [comment]
*[seele/api.go, line 126 at r1](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBZiClk7HFBLnxwLT6c:-LBcv_Y85REvx0033HaU:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/362feab771dfb4bb1f2714b5dfb613074cfeeb81/seele/api.go#L126)):*
<details><summary><i>Previously, webbergao1 (weibogao) wrote…</i></summary><blockquote>

Should we return all the information to the user? For example 'TxHash' or 'StateHash'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/140)*

**Comment by lucusfly** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/client/cmd/getblockbyhash.go, line 63 at r1](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBZcqUBASYrXWXZPcN2:-LBdANXVDK999-EBn2Yf:bibpg4v) ([raw file](https://github.com/seeleteam/go-seele/blob/362feab771dfb4bb1f2714b5dfb613074cfeeb81/cmd/client/cmd/getblockbyhash.go#L63)):*
<details><summary><i>Previously, wuliaodw88 (Anzai) wrote…</i></summary><blockquote>

h is uesd,i use k to express the meaning of key,or i will not use short for this flag
</blockquote></details>

key don't make sense for me. if there is no better shorthand, I suggest not use.

---

*[cmd/client/cmd/getblockbyhash.go, line 62 at r2](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBdAG7UBKvyGGFCe3oc:-LBdAG7VCrPPiKce6WTU:b-b32ni) ([raw file](https://github.com/seeleteam/go-seele/blob/ca69c67f179e05beab781ae9e68d8764a05f3c4e/cmd/client/cmd/getblockbyhash.go#L62)):*
> ```Go
> 	getblockbyhashCmd.MarkFlagRequired("hash")
> 
> 	fullTx = getblockbyhashCmd.Flags().StringP("fulltx", "f", "false", "is add full tx, default is false")
> ```

why not use Bool?

---

*[seele/api.go, line 127 at r2](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBdCdKDBgpb4wNWI5bw:-LBdCdKDBgpb4wNWI5bx:b-78vig2) ([raw file](https://github.com/seeleteam/go-seele/blob/ca69c67f179e05beab781ae9e68d8764a05f3c4e/seele/api.go#L127)):*
> ```
> request *GetBlockByHashRequest
> ```

this rpc usage is painful. As you guys will write so many rpc APIs later, I suggest you implement multiple parameters for rpc call first.

---

*[seele/api.go, line 161 at r2](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBdBPaL4FPs6Iizeo-M:-LBdBPaL4FPs6Iizeo-N:b-lsl7rn) ([raw file](https://github.com/seeleteam/go-seele/blob/ca69c67f179e05beab781ae9e68d8764a05f3c4e/seele/api.go#L161)):*
> ```Go
> 	}
> 
> 	formatTx := func(tx *types.Transaction) (interface{}, error) {
> ```

I don't think you need an anonymous function to do it. if is enough.

---

*[cmd/client/cmd/getblockbynumber.go, line 47 at r2](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBdCIeVAGl6dFYyqakr:-LBdCIeVAGl6dFYyqaks:b82weqm) ([raw file](https://github.com/seeleteam/go-seele/blob/ca69c67f179e05beab781ae9e68d8764a05f3c4e/cmd/client/cmd/getblockbynumber.go#L47)):*
> ```Go
> 		}
> 
> 		jsonResult, err := json.Marshal(result)
> ```

better print json pretty.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/140)*

**Comment by WTer** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[cmd/client/cmd/getblockbyhash.go, line 27 at r3](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBdXA5M1xABThYXCbqR:-LBdXA5M1xABThYXCbqS:b-xjp08g) ([raw file](https://github.com/seeleteam/go-seele/blob/aabd68bc0e670a01feaf6c8444ad5d83ade17661/cmd/client/cmd/getblockbyhash.go#L27)):*
> ```
> [-f true] [-a...
> ```
nice to add detailed info for these 2 parameters, such as -f: Print full transaction info

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/140)*

**Comment by wuliaodw88** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[cmd/client/cmd/getblockbyhash.go, line 63 at r1](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBZcqUBASYrXWXZPcN2:-LBde2mf8ixzALBlU2Og:bqg6yvj) ([raw file](https://github.com/seeleteam/go-seele/blob/362feab771dfb4bb1f2714b5dfb613074cfeeb81/cmd/client/cmd/getblockbyhash.go#L63)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

key don't make sense for me. if there is no better shorthand, I suggest not use.
</blockquote></details>

yes,i cancel short already

---

*[cmd/client/cmd/getblockbyhash.go, line 62 at r2](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBdAG7UBKvyGGFCe3oc:-LBdeK6VCDbPXmgXg7lD:by5gxw6) ([raw file](https://github.com/seeleteam/go-seele/blob/ca69c67f179e05beab781ae9e68d8764a05f3c4e/cmd/client/cmd/getblockbyhash.go#L62)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

why not use Bool?
</blockquote></details>

bool has some problem,i will consult you

---

*[cmd/client/cmd/getblockbyhash.go, line 27 at r3](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBdXA5M1xABThYXCbqR:-LBddeR86EXQCO6ocPki:bojjalt) ([raw file](https://github.com/seeleteam/go-seele/blob/aabd68bc0e670a01feaf6c8444ad5d83ade17661/cmd/client/cmd/getblockbyhash.go#L27)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> [-f true] [-a...
> ```
nice to add detailed info for these 2 parameters, such as -f: Print full transaction info
</blockquote></details>

detail will be display when input --help,this is just an example

---

*[seele/api.go, line 95 at r2](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBctvXJ6rPwT7bZ7QRb:-LBdCuQq5qirZHpRnZVC:b-cjbne2) ([raw file](https://github.com/seeleteam/go-seele/blob/ca69c67f179e05beab781ae9e68d8764a05f3c4e/seele/api.go#L95)):*
<details><summary><i>Previously, webbergao1 (weibogao) wrote…</i></summary><blockquote>

The function named 'GetBlockByNumber' should be changed to 'GetBlockByHeight' ? Because in our block struct it's called 'Height'
</blockquote></details>

Good opinion,i rename all Number to Height inthis pr

---

*[seele/api.go, line 127 at r2](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBdCdKDBgpb4wNWI5bw:-LBdcwbsE9RA1O2d9LXk:b1jnnh2) ([raw file](https://github.com/seeleteam/go-seele/blob/ca69c67f179e05beab781ae9e68d8764a05f3c4e/seele/api.go#L127)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> request *GetBlockByHashRequest
> ```

this rpc usage is painful. As you guys will write so many rpc APIs later, I suggest you implement multiple parameters for rpc call first.
</blockquote></details>

use different structs's advantage is that the user can  understand the rules of incoming parameters better.

---

*[seele/api.go, line 161 at r2](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBdBPaL4FPs6Iizeo-M:-LBddCyx5HwjN-9i7Mu5:b6d4y8t) ([raw file](https://github.com/seeleteam/go-seele/blob/ca69c67f179e05beab781ae9e68d8764a05f3c4e/seele/api.go#L161)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

I don't think you need an anonymous function to do it. if is enough.
</blockquote></details>

if use if,it means every item in range will be judge once,i think it is not elegant

---

*[cmd/client/cmd/getblockbynumber.go, line 47 at r2](https://reviewable.io/reviews/seeleteam/go-seele/140#-LBdCIeVAGl6dFYyqakr:-LBdeexK4m4wWc7zZjEe:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/ca69c67f179e05beab781ae9e68d8764a05f3c4e/cmd/client/cmd/getblockbynumber.go#L47)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

better print json pretty.
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/140)*

**Comment by lucusfly** [comment]
Reviewed 1 of 8 files at r3, 3 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/140)*

**Comment by WTer** [comment]
Reviewed 1 of 8 files at r3, 3 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/140)*

**Pull request merged**
