### PR TITLE
add websocket

### PR DESCRIPTION
**Pull request by wuliaodw88**
Add websocket&Delete cmd json

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/175)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 35 files reviewed at latest revision, all discussions resolved.

---

*[node/node.go, line 153 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCfuVRbBkm2TgoPFYHA:-LCfuVRc6G0zyky8ObwJ:b-40a7lx) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/node/node.go#L153)):*
> ```Go
> 	if err := n.startWSRPC(apis); err != nil {
> 		n.log.Error("start websocket err", err)
> 		return err
> ```

Just double confirm, once error occurred, is it necessary to close the previous started RPC (JSON & HTTP)?

---

*[rpc/websocket.go, line 48 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCfurr8-YewsMaZUVKw:-LCfurr8-YewsMaZUVKx:b-47g022) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/rpc/websocket.go#L48)):*
> ```Go
> func ServeWS(w http.ResponseWriter, r *http.Request) {
> 	ws, err := upgrader.Upgrade(w, r, nil)
> 	defer ws.Close()
> ```

do you expect to call Close() even error occurred?

---

*[rpc/websocket.go, line 60 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCfvWnS6G71FylUf51b:-LCfvWnS6G71FylUf51c:brnvgxd) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/rpc/websocket.go#L60)):*
> ```Go
> // Read represents read data from websocket connection.
> func (wc *WebsocketServerConn) Read(p []byte) (n int, err error) {
> 	if wc.r == nil {
> ```

not thread safe

---

*[rpc/websocket.go, line 79 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCfvj4p1WZL8loGydx5:-LCfvj4p1WZL8loGydx6:brnvgxd) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/rpc/websocket.go#L79)):*
> ```Go
> // Write represents write data for websocket connection.
> func (wc *WebsocketServerConn) Write(p []byte) (n int, err error) {
> 	if wc.w == nil {
> ```

not thread safe

---

*[rpc/websocket.go, line 97 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCfw1s1AqMjK_Ej6yBA:-LCfw1s1AqMjK_Ej6yBB:brnvgxd) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/rpc/websocket.go#L97)):*
> ```Go
> // Close represents close the websocket connection.
> func (wc *WebsocketServerConn) Close() (err error) {
> 	if wc.w != nil {
> ```

not thread safe

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/175)*

**Comment by gongliaoan** [comment]
Review status: 0 of 35 files reviewed at latest revision, 8 unresolved discussions.

---

*[node/node.go, line 224 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCgba7w9ddvbKtLYsWx:-LCgba7w9ddvbKtLYsWy:bqdhf9e) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/node/node.go#L224)):*
> ```Go
> func (n *Node) startWSRPC(apis []rpc.API) error {
> 	for _, api := range apis {
> 		if err := netrpc.RegisterName(api.Namespace, api.Service); err != nil {
> ```

 netrpc is not json-rpc2.0

need create NewWSServer() to get the rpc in seele and not use net/rpc.

---

*[rpc/websocket.go, line 46 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCgazrE5LZ1b0supfd_:-LCgazrE5LZ1b0supfda:bm4iv13) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/rpc/websocket.go#L46)):*
> ```Go
> 
> // ServeWS runs the JSON-RPC server on a single websocket connection.
> func ServeWS(w http.ResponseWriter, r *http.Request) {
> ```

the func name is ServerWS?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/175)*

**Comment by lucusfly** [comment]
Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/175)*

**Comment by gongliaoan** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[cmd/client/cmd/cmd.go, line 18 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCgh57fEM-5249niVSv:-LCgh57fEM-5249niVSw:b-re7v88) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/cmd/client/cmd/cmd.go#L18)):*
> ```Go
> )
> 
> func init() {
> ```

need add client to use websorcket.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/175)*

**Comment by wuliaodw88** [comment]
Review status: 25 of 35 files reviewed at latest revision, 11 unresolved discussions.

---

*[cmd/client/cmd/cmd.go, line 18 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCgh57fEM-5249niVSv:-LChKJaHE9oCeorVGEiI:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/cmd/client/cmd/cmd.go#L18)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

need add client to use websorcket.
</blockquote></details>

Done.

---

*[cmd/node/cmd/config.go, line 82 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCgW4xTAhmz9fO7VKAx:-LChU13L3HpchfUFKYFt:b-efnm2s) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/cmd/node/cmd/config.go#L82)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> WSServer
> ```

rename to WSServerConfig. and also use this struct in node config.
</blockquote></details>

it is in config.go, so i think we can omit suffix

---

*[cmd/node/cmd/config.go, line 84 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCgWDPl9i5I4nSE4pzJ:-LChTnms8_7s33Z5x4Nk:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/cmd/node/cmd/config.go#L84)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> WSAddr string
> ```

define `json` name
</blockquote></details>

Done.

---

*[cmd/node/config/node1.json, line 24 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCgWToF-OcRp3nVWMeC:-LChKOFR4degsdtmLf-N:b-50j456) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/cmd/node/config/node1.json#L24)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

too many addresses in our services. Could we merge them to one?
</blockquote></details>

they have different ports

---

*[node/node.go, line 153 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCfuVRbBkm2TgoPFYHA:-LChKan99KNdallUIGre:bqfxv7p) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/node/node.go#L153)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Just double confirm, once error occurred, is it necessary to close the previous started RPC (JSON & HTTP)?
</blockquote></details>

yes, when one of this three services has error, all will be closed by parent method 

---

*[node/node.go, line 224 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCgba7w9ddvbKtLYsWx:-LChLjeu3mKebFfoHuUB:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/node/node.go#L224)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

 netrpc is not json-rpc2.0

need create NewWSServer() to get the rpc in seele and not use net/rpc.

</blockquote></details>

Done.

---

*[rpc/websocket.go, line 46 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCgazrE5LZ1b0supfd_:-LChFBI1E9fGHsOunawe:b2nign6) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/rpc/websocket.go#L46)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

the func name is ServerWS?
</blockquote></details>

yes

---

*[rpc/websocket.go, line 48 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCfurr8-YewsMaZUVKw:-LChIBokDdCRUOx-cYEV:b-qrhlnm) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/rpc/websocket.go#L48)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

do you expect to call Close() even error occurred?
</blockquote></details>

yes,when error it will be closed by itself, but call Close() will make no difference

---

*[rpc/websocket.go, line 60 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCfvWnS6G71FylUf51b:-LChJC6iE2l4C5OeqDBv:bycy9me) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/rpc/websocket.go#L60)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

not thread safe
</blockquote></details>

it implemented io interface and called by toolkit, i think thread safe  has been taken into by toolkit already

---

*[rpc/websocket.go, line 79 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCfvj4p1WZL8loGydx5:-LChKFXw422Ut4fmecQo:b-5rk6uk) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/rpc/websocket.go#L79)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

not thread safe
</blockquote></details>

it implemented io interface and called by toolkit, i think thread safe  has been taken into by toolkit already

---

*[rpc/websocket.go, line 97 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCfw1s1AqMjK_Ej6yBA:-LChKH2z8YNsK0ruv302:b-5rk6uk) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/rpc/websocket.go#L97)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

not thread safe
</blockquote></details>

it implemented io interface and called by toolkit, i think thread safe  has been taken into by toolkit already

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/175)*

**Comment by lucusfly** [comment]
Review status: 25 of 35 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cmd/node/cmd/config.go, line 82 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCgW4xTAhmz9fO7VKAx:-LCl7aGN-F2-vPX8_TTf:b-wrsor9) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/cmd/node/cmd/config.go#L82)):*
<details><summary><i>Previously, wuliaodw88 (Anzai) wrote…</i></summary><blockquote>

it is in config.go, so i think we can omit suffix
</blockquote></details>

node config also have these parameter. better to use the same one.

---

*[cmd/node/cmd/config.go, line 84 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCgWDPl9i5I4nSE4pzJ:-LCl5eGICxxXSyzvrxzG:b-z6smty) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/cmd/node/cmd/config.go#L84)):*
<details><summary><i>Previously, wuliaodw88 (Anzai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

json name always is lowercase. Suggest use address and patter.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/175)*

**Comment by wuliaodw88** [comment]
Review status: 24 of 35 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cmd/node/cmd/config.go, line 82 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCgW4xTAhmz9fO7VKAx:-LClLr0_Ef1XyDwy_hD8:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/cmd/node/cmd/config.go#L82)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

node config also have these parameter. better to use the same one.
</blockquote></details>

Done.

---

*[cmd/node/cmd/config.go, line 84 at r1](https://reviewable.io/reviews/seeleteam/go-seele/175#-LCgWDPl9i5I4nSE4pzJ:-LClLrm34CjA5Yw8vfOI:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/05881f5b8111a029ffd6f9ad6393820bee4e4dd8/cmd/node/cmd/config.go#L84)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

json name always is lowercase. Suggest use address and patter.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/175)*

**Comment by lucusfly** [comment]
Review status: 24 of 35 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[cmd/node/cmd/config.go, line 120 at r2](https://reviewable.io/reviews/seeleteam/go-seele/175#-LClwGly8rBjNU8LbuJH:-LClwGly8rBjNU8LbuJI:b-h2z248) ([raw file](https://github.com/seeleteam/go-seele/blob/faa926a5a8406cc501bc0a6606db3ed5a296f231/cmd/node/cmd/config.go#L120)):*
> ```
> 	nodeConfig.WSServerConfig.WSAddr = config.WSServerConfig.WSAddr
> 	nodeConfig.WSServerConfig.WSPattern = config.WSServerConfig.WSPattern
> ```

nodeConfig.WSServerConfig = config.WSServerConfig

---

*[rpc/websocket.go, line 26 at r2](https://reviewable.io/reviews/seeleteam/go-seele/175#-LClvzQUCsEwb7jgdQcu:-LClvzQUCsEwb7jgdQcv:btrqlfs) ([raw file](https://github.com/seeleteam/go-seele/blob/faa926a5a8406cc501bc0a6606db3ed5a296f231/rpc/websocket.go#L26)):*
> ```
> json:"wsaddr"
> ```

call address as it is already in WS

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/175)*

**Comment by wuliaodw88** [comment]
Review status: 24 of 35 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cmd/node/cmd/config.go, line 120 at r2](https://reviewable.io/reviews/seeleteam/go-seele/175#-LClwGly8rBjNU8LbuJH:-LCm6U0WDN1ZBVDVlVkC:btpte1o) ([raw file](https://github.com/seeleteam/go-seele/blob/faa926a5a8406cc501bc0a6606db3ed5a296f231/cmd/node/cmd/config.go#L120)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> 	nodeConfig.WSServerConfig.WSAddr = config.WSServerConfig.WSAddr
> 	nodeConfig.WSServerConfig.WSPattern = config.WSServerConfig.WSPattern
> ```

nodeConfig.WSServerConfig = config.WSServerConfig
</blockquote></details>

fixed it

---

*[rpc/websocket.go, line 26 at r2](https://reviewable.io/reviews/seeleteam/go-seele/175#-LClvzQUCsEwb7jgdQcu:-LCm6Vo4-GJM120C9-nb:btpte1o) ([raw file](https://github.com/seeleteam/go-seele/blob/faa926a5a8406cc501bc0a6606db3ed5a296f231/rpc/websocket.go#L26)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> json:"wsaddr"
> ```

call address as it is already in WS
</blockquote></details>

fixed it

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/175)*

**Comment by lucusfly** [comment]
Reviewed 7 of 11 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/175)*

**Comment by boqiu** [comment]
Reviewed 24 of 35 files at r1, 7 of 11 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/175)*

**Comment by boqiu** [comment]
Review status: 32 of 35 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[monitor/api_test.go, line 48 at r4](https://reviewable.io/reviews/seeleteam/go-seele/175#-LD-aAs39eVOXCQIzQo1:-LD-aAs39eVOXCQIzQo2:bhe0br8) ([raw file](https://github.com/seeleteam/go-seele/blob/82b62c64791a185cf23cb689edaccd7a2a6e8e01/monitor/api_test.go#L48)):*
> ```
> },
> ```

new line.

---

*[node/node_test.go, line 26 at r4](https://reviewable.io/reviews/seeleteam/go-seele/175#-LD-aDusEmxnt4XZ6Hq7:-LD-aDusEmxnt4XZ6Hq8:bhe0br8) ([raw file](https://github.com/seeleteam/go-seele/blob/82b62c64791a185cf23cb689edaccd7a2a6e8e01/node/node_test.go#L26)):*
> ```
> },
> ```

new line.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/175)*

**Comment by lucusfly** [comment]
Review status: 31 of 35 files reviewed at latest revision, 2 unresolved discussions.

---

*[rpc/websocket_test.go, line 27 at r5](https://reviewable.io/reviews/seeleteam/go-seele/175#-LD-emsI72JkrtEml1LJ:-LD-emsJE0cyPtTsWgAM:b-i60hub) ([raw file](https://github.com/seeleteam/go-seele/blob/d9bddc037b3d369058b03216ed69ed4df21ef783/rpc/websocket_test.go#L27)):*
> ```
> go func() {
> ```

these codes will not run in test

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/175)*

**Comment by wuliaodw88** [comment]
Review status: 31 of 35 files reviewed at latest revision, 3 unresolved discussions.

---

*[monitor/api_test.go, line 48 at r4](https://reviewable.io/reviews/seeleteam/go-seele/175#-LD-aAs39eVOXCQIzQo1:-LD-eqX09iRnv-6Ftsbo:btpte1o) ([raw file](https://github.com/seeleteam/go-seele/blob/82b62c64791a185cf23cb689edaccd7a2a6e8e01/monitor/api_test.go#L48)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> },
> ```

new line.
</blockquote></details>

fixed it

---

*[node/node_test.go, line 26 at r4](https://reviewable.io/reviews/seeleteam/go-seele/175#-LD-aDusEmxnt4XZ6Hq7:-LD-etxy885agsIMkXBt:btpte1o) ([raw file](https://github.com/seeleteam/go-seele/blob/82b62c64791a185cf23cb689edaccd7a2a6e8e01/node/node_test.go#L26)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> },
> ```

new line.
</blockquote></details>

fixed it

---

*[rpc/websocket_test.go, line 27 at r5](https://reviewable.io/reviews/seeleteam/go-seele/175#-LD-emsI72JkrtEml1LJ:-LD-giQt5jRol5DPNw0V:btpte1o) ([raw file](https://github.com/seeleteam/go-seele/blob/d9bddc037b3d369058b03216ed69ed4df21ef783/rpc/websocket_test.go#L27)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> go func() {
> ```

these codes will not run in test
</blockquote></details>

fixed it

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/175)*

**Comment by boqiu** [comment]
Reviewed 1 of 3 files at r4, 2 of 3 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/175)*

**Comment by lucusfly** [comment]
Reviewed 1 of 3 files at r4, 2 of 3 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/175)*

**Comment by wuliaodw88** [comment]
add websocket

**Pull request merged**
