### PR TITLE
add miner module

### PR DESCRIPTION
**Pull request by tianlao**
add miner directory which includes miner.go and engine.go, add some function into blockchain and tx_pool

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/83)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[miner/engine.go, line 16 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/83#-L7vzRzA6OwMuxeGkgwA:-L7vzRzA6OwMuxeGkgwB:b-6chrve) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/engine.go#L16)):*
> CPUEngine

why do you add this consensus implementation instead of using pow sha3?

---

*[miner/miner.go, line 49 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/83#-L7vzwE5Dq8Bf_Xbmh-5:-L7vzwE5Dq8Bf_Xbmh-6:btao8ac) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L49)):*
> Miner

nice to indent all members of it

---

*[miner/miner.go, line 290 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/83#-L7w0_zY6Qajg32bHVi9:-L7w0_zY6Qajg32bHViA:b-m2tmww) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L290)):*
> // execute tx

how can we understand 'execute'?  verify tx's information, or pack it into block? 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/83)*

**Comment by boqiu** [comment]
Review status: 0 of 5 files reviewed at latest revision, 14 unresolved discussions.

---

*[core/tx_pool.go, line 102 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7vy--UlE6JkIyz6uVg:-L7vy--VzqlGi8NFBr4q:b-u6ae01) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/core/tx_pool.go#L102)):*
> ```Go
> 
> // Pending returns the pending transactions in the transaction pool.
> func (pool *TransactionPool) Pending() ([]*types.Transaction, error) {
> ```

Please refer to the existing API  GetProcessableTransactions() map[common.Address][]*types.Transaction

---

*[miner/engine.go, line 22 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w0Xi7GOQW3w0rHyCw:-L7w0Xi7GOQW3w0rHyCx:b-ygqm8o) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/engine.go#L22)):*
> ```Go
> 	stopChan    chan struct{}
> 	retChan     chan<- *Result
> 	currentChan chan struct{}
> ```

from the API "mine", I think the right variable name is "taskStopChan" or "currentTaskStopChan"

---

*[miner/engine.go, line 41 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7vz769rx_h02zYJ-EH:-L7vz769rx_h02zYJ-EI:b-5ypyrq) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/engine.go#L41)):*
> Task()

TaskChan()?

---

*[miner/engine.go, line 84 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w-_i_5QJNi_FSmvbA:-L7w-_i_5QJNi_FSmvbB:b-z4i9im) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/engine.go#L84)):*
> ```Go
> 		case work := <-eng.taskChan:
> 			eng.mutex.Lock()
> 			if eng.currentChan != nil {
> ```

The currentChan is used to stop the current task, right? If so, why not write the chan and wait for completion signal?

Otherwise, use READ chan in the task goroutine to stop mining.

---

*[miner/engine.go, line 102 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w1jNWbcyY-SHYeVr8:-L7w1jNWbcyY-SHYeVr9:b3bx6go) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/engine.go#L102)):*
> ```Go
> }
> 
> func (eng *CPUEngine) mine(work *Task, stop chan<- struct{}) {
> ```

WRITE channel or READ channel to notify the current mining task to stop?

---

*[miner/miner.go, line 26 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w27jv8AEHaBEIqSrW:-L7w27jv8AEHaBEIqSrX:b-7646rd) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L26)):*
> ```Go
> 	header *types.BlockHeader
> 	txs    []*types.Transaction
> 	txNum  int32
> ```

uint32 to avoid negative value?

On the other hand, the txNum is unnecessary if txNum == len(txs)

---

*[miner/miner.go, line 37 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w2_FMnvtqZX_63nz4:-L7w2_FMnvtqZX_63nz5:b-fsi9tz) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L37)):*
> ```Go
> type Result struct {
> 	Task  *Task
> 	Block *types.Block // mined block
> ```

what's the difference between the "block in task" and the mined block? If possible, add necessary comments to avoid confuse.

---

*[miner/miner.go, line 90 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w4Mn-IRE5giswkLPl:-L7w4Mn-IRE5giswkLPm:b-arom72) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L90)):*
> ```Go
> // Start function is used to start miner
> func (miner *Miner) Start() bool {
> 	miner.mutex.Lock()
> ```

It's better to use double check pattern for miner.minging

---

*[miner/miner.go, line 103 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w5E5-LrcNNOw4K-66:-L7w5E5-LrcNNOw4K-67:b-plbuad) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L103)):*
> ```Go
> 	}
> 
> 	atomic.StoreInt32(&miner.mining, 1)
> ```

convert load/store to compareandswap?

---

*[miner/miner.go, line 159 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w6EEJUwZ_zd8lQVns:-L7w6EEJUwZ_zd8lQVnt:b-t87dq2) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L159)):*
> ```Go
> 
> func (miner *Miner) downloadEventCallback(e event.Event) {
> 	p := e.(int)
> ```

meaningful variable name is always better:)

---

*[miner/miner.go, line 191 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w6hdasSsj2viQClba:-L7w6hdasSsj2viQClbb:blcv5a9) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L191)):*
> ```Go
> 			miner.prepareNewBlock()
> 		case <-miner.stopChan:
> 			miner.stopChan <- struct{}{}
> ```

Why write a data to the same stopChan again? If possible, please add necessary comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/83)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 15 unresolved discussions.

---

*[miner/miner.go, line 125 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7wIctzlShOC3u7dO_A:-L7wIctzlShOC3u7dO_B:b-wf630x) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L125)):*
> ```Go
> 	atomic.StoreInt32(&miner.mining, 0)
> 	miner.stopChan <- struct{}{}
> ```

should use close(miner.stopChan) like p2p.server.quit channel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/83)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 15 unresolved discussions.

---

*[miner/miner.go, line 191 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w6hdasSsj2viQClba:-L7wf476AiHZdYu8vERp:b-jd4tep) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L191)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Why write a data to the same stopChan again? If possible, please add necessary comment.
</blockquote></details>

If close stopChan in function Stop, this line is not required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/83)*

**Comment by WTer** [comment]
Review status: 0 of 5 files reviewed at latest revision, 15 unresolved discussions.

---

*[miner/miner.go, line 202 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/83#-L7xaqs82Sz6XQ5eW3Ep:-L7xaqs82Sz6XQ5eW3Eq:b16570q) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L202)):*
> if result == nil

when will this result be nil?

---

*[miner/miner.go, line 209 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/83#-L7xbgOb8hugtUncKIFF:-L7xbgOb8hugtUncKIFG:b-irgh9g) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L209)):*
> continue

so when failed to save block, we just discard this block, which means all txs in this block will be lost, right?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/83)*

**Comment by WTer** [comment]
Review status: 0 of 5 files reviewed at latest revision, 17 unresolved discussions.

---

*[miner/miner.go, line 217 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/83#-L7xbuA-E2H-KPaJul9w:-L7xbuA-E2H-KPaJul9x:b-klow16) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L217)):*
> miner.stopChan <- struct{}{}

why do you add this?

---

*[miner/miner.go, line 232 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/83#-L7xd9vG4TdLhIpQdtNz:-L7xd9vG4TdLhIpQdtO-:bexku11) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L232)):*
> 1

nice to define this magic number 1 as constant var with meaningful name.
also for the following 1 in statement 'now+1'

---

*[miner/miner.go, line 238 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/83#-L7xdRGc-jrN9y35Qa1q:-L7xdRGc-jrN9y35Qa1r:b-w151t5) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L238)):*
> time.Sleep(wait)

this is very vulnerable, suppose adversary change the local time between 
tstart := time.Now()
and 
now:= time.Now

to make their difference so large, then this process/thread will be sleep infinitely. 

I think you can just log.error and return if the time difference is larger a threshold.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/83)*

**Comment by WTer** [comment]
Review status: 0 of 5 files reviewed at latest revision, 20 unresolved discussions.

---

*[miner/miner.go, line 224 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/83#-L7xgDHGEYtvCSvgA2XH:-L7xgDHGEYtvCSvgA2XI:bh0kk2g) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L224)):*
> miner.mutex.Lock()

do we need lock the whole function logic?

---

*[miner/miner.go, line 252 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/83#-L7xfHJtDz8jKqt8zx8Z:-L7xfHJtDz8jKqt8zx8_:bs2y4e8) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L252)):*
> time.Now(),

why don't you use tstart?

---

*[miner/miner.go, line 256 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/83#-L7xfUbC9rc6BL6KJfgg:-L7xfUbC9rc6BL6KJfgh:b8tuhiu) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L256)):*
> if err != nil {

if no txs returned from Pending, what's the err?
I suppose the empty txs during some time of period is expected case, 
and we also need to avoid creating block with empty txs.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/83)*

**Comment by tianlao** [comment]
Review status: 0 of 5 files reviewed at latest revision, 23 unresolved discussions, some commit checks failed.

---

*[miner/engine.go, line 22 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w0Xi7GOQW3w0rHyCw:-L82f6Twzw2yQ60Tw3CC:b-emp4kw) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/engine.go#L22)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

from the API "mine", I think the right variable name is "taskStopChan" or "currentTaskStopChan"
</blockquote></details>

taskStopChan is ok

---

*[miner/engine.go, line 41 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7vz769rx_h02zYJ-EH:-L82fB002mX6CwsFhehl:b2nign6) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/engine.go#L41)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

> Task()

TaskChan()?
</blockquote></details>

yes

---

*[miner/engine.go, line 84 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w-_i_5QJNi_FSmvbA:-L82fkrcoaYdMo5lqoWR:b-4u9lie) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/engine.go#L84)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

The currentChan is used to stop the current task, right? If so, why not write the chan and wait for completion signal?

Otherwise, use READ chan in the task goroutine to stop mining.
</blockquote></details>

I think closing the chan will get the same result

---

*[miner/engine.go, line 102 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w1jNWbcyY-SHYeVr8:-L82gNtIZTb9_EjkLozm:b-7s6oz1) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/engine.go#L102)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

WRITE channel or READ channel to notify the current mining task to stop?
</blockquote></details>

close

---

*[miner/miner.go, line 26 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w27jv8AEHaBEIqSrW:-L82gfPrb5bYfCtnRS_C:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L26)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

uint32 to avoid negative value?

On the other hand, the txNum is unnecessary if txNum == len(txs)
</blockquote></details>

ok

---

*[miner/miner.go, line 37 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w2_FMnvtqZX_63nz4:-L82gtP3VVps-GFN1LUX:bveqaji) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L37)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

what's the difference between the "block in task" and the mined block? If possible, add necessary comments to avoid confuse.
</blockquote></details>

ok, I will add more comments

---

*[miner/miner.go, line 103 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w5E5-LrcNNOw4K-66:-L82ikbCXAwJ_M_Rgose:b49gufv) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L103)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

convert load/store to compareandswap?
</blockquote></details>

no need here, we have locked before

---

*[miner/miner.go, line 125 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7wIctzlShOC3u7dO_A:-L82jJRxb3xQMIZ1_yqB:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L125)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

should use close(miner.stopChan) like p2p.server.quit channel.
</blockquote></details>

ok

---

*[miner/miner.go, line 159 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w6EEJUwZ_zd8lQVns:-L82jRA58nddoEHObfhd:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L159)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

meaningful variable name is always better:)
</blockquote></details>

ok

---

*[miner/miner.go, line 191 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w6hdasSsj2viQClba:-L82ja1rPE3osnLyn4z8:brvdb0s) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L191)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

If close stopChan in function Stop, this line is not required.
</blockquote></details>

ok, use close instead

---

*[miner/miner.go, line 202 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7xaqs82Sz6XQ5eW3Ep:-L82jiogQzCsrA0oCr2T:b2biyk3) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L202)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> if result == nil

when will this result be nil?
</blockquote></details>

never know, just protect

---

*[miner/miner.go, line 209 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7xbgOb8hugtUncKIFF:-L82jsJFaBllobdfPa1v:b-swmkne) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L209)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> continue

so when failed to save block, we just discard this block, which means all txs in this block will be lost, right?
</blockquote></details>

Txs will be discarded only when it has been written to disk successfully, so here will not discard any txs in pool

---

*[miner/miner.go, line 217 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7xbuA-E2H-KPaJul9w:-L82kFNbCExR_KmEY6r9:bso1y7k) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L217)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> miner.stopChan <- struct{}{}

why do you add this?
</blockquote></details>

delete it,  use close instead

---

*[miner/miner.go, line 224 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7xgDHGEYtvCSvgA2XH:-L82kWsxu8qJA9z9wDGq:b9h2lkr) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L224)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> miner.mutex.Lock()

do we need lock the whole function logic?
</blockquote></details>

i think it's ok

---

*[miner/miner.go, line 232 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7xd9vG4TdLhIpQdtNz:-L82kxgbFKouR-Gz236M:b-am64k2) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L232)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> 1

nice to define this magic number 1 as constant var with meaningful name.
also for the following 1 in statement 'now+1'
</blockquote></details>

1 is magic number ???  I don't think so

---

*[miner/miner.go, line 238 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7xdRGc-jrN9y35Qa1q:-L82mU2YTx1BF6WC8wJB:b-mhtsjq) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L238)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> time.Sleep(wait)

this is very vulnerable, suppose adversary change the local time between 
tstart := time.Now()
and 
now:= time.Now

to make their difference so large, then this process/thread will be sleep infinitely. 

I think you can just log.error and return if the time difference is larger a threshold.
</blockquote></details>

firstly, adversary will not attack his own peer,  then,  if local time has been changed,  many functions can not running 

---

*[miner/miner.go, line 252 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7xfHJtDz8jKqt8zx8Z:-L82mKCLvo4Gj4wUWQv6:b7r5q1h) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L252)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> time.Now(),

why don't you use tstart?
</blockquote></details>

because maybe sleep some time after getting tstart

---

*[miner/miner.go, line 256 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7xfUbC9rc6BL6KJfgg:-L82n7OgK49Aci8VFUEc:b-lrtro2) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L256)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> if err != nil {

if no txs returned from Pending, what's the err?
I suppose the empty txs during some time of period is expected case, 
and we also need to avoid creating block with empty txs.
</blockquote></details>

most of public blockchain will creating block with empy txs,  beacuse the block time interval is constant

---

*[miner/miner.go, line 290 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w0_zY6Qajg32bHVi9:-L82oPpvqmtACoBQiTz3:b-om70k7) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L290)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> // execute tx

how can we understand 'execute'?  verify tx's information, or pack it into block? 
</blockquote></details>

execute the transaction to change blockchain state, and pack it into block

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/83)*

**Comment by tianlao** [comment]
Review status: 0 of 5 files reviewed at latest revision, 23 unresolved discussions, some commit checks failed.

---

*[core/tx_pool.go, line 102 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7vy--UlE6JkIyz6uVg:-L82r30P-8uv0ZWjROU8:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/core/tx_pool.go#L102)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Please refer to the existing API  GetProcessableTransactions() map[common.Address][]*types.Transaction
</blockquote></details>

ok

---

*[miner/engine.go, line 16 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7vzRzA6OwMuxeGkgwA:-L82r4pLQVBK4kSOHNCP:b-vti2xx) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/engine.go#L16)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> CPUEngine

why do you add this consensus implementation instead of using pow sha3?
</blockquote></details>

this is upper layer engine,  will call  the pow sha3 service

---

*[miner/miner.go, line 49 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7vzwE5Dq8Bf_Xbmh-5:-L82qtwhVr9Gldy97G9N:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L49)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> Miner

nice to indent all members of it
</blockquote></details>

ok

---

*[miner/miner.go, line 90 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w4Mn-IRE5giswkLPl:-L82qulpPP_QCw_Er5vG:b1m24dt) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L90)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

It's better to use double check pattern for miner.minging
</blockquote></details>

ok, I love using int

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/83)*

**Comment by WTer** [comment]
Review status: 0 of 5 files reviewed at latest revision, 23 unresolved discussions, some commit checks failed.

---

*[miner/miner.go, line 232 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7xd9vG4TdLhIpQdtNz:-L830YsqGHO_cajB2l5W:b-4rl5ve) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L232)):*
<details><summary><i>Previously, tianlao wrote…</i></summary><blockquote>

1 is magic number ???  I don't think so
</blockquote></details>

I  just mean why you chose 1 instead of other values

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/83)*

**Comment by WTer** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/83)*

**Comment by tianlao** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[miner/miner.go, line 232 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7xd9vG4TdLhIpQdtNz:-L8XnIg8QeQj9uWh_dxQ:bgq4lo5) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L232)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

I  just mean why you chose 1 instead of other values
</blockquote></details>

the created time of one block should be larger than parent's 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/83)*

**Comment by boqiu** [comment]
Reviewed 2 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/83)*

**Comment by WTer** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/83)*

**Comment by tianlao** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[miner/miner.go, line 125 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7wIctzlShOC3u7dO_A:-L8Y-vibK4-3p4tTjwUc:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L125)):*
<details><summary><i>Previously, tianlao wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[miner/miner.go, line 191 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/83#-L7w6hdasSsj2viQClba:-L8Y-rJpzq28VP92XOAk:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/bdcb55bfb8468e9df1aba545f93f142b8476fb47/miner/miner.go#L191)):*
<details><summary><i>Previously, tianlao wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/83)*

**Pull request merged**
