### PR TITLE
define txpool struct

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/58)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[core/tx_pool.go, line 40 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/58#-L6piA-cyl29HLXIE8Cb:-L6piA-cyl29HLXIE8Cc:blpn0n4) ([raw file](https://github.com/seeleteam/go-seele/blob/1cbced2a3b51adb5293bdba351d2d214ee15e375/core/tx_pool.go#L40)):*
> AddTransaction

No RemoveTransaction?

---

*[core/tx_pool.go, line 44 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/58#-L6piSZZECJIBpWyd5qh:-L6piSZZECJIBpWyd5qi:bq90ss2) ([raw file](https://github.com/seeleteam/go-seele/blob/1cbced2a3b51adb5293bdba351d2d214ee15e375/core/tx_pool.go#L44)):*
> if err := tx.Validate()

how about to move this code block out of Lock to improve performance?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/58)*

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[core/tx_pool_config.go, line 10 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/58#-L6pjvPTz30wnE5fLnwE:-L6pjvPTz30wnE5fLnwF:b9lwjk8) ([raw file](https://github.com/seeleteam/go-seele/blob/1cbced2a3b51adb5293bdba351d2d214ee15e375/core/tx_pool_config.go#L10)):*
> MaximumTransactions

rename to Size or Capacity would be simple and concise, since TransactionPoolConfig already indicates it's transaction and pool.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/58)*

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[core/tx_pool.go, line 40 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/58#-L6piA-cyl29HLXIE8Cb:-L6pjm_JZYcDN1GafXsp:b-i2fr2l) ([raw file](https://github.com/seeleteam/go-seele/blob/1cbced2a3b51adb5293bdba351d2d214ee15e375/core/tx_pool.go#L40)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> AddTransaction

No RemoveTransaction?
</blockquote></details>

This is the first version, will add (batch) remove method along with block archive logic.

---

*[core/tx_pool.go, line 44 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/58#-L6piSZZECJIBpWyd5qh:-L6plPZznL7uNfyaTkrl:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/1cbced2a3b51adb5293bdba351d2d214ee15e375/core/tx_pool.go#L44)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> if err := tx.Validate()

how about to move this code block out of Lock to improve performance?
</blockquote></details>

Done.

---

*[core/tx_pool_config.go, line 10 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/58#-L6pjvPTz30wnE5fLnwE:-L6plXMbenVihdd6mS-c:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/1cbced2a3b51adb5293bdba351d2d214ee15e375/core/tx_pool_config.go#L10)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> MaximumTransactions

rename to Size or Capacity would be simple and concise, since TransactionPoolConfig already indicates it's transaction and pool.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/58)*

**Comment by jessonzheng** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/58)*

**Comment by WTer** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/58)*

**Pull request closed without merging**
