### PR TITLE
Task statedb evm interface

### PR DESCRIPTION
**Pull request by boqiu**
Enhance the statedb to implements the EVM required interface. Note, this is iteration 1 that only add APIs without implementation.

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/141)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---

*[core/state/statedb.go, line 53 at r1](https://reviewable.io/reviews/seeleteam/go-seele/141#-LBZiba83FAKUTGtYhys:-LBZiba83FAKUTGtYhyt:b-ybdwsi) ([raw file](https://github.com/seeleteam/go-seele/blob/f02e5283086daa5c9ee7e818d3eb8b0e73bca2d2/core/state/statedb.go#L53)):*
> ```Go
> 
> // GetBalance get balance of account
> func (s *Statedb) GetBalance(addr common.Address) (*big.Int, bool) {
> ```

remove bool as return value.

---

*[core/state/statedb.go, line 86 at r1](https://reviewable.io/reviews/seeleteam/go-seele/141#-LBZj6GwCG4gRNYr4IIM:-LBZj6GwCG4gRNYr4IIN:b-13un4g) ([raw file](https://github.com/seeleteam/go-seele/blob/f02e5283086daa5c9ee7e818d3eb8b0e73bca2d2/core/state/statedb.go#L86)):*
> ```Go
> 
> // GetNonce get nonce of account
> func (s *Statedb) GetNonce(addr common.Address) (uint64, bool) {
> ```

remove bool as return value

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/141)*

**Comment by boqiu** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[core/state/statedb.go, line 53 at r1](https://reviewable.io/reviews/seeleteam/go-seele/141#-LBZiba83FAKUTGtYhys:-LB_SUBqCzZp9pxSKrzu:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f02e5283086daa5c9ee7e818d3eb8b0e73bca2d2/core/state/statedb.go#L53)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

remove bool as return value.
</blockquote></details>

Done.

---

*[core/state/statedb.go, line 86 at r1](https://reviewable.io/reviews/seeleteam/go-seele/141#-LBZj6GwCG4gRNYr4IIM:-LB_SZWl9edsHm2TQoGq:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f02e5283086daa5c9ee7e818d3eb8b0e73bca2d2/core/state/statedb.go#L86)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

remove bool as return value
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/141)*

**Comment by lucusfly** [comment]
Reviewed 1 of 11 files at r1, 5 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/141)*

**Comment by lucusfly** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/141)*

**Pull request merged**
