### PR TITLE
Add MaxPeers, IsSpecial viarables to p2p module

### PR DESCRIPTION
**Pull request by qiaozhigang**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/51)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[p2p/protocol.go, line 36 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/51#-L6lD4nT4DTB2kzBnpCm:-L6lD4nUukR9awB-tdRo:bix2vkc) ([raw file](https://github.com/seeleteam/go-seele/blob/0256c231634ffe0946008af4c0cd098e3b16e843/p2p/protocol.go#L36)):*
> IsSpecial

according to your comments for it, seems rename it to IsShared will be more meaningful.

---

*[p2p/server.go, line 36 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/51#-L6lDJ7Rbdou4xoXH64L:-L6lDJ7Rbdou4xoXH64M:b889b5v) ([raw file](https://github.com/seeleteam/go-seele/blob/0256c231634ffe0946008af4c0cd098e3b16e843/p2p/server.go#L36)):*
> maxAcceptConns = 50


if defaultMaxPeers is 30, there will be different type of messages, one peer can issue several connections at the same time, so maxAcceptConns = 50 seems not enough,

how about if we increase maxAcceptConns to a larger number? 

---

*[p2p/server.go, line 68 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/51#-L6o0kIHtUhqYR6gpa-c:-L6o0kIItx3qB106oC-D:b13l8lv) ([raw file](https://github.com/seeleteam/go-seele/blob/0256c231634ffe0946008af4c0cd098e3b16e843/p2p/server.go#L68)):*
> int

unit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/51)*

**Comment by boqiu** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/51)*

**Comment by qiaozhigang** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[p2p/protocol.go, line 36 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/51#-L6lD4nT4DTB2kzBnpCm:-L6oQ7jXzt_V6RrMfLSE:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/0256c231634ffe0946008af4c0cd098e3b16e843/p2p/protocol.go#L36)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> IsSpecial

according to your comments for it, seems rename it to IsShared will be more meaningful.
</blockquote></details>

ok

---

*[p2p/server.go, line 36 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/51#-L6lDJ7Rbdou4xoXH64L:-L6oQAPYc9ACU0B1CWOK:bb7gzlu) ([raw file](https://github.com/seeleteam/go-seele/blob/0256c231634ffe0946008af4c0cd098e3b16e843/p2p/server.go#L36)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> maxAcceptConns = 50


if defaultMaxPeers is 30, there will be different type of messages, one peer can issue several connections at the same time, so maxAcceptConns = 50 seems not enough,

how about if we increase maxAcceptConns to a larger number? 
</blockquote></details>

good

---

*[p2p/server.go, line 68 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/51#-L6o0kIHtUhqYR6gpa-c:-L6oQC6VyxBrx19VAsAx:b-teur8y) ([raw file](https://github.com/seeleteam/go-seele/blob/0256c231634ffe0946008af4c0cd098e3b16e843/p2p/server.go#L68)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> int

unit?
</blockquote></details>

all the same values are int type

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/51)*

**Comment by WTer** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[p2p/protocol.go, line 34 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/51#-L6qRZSZq42CIFyVuGPN:-L6qRZSZq42CIFyVuGPO:bnmh5sc) ([raw file](https://github.com/seeleteam/go-seele/blob/93ee052ede03bcdb06593c7383f4736e7778d671/p2p/protocol.go#L34)):*
> IsSpecial

IsSelfConnect

---

*[p2p/server.go, line 36 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/51#-L6lDJ7Rbdou4xoXH64L:-L6qRd1mn4nvX5JO0qEp:b1fmdx0) ([raw file](https://github.com/seeleteam/go-seele/blob/0256c231634ffe0946008af4c0cd098e3b16e843/p2p/server.go#L36)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

good
</blockquote></details>

I just mean you can increase the value of maxAcceptConns instead of defaultMaxPeers:)

just for discussion, doesn't matter. we can refine these values for specific scenarios.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/51)*

**Comment by WTer** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/51)*

**Comment by qiaozhigang** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[p2p/protocol.go, line 34 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/51#-L6qRZSZq42CIFyVuGPN:-L6snfcIO9FKRIEe2ba8:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/93ee052ede03bcdb06593c7383f4736e7778d671/p2p/protocol.go#L34)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> IsSpecial

IsSelfConnect
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/51)*

**Pull request merged**
