### PR TITLE
Get block transaction count and transaction info api

### PR DESCRIPTION
**Pull request by gongliaoan**
1、GetBlockTransactionCountByHeight
2、GetBlockTransactionCountByHash
3、GetTransactionByBlockHeightAndIndex
4、GetTransactionByBlockHashAndIndex

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/184)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[seele/api.go, line 56 at r1](https://reviewable.io/reviews/seeleteam/go-seele/184#-LCl3GhY6r_bRfuRw8k-:-LCl3GhY6r_bRfuRw8k0:b-cgwyp3) ([raw file](https://github.com/seeleteam/go-seele/blob/1497240f62596bd4a82829c17b470b4877c43500/seele/api.go#L56)):*
> ```Go
> // GetBlockTxCountByHeightRequest request param for GetBlockTransactionCountByHeight api
> type GetBlockTxCountByHeightRequest struct {
> 	Height int64
> ```

For only one input parameter, it's unnecessary to use struct.

---

*[seele/api.go, line 280 at r1](https://reviewable.io/reviews/seeleteam/go-seele/184#-LCl3aV_3ZWNFlQ_JGgR:-LCl3aV_3ZWNFlQ_JGgS:b-y0nzmz) ([raw file](https://github.com/seeleteam/go-seele/blob/1497240f62596bd4a82829c17b470b4877c43500/seele/api.go#L280)):*
> ```Go
> 	txs := block.Transactions
> 	if request.Index >= len(txs) {
> 		return errIndexOutRange
> ```

better to return detailed error info, e.g. including the len(txs) info in error message.

---

*[seele/api.go, line 303 at r1](https://reviewable.io/reviews/seeleteam/go-seele/184#-LCl3oJb70SjbhfE6-Kr:-LCl3oJb70SjbhfE6-Ks:b-fj649a) ([raw file](https://github.com/seeleteam/go-seele/blob/1497240f62596bd4a82829c17b470b4877c43500/seele/api.go#L303)):*
> ```Go
> 	txs := block.Transactions
> 	if request.Index >= len(txs) {
> 		return errIndexOutRange
> ```

better to include the txs len in returned error message.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/184)*

**Comment by lucusfly** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/client/cmd/cmddata.go, line 12 at r1](https://reviewable.io/reviews/seeleteam/go-seele/184#-LCl34Gw0dKC47hkSThB:-LCl34Gw0dKC47hkSThC:b-384s6) ([raw file](https://github.com/seeleteam/go-seele/blob/1497240f62596bd4a82829c17b470b4877c43500/cmd/client/cmd/cmddata.go#L12)):*
> ```Go
> 	return []*Request{
> 		&Request{
> 			Use:              "teststruct",
> ```

refine the test part.

---

*[cmd/client/cmd/cmddata.go, line 76 at r1](https://reviewable.io/reviews/seeleteam/go-seele/184#-LCl3D_H3n7wnIvIHUG4:-LCl3D_H3n7wnIvIHUG5:b-rwo9lp) ([raw file](https://github.com/seeleteam/go-seele/blob/1497240f62596bd4a82829c17b470b4877c43500/cmd/client/cmd/cmddata.go#L76)):*
> ```Go
> 					ShortHand:    "",
> 					ParamType:    "*int64",
> 					DefaultValue: -1,
> ```

add comments for -1

---

*[seele/api.go, line 235 at r1](https://reviewable.io/reviews/seeleteam/go-seele/184#-LCl8YG3DevJoen4V7SK:-LCl8YG3DevJoen4V7SL:b-54t6gm) ([raw file](https://github.com/seeleteam/go-seele/blob/1497240f62596bd4a82829c17b470b4877c43500/seele/api.go#L235)):*
> ```Go
> 
> // PublicTransactionPoolAPI provides an API to access transaction pool information.
> type PublicTransactionPoolAPI struct {
> ```

move to a new file for PublicTransactionPoolAPI

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/184)*

**Comment by gongliaoan** [comment]
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[cmd/client/cmd/cmddata.go, line 12 at r1](https://reviewable.io/reviews/seeleteam/go-seele/184#-LCl34Gw0dKC47hkSThB:-LD-f24I9UuwFf9Eb5l_:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/1497240f62596bd4a82829c17b470b4877c43500/cmd/client/cmd/cmddata.go#L12)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

refine the test part.
</blockquote></details>

Done.

---

*[cmd/client/cmd/cmddata.go, line 76 at r1](https://reviewable.io/reviews/seeleteam/go-seele/184#-LCl3D_H3n7wnIvIHUG4:-LD-ZxA9BfNaw1UveCh1:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/1497240f62596bd4a82829c17b470b4877c43500/cmd/client/cmd/cmddata.go#L76)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

add comments for -1
</blockquote></details>

Done.

---

*[seele/api.go, line 56 at r1](https://reviewable.io/reviews/seeleteam/go-seele/184#-LCl3GhY6r_bRfuRw8k-:-LD-ZyQL3O4wr7hXns9X:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/1497240f62596bd4a82829c17b470b4877c43500/seele/api.go#L56)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

For only one input parameter, it's unnecessary to use struct.
</blockquote></details>

Done.

---

*[seele/api.go, line 235 at r1](https://reviewable.io/reviews/seeleteam/go-seele/184#-LCl8YG3DevJoen4V7SK:-LD-jfqU53UEoKCYj5F2:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/1497240f62596bd4a82829c17b470b4877c43500/seele/api.go#L235)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

move to a new file for PublicTransactionPoolAPI
</blockquote></details>

Done.

---

*[seele/api.go, line 280 at r1](https://reviewable.io/reviews/seeleteam/go-seele/184#-LCl3aV_3ZWNFlQ_JGgR:-LD-_2M9BVpVqN1e7x0f:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/1497240f62596bd4a82829c17b470b4877c43500/seele/api.go#L280)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

better to return detailed error info, e.g. including the len(txs) info in error message.
</blockquote></details>

Done.

---

*[seele/api.go, line 303 at r1](https://reviewable.io/reviews/seeleteam/go-seele/184#-LCl3oJb70SjbhfE6-Kr:-LD-_2xQ5w4uhD3u-ATq:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/1497240f62596bd4a82829c17b470b4877c43500/seele/api.go#L303)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

better to include the txs len in returned error message.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/184)*

**Comment by lucusfly** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/client/cmd/cmddata.go, line 34 at r2](https://reviewable.io/reviews/seeleteam/go-seele/184#-LD-kxlS9AKDxMiiJCU8:-LD-kxlS9AKDxMiiJCU9:b-83jx2z) ([raw file](https://github.com/seeleteam/go-seele/blob/0375c3feead7037bb89dbe0f61b0c2dfccfb0702/cmd/client/cmd/cmddata.go#L34)):*
> ```
> is add full tx, default is false
> ```

whether get full transaction info, default is false

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/184)*

**Comment by lucusfly** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/184)*

**Comment by gongliaoan** [comment]
Review status: 7 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/client/cmd/cmddata.go, line 34 at r2](https://reviewable.io/reviews/seeleteam/go-seele/184#-LD-kxlS9AKDxMiiJCU8:-LD-mFVh2YOhDZ8EDK4S:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/0375c3feead7037bb89dbe0f61b0c2dfccfb0702/cmd/client/cmd/cmddata.go#L34)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> is add full tx, default is false
> ```

whether get full transaction info, default is false
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/184)*

**Comment by gongliaoan** [comment]
Reviewed 7 of 8 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/184)*

**Comment by boqiu** [comment]
Reviewed 7 of 8 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/184)*

**Comment by lucusfly** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/184)*

**Pull request merged**
