### PR TITLE
Add MaxPeers, IsSpecial viarables to p2p module

### PR DESCRIPTION
**Pull request by qiaozhigang**
Add MaxPeers to p2p.Server
Add IsSpecial to p2p.Protocol, 
see comments in sourcecode

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/49)

### CODE REVIEW

**Comment by boqiu** [comment]
This PR still contains commits of previous PR, please create a new branch or add commit to the existing PR.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/49#-:-L6fviNyB7HPU_cpERfn:b-ct13sh)*

**Comment by WTer** [comment]
Seems this change depends on the previous PR, so you need to commit that PR firstly.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/49#-:-L6fyTpy5r8LuliTxKEL:b-z8251b)*

**Comment by qiaozhigang** [comment]
oh no, independent with other PRs
p2p.MaxPeers has not used yet. It will be used in node.Start to initiate seeleservice.maxPeers

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/49#-:-L6gFy8omxforqP83M9m:b-74z1th)*

**Comment by qiaozhigang** [comment]
oh， I see. This change should based on previous code before seele framework.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/49#-:-L6ij0falomcQQDnd-Mb:b4stusq)*

**Pull request closed without merging**
