### PR TITLE
Add WriteBlock API for Blockchain struct.

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/86)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---

*[core/blockchain.go, line 48 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/86#-L813rX1DnN1VrGDbt9g:-L813rX1DnN1VrGDbt9h:bxrdp5s) ([raw file](https://github.com/seeleteam/go-seele/blob/17199fbb7ebc8e31e3f4232c64fe0231f42eb1ef/core/blockchain.go#L48)):*
> 0

rename magic number 0 as GenesisBlockHeight?

---

*[core/blockchain.go, line 58 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/86#-L815oA8-BSDRVrSNTfC:-L815oA8-BSDRVrSNTfD:b-gccufq) ([raw file](https://github.com/seeleteam/go-seele/blob/17199fbb7ebc8e31e3f4232c64fe0231f42eb1ef/core/blockchain.go#L58)):*
> HEAD

nice to rename it to LATEST, TOP:)

---

*[core/blockchain.go, line 77 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/86#-L81616047iF0DHmKCMu:-L81616047iF0DHmKCMv:b-5wpais) ([raw file](https://github.com/seeleteam/go-seele/blob/17199fbb7ebc8e31e3f4232c64fe0231f42eb1ef/core/blockchain.go#L77)):*
> bc.currentBlock

why do we add lock this simple return?

---

*[core/blockchain.go, line 99 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/86#-L816Mmw0yO0Bc8TmqId:-L816Mmw0yO0Bc8TmqIe:bgaoztw) ([raw file](https://github.com/seeleteam/go-seele/blob/17199fbb7ebc8e31e3f4232c64fe0231f42eb1ef/core/blockchain.go#L99)):*
> PutBlock

do we need to check whether put duplicated blocks?
this function may be called more than once by the same caller.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/86)*

**Comment by boqiu** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[core/blockchain.go, line 48 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/86#-L813rX1DnN1VrGDbt9g:-L81CkGK7OlJw2LYEQno:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/17199fbb7ebc8e31e3f4232c64fe0231f42eb1ef/core/blockchain.go#L48)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> 0

rename magic number 0 as GenesisBlockHeight?
</blockquote></details>

Done.

---

*[core/blockchain.go, line 58 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/86#-L815oA8-BSDRVrSNTfC:-L81ClTw6JwzpgEhtcAU:b-4hhskh) ([raw file](https://github.com/seeleteam/go-seele/blob/17199fbb7ebc8e31e3f4232c64fe0231f42eb1ef/core/blockchain.go#L58)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> HEAD

nice to rename it to LATEST, TOP:)

</blockquote></details>

Good suggestion. I would like to keep it as it is in this RP, since the code changes may be a lot.

---

*[core/blockchain.go, line 77 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/86#-L81616047iF0DHmKCMu:-L81D6aY-YmsebhTaO-F:bz5clz5) ([raw file](https://github.com/seeleteam/go-seele/blob/17199fbb7ebc8e31e3f4232c64fe0231f42eb1ef/core/blockchain.go#L77)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> bc.currentBlock

why do we add lock this simple return?
</blockquote></details>

Blockchain struct is thread safe, including this getter.

---

*[core/blockchain.go, line 99 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/86#-L816Mmw0yO0Bc8TmqId:-L81DSJQ01QW2tq-yTug:b-ykullb) ([raw file](https://github.com/seeleteam/go-seele/blob/17199fbb7ebc8e31e3f4232c64fe0231f42eb1ef/core/blockchain.go#L99)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> PutBlock

do we need to check whether put duplicated blocks?
this function may be called more than once by the same caller.
</blockquote></details>

There're enough validation at the beginning of the WriteBlock API, duplicated blocks cannot insert into the blockchain twice.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/86)*

**Comment by boqiu** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[core/blockchain.go, line 99 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/86#-L816Mmw0yO0Bc8TmqId:-L81IItuELbrx4dkBnmV:by803bo) ([raw file](https://github.com/seeleteam/go-seele/blob/17199fbb7ebc8e31e3f4232c64fe0231f42eb1ef/core/blockchain.go#L99)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

There're enough validation at the beginning of the WriteBlock API, duplicated blocks cannot insert into the blockchain twice.
</blockquote></details>

Also add UT to cover the dup blocks case.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/86)*

**Comment by WTer** [comment]
Reviewed 5 of 8 files at r1, 3 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/86)*

**Pull request merged**
