### PR TITLE
Download: fix some bugs and add some logs

### PR DESCRIPTION
**Pull request by qiaozhigang**
Fix some bugs and add some logs

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/117)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[seele/peer.go, line 159 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/117#-L9nRDPo7hfm55pKT5Br:-L9nRDPo7hfm55pKT5Bs:b72ly7c) ([raw file](https://github.com/seeleteam/go-seele/blob/56b15b233c57f7cab6e5ff3a935ea0ede102993d/seele/peer.go#L159)):*
> ```Go
> // RequestHeadersByHashOrNumber fetches a batch of blocks' headers corresponding to the
> // specified header query, based on the hash of an origin block.
> func (p *peer) RequestHeadersByHashOrNumber(origin common.Hash, num uint64, amount int, reverse bool) error {
> ```

change parameter amount to uint64?

---

*[seele/seeleprotocol.go, line 130 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/117#-L9nQIGhAoDwAZHHEzys:-L9nQIGhAoDwAZHHEzyt:b-fy00yf) ([raw file](https://github.com/seeleteam/go-seele/blob/56b15b233c57f7cab6e5ff3a935ea0ede102993d/seele/seeleprotocol.go#L130)):*
> ```Go
> 	pHead, pTd := p.Head()
> 
> 	fmt.Println("SeeleProtocol.synchronise", localTD, pTd)
> ```

move to log

---

*[seele/seeleprotocol.go, line 396 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/117#-L9nQZBv7RynKwC2RV93:-L9nQZBv7RynKwC2RV94:b-2q4854) ([raw file](https://github.com/seeleteam/go-seele/blob/56b15b233c57f7cab6e5ff3a935ea0ede102993d/seele/seeleprotocol.go#L396)):*
> ```Go
> 			var head *types.BlockHeader
> 			orgNum := query.Number
> 			fmt.Println(query)
> ```

remove or move to log

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/117)*

**Comment by lucusfly** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/117)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[seele/seeleprotocol.go, line 151 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/117#-L9nbMlZ1lkAQbh3No3H:-L9nbMlZ1lkAQbh3No3I:b-a1aymm) ([raw file](https://github.com/seeleteam/go-seele/blob/56b15b233c57f7cab6e5ff3a935ea0ede102993d/seele/seeleprotocol.go#L151)):*
> ```
> sp.log.Error("broadcastChainHead GetBlockTotalDifficulty err. %s", err)
> ```
we need to add more info, such as head info, to quickly locate the root source, 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/117)*

**Comment by qiaozhigang** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[seele/peer.go, line 159 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/117#-L9nRDPo7hfm55pKT5Br:-L9njiedBMh7QKUMZ00h:b-ehv6f8) ([raw file](https://github.com/seeleteam/go-seele/blob/56b15b233c57f7cab6e5ff3a935ea0ede102993d/seele/peer.go#L159)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

change parameter amount to uint64?
</blockquote></details>

type int is reasonable for caller.
because the length of int is not certain, so int is not used in rlp, using uint64 just to avoid this limitation.

---

*[seele/seeleprotocol.go, line 130 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/117#-L9nQIGhAoDwAZHHEzys:-L9nk-6U84skFp4R3Syo:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/56b15b233c57f7cab6e5ff3a935ea0ede102993d/seele/seeleprotocol.go#L130)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

move to log
</blockquote></details>

ok

---

*[seele/seeleprotocol.go, line 151 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/117#-L9nbMlZ1lkAQbh3No3H:-L9nk9k47Y0WnQmvXo8l:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/56b15b233c57f7cab6e5ff3a935ea0ede102993d/seele/seeleprotocol.go#L151)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> sp.log.Error("broadcastChainHead GetBlockTotalDifficulty err. %s", err)
> ```
we need to add more info, such as head info, to quickly locate the root source, 
</blockquote></details>

ok

---

*[seele/seeleprotocol.go, line 396 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/117#-L9nQZBv7RynKwC2RV93:-L9nkEJj1CZ8vgftI3ss:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/56b15b233c57f7cab6e5ff3a935ea0ede102993d/seele/seeleprotocol.go#L396)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

remove or move to log
</blockquote></details>

ok

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/117)*

**Comment by lucusfly** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/117)*

**Comment by WTer** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/117)*

**Pull request merged**
