### PR TITLE
return error when statedb commit failed.

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/169)

### CODE REVIEW

**Comment by lucusfly** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/169)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[core/state/statedb_evm_test.go, line 47 at r1](https://reviewable.io/reviews/seeleteam/go-seele/169#-LCXv6pVEgWe6XxhqYL9:-LCXv6pVEgWe6XxhqYLA:b6mn0n7) ([raw file](https://github.com/seeleteam/go-seele/blob/ca906aa31248b59c3ee8398492b44db85d07ae43/core/state/statedb_evm_test.go#L47)):*
> ```
> panic(err)
> ```
do we need to log error into local for debugging?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/169)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[core/state/statedb_evm_test.go, line 47 at r1](https://reviewable.io/reviews/seeleteam/go-seele/169#-LCXv6pVEgWe6XxhqYL9:-LCY1cL4DW3bNgZ0BXVO:b-3tsvio) ([raw file](https://github.com/seeleteam/go-seele/blob/ca906aa31248b59c3ee8398492b44db85d07ae43/core/state/statedb_evm_test.go#L47)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> panic(err)
> ```
do we need to log error into local for debugging?
</blockquote></details>

panic will cause UT fail, you could treat it as t.Fatal()

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/169)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[core/state/statedb_evm_test.go, line 47 at r1](https://reviewable.io/reviews/seeleteam/go-seele/169#-LCXv6pVEgWe6XxhqYL9:-LCY4eiu4pyAqAEGunY4:bd7sfgq) ([raw file](https://github.com/seeleteam/go-seele/blob/ca906aa31248b59c3ee8398492b44db85d07ae43/core/state/statedb_evm_test.go#L47)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

panic will cause UT fail, you could treat it as t.Fatal()
</blockquote></details>

my wrong, it's test code, haha

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/169)*

**Comment by WTer** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/169)*

**Pull request merged**
