### PR TITLE
add time in tx to avoid miner tx hash is the same issue

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/127)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[core/types/transaction.go, line 100 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/127#-LAXXArf-ZbsInHBM1NQ:-LAXXArf-ZbsInHBM1NR:b27b2cb) ([raw file](https://github.com/seeleteam/go-seele/blob/9187b906ac3d099d2523138b3b2a53185b197db6/core/types/transaction.go#L100)):*
> ```
> Timestamp:    uint64(time.Now().Unix()),
> ```
still not clear about the background of this pr, explain shortly?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/127)*

**Comment by boqiu** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[core/types/transaction.go, line 100 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/127#-LAXXArf-ZbsInHBM1NQ:-LAkENBo4yW9sl5r2gvq:b-4587x3) ([raw file](https://github.com/seeleteam/go-seele/blob/9187b906ac3d099d2523138b3b2a53185b197db6/core/types/transaction.go#L100)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

reward tx is stored in the first tx in a block. and its account nonce is zero as there is no from address. So the same miner's reward tx are the same. thus it's tx hash are the same. For different reward tx, we need to keep them different. so add timestamp info for tx.
</blockquote></details>

If so, we can use block nonce or height as reward tx nonce instead.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/127)*

**Comment by WTer** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/127)*

**Comment by boqiu** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/127)*

**Pull request merged**
