### PR TITLE
Some coding refinement and bugs fix

### PR DESCRIPTION
**Pull request by WTer**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/332)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @WTer, @qqtou, @ypenghui6, @boqiu, @wangff15386, @yanllearnn, and @lucusfly)

---

*[cmd/client/cmd/signature.go, line 40 at r1](https://reviewable.io/reviews/seeleteam/go-seele/332#-LG-dZhP4tnE6YYO6B__:-LG-dZhQ1tMF0sr-3RuW:b-t95oay) ([raw file](https://github.com/seeleteam/go-seele/blob/97eb48e0bce74c0a5a220cf5685769799c32a5d9/cmd/client/cmd/signature.go#L40)):*
> ```Go
> 		key, err := crypto.LoadECDSAFromString(*privateKey)
> 		if err != nil {
> 			fmt.Printf("load key failed %s", err)
> ```

add \n

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/332)*

**Comment by lucusfly** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @WTer, @qqtou, @ypenghui6, @boqiu, @wangff15386, and @yanllearnn)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/332)*

**Comment by ypenghui6** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @WTer, @qqtou, @boqiu, @wangff15386, and @yanllearnn)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/332)*

**Comment by WTer** [comment]
Review status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ypenghui6, @lucusfly, @qqtou, @boqiu, @wangff15386, and @yanllearnn)

---

*[cmd/client/cmd/signature.go, line 40 at r1](https://reviewable.io/reviews/seeleteam/go-seele/332#-LG-dZhP4tnE6YYO6B__:-LG-non63SzDWzsfXHDy:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/97eb48e0bce74c0a5a220cf5685769799c32a5d9/cmd/client/cmd/signature.go#L40)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

add \n
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/332)*

**Comment by ypenghui6** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed, 1 unresolved discussion (waiting on @lucusfly, @qqtou, @boqiu, @wangff15386, and @yanllearnn)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/332)*

**Comment by lucusfly** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @qqtou, @boqiu, @wangff15386, and @yanllearnn)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/332)*

**Pull request merged**
