### PR TITLE
add miner hashrate api

### PR DESCRIPTION
**Pull request by gongliaoan**
add miner hashrate api

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/155)

### CODE REVIEW

**Comment by lucusfly** [comment]
Please use govendor to import external packages

---

Review status: 0 of 56 files reviewed at latest revision, all discussions resolved.

---

*[miner/core.go, line 47 at r1](https://reviewable.io/reviews/seeleteam/go-seele/155#-LC1k3h29mVO28WNhtlr:-LC1k3h29mVO28WNhtls:b7zo67d) ([raw file](https://github.com/seeleteam/go-seele/blob/3f4479157e9c34297b39cad66ae5d63dcd46898f/miner/core.go#L47)):*
> ```
> (caltimes & (1 << 15))
> ```

I think it should be xor

---

*[miner/miner.go, line 293 at r1](https://reviewable.io/reviews/seeleteam/go-seele/155#-LC1m9pn7RpVjaxcRTdp:-LC1m9pn7RpVjaxcRTdq:bmfrz7s) ([raw file](https://github.com/seeleteam/go-seele/blob/3f4479157e9c34297b39cad66ae5d63dcd46898f/miner/miner.go#L293)):*
> ```Go
> // min is the min number for the nonce per thread
> // max is the max number for the nonce per thread
> func (miner *Miner) startMining(task *Task, seed uint64, min uint64, max uint64) {
> ```

？ duplicate code

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/155#-:-LC1l2i2CIfgUI8h6Hx3:bhkl7s6)*

**Comment by boqiu** [comment]
Review status: 0 of 56 files reviewed at latest revision, 2 unresolved discussions.

---

*[miner/core.go, line 47 at r1](https://reviewable.io/reviews/seeleteam/go-seele/155#-LC1k3h29mVO28WNhtlr:-LC2ni-aATc_A7nrQ364:b-s7ypdo) ([raw file](https://github.com/seeleteam/go-seele/blob/3f4479157e9c34297b39cad66ae5d63dcd46898f/miner/core.go#L47)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> (caltimes & (1 << 15))
> ```

I think it should be xor
</blockquote></details>

Why not caltimes == 0x7FFF?

BTW, I think it's better to declare caltimes as byte or uint16. Thus, the if clause could simply changed to "if caltimes == 0"

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/155)*

**Comment by gongliaoan** [comment]
Review status: 0 of 33 files reviewed at latest revision, 2 unresolved discussions.

---

*[miner/core.go, line 47 at r1](https://reviewable.io/reviews/seeleteam/go-seele/155#-LC1k3h29mVO28WNhtlr:-LC3MkY08J_-mDjEQ3MS:b-7ro86f) ([raw file](https://github.com/seeleteam/go-seele/blob/3f4479157e9c34297b39cad66ae5d63dcd46898f/miner/core.go#L47)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not caltimes == 0x7FFF?

BTW, I think it's better to declare caltimes as byte or uint16. Thus, the if clause could simply changed to "if caltimes == 0"
</blockquote></details>


it should be caltimes % (1 << 15)

---

*[miner/miner.go, line 293 at r1](https://reviewable.io/reviews/seeleteam/go-seele/155#-LC1m9pn7RpVjaxcRTdp:-LC39hT97Hr5Mt9G1RYb:bqdstt3) ([raw file](https://github.com/seeleteam/go-seele/blob/3f4479157e9c34297b39cad66ae5d63dcd46898f/miner/miner.go#L293)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

？ duplicate code
</blockquote></details>


i will delete StartMining func in core.go

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/155)*

**Comment by lucusfly** [comment]
Review status: 0 of 33 files reviewed at latest revision, 2 unresolved discussions.

---

*[miner/miner.go, line 293 at r1](https://reviewable.io/reviews/seeleteam/go-seele/155#-LC1m9pn7RpVjaxcRTdp:-LC6z28z0UML8YBmvHs8:b-mbeqe7) ([raw file](https://github.com/seeleteam/go-seele/blob/3f4479157e9c34297b39cad66ae5d63dcd46898f/miner/miner.go#L293)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

i will delete StartMining func in core.go
</blockquote></details>

please keep func in core.go and delete this one, so we could know what you changed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/155)*

**Comment by gongliaoan** [comment]
Review status: 0 of 33 files reviewed at latest revision, 2 unresolved discussions.

---

*[miner/miner.go, line 293 at r1](https://reviewable.io/reviews/seeleteam/go-seele/155#-LC1m9pn7RpVjaxcRTdp:-LC8Oxbi-NgA1V7QPupa:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/3f4479157e9c34297b39cad66ae5d63dcd46898f/miner/miner.go#L293)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

please keep func in core.go and delete this one, so we could know what you changed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/155)*

**Comment by boqiu** [comment]
Review status: 0 of 33 files reviewed at latest revision, 2 unresolved discussions.

---

*[miner/miner.go, line 322 at r3](https://reviewable.io/reviews/seeleteam/go-seele/155#-LC8QfJ264Tq9E56Wd5L:-LC8QfJ264Tq9E56Wd5M:b-j58elv) ([raw file](https://github.com/seeleteam/go-seele/blob/625f791f3bd76c69da57941674af7c527de62a7f/miner/miner.go#L322)):*
> ```
> caltimes % (1 << 15)) == 0
> ```

1) The maximum caltimes is 0x8000, so 16 bytes are enough.
2) You could also simplify the code as below:
    a. declare caltimes as uint16
    b. change the if clause to "if caltimes == 0x7FFF {"

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/155)*

**Comment by gongliaoan** [comment]
Review status: 0 of 33 files reviewed at latest revision, 3 unresolved discussions.

---

*[miner/miner.go, line 322 at r3](https://reviewable.io/reviews/seeleteam/go-seele/155#-LC8QfJ264Tq9E56Wd5L:-LCBnuTr-g8UrGJt656t:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/625f791f3bd76c69da57941674af7c527de62a7f/miner/miner.go#L322)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> caltimes % (1 << 15)) == 0
> ```

1) The maximum caltimes is 0x8000, so 16 bytes are enough.
2) You could also simplify the code as below:
    a. declare caltimes as uint16
    b. change the if clause to "if caltimes == 0x7FFF {"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/155)*

**Comment by lucusfly** [comment]
Review status: 0 of 33 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/client/cmd/miner.go, line 26 at r5](https://reviewable.io/reviews/seeleteam/go-seele/155#-LCC-WTQ38Ka4lMD-_GO:-LCC-WTQ38Ka4lMD-_GP:b-js6oo4) ([raw file](https://github.com/seeleteam/go-seele/blob/df614857e50f600e183cd2672438597cf78e4b07/cmd/client/cmd/miner.go#L26)):*
> ```Go
> 	 client.exe miner -o start [-t <miner threads num>]
> 	 client.exe miner -o stop
> 	 client.ext miner -o hashrate`,
> ```

better use a subcommand gethashrate.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/155)*

**Comment by lucusfly** [comment]
Review status: 0 of 33 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/client/cmd/miner.go, line 24 at r5](https://reviewable.io/reviews/seeleteam/go-seele/155#-LCC0aRTBLmI9rMDxQla:-LCC0aRTBLmI9rMDxQlb:bio8jwq) ([raw file](https://github.com/seeleteam/go-seele/blob/df614857e50f600e183cd2672438597cf78e4b07/cmd/client/cmd/miner.go#L24)):*
> ```
> 	 client.exe miner -o start [-t <miner threads num>]
> 	 client.exe miner -o stop
> ```

for start and stop command, I think you'd better use flagset to do it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/155)*

**Comment by herove** [comment]
Review status: 0 of 33 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/client/cmd/miner.go, line 24 at r5](https://reviewable.io/reviews/seeleteam/go-seele/155#-LCC0aRTBLmI9rMDxQla:-LCCDwUtDyyiWqKgQgB2:b8k24hn) ([raw file](https://github.com/seeleteam/go-seele/blob/df614857e50f600e183cd2672438597cf78e4b07/cmd/client/cmd/miner.go#L24)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> 	 client.exe miner -o start [-t <miner threads num>]
> 	 client.exe miner -o stop
> ```

for start and stop command, I think you'd better use flagset to do it.
</blockquote></details>

better to use ./miner start, different binary file.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/155)*

**Comment by boqiu** [comment]
Reviewed 27 of 58 files at r1, 1 of 30 files at r2, 1 of 2 files at r3, 3 of 5 files at r5, 5 of 6 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/155)*

**Comment by gongliaoan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/client/cmd/miner.go, line 24 at r5](https://reviewable.io/reviews/seeleteam/go-seele/155#-LCC0aRTBLmI9rMDxQla:-LCD0AzR9ywUMCtWS88p:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/df614857e50f600e183cd2672438597cf78e4b07/cmd/client/cmd/miner.go#L24)):*
<details><summary><i>Previously, herove (Leihao Zhou) wrote…</i></summary><blockquote>

better to use ./miner start, different binary file.
</blockquote></details>

Done.

---

*[cmd/client/cmd/miner.go, line 26 at r5](https://reviewable.io/reviews/seeleteam/go-seele/155#-LCC-WTQ38Ka4lMD-_GO:-LCD06RY8w5JRAOWkczF:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/df614857e50f600e183cd2672438597cf78e4b07/cmd/client/cmd/miner.go#L26)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

better use a subcommand gethashrate.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/155)*

**Comment by lucusfly** [comment]
Review status: 35 of 36 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/client/cmd/miner.go, line 24 at r5](https://reviewable.io/reviews/seeleteam/go-seele/155#-LCC0aRTBLmI9rMDxQla:-LCDH0vE9EjIbc6qNSyG:b-4wx3qa) ([raw file](https://github.com/seeleteam/go-seele/blob/df614857e50f600e183cd2672438597cf78e4b07/cmd/client/cmd/miner.go#L24)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

Done.
</blockquote></details>

too many binary files is not good for usage. I suggest we use client to it all.

---

*[cmd/miner/cmd/miner.go, line 25 at r7](https://reviewable.io/reviews/seeleteam/go-seele/155#-LCDHFVzExZfhjtjk-nG:-LCDHFVzExZfhjtjk-nH:bheibrt) ([raw file](https://github.com/seeleteam/go-seele/blob/ae18a2dfbf1981dd90863daea14a06beff7d96da/cmd/miner/cmd/miner.go#L25)):*
> ```
> miner.exe miner start [-t <miner threads num>]
> ```

make sure your sample is right. I think it is  miner.exe miner --start [-t <miner threads num>]

---

*[cmd/miner/cmd/miner.go, line 67 at r7](https://reviewable.io/reviews/seeleteam/go-seele/155#-LCDIT0l6OhIyVysCLbG:-LCDIT0l6OhIyVysCLbH:btdoxgv) ([raw file](https://github.com/seeleteam/go-seele/blob/ae18a2dfbf1981dd90863daea14a06beff7d96da/cmd/miner/cmd/miner.go#L67)):*
> ```Go
> 	threadsNum = minerCmd.Flags().IntP("threads", "t", 0, "threads num of the miner")
> 
> 	minerCmd.Flags().BoolVar(&start, "start", false, "start miner")
> ```

how could I know if  miner is started, before I call start or stop?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/155)*

**Comment by lucusfly** [comment]
Reviewed 27 of 58 files at r1, 1 of 30 files at r2, 1 of 2 files at r3, 3 of 5 files at r5, 1 of 6 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/155)*

**Pull request merged**
