### PR TITLE
add cmd common

### PR DESCRIPTION
**Pull request by wuliaodw88**
add cmd common and three examples.support common basic types and non nested struct

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/162)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/client/cmd/cmd.go, line 21 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD18nf8BMUJWa1CXpT:-LCD18nf8BMUJWa1CXpU:b2pn7ux) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmd.go#L21)):*
> ```Go
> 	config, err := NewConfig(DefaultPath)
> 	if err != nil {
> 		fmt.Println("init cmd fail :\n", err)
> ```

1) err info missed.
2) redundant new line '\n'

---

*[cmd/client/cmd/cmd.go, line 27 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD1OClCkopBLjxd4tv:-LCD1OClCkopBLjxd4tw:b2pn7ux) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmd.go#L27)):*
> ```Go
> 		cmd, err := config.InitCommand(request)
> 		if err != nil {
> 			fmt.Println("init cmd fail :\n", err)
> ```

1) err info missed.
2) redundant new line '\n'

---

*[cmd/client/cmd/cmd.go, line 76 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD2wmH6ivXR4hGDxEX:-LCD2wmH6ivXR4hGDxEY:b-5izmti) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmd.go#L76)):*
> ```Go
> 				return
> 			}
> 			fmt.Println("output :\n", string(jsonOutput))
> ```

1) print output only when succeeded.
2) output info missed
3) redundant \n

---

*[cmd/client/cmd/cmd.go, line 101 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD3Kww4TD94MxFEu1J:-LCD3Kww4TD94MxFEu1K:bm3ipto) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmd.go#L101)):*
> ```Go
> 			paramFlags[param.ReflectName] = cmd.Flags().IntP(param.ParamName, param.ShortHand, int(param.DefaultValue.(float64)), param.Usage)
> 		default:
> 			return errors.New("flag type match miss")
> ```

unexpected flag type xxx

---

*[cmd/client/cmd/cmd.go, line 116 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD3UbU6sd2auzuhlV8:-LCD3UbU6sd2auzuhlV9:bm3ipto) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmd.go#L116)):*
> ```Go
> 			paramFlags[param.ReflectName] = cmd.Flags().Int(param.ParamName, int(param.DefaultValue.(float64)), param.Usage)
> 		default:
> 			return errors.New("flag type match miss")
> ```

unexpected flag type xxx

---

*[cmd/client/cmd/cmdconfig.go, line 25 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD4fbHEDL_2fWigVTA:-LCD4fbHEDL_2fWigVTB:bir3whz) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmdconfig.go#L25)):*
> ```Go
> 	Short       string  // Short is the short description shown in the 'help' output
> 	Long        string  // Long is the long message shown in the 'help <this-command>' output
> 	RequestType string  // RequestType is the type of param used to visit rpc api
> ```

2 suggestions:
1) Rename it to ParamType
2) Detailed comment is desired to explain what kinds of type supported.

---

*[cmd/client/cmd/cmdconfig.go, line 45 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD5xyn5n8B3H1fco2y:-LCD5xyn5n8B3H1fco2z:b7otnon) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmdconfig.go#L45)):*
> ```Go
> type Config struct {
> 	structMap map[string]interface{}
> 	basicMap  map[string]interface{}
> ```

recommend to add necessary comments to describe what these 2 maps used for?

---

*[cmd/client/cmd/cmdconfig.go, line 46 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD6F3xEjHcuMGE2Gx5:-LCD6F3xEjHcuMGE2Gx6:b-p6fmcl) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmdconfig.go#L46)):*
> ```Go
> 	structMap map[string]interface{}
> 	basicMap  map[string]interface{}
> 	request   []Request
> ```

[]*Request to avoid unnecessary copy

---

*[cmd/client/cmd/cmdconfig.go, line 68 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD6XM8-K8Ya2anZAhz:-LCD6XM8-K8Ya2anZAi-:bogrqre) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmdconfig.go#L68)):*
> ```Go
> func (c *Config) InitStructData() {
> 	c.structMap["GetBlockByHeightRequest"] = seele.GetBlockByHeightRequest{}
> 	c.structMap["GetBlockByHashRequest"] = seele.GetBlockByHashRequest{}
> ```

Is it possible to pass the struct param type in cmd?

A better way is define a rule to map the method name to param struct type name, e.g. method name is GetBlockByHash, then its input parameter struct type is GetBlockByHashRequest.

---

*[cmd/client/cmd/cmdconfig.go, line 78 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD73jK9i8nXO83UBzS:-LCD73jK9i8nXO83UBzT:b-7qyxhp) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmdconfig.go#L78)):*
> ```Go
> 	c.basicMap["int64"] = nil
> 	c.basicMap["uint64"] = nil
> 	c.basicMap["nil"] = nil
> ```

Once we know the method name, is it possible to reflect the 1st param type? So that, this kind of init is unnecessary.

---

*[cmd/client/cmd/cmdconfig.go, line 115 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD7WZE52QqIb6ZRxqa:-LCD7WZE52QqIb6ZRxqb:b-tvrk91) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmdconfig.go#L115)):*
> ```Go
> 
> // AddStructData add struct data for cmd config
> func (c *Config) AddStructData(name string, value interface{}) {
> ```

not used, remove it?

---

*[cmd/client/cmd/cmdconfig.go, line 120 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD7bOl4sNx8VmHHz01:-LCD7bOl4sNx8VmHHz02:b-tvrk91) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmdconfig.go#L120)):*
> ```Go
> 
> // AddBasicData add basic data for cmd config
> func (c *Config) AddBasicData(name string, value interface{}) {
> ```

not used, remove it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/162)*

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 13 unresolved discussions.

---

*[cmd/client/config/cmd.json, line 2 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD7vjZAEwfuEsy9KaI:-LCD7vjZAEwfuEsy9KaJ:b-zgbwy3) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/config/cmd.json#L2)):*
> ```JSON
> [
>     {
> ```

do we need multiple config files for different modules?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/162)*

**Comment by boqiu** [comment]
This is really a nice PR. BTW, it seems that we can support multiple input parameters based on current framework.

---

Review status: 0 of 3 files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/162#-:-LCD8TixDV_OB2Pqy8Tg:b-vag1jy)*

**Comment by lucusfly** [comment]
Review status: 0 of 3 files reviewed at latest revision, 14 unresolved discussions.

---

*[cmd/client/cmd/cmd.go, line 99 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCRVkJCDDx187hvByE6:-LCRVkJCDDx187hvByE7:b-r05yyq) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmd.go#L99)):*
> ```
> int(param.DefaultValue.(float64))
> ```

why not param.DefaultValue.(int)?

---

*[cmd/client/config/cmd.json, line 17 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCRRInD6Bf4Xm21Esie:-LCRRInD6Bf4Xm21Esif:bzbplzt) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/config/cmd.json#L17)):*
> ```
> "UseShort": false
> ```

actually UseShort is not necessary. when ShortHand is "", it means not use short.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/162)*

**Comment by wuliaodw88** [comment]
yes, if rpc client support, it is easy to do it

---

Review status: 0 of 3 files reviewed at latest revision, 16 unresolved discussions.

---

*[cmd/client/cmd/cmd.go, line 21 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD18nf8BMUJWa1CXpT:-LCRhaGv61sKLqqk-pvT:b-fx0eo) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmd.go#L21)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

1) err info missed.
2) redundant new line '\n'
</blockquote></details>

println is no problem here 

---

*[cmd/client/cmd/cmd.go, line 27 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD1OClCkopBLjxd4tv:-LCRi2E09Au_lQGbA4k3:b-rzc2py) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmd.go#L27)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

1) err info missed.
2) redundant new line '\n'
</blockquote></details>

 println is no problem here 

---

*[cmd/client/cmd/cmd.go, line 76 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD2wmH6ivXR4hGDxEX:-LCRi45K7ulqS427p0R0:b-fx0eo) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmd.go#L76)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

1) print output only when succeeded.
2) output info missed
3) redundant \n
</blockquote></details>

println is no problem here 

---

*[cmd/client/cmd/cmd.go, line 99 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCRVkJCDDx187hvByE6:-LCS_HPKE5JXcKtJgBUJ:bi8xvao) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmd.go#L99)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> int(param.DefaultValue.(float64))
> ```

why not param.DefaultValue.(int)?
</blockquote></details>

int in json trans to interface is defaults to float64 ,if use int it will reutrn "interface conversion: interface {} is float64, not int"

---

*[cmd/client/cmd/cmd.go, line 101 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD3Kww4TD94MxFEu1J:-LCS_n3_35eAecX5YCub:btpte1o) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmd.go#L101)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

unexpected flag type xxx
</blockquote></details>

fixed it

---

*[cmd/client/cmd/cmd.go, line 116 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD3UbU6sd2auzuhlV8:-LCS_r7P3oRK22yKIMGl:btpte1o) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmd.go#L116)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

unexpected flag type xxx
</blockquote></details>

fixed it

---

*[cmd/client/cmd/cmdconfig.go, line 25 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD4fbHEDL_2fWigVTA:-LCS_y4b1ZIGYltinIK8:btpte1o) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmdconfig.go#L25)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

2 suggestions:
1) Rename it to ParamType
2) Detailed comment is desired to explain what kinds of type supported.
</blockquote></details>

fixed it

---

*[cmd/client/cmd/cmdconfig.go, line 45 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD5xyn5n8B3H1fco2y:-LCS_zoN5jXDj15KxloW:btpte1o) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmdconfig.go#L45)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

recommend to add necessary comments to describe what these 2 maps used for?
</blockquote></details>

fixed it

---

*[cmd/client/cmd/cmdconfig.go, line 46 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD6F3xEjHcuMGE2Gx5:-LCSa6yvDjxdIuUi6aXm:bmxja9s) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmdconfig.go#L46)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

[]*Request to avoid unnecessary copy
</blockquote></details>

function return []Request

---

*[cmd/client/cmd/cmdconfig.go, line 68 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD6XM8-K8Ya2anZAhz:-LCSaLMZ2MqZs82t5pT_:b6vfela) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmdconfig.go#L68)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Is it possible to pass the struct param type in cmd?

A better way is define a rule to map the method name to param struct type name, e.g. method name is GetBlockByHash, then its input parameter struct type is GetBlockByHashRequest.
</blockquote></details>

they are two different parts,we can't stipulate how others do it in the rpc methods

---

*[cmd/client/cmd/cmdconfig.go, line 78 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD73jK9i8nXO83UBzS:-LCSb9lz3uTXdijBNdQs:b-sstgv3) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmdconfig.go#L78)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Once we know the method name, is it possible to reflect the 1st param type? So that, this kind of init is unnecessary.
</blockquote></details>

it is defined in go rpc client,i can not get it. o(╥﹏╥)o

---

*[cmd/client/cmd/cmdconfig.go, line 115 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD7WZE52QqIb6ZRxqa:-LCRifC8-MYmIxE_e1yB:b-rmq22v) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmdconfig.go#L115)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

not used, remove it?
</blockquote></details>

This method is used for extension

---

*[cmd/client/cmd/cmdconfig.go, line 120 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD7bOl4sNx8VmHHz01:-LCRiefP4A7HBiKXWIdD:b-rmq22v) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmdconfig.go#L120)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

not used, remove it?
</blockquote></details>

This method is used for extension

---

*[cmd/client/config/cmd.json, line 2 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD7vjZAEwfuEsy9KaI:-LCSbcWF-KbGyoEEpc8X:b-mj7ei3) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/config/cmd.json#L2)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

do we need multiple config files for different modules?
</blockquote></details>

it is flexible, you can load different file by use NewConfig funciton

---

*[cmd/client/config/cmd.json, line 17 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCRRInD6Bf4Xm21Esie:-LCSc0g25T2a9b3c8FLl:b-xdq0a5) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/config/cmd.json#L17)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> "UseShort": false
> ```

actually UseShort is not necessary. when ShortHand is "", it means not use short.
</blockquote></details>

good advice,fixed it 

---

*[cmd/client/config/cmd.json, line 58 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD4bJm4ouAINff4ezo:-LCSc90e7-vBxOxAkwLz:btpte1o) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/config/cmd.json#L58)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

no new line at the end of the file
</blockquote></details>

fixed it

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/162#-:-LCScESH8OR9x2qSImwN:b-gbqida)*

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/client/cmd/cmd.go, line 125 at r2](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCSefAtDua3FlU0HC9N:-LCSefAtDua3FlU0HC9O:b-gxi1qr) ([raw file](https://github.com/seeleteam/go-seele/blob/6b0b0057cd25c6f7425674029625709cd2e43536/cmd/client/cmd/cmd.go#L125)):*
> ```
> miss,check
> ```

whitespace after comma

---

*[cmd/client/cmd/cmdconfig.go, line 25 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD4fbHEDL_2fWigVTA:-LCSetaU6OqcicSnEZv8:b-11ff4v) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmdconfig.go#L25)):*
<details><summary><i>Previously, wuliaodw88 (Anzai) wrote…</i></summary><blockquote>

fixed it
</blockquote></details>

whitespace after comma, also double check all messages/comments in your RP.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/162)*

**Comment by wuliaodw88** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmd/client/cmd/cmd.go, line 125 at r2](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCSefAtDua3FlU0HC9N:-LCSlGAc4y4VckH4lEsv:btpte1o) ([raw file](https://github.com/seeleteam/go-seele/blob/6b0b0057cd25c6f7425674029625709cd2e43536/cmd/client/cmd/cmd.go#L125)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> miss,check
> ```

whitespace after comma
</blockquote></details>

fixed it

---

*[cmd/client/cmd/cmdconfig.go, line 25 at r1](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCD4fbHEDL_2fWigVTA:-LCSlBqQDlcQZ7jKfOoe:btpte1o) ([raw file](https://github.com/seeleteam/go-seele/blob/5d6bd13e54d743d7e4ff721c68c1e6736ba00269/cmd/client/cmd/cmdconfig.go#L25)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

whitespace after comma, also double check all messages/comments in your RP.
</blockquote></details>

fixed it

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/162)*

**Comment by boqiu** [comment]
Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/162)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/client/cmd/cmd.go, line 98 at r3](https://reviewable.io/reviews/seeleteam/go-seele/162#-LCTxPOJA_FQVm3W-siD:-LCTxPOJA_FQVm3W-siE:b-79ya5r) ([raw file](https://github.com/seeleteam/go-seele/blob/1df0f1bf3ed71df1c04cadc5904310cc488f7a13/cmd/client/cmd/cmd.go#L98)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 		if param.ShortHand == "" {
> 			paramFlags[param.ReflectName] = cmd.Flags().String(param.ParamName, param.DefaultValue.(string), param.Usage)
> 		} else {
> 			paramFlags[param.ReflectName] = cmd.Flags().StringP(param.ParamName, param.ShortHand, param.DefaultValue.(string), param.Usage)
> 		}
> ```
</details>

you could just use 
paramFlags[param.ReflectName] = cmd.Flags().StringP(param.ParamName, param.ShortHand, param.DefaultValue.(string), param.Usage)

because when shortHand is empty string,  it means no short.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/162)*

**Comment by lucusfly** [comment]
Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/162)*

**Pull request merged**
