### PR TITLE
Add message handler in seeleprotocol

### PR DESCRIPTION
**Pull request by qiaozhigang**
Add message handler in seeleprotocol

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/110)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[seele/peer.go, line 81 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9d4WnXE7yIX_GVGJD5:-L9d4WnXE7yIX_GVGJD6:b-1bc3yj) ([raw file](https://github.com/seeleteam/go-seele/blob/c1e636368ed46e81aa60f8ab3f7dc97079472737/seele/peer.go#L81)):*
> ```
> mark
> ```
mark is not clear, change to push?

---

*[seele/peer.go, line 89 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9d6Wlw8vO5YN0bEHEy:-L9d6Wlw8vO5YN0bEHEz:b-x7e261) ([raw file](https://github.com/seeleteam/go-seele/blob/c1e636368ed46e81aa60f8ab3f7dc97079472737/seele/peer.go#L89)):*
> ```
> SendTransactionHash
> ```
no any reference to this function?

---

*[seele/peer.go, line 96 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9d5R9W4aMuA51Mi72o:-L9d5R9W4aMuA51Mi72p:b-qok3om) ([raw file](https://github.com/seeleteam/go-seele/blob/c1e636368ed46e81aa60f8ab3f7dc97079472737/seele/peer.go#L96)):*
> ```
> p.knownTxs.Add
> ```
change to call markTransaction() to make the the same addition logic.

---

*[seele/seeleprotocol.go, line 38 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9d6mJjBqc9Pn_fRvgs:-L9d6mJjBqc9Pn_fRvgt:bt1kvgz) ([raw file](https://github.com/seeleteam/go-seele/blob/c1e636368ed46e81aa60f8ab3f7dc97079472737/seele/seeleprotocol.go#L38)):*
> ```
> //transactionMsgCode uint16 = 8
> ```
remove this unused line

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/110)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[seele/peer.go, line 81 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9d4WnXE7yIX_GVGJD5:-L9dIKpyCp4u_782lZIz:byz4oe6) ([raw file](https://github.com/seeleteam/go-seele/blob/c1e636368ed46e81aa60f8ab3f7dc97079472737/seele/peer.go#L81)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> mark
> ```
mark is not clear, change to push?
</blockquote></details>

This function is only used to identify that peer already exists the transaction hash, push means push a transaction to the peer, not proper for here.

---

*[seele/peer.go, line 89 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9d6Wlw8vO5YN0bEHEy:-L9dKy5GBIJCt70nXePW:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/c1e636368ed46e81aa60f8ab3f7dc97079472737/seele/peer.go#L89)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> SendTransactionHash
> ```
no any reference to this function?
</blockquote></details>

ok

---

*[seele/peer.go, line 96 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9d5R9W4aMuA51Mi72o:-L9dKwtYA5bmPyTBs26v:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/c1e636368ed46e81aa60f8ab3f7dc97079472737/seele/peer.go#L96)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> p.knownTxs.Add
> ```
change to call markTransaction() to make the the same addition logic.
</blockquote></details>

ok

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/110)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[seele/seeleprotocol.go, line 38 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9d6mJjBqc9Pn_fRvgs:-L9dLpH0D4wk24PQeibo:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/c1e636368ed46e81aa60f8ab3f7dc97079472737/seele/seeleprotocol.go#L38)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> //transactionMsgCode uint16 = 8
> ```
remove this unused line
</blockquote></details>

ok

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/110)*

**Comment by WTer** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[seele/peer.go, line 81 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9d4WnXE7yIX_GVGJD5:-L9dX3nw6ffLT4gG8X0f:b-tcx654) ([raw file](https://github.com/seeleteam/go-seele/blob/c1e636368ed46e81aa60f8ab3f7dc97079472737/seele/peer.go#L81)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

This function is only used to identify that peer already exists the transaction hash, push means push a transaction to the peer, not proper for here.
</blockquote></details>

got it.
anyway, you'd better to add comments to avoid confusion and readable.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/110)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[seele/peer.go, line 81 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9d4WnXE7yIX_GVGJD5:-L9dacjIDNCQ1fputDQe:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/c1e636368ed46e81aa60f8ab3f7dc97079472737/seele/peer.go#L81)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

got it.
anyway, you'd better to add comments to avoid confusion and readable.
</blockquote></details>

ok

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/110)*

**Comment by lucusfly** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[seele/peer.go, line 63 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9daSh102A7GGgUFZ5B:-L9daSh102A7GGgUFZ5C:bybfiyf) ([raw file](https://github.com/seeleteam/go-seele/blob/20baf4eae3d91c805df1cd859cd85faef5ae6183/seele/peer.go#L63)):*
> ```Go
> 		td:          big.NewInt(0),
> 		peerID:      p.Node.ID,
> 		peerStrID:   fmt.Sprintf("%x", p.Node.ID[:8]),
> ```

why not just use peerID? this will cause more collide

---

*[seele/seeleprotocol.go, line 163 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9dcdcO4585ApLDSU5n:-L9dcdcO4585ApLDSU5o:bz1e4p9) ([raw file](https://github.com/seeleteam/go-seele/blob/20baf4eae3d91c805df1cd859cd85faef5ae6183/seele/seeleprotocol.go#L163)):*
> ```Go
> 
> // syncTransactions sends pending transactions to remote peer.
> func (sp *SeeleProtocol) syncTransactions(p *peer) {
> ```

I didn't find any place call this method. when will sync transaction start?

---

*[seele/seeleprotocol.go, line 168 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9dcToDDBD040WV4xf2:-L9dcToDDBD040WV4xf3:blr6iuj) ([raw file](https://github.com/seeleteam/go-seele/blob/20baf4eae3d91c805df1cd859cd85faef5ae6183/seele/seeleprotocol.go#L168)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 	txs := sp.txPool.GetProcessableTransactions()
> 	pending := make([]*types.Transaction, 0)
> 	for _, value := range txs {
> 		pending = append(pending, value...)
> 	}
>  
> ```
</details>

This should be a method of txPool, could you move it to txPool?

---

*[seele/seeleprotocol.go, line 216 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9ddCsjB2zSyII_UigZ:-L9ddCsjB2zSyII_Uig_:b-natk04) ([raw file](https://github.com/seeleteam/go-seele/blob/8f392a05d4bdde4a5a374388e3a4f76e3d7ca9d0/seele/seeleprotocol.go#L216)):*
> ```Go
> 
> 		switch msg.Code {
> 		case transactionHashMsgCode:
> ```

please keep what I already did. This will reduce our network call.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/110)*

**Comment by lucusfly** [comment]
Reviewed 2 of 4 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/110)*

**Comment by qiaozhigang** [comment]
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[seele/peer.go, line 63 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9daSh102A7GGgUFZ5B:-L9dioleDTBaUPFp3GZw:bouwzty) ([raw file](https://github.com/seeleteam/go-seele/blob/20baf4eae3d91c805df1cd859cd85faef5ae6183/seele/peer.go#L63)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

why not just use peerID? this will cause more collide
</blockquote></details>

From beginning, in seele module, use string format of nodeid[:8] as peerID, but 

---

*[seele/seeleprotocol.go, line 163 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9dcdcO4585ApLDSU5n:-L9dv11f1XJhLh3-nSbe:b2ni9bh) ([raw file](https://github.com/seeleteam/go-seele/blob/20baf4eae3d91c805df1cd859cd85faef5ae6183/seele/seeleprotocol.go#L163)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

I didn't find any place call this method. when will sync transaction start?
</blockquote></details>

ok.

---

*[seele/seeleprotocol.go, line 168 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9dcToDDBD040WV4xf2:-L9dvKt-1ES0wshD6XfB:b-b3h2l4) ([raw file](https://github.com/seeleteam/go-seele/blob/20baf4eae3d91c805df1cd859cd85faef5ae6183/seele/seeleprotocol.go#L168)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> 	txs := sp.txPool.GetProcessableTransactions()
> 	pending := make([]*types.Transaction, 0)
> 	for _, value := range txs {
> 		pending = append(pending, value...)
> 	}
>  
> ```
This should be a method of txPool, could you move it to txPool?
</blockquote></details>

yes, it should be a function in txPool, but it is removed from txpool for some unknown reason,
maybe refactor in future.

---

*[seele/seeleprotocol.go, line 216 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/110#-L9ddCsjB2zSyII_UigZ:-L9dvuZ1-sYiMON1ExoJ:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/8f392a05d4bdde4a5a374388e3a4f76e3d7ca9d0/seele/seeleprotocol.go#L216)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

please keep what I already did. This will reduce our network call.
</blockquote></details>

ok

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/110)*

**Comment by lucusfly** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/110)*

**Comment by lucusfly** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/110)*

**Comment by WTer** [comment]
Reviewed 2 of 4 files at r1, 1 of 4 files at r2, 3 of 3 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/110)*

**Pull request merged**
