### PR TITLE
statedb implement EVM code related interfaces.

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/157)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[core/state/statedb.go, line 143 at r1](https://reviewable.io/reviews/seeleteam/go-seele/157#-LC7guoN3h_YilVK7XDl:-LC7guoN3h_YilVK7XDm:b-75b9wc) ([raw file](https://github.com/seeleteam/go-seele/blob/5190c3b962beff5812f8f64971c59ad1f07782d3/core/state/statedb.go#L143)):*
> ```
> occur
> ```
occurs

---

*[core/state/statedb_evm.go, line 45 at r1](https://reviewable.io/reviews/seeleteam/go-seele/157#-LC7j9i_3J1ymMpPE7WE:-LC7j9i_3J1ymMpPE7WF:byxn6zt) ([raw file](https://github.com/seeleteam/go-seele/blob/5190c3b962beff5812f8f64971c59ad1f07782d3/core/state/statedb_evm.go#L45)):*
> ```
> if stateObj != nil {
> ```
do we need to return err if stateObj is nil?

and nice to add comments to explain this func only and must be called once when contract created.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/157)*

**Comment by lucusfly** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[core/state/statedb_evm.go, line 58 at r1](https://reviewable.io/reviews/seeleteam/go-seele/157#-LC7i0AgBnmfZAWney14:-LC7i0AgBnmfZAWney15:bmq6idv) ([raw file](https://github.com/seeleteam/go-seele/blob/5190c3b962beff5812f8f64971c59ad1f07782d3/core/state/statedb_evm.go#L58)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 	stateObj := s.getStateObject(address)
> 	if stateObj == nil {
> 		return 0
> 	}
>  
> 	code := stateObj.loadCode(s.db)
> ```
</details>


use GetCode instead

---

*[core/state/stateobject.go, line 57 at r1](https://reviewable.io/reviews/seeleteam/go-seele/157#-LC7ic2pEcyUGNJFF9aw:-LC7ic2pEcyUGNJFF9ax:b-lfqtc8) ([raw file](https://github.com/seeleteam/go-seele/blob/5190c3b962beff5812f8f64971c59ad1f07782d3/core/state/stateobject.go#L57)):*
> ```
> s.code
> ```
copy byte

---

*[core/state/stateobject.go, line 107 at r1](https://reviewable.io/reviews/seeleteam/go-seele/157#-LC7jiHj2N6suKmyTRk9:-LC7jiHj2N6suKmyTRkA:btxbjnh) ([raw file](https://github.com/seeleteam/go-seele/blob/5190c3b962beff5812f8f64971c59ad1f07782d3/core/state/stateobject.go#L107)):*
> ```Go
> 	code, err := db.Get(s.getCodeKey(s.address))
> 	if err != nil {
> 		s.dbErr = err
> ```

better to return err, this will overwrite err when called more than once.

---

*[core/state/stateobject.go, line 129 at r1](https://reviewable.io/reviews/seeleteam/go-seele/157#-LC7jDIO6FOXADV-txwM:-LC7jDIO6FOXADV-txwN:by7m72m) ([raw file](https://github.com/seeleteam/go-seele/blob/5190c3b962beff5812f8f64971c59ad1f07782d3/core/state/stateobject.go#L129)):*
> ```Go
> func (s *StateObject) serializeCode(batch database.Batch) {
> 	if s.code == nil {
> 		batch.Delete(s.getCodeKey(s.address))
> ```

when we need delete, this will delete exist code in db.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/157)*

**Comment by WTer** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[core/state/statedb_evm_test.go, line 64 at r1](https://reviewable.io/reviews/seeleteam/go-seele/157#-LC7m0j4BnFrA5qm6hG7:-LC7m0j4BnFrA5qm6hG8:bulod5p) ([raw file](https://github.com/seeleteam/go-seele/blob/5190c3b962beff5812f8f64971c59ad1f07782d3/core/state/statedb_evm_test.go#L64)):*
> ```
> // Validate code APIs
> ```
nice to add the check for dirtyCode to ensure it must be true at this time

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/157)*

**Comment by boqiu** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[core/state/statedb.go, line 143 at r1](https://reviewable.io/reviews/seeleteam/go-seele/157#-LC7guoN3h_YilVK7XDl:-LC7yEF17wMORRyMoF1Y:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/5190c3b962beff5812f8f64971c59ad1f07782d3/core/state/statedb.go#L143)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> occur
> ```
occurs
</blockquote></details>

Done.

---

*[core/state/statedb_evm.go, line 45 at r1](https://reviewable.io/reviews/seeleteam/go-seele/157#-LC7j9i_3J1ymMpPE7WE:-LC7yKhFCmHHoejWMtvP:bvj2l22) ([raw file](https://github.com/seeleteam/go-seele/blob/5190c3b962beff5812f8f64971c59ad1f07782d3/core/state/statedb_evm.go#L45)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> if stateObj != nil {
> ```
do we need to return err if stateObj is nil?

and nice to add comments to explain this func only and must be called once when contract created.
</blockquote></details>

Unnecessary, this is the EVM required interface. In fact, EVM will call CreateAccount before SetCode

---

*[core/state/statedb_evm.go, line 58 at r1](https://reviewable.io/reviews/seeleteam/go-seele/157#-LC7i0AgBnmfZAWney14:-LC7y_7wBELE0bvaGMq-:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/5190c3b962beff5812f8f64971c59ad1f07782d3/core/state/statedb_evm.go#L58)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> 	stateObj := s.getStateObject(address)
> 	if stateObj == nil {
> 		return 0
> 	}
>  
> 	code := stateObj.loadCode(s.db)
> ```

use GetCode instead
</blockquote></details>

Done.

---

*[core/state/statedb_evm_test.go, line 64 at r1](https://reviewable.io/reviews/seeleteam/go-seele/157#-LC7m0j4BnFrA5qm6hG7:-LC7ydBR2dunG_xIL_RA:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/5190c3b962beff5812f8f64971c59ad1f07782d3/core/state/statedb_evm_test.go#L64)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> // Validate code APIs
> ```
nice to add the check for dirtyCode to ensure it must be true at this time
</blockquote></details>

Done.

---

*[core/state/stateobject.go, line 57 at r1](https://reviewable.io/reviews/seeleteam/go-seele/157#-LC7ic2pEcyUGNJFF9aw:-LC7yem32kuiK_JGpkjS:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/5190c3b962beff5812f8f64971c59ad1f07782d3/core/state/stateobject.go#L57)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> s.code
> ```
copy byte
</blockquote></details>

Done.

---

*[core/state/stateobject.go, line 107 at r1](https://reviewable.io/reviews/seeleteam/go-seele/157#-LC7jiHj2N6suKmyTRk9:-LC7ygTS6lx2CP20WTUI:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/5190c3b962beff5812f8f64971c59ad1f07782d3/core/state/stateobject.go#L107)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

better to return err, this will overwrite err when called more than once.
</blockquote></details>

Done.

---

*[core/state/stateobject.go, line 129 at r1](https://reviewable.io/reviews/seeleteam/go-seele/157#-LC7jDIO6FOXADV-txwM:-LC7ygxg2N_jdO2lUI4r:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/5190c3b962beff5812f8f64971c59ad1f07782d3/core/state/stateobject.go#L129)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

when we need delete, this will delete exist code in db.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/157)*

**Comment by WTer** [comment]
Reviewed 1 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/157)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[core/state/statedb_evm.go, line 41 at r2](https://reviewable.io/reviews/seeleteam/go-seele/157#-LC85U4Z9pQ7DVjOCjLu:-LC85U4Z9pQ7DVjOCjLv:b64wqbz) ([raw file](https://github.com/seeleteam/go-seele/blob/0bad0e4531f56ad5c6301c906051d7f7081ff12c/core/state/statedb_evm.go#L41)):*
> ```Go
> 	code, err := stateObj.loadCode(s.db)
> 	if err != nil {
> 		stateObj.dbErr = err
> ```

same return err instead of store it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/157)*

**Comment by lucusfly** [comment]
Reviewed 1 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/157)*

**Pull request merged**
