### PR TITLE
Add p2p start cmd

### PR DESCRIPTION
**Pull request by gongliaoan**
add p2p start cmd

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/71)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/node/cmd/start.go, line 34 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/71#-L7SD0Z4SJ4emN2Z25WY:-L7SD0Z4SJ4emN2Z25WZ:bxj7yrr) ([raw file](https://github.com/seeleteam/go-seele/blob/57db07e75ad4935ab80af94bd178755b459a93be/cmd/node/cmd/start.go#L34)):*
> ```Go
> 
> func (s TestServiceA) Protocols() []p2p.ProtocolInterface { return nil }
> func (s TestServiceA) Start(*p2p.Server) error            { return nil }
> ```

do you need to do something for test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/71)*

**Comment by gongliaoan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/node/cmd/start.go, line 34 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/71#-L7SD0Z4SJ4emN2Z25WY:-L7SFPID85F0SSaMLvIW:b6xfijp) ([raw file](https://github.com/seeleteam/go-seele/blob/57db07e75ad4935ab80af94bd178755b459a93be/cmd/node/cmd/start.go#L34)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

do you need to do something for test?
</blockquote></details>

I will add something after we finish the service interface. but now this is only a mock implementation of the service interface.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/71)*

**Comment by herove** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/node/cmd/start.go, line 31 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/71#-L7SF1wB7TB-eqJ_7vqu:-L7SF1wB7TB-eqJ_7vqv:b-jc38c5) ([raw file](https://github.com/seeleteam/go-seele/blob/57db07e75ad4935ab80af94bd178755b459a93be/cmd/node/cmd/start.go#L31)):*
> ```Go
> 
> // TestServiceA is a test implementation of the Service interface.
> type TestServiceA struct{}
> ```

test implementation in start.go? 

---

*[cmd/node/cmd/p2pstart.go, line 112 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/71#-L7SEEDaAb6j43Of13N7:-L7SEEDaAb6j43Of13N8:b-d5kze4) ([raw file](https://github.com/seeleteam/go-seele/blob/57db07e75ad4935ab80af94bd178755b459a93be/cmd/node/cmd/p2pstart.go#L112)):*
>  startCmd 
P2PStartCmd？

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/71)*

**Comment by gongliaoan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/node/cmd/start.go, line 31 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/71#-L7SF1wB7TB-eqJ_7vqu:-L7SI5mSI-rQpnihlfcj:b2nhswy) ([raw file](https://github.com/seeleteam/go-seele/blob/57db07e75ad4935ab80af94bd178755b459a93be/cmd/node/cmd/start.go#L31)):*
<details><summary><i>Previously, herove (Leihao Zhou) wrote…</i></summary><blockquote>

test implementation in start.go? 
</blockquote></details>

Yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/71)*

**Comment by gongliaoan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/node/cmd/p2pstart.go, line 112 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/71#-L7SEEDaAb6j43Of13N7:-L7SLbO1f9m1gBEJG2uv:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/57db07e75ad4935ab80af94bd178755b459a93be/cmd/node/cmd/p2pstart.go#L112)):*
<details><summary><i>Previously, herove (Leihao Zhou) wrote…</i></summary><blockquote>

>  startCmd 
P2PStartCmd？
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/71)*

**Comment by herove** [comment]
Reviewed 2 of 6 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/71)*

**Comment by boqiu** [comment]
Reviewed 2 of 6 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/71)*

**Comment by lucusfly** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/71)*

**Pull request merged**
