### PR TITLE
Task receipts query API

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/177)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[core/store/db_store.go, line 38 at r1](https://reviewable.io/reviews/seeleteam/go-seele/177#-LCdcVRU4ohDNmL85eup:-LCdcVRYEhgd_bcjHrVo:b-2r8ray) ([raw file](https://github.com/seeleteam/go-seele/blob/e4d65f57e026c27d2aab6c531a22652e35454c80/core/store/db_store.go#L38)):*
> ```
> BlockHeight
> ```
seems this var is never be referenced, do we need it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/177)*

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[core/store/db_store.go, line 181 at r1](https://reviewable.io/reviews/seeleteam/go-seele/177#-LCdfsUo6V6t4eZmm1uU:-LCdfsUr4IPWKDxUEBPg:b-77g36e) ([raw file](https://github.com/seeleteam/go-seele/blob/e4d65f57e026c27d2aab6c531a22652e35454c80/core/store/db_store.go#L181)):*
> ```
> encodedTxIndex
> ```
there will be security risk as no any protection on it, so adversary can modify and mislead us. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/177)*

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[core/store/db_store.go, line 38 at r1](https://reviewable.io/reviews/seeleteam/go-seele/177#-LCdcVRU4ohDNmL85eup:-LCghRJM-dfRoMVLQ7dL:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e4d65f57e026c27d2aab6c531a22652e35454c80/core/store/db_store.go#L38)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> BlockHeight
> ```
seems this var is never be referenced, do we need it?
</blockquote></details>

Done.

---

*[core/store/db_store.go, line 181 at r1](https://reviewable.io/reviews/seeleteam/go-seele/177#-LCdfsUo6V6t4eZmm1uU:-LCgfvR31qnE8xcnt1rQ:b9lxww9) ([raw file](https://github.com/seeleteam/go-seele/blob/e4d65f57e026c27d2aab6c531a22652e35454c80/core/store/db_store.go#L181)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> encodedTxIndex
> ```
there will be security risk as no any protection on it, so adversary can modify and mislead us. 
</blockquote></details>

only used for query, so no security issue.

---

*[core/store/db_store.go, line 281 at r1](https://reviewable.io/reviews/seeleteam/go-seele/177#-LCfsk3l-qpPOUVZ8Wxf:-LCghY7REpeEv6H4iXJx:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e4d65f57e026c27d2aab6c531a22652e35454c80/core/store/db_store.go#L281)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> GetReceipts
> ```

better use GetReceiptsByBlockHash
</blockquote></details>

Done.

---

*[core/store/db_store.go, line 297 at r1](https://reviewable.io/reviews/seeleteam/go-seele/177#-LCfsq-MEjWujEmE_y9z:-LCgh_w_0Z49fKtAMtke:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e4d65f57e026c27d2aab6c531a22652e35454c80/core/store/db_store.go#L297)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> GetReceipt
> ```
GetReceiptByTxHash
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/177)*

**Comment by WTer** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/177)*

**Comment by lucusfly** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/177)*

**Pull request merged**
