### PR TITLE
remove pub key in signature struct

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/53)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[core/types/transaction.go, line 50 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/53#-L6ju3HazN3agm88syZN:-L6ju3HazN3agm88syZO:b-bqw9pp) ([raw file](https://github.com/seeleteam/go-seele/blob/e3c4251422117b41752a18160c0272c97b1a6ada/core/types/transaction.go#L50)):*
> ```Go
> 		AccountNonce: nonce,
> 	}
> ```

why do we need an empty amount transaction?

---

*[crypto/signature.go, line 26 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/53#-L6jv7Y6-Xy13o1MXylU:-L6jv7Y6-Xy13o1MXylV:b-882f2p) ([raw file](https://github.com/seeleteam/go-seele/blob/e3c4251422117b41752a18160c0272c97b1a6ada/crypto/signature.go#L26)):*
> ```Go
> 	r, s, err := ecdsa.Sign(rand.Reader, privKey, hash)
> 	if err != nil {
> 		panic(fmt.Errorf("Failed to sign hash, private key = %+v, hash = %v, error = %v", privKey, hash, err.Error()))
> ```

return error instead of panic

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/53)*

**Comment by WTer** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[core/types/transaction.go, line 88 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/53#-L6jvn5mG4BKCLE60SuJ:-L6jvn5mG4BKCLE60SuK:b-vxh1o3) ([raw file](https://github.com/seeleteam/go-seele/blob/e3c4251422117b41752a18160c0272c97b1a6ada/core/types/transaction.go#L88)):*
> // TODO validate amount and nonce against account.

Just curious, how do you want to verify the amount? amount >= 0.
I think amount is valid when its value is greater than 0 if no specific scenario. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/53)*

**Comment by boqiu** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[core/types/transaction.go, line 50 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/53#-L6ju3HazN3agm88syZN:-L6k11puvIDneGcfozeC:b-3cdv9g) ([raw file](https://github.com/seeleteam/go-seele/blob/e3c4251422117b41752a18160c0272c97b1a6ada/core/types/transaction.go#L50)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

why do we need an empty amount transaction?
</blockquote></details>

not empty, value set below. Previous code has bug that assume the input amount is int64

---

*[core/types/transaction.go, line 88 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/53#-L6jvn5mG4BKCLE60SuJ:-L6k1ZNi0udH923ERHcY:b-5jxdx4) ([raw file](https://github.com/seeleteam/go-seele/blob/e3c4251422117b41752a18160c0272c97b1a6ada/core/types/transaction.go#L88)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> // TODO validate amount and nonce against account.

Just curious, how do you want to verify the amount? amount >= 0.
I think amount is valid when its value is greater than 0 if no specific scenario. 
</blockquote></details>

1) amount must <= account.balance
2) tx nonce must match the account nonce.
So, one more input parameter Account may be added for the Validate API in future.

---

*[crypto/signature.go, line 26 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/53#-L6jv7Y6-Xy13o1MXylU:-L6k7zD2Ygh3frW8ikT4:b-k4p6md) ([raw file](https://github.com/seeleteam/go-seele/blob/e3c4251422117b41752a18160c0272c97b1a6ada/crypto/signature.go#L26)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

return error instead of panic
</blockquote></details>

Unnecessary, return error will force client code to handle error everywhere.

In fact, any unexpected error of ecdsa.Sign (e.g. invalid hash length) should be found during development/testing phase.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/53)*

**Comment by WTer** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[contract/handler.go, line 15 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/53#-L6nvBgiD4D1HX58sth2:-L6nvBgiD4D1HX58sth3:b-bnpwqt) ([raw file](https://github.com/seeleteam/go-seele/blob/e3c4251422117b41752a18160c0272c97b1a6ada/contract/handler.go#L15)):*
> return

do we need to return err?

---

*[core/types/transaction.go, line 51 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/53#-L6nvwgS9Z1LBj2fEszr:-L6nvwgS9Z1LBj2fEszs:b-dfzm7j) ([raw file](https://github.com/seeleteam/go-seele/blob/e3c4251422117b41752a18160c0272c97b1a6ada/core/types/transaction.go#L51)):*
> if amount != nil

add check whether amount is valid value (>= 0)?

---

*[core/types/transaction.go, line 88 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/53#-L6jvn5mG4BKCLE60SuJ:-L6nwY8154UH5pz-89dl:bonesz3) ([raw file](https://github.com/seeleteam/go-seele/blob/e3c4251422117b41752a18160c0272c97b1a6ada/core/types/transaction.go#L88)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

1) amount must <= account.balance
2) tx nonce must match the account nonce.
So, one more input parameter Account may be added for the Validate API in future.

</blockquote></details>

nice to add these as comments.

---

*[crypto/signature.go, line 18 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/53#-L6nxQ8x4YvuCa3XMTpX:-L6nxQ8x4YvuCa3XMTpY:bh243ah) ([raw file](https://github.com/seeleteam/go-seele/blob/e3c4251422117b41752a18160c0272c97b1a6ada/crypto/signature.go#L18)):*
> S *big.Int

nice to add comments for R and S.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/53)*

**Comment by boqiu** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[contract/handler.go, line 15 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/53#-L6nvBgiD4D1HX58sth2:-L6o1Diu9zYp1mBPRzik:b-amybkr) ([raw file](https://github.com/seeleteam/go-seele/blob/e3c4251422117b41752a18160c0272c97b1a6ada/contract/handler.go#L15)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> return

do we need to return err?
</blockquote></details>

Firstly, this is not the final version. In my mind, HandTx is used to handle Tx related msg (event handle chain), and do not return anything. Because, when receive a msg/event, we shall start a go-routine to handle it without any return value. Once error occurred, just log it or further fault handling.

---

*[core/types/transaction.go, line 50 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/53#-L6ju3HazN3agm88syZN:-L6o1soh9BfEif9iRcyh:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e3c4251422117b41752a18160c0272c97b1a6ada/core/types/transaction.go#L50)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

not empty, value set below. Previous code has bug that assume the input amount is int64
</blockquote></details>

Done.

---

*[core/types/transaction.go, line 51 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/53#-L6nvwgS9Z1LBj2fEszr:-L6oAPCr3uyoHjZQCFvI:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e3c4251422117b41752a18160c0272c97b1a6ada/core/types/transaction.go#L51)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> if amount != nil

add check whether amount is valid value (>= 0)?
</blockquote></details>

Done.

---

*[core/types/transaction.go, line 88 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/53#-L6jvn5mG4BKCLE60SuJ:-L6oAS3TD7hehS4e4I8_:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e3c4251422117b41752a18160c0272c97b1a6ada/core/types/transaction.go#L88)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

nice to add these as comments.
</blockquote></details>

Done.

---

*[crypto/signature.go, line 18 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/53#-L6nxQ8x4YvuCa3XMTpX:-L6oATFw1-6n-6wsdERq:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e3c4251422117b41752a18160c0272c97b1a6ada/crypto/signature.go#L18)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> S *big.Int

nice to add comments for R and S.
</blockquote></details>

Done.

---

*[crypto/signature.go, line 26 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/53#-L6jv7Y6-Xy13o1MXylU:-L6o2t1FEGuEztNhffWR:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e3c4251422117b41752a18160c0272c97b1a6ada/crypto/signature.go#L26)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Unnecessary, return error will force client code to handle error everywhere.

In fact, any unexpected error of ecdsa.Sign (e.g. invalid hash length) should be found during development/testing phase.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/53)*

**Comment by jessonzheng** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[crypto/signature.go, line 24 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/53#-L6p0PWOC9NDnenysLvm:-L6p0PWOC9NDnenysLvn:bi78onk) ([raw file](https://github.com/seeleteam/go-seele/blob/34489144fcc57c8c0e5ff273c2f5e1d38da5bb42/crypto/signature.go#L24)):*
> ```Go
> // Panics if failed to sign hash.
> func NewSignature(privKey *ecdsa.PrivateKey, hash []byte) *Signature {
> 	r, s, err := ecdsa.Sign(rand.Reader, privKey, hash)
> ```

maybe “secp256k1.Sign” cgo way is  better than using go ecdsa lib?

---

*[crypto/signature.go, line 35 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/53#-L6p-Y07mO6VOK7JhQ-W:-L6p-Y07mO6VOK7JhQ-X:bdvmryw) ([raw file](https://github.com/seeleteam/go-seele/blob/34489144fcc57c8c0e5ff273c2f5e1d38da5bb42/crypto/signature.go#L35)):*
> ```Go
> // Return true if signature is valid, otherwise false.
> func (sig *Signature) Verify(pubKey *ecdsa.PublicKey, hash []byte) bool {
> 	return ecdsa.Verify(pubKey, hash, sig.R, sig.S)
> ```

using secp256k1.VerifySignature  cgo is better than go ecdsa lib?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/53)*

**Comment by boqiu** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[crypto/signature.go, line 24 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/53#-L6p0PWOC9NDnenysLvm:-L6p8CP0hoN5UqoilJFm:bh6zcoo) ([raw file](https://github.com/seeleteam/go-seele/blob/34489144fcc57c8c0e5ff273c2f5e1d38da5bb42/crypto/signature.go#L24)):*
<details><summary><i>Previously, jessonzheng wrote…</i></summary><blockquote>

maybe “secp256k1.Sign” cgo way is  better than using go ecdsa lib?
</blockquote></details>

We could keep it as it is and switch to cgo version once required.

---

*[crypto/signature.go, line 35 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/53#-L6p-Y07mO6VOK7JhQ-W:-L6p8jgNP9zwP1Dbx0EY:bh6zcoo) ([raw file](https://github.com/seeleteam/go-seele/blob/34489144fcc57c8c0e5ff273c2f5e1d38da5bb42/crypto/signature.go#L35)):*
<details><summary><i>Previously, jessonzheng wrote…</i></summary><blockquote>

using secp256k1.VerifySignature  cgo is better than go ecdsa lib?
</blockquote></details>

We could keep it as it is and switch to cgo version once required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/53)*

**Comment by jessonzheng** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/53)*

**Pull request merged**
