### PR TITLE
Big int to decimal

### PR DESCRIPTION
**Pull request by yanllearnn**
change big int to decimal

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/209)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[cmd/client/cmd/balance_test.go, line 33 at r1](https://reviewable.io/reviews/seeleteam/go-seele/209#-LDK4nm-A90kA8VJWwiP:-LDK4nm-A90kA8VJWwiQ:bkv44x9) ([raw file](https://github.com/seeleteam/go-seele/blob/5c8dfad0931a17ec6f252dd9c84c50b7db726c96/cmd/client/cmd/balance_test.go#L33)):*
> ```Go
> 	fmt.Println("Quotient is:", quotient)
> 	fmt.Println("Mod is:", mod)
> 	fmt.Println("numstr is:", numstr)
> ```

test more cases.

---

*[cmd/client/cmd/simple_decimal.go, line 15 at r1](https://reviewable.io/reviews/seeleteam/go-seele/209#-LDK4rOKCg44nPYL8-V5:-LDK4rOKCg44nPYL8-V6:bgghjy3) ([raw file](https://github.com/seeleteam/go-seele/blob/5c8dfad0931a17ec6f252dd9c84c50b7db726c96/cmd/client/cmd/simple_decimal.go#L15)):*
> ```Go
> )
> 
> //BigToDecimalfl simply changes big int to float64 which will miss 0 in the last
> ```

refine your comments.

---

*[cmd/client/cmd/simple_decimal.go, line 23 at r1](https://reviewable.io/reviews/seeleteam/go-seele/209#-LDK4e3U1AZBQ6PnfoCf:-LDK4e3U1AZBQ6PnfoCg:bjol351) ([raw file](https://github.com/seeleteam/go-seele/blob/5c8dfad0931a17ec6f252dd9c84c50b7db726c96/cmd/client/cmd/simple_decimal.go#L23)):*
> ```Go
> 	mod.Mod(amount, base)
> 	numstr := quotient.Text(10) + "." + fmt.Sprintf("%08s", mod.Text(10))
> 	numstr = strings.TrimRight(numstr, "0")
> ```

what if mod is 0? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/209)*

**Comment by lucusfly** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/client/cmd/simple_decimal.go, line 16 at r1](https://reviewable.io/reviews/seeleteam/go-seele/209#-LDK4xkx2rwBQFsRZLKh:-LDK4xkx2rwBQFsRZLKi:b-ngvkwm) ([raw file](https://github.com/seeleteam/go-seele/blob/5c8dfad0931a17ec6f252dd9c84c50b7db726c96/cmd/client/cmd/simple_decimal.go#L16)):*
> ```Go
> 
> //BigToDecimalfl simply changes big int to float64 which will miss 0 in the last
> func BigToDecimalfl(amount *big.Int) string {
> ```

use it in getbalance

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/209)*

**Comment by yanllearnn** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/client/cmd/simple_decimal.go, line 15 at r1](https://reviewable.io/reviews/seeleteam/go-seele/209#-LDK4rOKCg44nPYL8-V5:-LDKgAjJ7uP-JCcxwFSR:b-neiyo1) ([raw file](https://github.com/seeleteam/go-seele/blob/5c8dfad0931a17ec6f252dd9c84c50b7db726c96/cmd/client/cmd/simple_decimal.go#L15)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

refine your comments.
</blockquote></details>

modify

---

*[cmd/client/cmd/simple_decimal.go, line 16 at r1](https://reviewable.io/reviews/seeleteam/go-seele/209#-LDK4xkx2rwBQFsRZLKh:-LDKgQyg8NH9OTm7vpj4:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/5c8dfad0931a17ec6f252dd9c84c50b7db726c96/cmd/client/cmd/simple_decimal.go#L16)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

use it in getbalance
</blockquote></details>

Done.

---

*[cmd/client/cmd/simple_decimal.go, line 23 at r1](https://reviewable.io/reviews/seeleteam/go-seele/209#-LDK4e3U1AZBQ6PnfoCf:-LDKgTHv6n-HM_6zMFTh:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/5c8dfad0931a17ec6f252dd9c84c50b7db726c96/cmd/client/cmd/simple_decimal.go#L23)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

what if mod is 0? 
</blockquote></details>

Done.

---

*[cmd/client/cmd/balance_test.go, line 33 at r1](https://reviewable.io/reviews/seeleteam/go-seele/209#-LDK4nm-A90kA8VJWwiP:-LDKgVPY6380FRD6mOYq:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/5c8dfad0931a17ec6f252dd9c84c50b7db726c96/cmd/client/cmd/balance_test.go#L33)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

test more cases.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/209)*

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[cmd/client/cmd/simple_decimal_test.go, line 16 at r2](https://reviewable.io/reviews/seeleteam/go-seele/209#-LDLEREm3onp1mS7THGe:-LDLEPrR6TuICOQDWbrV:b79a1tg) ([raw file](https://github.com/seeleteam/go-seele/blob/94cd65e79b506786a1f9afaf3f73505b1231873f/cmd/client/cmd/simple_decimal_test.go#L16)):*
> ```Go
> 
> func Test_BigToDecimal(t *testing.T) {
> 	// 8位
> ```

DO NOT use Chinese in Seele.

---

*[cmd/client/cmd/simple_decimal_test.go, line 32 at r2](https://reviewable.io/reviews/seeleteam/go-seele/209#-LDLEy_D-B0nXgnj7P6y:-LDLEy_D-B0nXgnj7P6z:b-hy527y) ([raw file](https://github.com/seeleteam/go-seele/blob/94cd65e79b506786a1f9afaf3f73505b1231873f/cmd/client/cmd/simple_decimal_test.go#L32)):*
> ```Go
> 	}
> 
> 	fmt.Println("amount is:", amount)
> ```

use t.Log() instead of fmt.Println() in this file.

---

*[cmd/client/cmd/simple_decimal_test.go, line 37 at r2](https://reviewable.io/reviews/seeleteam/go-seele/209#-LDLF3Km8ll6El4W0ZnV:-LDLF3Km8ll6El4W0ZnW:b-2eit99) ([raw file](https://github.com/seeleteam/go-seele/blob/94cd65e79b506786a1f9afaf3f73505b1231873f/cmd/client/cmd/simple_decimal_test.go#L37)):*
> ```Go
> 	fmt.Println("Mod is:", mod)
> 	fmt.Println("numstr is:", numstr)
> 	// 大于8位
> ```

Use English for all comments in this file.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/209)*

**Comment by yanllearnn** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/client/cmd/simple_decimal_test.go, line 16 at r2](https://reviewable.io/reviews/seeleteam/go-seele/209#-LDLEREm3onp1mS7THGe:-LDLRD_eDcvnXwTSmDqS:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/94cd65e79b506786a1f9afaf3f73505b1231873f/cmd/client/cmd/simple_decimal_test.go#L16)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

DO NOT use Chinese in Seele.
</blockquote></details>

Done.

---

*[cmd/client/cmd/simple_decimal_test.go, line 32 at r2](https://reviewable.io/reviews/seeleteam/go-seele/209#-LDLEy_D-B0nXgnj7P6y:-LDLRECX6PY1QHkQ0rMb:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/94cd65e79b506786a1f9afaf3f73505b1231873f/cmd/client/cmd/simple_decimal_test.go#L32)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

use t.Log() instead of fmt.Println() in this file.
</blockquote></details>

Done.

---

*[cmd/client/cmd/simple_decimal_test.go, line 37 at r2](https://reviewable.io/reviews/seeleteam/go-seele/209#-LDLF3Km8ll6El4W0ZnV:-LDLREi25WVQUdR3X-pL:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/94cd65e79b506786a1f9afaf3f73505b1231873f/cmd/client/cmd/simple_decimal_test.go#L37)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Use English for all comments in this file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/209)*

**Comment by boqiu** [comment]
Reviewed 5 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/209)*

**Comment by WTer** [comment]
Reviewed 4 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/209)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[common/simple_decimal_test.go, line 19 at r3](https://reviewable.io/reviews/seeleteam/go-seele/209#-LDLt2zb-QZeR14FAjHF:-LDLt2zb-QZeR14FAjHG:b89kf04) ([raw file](https://github.com/seeleteam/go-seele/blob/5002545671a773db4113fbf19be8a186d5e034d9/common/simple_decimal_test.go#L19)):*
> ```Go
> 	var number = big.NewInt(100000000)
> 	re = BigToDecimal(number)
> 	equal = ("1" == re)
> ```

assert.Equal(t, re, "1") is enough

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/209)*

**Comment by yanllearnn** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/simple_decimal_test.go, line 19 at r3](https://reviewable.io/reviews/seeleteam/go-seele/209#-LDLt2zb-QZeR14FAjHF:-LDZLfDR97S737qdPFJv:bflwai1) ([raw file](https://github.com/seeleteam/go-seele/blob/5002545671a773db4113fbf19be8a186d5e034d9/common/simple_decimal_test.go#L19)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

assert.Equal(t, re, "1") is enough
</blockquote></details>

Done. modified it

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/209)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/209)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/209)*

**Pull request merged**
