### PR TITLE
Add service register to node

### PR DESCRIPTION
**Pull request by gongliaoan**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/61)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[node/config.go, line 24 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/61#-L6tVtZfDpQqvPG1bovQ:-L6tVtZfDpQqvPG1bovR:b-pthemj) ([raw file](https://github.com/seeleteam/go-seele/blob/16dae2c637244f81072a922d7b34b2d1201af364/node/config.go#L24)):*
> ```Go
> 
> 	// The configuration of p2p network
> 	P2P p2p.Config
> ```

How about inherit from the p2p.Config and remove the P2P variable?

---

*[node/service.go, line 18 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/61#-L6tWg036pokVUe39Fnl:-L6tWg036pokVUe39Fnm:b-yka89w) ([raw file](https://github.com/seeleteam/go-seele/blob/16dae2c637244f81072a922d7b34b2d1201af364/node/service.go#L18)):*
> ```Go
> 
> 	Stop() error
> }
> ```

new blank line at the end of this file. This could be detected and auto formatted by go plugins. Please double confirm with your IDE.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/61)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[node/node.go, line 27 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/61#-L6t_Ki9AH9LC2bNW8_r:-L6t_KiAX3Ugwv9tnPsI:b-966xf3) ([raw file](https://github.com/seeleteam/go-seele/blob/16dae2c637244f81072a922d7b34b2d1201af364/node/node.go#L27)):*
> DuplicateServiceError
should remove? instead with error variable

---

*[node/node.go, line 73 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/61#-L6tbWlHdAtwLBveS2bn:-L6tbWlHdAtwLBveS2bo:bu26tnv) ([raw file](https://github.com/seeleteam/go-seele/blob/16dae2c637244f81072a922d7b34b2d1201af364/node/node.go#L73)):*
> ```Go
> 		return ErrNodeRunning
> 	}
> ```

should start services in func start and stop services in func stop

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/61)*

**Comment by boqiu** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[node/config.go, line 24 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/61#-L6tVtZfDpQqvPG1bovQ:-L6v4esrh1GTE2p96sLm:b61oa0s) ([raw file](https://github.com/seeleteam/go-seele/blob/16dae2c637244f81072a922d7b34b2d1201af364/node/config.go#L24)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

Cannot inherit or remove, there will be some other config variable.
</blockquote></details>

type Config struct {
    p2p.Config    // inherit syntax make
    // other fields.

Anyway, current way is ok. I just figure out that way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/61)*

**Comment by gongliaoan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[node/config.go, line 24 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/61#-L6tVtZfDpQqvPG1bovQ:-L6tZhExIe_DjGciLRKp:b-gsid20) ([raw file](https://github.com/seeleteam/go-seele/blob/16dae2c637244f81072a922d7b34b2d1201af364/node/config.go#L24)):*
>  
> }
>  
>  
>  
>  
>  
>  
> /**
> /**
> *  @file
> *  @file
> *  @copyright defined in go-seele/LICENSE
> *  @copyright defined in go-seele/LICENSE
>  */
>  */
>  
>  
> package node
> package node
>  
>  
> import (
> import (
>  
> 	"reflect"
> 	"errors"
> 	"errors"
> 	"sync"
> 	"sync"
>  
>  
> 	"github.com/seeleteam/go-seele/log"
> 	"github.com/seeleteam/go-seele/log"
> 	"github.com/seeleteam/go-seele/p2p"
> 	"github.com/seeleteam/go-seele/p2p"
> )
> )
>  
>  
> var (
> var (
> 	ErrNodeRunning = errors.New("node is already running")
> 	ErrNodeRunning = errors.New("node is already running")
> 	ErrNodeStopped = errors.New("node is not started")
> 	ErrNodeStopped = errors.New("node is not started")
> )
> )
>  
>  
>  
> // DuplicateServiceError is returned during Node startup if a registered service
>  
> // constructor returns a service of the same type that was already started.
>  
> type DuplicateServiceError struct {
>  
> 	Kind reflect.Type
>  
> }
>  
>  
> // Node is a container for registering services.
> // Node is a container for registering services.
> type Node struct {
> type Node struct {
>  
> 	config *Config
>  
>  
> 	serverConfig p2p.Config
> 	serverConfig p2p.Config
> 	server       *p2p.Server
> 	server       *p2p.Server
>  
>  
>  
> 	services []Service
>  
>  
> 	log  *log.SeeleLog
> 	log  *log.SeeleLog
> 	lock sync.RWMutex
> 	lock sync.RWMutex
>  
> }
>  
>  
>  
> // New creates a new P2P node.
>  
> func New(conf *Config) (*Node, error) {
>  
> 	confCopy := *conf
>  
> 	conf = &confCopy
>  
>  
>  
> 	return &Node{
>  
> 		config: conf,
>  
> 		services: []Service{},
>  
> 	}, nil
>  
> }
>  
>  
>  
> // Register append a new service into the node's stack.
>  
> func (n *Node) Register(service Service) error {
>  
> 	n.lock.Lock()
>  
> 	defer n.lock.Unlock()
>  
>  
>  
> 	if n.server != nil {
>  
> 		return ErrNodeRunning
>  
> 	}
>  
> 	n.services = append(n.services, service)
>  
>  
>  
> 	return nil
> }
> }
>  
>  
> // Start create a p2p node.
> // Start create a p2p node.
>  
>  
>  
> /**
>  
> *  @file
>  
> *  @copyright defined in go-seele/LICENSE
>  
> */
>  
>  
>  
> package node
>  
>  
>  
> import (
>  
> 	"testing"
>  
>  
>  
> 	"github.com/seeleteam/go-seele/crypto"
>  
> 	"github.com/seeleteam/go-seele/p2p"
>  
> )
>  
>  
>  
> var(
>  
> 	testNodeKey, _ = crypto.GenerateKey()
>  
> )
>  
> 	
>  
> func testNodeConfig() *Config {
>  
> 	return &Config{
>  
> 		Name: "test node",
>  
> 		Version: "test version",
>  
> 		P2P: p2p.Config{PrivateKey: testNodeKey},
>  
> 	}
>  
> }
>  
>  
>  
> // TestServiceA is a test implementation of the Service interface.
>  
> type TestServiceA struct{}
>  
> func (s TestServiceA) Protocols() []p2p.Protocol { return nil }
>  
> func (s TestServiceA) Start(*p2p.Server) error   { return nil }
>  
> func (s TestServiceA) Stop() error               { return nil }
>  
>  
>  
> // TestServiceB is a test implementation of the Service interface.
>  
> type TestServiceB struct{}
>  
> func (s TestServiceB) Protocols() []p2p.Protocol { return nil }
>  
> func (s TestServiceB) Start(*p2p.Server) error   { return nil }
>  
> func (s TestServiceB) Stop() error               { return nil }
>  
>  
>  
> // TestServiceC is a test implementation of the Service interface.
>  
> type TestServiceC struct{}
>  
> func (s TestServiceC) Protocols() []p2p.Protocol { return nil }
>  
> func (s TestServiceC) Start(*p2p.Server) error   { return nil }
>  
> func (s TestServiceC) Stop() error               { return nil }
>  
>  
>  
> var testServiceA TestServiceA
>  
> var testServiceB TestServiceB
>  
> var testServiceC TestServiceC
>  
>  
>  
> func Test_ServiceRegistry(t *testing.T) {
>  
> 	stack, err := New(testNodeConfig())
>  
> 	if err != nil {
>  
> 		t.Fatalf("failed to create node: %v", err)
>  
> 	}
>  
> 	// Register a batch of services
>  
> 	services := []Service{testServiceA, testServiceB, testServiceC}
>  
> 	for i, service := range services {
>  
> 		if err := stack.Register(service); err != nil {
>  
> 			t.Fatalf("service #%d: registration failed: %v", i, err)
>  
> 		}
>  
> 	}
>  
> }
>  
>  
> type Service interface {
> type Service interface {
> 	Start(server *p2p.Server) error
> 	Start(server *p2p.Server) error
>  
>  
> 	Stop() error
> 	Stop() error
> }
> }

---

*[node/node.go, line 27 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/61#-L6t_Ki9AH9LC2bNW8_r:-L6tbo3YpFotLilNxBuA:b-7tdf7d) ([raw file](https://github.com/seeleteam/go-seele/blob/16dae2c637244f81072a922d7b34b2d1201af364/node/node.go#L27)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

> DuplicateServiceError
should remove? instead with error variable
</blockquote></details>

agree

---

*[node/node.go, line 73 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/61#-L6tbWlHdAtwLBveS2bn:-L6tf4YFmstp2XPDdTia:b-m2ip36) ([raw file](https://github.com/seeleteam/go-seele/blob/16dae2c637244f81072a922d7b34b2d1201af364/node/node.go#L73)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

should start services in func start and stop services in func stop
</blockquote></details>

agree, i will add start and stop later.

---

*[node/service.go, line 18 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/61#-L6tWg036pokVUe39Fnl:-L6teyBbKZJ-IrwM9uwg:bcotid) ([raw file](https://github.com/seeleteam/go-seele/blob/16dae2c637244f81072a922d7b34b2d1201af364/node/service.go#L18)):*
> e detected and 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/61)*

**Comment by gongliaoan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[node/config.go, line 24 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/61#-L6tVtZfDpQqvPG1bovQ:-L6yDc-wBJdP2hr7BpD9:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/16dae2c637244f81072a922d7b34b2d1201af364/node/config.go#L24)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

>  
> }
>  
>  
>  
>  
>  
>  
> /**
> /**
> *  @file
> *  @file
> *  @copyright defined in go-seele/LICENSE
> *  @copyright defined in go-seele/LICENSE
>  */
>  */
>  
>  
> package node
> package node
>  
>  
> import (
> import (
>  
> 	"reflect"
> 	"errors"
> 	"errors"
> 	"sync"
> 	"sync"
>  
>  
> 	"github.com/seeleteam/go-seele/log"
> 	"github.com/seeleteam/go-seele/log"
> 	"github.com/seeleteam/go-seele/p2p"
> 	"github.com/seeleteam/go-seele/p2p"
> )
> )
>  
>  
> var (
> var (
> 	ErrNodeRunning = errors.New("node is already running")
> 	ErrNodeRunning = errors.New("node is already running")
> 	ErrNodeStopped = errors.New("node is not started")
> 	ErrNodeStopped = errors.New("node is not started")
> )
> )
>  
>  
>  
> // DuplicateServiceError is returned during Node startup if a registered service
>  
> // constructor returns a service of the same type that was already started.
>  
> type DuplicateServiceError struct {
>  
> 	Kind reflect.Type
>  
> }
>  
>  
> // Node is a container for registering services.
> // Node is a container for registering services.
> type Node struct {
> type Node struct {
>  
> 	config *Config
>  
>  
> 	serverConfig p2p.Config
> 	serverConfig p2p.Config
> 	server       *p2p.Server
> 	server       *p2p.Server
>  
>  
>  
> 	services []Service
>  
>  
> 	log  *log.SeeleLog
> 	log  *log.SeeleLog
> 	lock sync.RWMutex
> 	lock sync.RWMutex
>  
> }
>  
>  
>  
> // New creates a new P2P node.
>  
> func New(conf *Config) (*Node, error) {
>  
> 	confCopy := *conf
>  
> 	conf = &confCopy
>  
>  
>  
> 	return &Node{
>  
> 		config: conf,
>  
> 		services: []Service{},
>  
> 	}, nil
>  
> }
>  
>  
>  
> // Register append a new service into the node's stack.
>  
> func (n *Node) Register(service Service) error {
>  
> 	n.lock.Lock()
>  
> 	defer n.lock.Unlock()
>  
>  
>  
> 	if n.server != nil {
>  
> 		return ErrNodeRunning
>  
> 	}
>  
> 	n.services = append(n.services, service)
>  
>  
>  
> 	return nil
> }
> }
>  
>  
> // Start create a p2p node.
> // Start create a p2p node.
>  
>  
>  
> /**
>  
> *  @file
>  
> *  @copyright defined in go-seele/LICENSE
>  
> */
>  
>  
>  
> package node
>  
>  
>  
> import (
>  
> 	"testing"
>  
>  
>  
> 	"github.com/seeleteam/go-seele/crypto"
>  
> 	"github.com/seeleteam/go-seele/p2p"
>  
> )
>  
>  
>  
> var(
>  
> 	testNodeKey, _ = crypto.GenerateKey()
>  
> )
>  
> 	
>  
> func testNodeConfig() *Config {
>  
> 	return &Config{
>  
> 		Name: "test node",
>  
> 		Version: "test version",
>  
> 		P2P: p2p.Config{PrivateKey: testNodeKey},
>  
> 	}
>  
> }
>  
>  
>  
> // TestServiceA is a test implementation of the Service interface.
>  
> type TestServiceA struct{}
>  
> func (s TestServiceA) Protocols() []p2p.Protocol { return nil }
>  
> func (s TestServiceA) Start(*p2p.Server) error   { return nil }
>  
> func (s TestServiceA) Stop() error               { return nil }
>  
>  
>  
> // TestServiceB is a test implementation of the Service interface.
>  
> type TestServiceB struct{}
>  
> func (s TestServiceB) Protocols() []p2p.Protocol { return nil }
>  
> func (s TestServiceB) Start(*p2p.Server) error   { return nil }
>  
> func (s TestServiceB) Stop() error               { return nil }
>  
>  
>  
> // TestServiceC is a test implementation of the Service interface.
>  
> type TestServiceC struct{}
>  
> func (s TestServiceC) Protocols() []p2p.Protocol { return nil }
>  
> func (s TestServiceC) Start(*p2p.Server) error   { return nil }
>  
> func (s TestServiceC) Stop() error               { return nil }
>  
>  
>  
> var testServiceA TestServiceA
>  
> var testServiceB TestServiceB
>  
> var testServiceC TestServiceC
>  
>  
>  
> func Test_ServiceRegistry(t *testing.T) {
>  
> 	stack, err := New(testNodeConfig())
>  
> 	if err != nil {
>  
> 		t.Fatalf("failed to create node: %v", err)
>  
> 	}
>  
> 	// Register a batch of services
>  
> 	services := []Service{testServiceA, testServiceB, testServiceC}
>  
> 	for i, service := range services {
>  
> 		if err := stack.Register(service); err != nil {
>  
> 			t.Fatalf("service #%d: registration failed: %v", i, err)
>  
> 		}
>  
> 	}
>  
> }
>  
>  
> type Service interface {
> type Service interface {
> 	Start(server *p2p.Server) error
> 	Start(server *p2p.Server) error
>  
>  
> 	Stop() error
> 	Stop() error
> }
> }

</blockquote></details>

Done.

---

*[node/node.go, line 73 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/61#-L6tbWlHdAtwLBveS2bn:-L6w7vaP1z4TVCEJP3Qi:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/16dae2c637244f81072a922d7b34b2d1201af364/node/node.go#L73)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

agree, i will add start and stop later.
</blockquote></details>

Done.

---

*[node/service.go, line 18 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/61#-L6tWg036pokVUe39Fnl:-L6w7op2PHaH0tIX_K3q:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/16dae2c637244f81072a922d7b34b2d1201af364/node/service.go#L18)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

> e detected and 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/61)*

**Comment by gongliaoan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[node/config.go, line 24 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/61#-L6tVtZfDpQqvPG1bovQ:-L6yG8b7z-Ja8_V6OQUz:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/16dae2c637244f81072a922d7b34b2d1201af364/node/config.go#L24)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[node/service.go, line 18 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/61#-L6tWg036pokVUe39Fnl:-L6yGB3H6w_o4RocLoyZ:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/16dae2c637244f81072a922d7b34b2d1201af364/node/service.go#L18)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/61)*

**Comment by boqiu** [comment]
Reviewed 1 of 5 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/61)*

**Pull request merged**
