### PR TITLE
Refine makefile

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/67)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Makefile, line 1 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/67#-L7OghTd6nY-SqZGv5SU:-L7OghTe-VNZFPGgOtRj:b-x4g4c9) ([raw file](https://github.com/seeleteam/go-seele/blob/f7a2070a742a76af02fcf09948ab8a9df64b07f2/Makefile#L1)):*
> seele

Seele

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/67)*

**Comment by WTer** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/67)*

**Comment by lucusfly** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Makefile, line 1 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/67#-L7OghTd6nY-SqZGv5SU:-L7SCNn4UXoBxJ1XRj4D:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f7a2070a742a76af02fcf09948ab8a9df64b07f2/Makefile#L1)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> seele

Seele
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/67)*

**Comment by WTer** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/67)*

**Pull request merged**
