### PR TITLE
Add txpool transaction status

### PR DESCRIPTION
**Pull request by gongliaoan**
1、add transaction status in txpool

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/208)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[core/tx_pool.go, line 30 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGAAs6AaLocgnv7aDV:-LDGAAs6AaLocgnv7aDW:b-cb1gks) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_pool.go#L30)):*
> ```Go
> const (
> 	PENDING uint = iota
> 	PROCESSING
> ```

we should also have ERROR and PACKED status.

---

*[core/tx_pool.go, line 149 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGA6BH3rkEs6Nh5GQn:-LDGA6BH3rkEs6Nh5GQo:b-l6mwxj) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_pool.go#L149)):*
> ```Go
> 		return
> 	}
> 	fmt.Println("++++++before", poolTx.txStatus)
> ```

remove

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/208)*

**Comment by boqiu** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[core/tx_collection.go, line 28 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGEH1v-2FtjK2wwi7d:-LDGEH1v-2FtjK2wwi7e:b9pe913) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_collection.go#L28)):*
> ```Go
> }
> 
> func (collection *txCollection) getPendingTxs() []*types.Transaction {
> ```

1) getTxsByStatus(status) ?
2) could you please merge with the getTxs() below?

---

*[core/tx_collection.go, line 50 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGF1iA87JG6c1FCI35:-LDGF1iA87JG6c1FCI36:bxx3mwr) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_collection.go#L50)):*
> ```Go
> }
> 
> func (collection *txCollection) findPendingTx(nonce uint64) *types.Transaction {
> ```

could merge with the findTx(nonce) method. E.g. findTx(nonce, status), where the status could be ALL

---

*[core/tx_collection.go, line 69 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGFEA_CsSCdEKb9H3b:-LDGFEA_CsSCdEKb9H3c:b-nsr8nx) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_collection.go#L69)):*
> ```Go
> }
> 
> func (collection *txCollection) countPendingTxs() int {
> ```

could merge with below method count(status)?

---

*[core/tx_collection.go, line 83 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGFXcFCdwO391QaNuj:-LDGFXcFCdwO391QaNuk:b-b7yuaa) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_collection.go#L83)):*
> ```Go
> }
> 
> func (collection *txCollection) getPendingTxsOrderByNonceAsc() []*types.Transaction {
> ```

getTxs(status, nonceAsc bool)?

---

*[core/tx_pool.go, line 29 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGC5OvCkIEDJmRFaSK:-LDGC5OvCkIEDJmRFaSL:b-nx2yth) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_pool.go#L29)):*
> ```Go
> // The status of transaction in tx pool
> const (
> 	PENDING uint = iota
> ```

byte is enough.

---

*[core/tx_pool.go, line 30 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGAAs6AaLocgnv7aDV:-LDGFjDdDD37v4TkH3IT:b-8v7siy) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_pool.go#L30)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

we should also have ERROR and PACKED status.
</blockquote></details>

Better to use bitmap (1, 2, 4, 8, ...), and define a flag ALL to include all status.

---

*[core/tx_pool.go, line 38 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGBvx4BCdsWSm8EeBP:-LDGBvx4BCdsWSm8EeBQ:b-84lkjh) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_pool.go#L38)):*
> ```Go
> }
> 
> type poolTransaction struct {
> ```

pooledTx ?

---

*[core/tx_pool.go, line 109 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGFzTh2txLfUhSChxi:-LDGFzTh2txLfUhSChxj:b-oc7c9d) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_pool.go#L109)):*
> ```Go
> 	poolTx := new(poolTransaction)
> 	poolTx.transaction = tx
> 	poolTx.txStatus = PENDING
> ```

initialization may be missed when new field added in poolTransaction. Suggest to define a constructor newPooledTx() or use &poolTransaction{tx, PENDING}

---

*[core/tx_pool.go, line 119 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGCSTp3x6N9vC4k61Q:-LDGCSTp3x6N9vC4k61R:b-sv42g7) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_pool.go#L119)):*
> ```Go
> }
> 
> func (pool *TransactionPool) findPendingTransaction(from common.Address, nonce uint64) *types.Transaction {
> ```

findTransaction(from, nonce, status) ?

---

*[core/tx_pool.go, line 134 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGGXnk7i69T0GVzaVF:-LDGGXnk7i69T0GVzaVG:btb3q7g) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_pool.go#L134)):*
> ```Go
> 
> 	if pool.hashToTxMap[txHash] != nil {
> 		return pool.hashToTxMap[txHash].transaction
> ```

unnecessary to look up in 2 times 

if pooledTx, ok := ...; ok {
    return pooledTx.transaction
}

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/208)*

**Comment by gongliaoan** [comment]
Review status: 0 of 6 files reviewed at latest revision, 11 unresolved discussions.

---

*[core/tx_collection.go, line 28 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGEH1v-2FtjK2wwi7d:-LDQ6Yb_C6hTAVhWs_m6:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_collection.go#L28)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

1) getTxsByStatus(status) ?
2) could you please merge with the getTxs() below?
</blockquote></details>

Done.

---

*[core/tx_collection.go, line 50 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGF1iA87JG6c1FCI35:-LDQ6allELH7oaJeyUKk:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_collection.go#L50)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

could merge with the findTx(nonce) method. E.g. findTx(nonce, status), where the status could be ALL
</blockquote></details>

Done.

---

*[core/tx_collection.go, line 69 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGFEA_CsSCdEKb9H3b:-LDQ6e8RC1DuP5bgyIbe:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_collection.go#L69)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

could merge with below method count(status)?
</blockquote></details>

Done.

---

*[core/tx_collection.go, line 83 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGFXcFCdwO391QaNuj:-LDQ6nGe3LL32CxXCY34:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_collection.go#L83)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

getTxs(status, nonceAsc bool)?
</blockquote></details>

Done.

---

*[core/tx_pool.go, line 29 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGC5OvCkIEDJmRFaSK:-LDQ6oVZ1P5AzUEUmK6I:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_pool.go#L29)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

byte is enough.
</blockquote></details>

Done.

---

*[core/tx_pool.go, line 30 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGAAs6AaLocgnv7aDV:-LDQ6pEP110Q5dBqQl4u:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_pool.go#L30)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Better to use bitmap (1, 2, 4, 8, ...), and define a flag ALL to include all status.
</blockquote></details>

Done.

---

*[core/tx_pool.go, line 38 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGBvx4BCdsWSm8EeBP:-LDQ8KE018tDKcm7nvMQ:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_pool.go#L38)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

pooledTx ?
</blockquote></details>

Done.

---

*[core/tx_pool.go, line 109 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGFzTh2txLfUhSChxi:-LDQ7PB43b_lSZDR8nW-:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_pool.go#L109)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

initialization may be missed when new field added in poolTransaction. Suggest to define a constructor newPooledTx() or use &poolTransaction{tx, PENDING}
</blockquote></details>

Done.

---

*[core/tx_pool.go, line 119 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGCSTp3x6N9vC4k61Q:-LDQ7Q5T9oDcQU8SmWVr:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_pool.go#L119)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

findTransaction(from, nonce, status) ?
</blockquote></details>

Done.

---

*[core/tx_pool.go, line 134 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGGXnk7i69T0GVzaVF:-LDQ8JUgCjly1_Uw472s:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_pool.go#L134)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

unnecessary to look up in 2 times 

if pooledTx, ok := ...; ok {
    return pooledTx.transaction
}
</blockquote></details>

Done.

---

*[core/tx_pool.go, line 149 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGA6BH3rkEs6Nh5GQn:-LDGn7r90EFMZQiM7ACW:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_pool.go#L149)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/208)*

**Comment by boqiu** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[core/tx_pool.go, line 40 at r2](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDVNi2W5VTqdkDW8bGt:-LDVNi2W5VTqdkDW8bGu:b-qhgbgq) ([raw file](https://github.com/seeleteam/go-seele/blob/3dbc6e502b696f4dc6772781086c90f89063b7cf/core/tx_pool.go#L40)):*
> ```Go
> 
> type pooledTx struct {
> 	transaction *types.Transaction
> ```

How about inherit from Transaction, not composite?

I can see many code like "tx.transacation.Data....", inheritance could simplify the code.

---

*[core/tx_pool.go, line 140 at r2](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDVNHuf9aHdrr_W7Ep-:-LDVNHuf9aHdrr_W7Ep0:b-q5a11k) ([raw file](https://github.com/seeleteam/go-seele/blob/3dbc6e502b696f4dc6772781086c90f89063b7cf/core/tx_pool.go#L140)):*
> ```Go
> 
> // ReflushTransactionStatus reflush the pool transaction status
> func (pool *TransactionPool) ReflushTransactionStatus(txHash common.Hash, status byte) {
> ```

According to the implementation below, the right method name is "UpdateTransactionStatus"

---

*[core/tx_pool.go, line 183 at r2](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDVOw6U4f0uhL4dod6s:-LDVOw6U4f0uhL4dod6t:bp2u658) ([raw file](https://github.com/seeleteam/go-seele/blob/3dbc6e502b696f4dc6772781086c90f89063b7cf/core/tx_pool.go#L183)):*
> ```Go
> 			if collection != nil {
> 				collection.remove(poolTx.transaction.Data.AccountNonce)
> 				if collection.count(ALL) == 0 {
> ```

could merge these codes into txCollection.remove(nonce) method.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/208)*

**Comment by gongliaoan** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[core/tx_pool.go, line 40 at r2](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDVNi2W5VTqdkDW8bGt:-LDZgZigBSmRkWp8lN3-:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/3dbc6e502b696f4dc6772781086c90f89063b7cf/core/tx_pool.go#L40)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about inherit from Transaction, not composite?

I can see many code like "tx.transacation.Data....", inheritance could simplify the code.
</blockquote></details>

Done.

---

*[core/tx_pool.go, line 140 at r2](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDVNHuf9aHdrr_W7Ep-:-LDZdGfg0hbWc9GstOv6:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/3dbc6e502b696f4dc6772781086c90f89063b7cf/core/tx_pool.go#L140)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

According to the implementation below, the right method name is "UpdateTransactionStatus"
</blockquote></details>

Done.

---

*[core/tx_pool.go, line 183 at r2](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDVOw6U4f0uhL4dod6s:-LDZm7Px719eke9pGLeu:b-7nuj7h) ([raw file](https://github.com/seeleteam/go-seele/blob/3dbc6e502b696f4dc6772781086c90f89063b7cf/core/tx_pool.go#L183)):*
> txCollection.remove

can not move to txCollection.remove, beasuse here delete data in pool.accountToTxsMap

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/208)*

**Comment by gongliaoan** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/208)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[core/tx_pool.go, line 139 at r3](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDZnQdVB66kCMQAEvqg:-LDZnQdVB66kCMQAEvqh:b-tdrv7s) ([raw file](https://github.com/seeleteam/go-seele/blob/e27f1d91743e2a7ce7520fe885400fe658396e33/core/tx_pool.go#L139)):*
> ```
> reflush
> ```

updates

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/208)*

**Comment by gongliaoan** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[core/tx_pool.go, line 139 at r3](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDZnQdVB66kCMQAEvqg:-LDZnv3fBUOPVa25tczv:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e27f1d91743e2a7ce7520fe885400fe658396e33/core/tx_pool.go#L139)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> reflush
> ```

updates
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/208)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/208)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[core/tx_pool.go, line 30 at r1](https://reviewable.io/reviews/seeleteam/go-seele/208#-LDGAAs6AaLocgnv7aDV:-LDf636--KVFWPpWmU-g:bkccwd2) ([raw file](https://github.com/seeleteam/go-seele/blob/e1951056e2c024f0d52e86557c395dfc9f893bef/core/tx_pool.go#L30)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

Done.
</blockquote></details>

They are exclusive flags. I don't we need to use bitmap. Use int is enough and clear.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/208)*

**Pull request merged**
