### PR TITLE
p2p handshake genesis verify 

### PR DESCRIPTION
**Pull request by yanllearnn**
p2p handshake genesis verify in handshake

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/261)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[p2p/server.go, line 413 at r2](https://reviewable.io/reviews/seeleteam/go-seele/261#-LEgbX-g4ohK9KZzFNkg:-LEgbX-g4ohK9KZzFNkh:b-r8yg9b) ([raw file](https://github.com/seeleteam/go-seele/blob/46451af6f03838b08e3944eae21b5e1f3f6dfb2a/p2p/server.go#L413)):*
> ```
> Text(10)
> ```
define it as constant?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/261)*

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[p2p/server.go, line 435 at r2](https://reviewable.io/reviews/seeleteam/go-seele/261#-LEgbxnm26wPSbplRb05:-LEgbxnm26wPSbplRb06:b-1x7kmp) ([raw file](https://github.com/seeleteam/go-seele/blob/46451af6f03838b08e3944eae21b5e1f3f6dfb2a/p2p/server.go#L435)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
> 		var genesis core.GenesisInfo
> 		err = json.Unmarshal(recvMsg.Params, &genesis)
> 		if err != nil {
> 			return nil, 0, 0, err
> 		}
> 		for key, val := range genesis.Accounts {
> 			v, ok := srv.genesis.Accounts[key]
> 			if !ok {
> 				return nil, 0, 0, errors.New("doHandShake genesis is not equal")
> 			}
> 			if val.Text(10) != v.Text(10) {
> 				return nil, 0, 0, errors.New("doHandShake genesis value is not equal")
> 			}
> 		}
> ```
</details>

duplicated code block with before, nice to add a private func for it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/261)*

**Comment by yanllearnn** [comment]
Review status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @yanllearnn and @WTer)

---

*[p2p/server.go, line 413 at r2](https://reviewable.io/reviews/seeleteam/go-seele/261#-LEgbX-g4ohK9KZzFNkg:-LEgf1aKB2Wwfoo8677C:b-ugpuhi) ([raw file](https://github.com/seeleteam/go-seele/blob/46451af6f03838b08e3944eae21b5e1f3f6dfb2a/p2p/server.go#L413)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> Text(10)
> ```
define it as constant?
</blockquote></details>

yes,this is BigInt pointer,and is built in config ,just change it to 10 base string to check if the two parameters is equal. It is the genesis basic details.

---

*[p2p/server.go, line 435 at r2](https://reviewable.io/reviews/seeleteam/go-seele/261#-LEgbxnm26wPSbplRb05:-LEgfiFX93JqRRMzpTic:b-vpomog) ([raw file](https://github.com/seeleteam/go-seele/blob/46451af6f03838b08e3944eae21b5e1f3f6dfb2a/p2p/server.go#L435)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> 		var genesis core.GenesisInfo
> 		err = json.Unmarshal(recvMsg.Params, &genesis)
> 		if err != nil {
> 			return nil, 0, 0, err
> 		}
> 		for key, val := range genesis.Accounts {
> 			v, ok := srv.genesis.Accounts[key]
> 			if !ok {
> 				return nil, 0, 0, errors.New("doHandShake genesis is not equal")
> 			}
> 			if val.Text(10) != v.Text(10) {
> 				return nil, 0, 0, errors.New("doHandShake genesis value is not equal")
> 			}
> 		}
> ```
duplicated code block with before, nice to add a private func for it.
</blockquote></details>

ok ,will modify it

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/261)*

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @WTer, @yanllearnn, and @lucusfly)

---

*[node/node.go, line 121 at r2](https://reviewable.io/reviews/seeleteam/go-seele/261#-LEXuu62B_IaEEbKl9RQ:-LEXuu631fAbakkOmb5P:btj4uyr) ([raw file](https://github.com/seeleteam/go-seele/blob/46451af6f03838b08e3944eae21b5e1f3f6dfb2a/node/node.go#L121)):*
> ```Go
> 	}
> 
> 	p2pSever := p2p.NewServer(n.config.SeeleConfig.GenesisConfig,n.config.P2PConfig, protocols)
> ```

please add necessary whitespace after comma

Just remind, the go-plugin tool will help to format the code automatically if using vs

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/261)*

**Comment by yanllearnn** [comment]
Review status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @WTer, @boqiu, and @lucusfly)

---

*[node/node.go, line 121 at r2](https://reviewable.io/reviews/seeleteam/go-seele/261#-LEXuu62B_IaEEbKl9RQ:-LEglCQC3pPFXCdXsDt6:bqdyjnu) ([raw file](https://github.com/seeleteam/go-seele/blob/46451af6f03838b08e3944eae21b5e1f3f6dfb2a/node/node.go#L121)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

please add necessary whitespace after comma

Just remind, the go-plugin tool will help to format the code automatically if using vs
</blockquote></details>

ok ,will go fmt 

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/261)*

**Comment by lucusfly** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[p2p/server.go, line 413 at r2](https://reviewable.io/reviews/seeleteam/go-seele/261#-LEgbX-g4ohK9KZzFNkg:-LEglI-e0WQWaCsWVUUF:bq5u68n) ([raw file](https://github.com/seeleteam/go-seele/blob/46451af6f03838b08e3944eae21b5e1f3f6dfb2a/p2p/server.go#L413)):*
<details><summary><i>Previously, yanllearnn (yanpengfei) wrote…</i></summary><blockquote>

yes,this is BigInt pointer,and is built in config ,just change it to 10 base string to check if the two parameters is equal. It is the genesis basic details.
</blockquote></details>

big int have its own compare function. better use that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/261)*

**Comment by yanllearnn** [comment]
Review status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @WTer, @boqiu, and @lucusfly)

---

*[node/node.go, line 121 at r2](https://reviewable.io/reviews/seeleteam/go-seele/261#-LEXuu62B_IaEEbKl9RQ:-LEhdz-84v8pvSsm54AP:b-7k2jpe) ([raw file](https://github.com/seeleteam/go-seele/blob/46451af6f03838b08e3944eae21b5e1f3f6dfb2a/node/node.go#L121)):*
<details><summary><i>Previously, yanllearnn (yanpengfei) wrote…</i></summary><blockquote>

ok ,will go fmt 
</blockquote></details>

ready

---

*[p2p/server.go, line 435 at r2](https://reviewable.io/reviews/seeleteam/go-seele/261#-LEgbxnm26wPSbplRb05:-LEhe2Sd8F497ZEoZwmd:b-7k2jpe) ([raw file](https://github.com/seeleteam/go-seele/blob/46451af6f03838b08e3944eae21b5e1f3f6dfb2a/p2p/server.go#L435)):*
<details><summary><i>Previously, yanllearnn (yanpengfei) wrote…</i></summary><blockquote>

ok ,will modify it
</blockquote></details>

ready

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/261)*

**Comment by boqiu** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed, 1 unresolved discussion (waiting on @WTer)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/261)*

**Pull request merged**
