### PR TITLE
change miner to be ready for command line

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/94)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[miner/core.go, line 50 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/94#-L8aHtFbAlNtJOmxFcGx:-L8aHtFbAlNtJOmxFcGy:b-dgemu) ([raw file](https://github.com/seeleteam/go-seele/blob/c774de7d30d888bcebfc2c13c1917f56838ca9ed/miner/core.go#L50)):*
> exit(log)

currently this function just log info, do we need to add some operations in it, such as close channel?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/94)*

**Comment by WTer** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[miner/task.go, line 32 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/94#-L8aJWDp-12GD8Z6y1Mu:-L8aJWDp-12GD8Z6y1Mv:bse4pig) ([raw file](https://github.com/seeleteam/go-seele/blob/c774de7d30d888bcebfc2c13c1917f56838ca9ed/miner/task.go#L32)):*
> continue

this tx will be discarded permanently, right? 

---

*[miner/core.go, line 74 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/94#-L8aIGun-eVS4ywCG2Cx:-L8aIGun-eVS4ywCG2Cy:b-ryuwdf) ([raw file](https://github.com/seeleteam/go-seele/blob/c774de7d30d888bcebfc2c13c1917f56838ca9ed/miner/core.go#L74)):*
> exit

seems this function doesn't match its name:)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/94)*

**Comment by lucusfly** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[miner/task.go, line 32 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/94#-L8aJWDp-12GD8Z6y1Mu:-L8aMU8BEL7f71K_N_Xd:b2nhswy) ([raw file](https://github.com/seeleteam/go-seele/blob/c774de7d30d888bcebfc2c13c1917f56838ca9ed/miner/task.go#L32)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> continue

this tx will be discarded permanently, right? 
</blockquote></details>

Yes

---

*[miner/core.go, line 50 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/94#-L8aHtFbAlNtJOmxFcGx:-L8aMYCJ81gGdqX608go:bllaior) ([raw file](https://github.com/seeleteam/go-seele/blob/c774de7d30d888bcebfc2c13c1917f56838ca9ed/miner/core.go#L50)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> exit(log)

currently this function just log info, do we need to add some operations in it, such as close channel?
</blockquote></details>

there is nothing to close

---

*[miner/core.go, line 74 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/94#-L8aIGun-eVS4ywCG2Cx:-L8aMV6V2rLUXgbXuXo5:b-rkz5tm) ([raw file](https://github.com/seeleteam/go-seele/blob/c774de7d30d888bcebfc2c13c1917f56838ca9ed/miner/core.go#L74)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> exit

seems this function doesn't match its name:)
</blockquote></details>

Change to logAbort

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/94)*

**Comment by WTer** [comment]
Reviewed 6 of 10 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/94)*

**Comment by herove** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/94)*

**Pull request merged**
