### PR TITLE
Fix bug: tx rlp decode failed due to nil address

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/270)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @boqiu, @WTer, and @lucusfly)

---

*[common/Address.go, line 93 at r1](https://reviewable.io/reviews/seeleteam/go-seele/270#-LEhnviu6IdHf_alwV4z:-LEhnviu6IdHf_alwV5-:b-zhrfp1) ([raw file](https://github.com/seeleteam/go-seele/blob/3f3b77cd3a09a283bf69e708cc97291a3aa88ffb/common/Address.go#L93)):*
> ```
> return id.Equal(EmptyAddress)
> ```
var EmptyAddress = Address{}

so id cannot be empty(string or other types instead of Address{}) ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/270)*

**Comment by WTer** [comment]
Review status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @boqiu, @WTer, and @lucusfly)

---

*[core/blockchain_test.go, line 193 at r1](https://reviewable.io/reviews/seeleteam/go-seele/270#-LEhoOgI0zvbYRXnMJdN:-LEhoOgI0zvbYRXnMJdO:b-27jrcm) ([raw file](https://github.com/seeleteam/go-seele/blob/3f3b77cd3a09a283bf69e708cc97291a3aa88ffb/core/blockchain_test.go#L193)):*
> ```Go
> 
> 	// _, err = state.NewStatedb(newBlock.Header.StateHash, db)
> 	// assert.Equal(t, err, error(nil))
> ```

why commented these 2 lines?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/270)*

**Comment by WTer** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lucusfly)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/270)*

**Comment by boqiu** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lucusfly)

---

*[core/blockchain_test.go, line 193 at r1](https://reviewable.io/reviews/seeleteam/go-seele/270#-LEhoOgI0zvbYRXnMJdN:-LEhreYA3KSculsuDPiC:bxcwc8b) ([raw file](https://github.com/seeleteam/go-seele/blob/3f3b77cd3a09a283bf69e708cc97291a3aa88ffb/core/blockchain_test.go#L193)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

why commented these 2 lines?
</blockquote></details>

deleted by accident during test:(

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/270)*

**Pull request merged**
