### PR TITLE
Task statedb implments EVM snapshot interface

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/195)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[core/state/journal.go, line 86 at r1](https://reviewable.io/reviews/seeleteam/go-seele/195#-LD9dW03DI5uNrrag1Gi:-LD9dW03DI5uNrrag1Gj:b-5q7o9i) ([raw file](https://github.com/seeleteam/go-seele/blob/c0704a67b766b9e8af753ed262a8ebfe55142b4e/core/state/journal.go#L86)):*
> ```Go
> 
> func (ch suicideChange) revert(s *Statedb) {
> 	obj := s.getStateObject(*ch.account)
> ```

what if obj doesn't exist? do we need to create it back?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/195)*

**Comment by boqiu** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[core/state/journal.go, line 86 at r1](https://reviewable.io/reviews/seeleteam/go-seele/195#-LD9dW03DI5uNrrag1Gi:-LD9fWpX6G7BQV6ZcW7D:b-e5j111) ([raw file](https://github.com/seeleteam/go-seele/blob/c0704a67b766b9e8af753ed262a8ebfe55142b4e/core/state/journal.go#L86)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

what if obj doesn't exist? do we need to create it back?
</blockquote></details>

A state object will not be deleted when process a tx.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/195)*

**Comment by WTer** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[core/state/journal.go, line 26 at r1](https://reviewable.io/reviews/seeleteam/go-seele/195#-LD9jTbE2CMGtoVe3-AV:-LD9jTbE2CMGtoVe3-AW:bh3gcs1) ([raw file](https://github.com/seeleteam/go-seele/blob/c0704a67b766b9e8af753ed262a8ebfe55142b4e/core/state/journal.go#L26)):*
> ```
> revert
> ```
need lock, and can revert more than once?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/195)*

**Comment by boqiu** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[core/state/journal.go, line 26 at r1](https://reviewable.io/reviews/seeleteam/go-seele/195#-LD9jTbE2CMGtoVe3-AV:-LD9k4Dn0TOZvRPuEqhR:b-xuxb9g) ([raw file](https://github.com/seeleteam/go-seele/blob/c0704a67b766b9e8af753ed262a8ebfe55142b4e/core/state/journal.go#L26)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> revert
> ```
need lock, and can revert more than once?
</blockquote></details>

Currently, we process tx one by one, and do not require lock.  One journal will be reverted only once.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/195)*

**Comment by WTer** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[core/state/statedb_evm.go, line 174 at r1](https://reviewable.io/reviews/seeleteam/go-seele/195#-LD9l5K07IfU8Y8uuL_Q:-LD9l5K07IfU8Y8uuL_R:b-movsj1) ([raw file](https://github.com/seeleteam/go-seele/blob/c0704a67b766b9e8af753ed262a8ebfe55142b4e/core/state/statedb_evm.go#L174)):*
> ```
> return 0
> ```
so we only can revert to last one snapshot?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/195)*

**Comment by boqiu** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[core/state/statedb_evm.go, line 174 at r1](https://reviewable.io/reviews/seeleteam/go-seele/195#-LD9l5K07IfU8Y8uuL_Q:-LD9lpNX2Y_dY7mNxeKD:b-s2nrw8) ([raw file](https://github.com/seeleteam/go-seele/blob/c0704a67b766b9e8af753ed262a8ebfe55142b4e/core/state/statedb_evm.go#L174)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> return 0
> ```
so we only can revert to last one snapshot?
</blockquote></details>

This is to support snapshot in normal case that without Calling other contract. Multiple snapshots scenario is under developing.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/195)*

**Comment by lucusfly** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/195)*

**Comment by WTer** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/195)*

**Pull request merged**
