### PR TITLE
add some metrics

### PR DESCRIPTION
**Pull request by webbergao1**
* add leveldb metrics
* add runtime memory metrics
* add peer connected and disconnected metrics

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/213)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[database/leveldb/leveldb.go, line 43 at r1](https://reviewable.io/reviews/seeleteam/go-seele/213#-LDLC5fsD2CBAr06jXNP:-LDLC5fsD2CBAr06jXNQ:bzhd2np) ([raw file](https://github.com/seeleteam/go-seele/blob/c5aabb8a8809622c18abd59da30d51502c3b1395/database/leveldb/leveldb.go#L43)):*
> ```Go
> // Close is used to close the db when not used
> func (db *LevelDB) Close() {
> 	db.quitChan <- struct{}{}
> ```

close channel is enough, unnecessary to send a data to the channel.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/213)*

**Comment by webbergao1** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[database/leveldb/leveldb.go, line 43 at r1](https://reviewable.io/reviews/seeleteam/go-seele/213#-LDLC5fsD2CBAr06jXNP:-LDLDgT4A20PWOiFqZTm:bolipzu) ([raw file](https://github.com/seeleteam/go-seele/blob/c5aabb8a8809622c18abd59da30d51502c3b1395/database/leveldb/leveldb.go#L43)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

close channel is enough, unnecessary to send a data to the channel.
</blockquote></details>

see new commit
add an mutex.lock and already remove close(chan)
chan will auto close when all goroutine returned

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/213)*

**Comment by boqiu** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---

*[database/leveldb/leveldb.go, line 12 at r2](https://reviewable.io/reviews/seeleteam/go-seele/213#-LDLIJPQ2prHf0HYgiTI:-LDLIJPRByp6NL33f1yS:bgtvbrm) ([raw file](https://github.com/seeleteam/go-seele/blob/ec3b00ac066f62d11d7a86f274e2a06d841cc8e5/database/leveldb/leveldb.go#L12)):*
> ```Go
> 
> 	"github.com/seeleteam/go-seele/database"
> ```

remove blank lines.

---

*[database/leveldb/leveldb.go, line 20 at r2](https://reviewable.io/reviews/seeleteam/go-seele/213#-LDLIMlz08_GmTvIUT4I:-LDLIMlz08_GmTvIUT4J:b9opxyc) ([raw file](https://github.com/seeleteam/go-seele/blob/ec3b00ac066f62d11d7a86f274e2a06d841cc8e5/database/leveldb/leveldb.go#L20)):*
> ```Go
> type LevelDB struct {
> 	db       *leveldb.DB
> 	quitChan chan struct{} // used by metrics
> ```

In fact, you could create the quitChan when create a levelDB to simplify the code and do not need mutex below.

---

*[database/leveldb/metrics.go, line 169 at r2](https://reviewable.io/reviews/seeleteam/go-seele/213#-LDLJHf1Engky5wK3zB0:-LDLJHf1Engky5wK3zB1:bdiqux5) ([raw file](https://github.com/seeleteam/go-seele/blob/ec3b00ac066f62d11d7a86f274e2a06d841cc8e5/database/leveldb/metrics.go#L169)):*
> ```Go
> 
> 	db.quitLock.Lock()
> 	db.quitChan = nil
> ```

close channel?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/213)*

**Comment by webbergao1** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[database/leveldb/leveldb.go, line 12 at r2](https://reviewable.io/reviews/seeleteam/go-seele/213#-LDLIJPQ2prHf0HYgiTI:-LDLQ22J719Vu-8CpVzz:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/ec3b00ac066f62d11d7a86f274e2a06d841cc8e5/database/leveldb/leveldb.go#L12)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

remove blank lines.
</blockquote></details>

Done.

---

*[database/leveldb/leveldb.go, line 20 at r2](https://reviewable.io/reviews/seeleteam/go-seele/213#-LDLIMlz08_GmTvIUT4I:-LDLNAzv18kT_xYxBbwV:bqxr23l) ([raw file](https://github.com/seeleteam/go-seele/blob/ec3b00ac066f62d11d7a86f274e2a06d841cc8e5/database/leveldb/leveldb.go#L20)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

In fact, you could create the quitChan when create a levelDB to simplify the code and do not need mutex below.
</blockquote></details>

right , used close(chan)  instead

---

*[database/leveldb/metrics.go, line 169 at r2](https://reviewable.io/reviews/seeleteam/go-seele/213#-LDLJHf1Engky5wK3zB0:-LDLNZNI2PkK_hzm2yjk:bc40s7m) ([raw file](https://github.com/seeleteam/go-seele/blob/ec3b00ac066f62d11d7a86f274e2a06d841cc8e5/database/leveldb/metrics.go#L169)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

close channel?
</blockquote></details>

close chan in LevelDB.Close

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/213)*

**Comment by boqiu** [comment]
Reviewed 4 of 7 files at r1, 2 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/213)*

**Pull request merged**
