### PR TITLE
Task blockchain init

### PR DESCRIPTION
**Pull request by boqiu**
Define blockchain data structures with limited impl, will add functions in the afterwards PR.

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/68)

### CODE REVIEW

**Comment by herove** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/hash.go, line 4 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/68#-L7PgYJrQf5mgty_vtWO:-L7PgYJrQf5mgty_vtWP:b-w7l33v) ([raw file](https://github.com/seeleteam/go-seele/blob/aa7620178d43c812184241bc4ea0ff9895107a60/common/hash.go#L4)):*
> ```Go
> *  @file
> *  @copyright defined in go-seele/LICENSE
>  */
> ```

blank line

---

*[core/genesis.go, line 59 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/68#-L7PhJM1NLoYPHWeIPW4:-L7PhJM1NLoYPHWeIPW5:b-l2fx4j) ([raw file](https://github.com/seeleteam/go-seele/blob/aa7620178d43c812184241bc4ea0ff9895107a60/core/genesis.go#L59)):*
> ```Go
> 	storedGenesisHash, err := genesis.bcStore.GetBlockHash(0)
> 
> 	// TODO use seele defined common error instead of concrete levelDB error.
> ```

When something is waiting to be done, use comment starts with TODO: to remind maintainers.
When a known problem/issue/bug needs to be fixed/improved, use comment starts with FIXME: to remind maintainers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/68)*

**Comment by boqiu** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/hash.go, line 4 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/68#-L7PgYJrQf5mgty_vtWO:-L7S43Q-CFuHz0PDC9d9:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/aa7620178d43c812184241bc4ea0ff9895107a60/common/hash.go#L4)):*
<details><summary><i>Previously, herove (Leihao Zhou) wrote…</i></summary><blockquote>

blank line
</blockquote></details>

Done.

---

*[core/genesis.go, line 59 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/68#-L7PhJM1NLoYPHWeIPW4:-L7S44y0u2bJEbIOkUhD:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/aa7620178d43c812184241bc4ea0ff9895107a60/core/genesis.go#L59)):*
<details><summary><i>Previously, herove (Leihao Zhou) wrote…</i></summary><blockquote>

When something is waiting to be done, use comment starts with TODO: to remind maintainers.
When a known problem/issue/bug needs to be fixed/improved, use comment starts with FIXME: to remind maintainers.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/68)*

**Comment by WTer** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[core/genesis.go, line 59 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/68#-L7PhJM1NLoYPHWeIPW4:-L7S6svb2ei1TXqI2dV8:bdo5w96) ([raw file](https://github.com/seeleteam/go-seele/blob/aa7620178d43c812184241bc4ea0ff9895107a60/core/genesis.go#L59)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you can also extract a function to handle such errors

---

*[core/genesis.go, line 47 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/68#-L7S6N8gDre7HweBX4-o:-L7S6N8gDre7HweBX4-p:b-wzm5bd) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/genesis.go#L47)):*
> 0

1?

---

*[core/headerchain.go, line 14 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/68#-L7S8wi20YAIxIyDrqpK:-L7S8wi20YAIxIyDrqpL:bbyg6j) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/headerchain.go#L14)):*
> block header chain

According to the members defined in this struct, it represents the  subchain of  genesisHeader, right?

---

*[core/headerchain.go, line 16 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/68#-L7S8Op334q4LiOvKmCQ:-L7S8Op334q4LiOvKmCR:b-3wmwg2) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/headerchain.go#L16)):*
> HeaderChain

ChainHeader?

---

*[core/headerchain.go, line 36 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/68#-L7S9buX6wWMQcTCBOLT:-L7S9buX6wWMQcTCBOLU:bl2qxvi) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/headerchain.go#L36)):*
> bcStore.GetBlockHeader(genesisHash)

seems we can merge bcStore.GetBlockHash(0) and this function, which means return header and its hash from 0(hash or height).

---

*[core/store/db_store.go, line 18 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/68#-L7SB2rM3l05LJhyOrYV:-L7SB2rM3l05LJhyOrYW:bb64hjs) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/store/db_store.go#L18)):*
> keyHeadBlockHash = []byte("HeadBlockHash")

it's refered in GetHeadBlockHash and PutBlockHeader, I'm not clear why you hard code it?

---

*[core/store/db_store.go, line 43 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/68#-L7SAUroEpDGw4ndRj8f:-L7SAUroEpDGw4ndRj8g:b943ity) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/store/db_store.go#L43)):*
> encodes a block height as big endian uint64

for the purpose of? network transfer or others?

---

*[core/store/store.go, line 17 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/68#-L7SBUtA2LCH_5Mby4Vj:-L7SBUtA2LCH_5Mby4Vk:b-d97ulc) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/store/store.go#L17)):*
> // GetHeadBlockHash retrieves the HEAD block hash.

nice to add a blank line before it. also for others.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/68)*

**Comment by boqiu** [comment]
Review status: 0 of 11 files reviewed at latest revision, 8 unresolved discussions.

---

*[core/genesis.go, line 59 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/68#-L7PhJM1NLoYPHWeIPW4:-L7SGPxo4maPV7uwfB9w:b-d86ke8) ([raw file](https://github.com/seeleteam/go-seele/blob/aa7620178d43c812184241bc4ea0ff9895107a60/core/genesis.go#L59)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

you can also extract a function to handle such errors
</blockquote></details>

Unnecessary, FIXME is enough.

---

*[core/genesis.go, line 47 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/68#-L7S6N8gDre7HweBX4-o:-L7SGKYsELuS0xseqiud:b-o5vq07) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/genesis.go#L47)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> 0

1?
</blockquote></details>

height starts from 0.

---

*[core/headerchain.go, line 14 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/68#-L7S8wi20YAIxIyDrqpK:-L7SGaln7r8XhKW8KY4Q:bye3iza) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/headerchain.go#L14)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> block header chain

According to the members defined in this struct, it represents the  subchain of  genesisHeader, right?
</blockquote></details>

No, it is a chain  that constructed only by block header (with block body). The members defined below, is to cache the necessary blocks for other APIs.

---

*[core/headerchain.go, line 16 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/68#-L7S8Op334q4LiOvKmCQ:-L7SGu4S6uQajgJ3ctX-:byol7ic) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/headerchain.go#L16)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> HeaderChain

ChainHeader?
</blockquote></details>

No, it's HeaderChain, which means the chain is constructed only with block header.

---

*[core/headerchain.go, line 36 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/68#-L7S9buX6wWMQcTCBOLT:-L7SHS2BBvUob_kZ70Cg:bgyd5o1) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/headerchain.go#L36)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> bcStore.GetBlockHeader(genesisHash)

seems we can merge bcStore.GetBlockHash(0) and this function, which means return header and its hash from 0(hash or height).
</blockquote></details>

No, these 2 APIs are for general purpose, not only for the genesis block.

---

*[core/store/db_store.go, line 18 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/68#-L7SB2rM3l05LJhyOrYV:-L7SIHbh-ZuiZ1QSCjyn:b-9pj6tp) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/store/db_store.go#L18)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> keyHeadBlockHash = []byte("HeadBlockHash")

it's refered in GetHeadBlockHash and PutBlockHeader, I'm not clear why you hard code it?
</blockquote></details>

This is a key to store the HEAD block hash, do you have better key?

---

*[core/store/db_store.go, line 43 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/68#-L7SAUroEpDGw4ndRj8f:-L7SJMGm9alsnc2XrPVw:b-1v8fyu) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/store/db_store.go#L43)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> encodes a block height as big endian uint64

for the purpose of? network transfer or others?
</blockquote></details>

Database key type is []byte, so need to convert uint64 to []byte.

---

*[core/store/store.go, line 17 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/68#-L7SBUtA2LCH_5Mby4Vj:-L7SL-d5EPjYo4XMX4do:b-p3uki) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/store/store.go#L17)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> // GetHeadBlockHash retrieves the HEAD block hash.

nice to add a blank line before it. also for others.
</blockquote></details>

This is to group the related APIs together.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/68)*

**Comment by lucusfly** [comment]
Review status: 0 of 11 files reviewed at latest revision, 13 unresolved discussions.

---

*[core/genesis.go, line 28 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/68#-L7SKn9rLAr9WdxVkj-g:-L7SKn9rLAr9WdxVkj-h:bbal2z4) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/genesis.go#L28)):*
> ```Go
> // Genesis represents the genesis block in the blockchain.
> type Genesis struct {
> 	bcStore store.BlockchainStore
> ```

I don't think Genesis should reference bcStore

---

*[core/genesis.go, line 49 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/68#-L7SKyfVMIdNu0V-IEq6:-L7SKyfVMIdNu0V-IEq7:be80g4r) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/genesis.go#L49)):*
> ```Go
> 			Height:            big.NewInt(0),
> 			CreateTimestamp:   big.NewInt(0),
> 			Nonce:             1,
> ```

do we need to add version here?

---

*[core/headerchain.go, line 17 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/68#-L7SJWnmrmvR2KfCdwF6:-L7SJWnmrmvR2KfCdwF7:budtvuq) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/headerchain.go#L17)):*
> ```Go
> // This is a non-thread safe structure.
> type HeaderChain struct {
> 	bcStore store.BlockchainStore
> ```

seems we don't need refer bcStore.

---

*[core/store/db_store.go, line 23 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/68#-L7SGDt-USV9f-oq5Hu_:-L7SGDt-USV9f-oq5Hua:bz9exz8) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/store/db_store.go#L23)):*
> ```Go
> type blockchainDatabase struct {
> 	db database.Database
> }
> ```

better to add a readme file to describe database structure, such as key value patterns

---

*[core/store/db_store.go, line 89 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/68#-L7SH-WnhRCYYXUxP0Ii:-L7SH-WnhRCYYXUxP0Ij:bhi2rpw) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/store/db_store.go#L89)):*
> ```Go
> 	batch.Put(headerHash, headerBytes)
> 
> 	if isHead {
> ```

what does isHead mean?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/68)*

**Comment by lucusfly** [comment]
Review status: 0 of 11 files reviewed at latest revision, 12 unresolved discussions.

---

*[core/headerchain.go, line 16 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/68#-L7S8Op334q4LiOvKmCQ:-L7SLzTpdSCxpSTSThuq:b4anu6o) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/headerchain.go#L16)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

No, it's HeaderChain, which means the chain is constructed only with block header.
</blockquote></details>

I think HeaderChain is a little wired, could we merge HeaderChain with BlockChain?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/68)*

**Comment by WTer** [comment]
Review status: 0 of 11 files reviewed at latest revision, 8 unresolved discussions.

---

*[core/store/db_store.go, line 18 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/68#-L7SB2rM3l05LJhyOrYV:-L7SMywM63cvZxdsUZ76:b-guln47) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/store/db_store.go#L18)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

This is a key to store the HEAD block hash, do you have better key?
</blockquote></details>

got it, let's keep it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/68)*

**Comment by boqiu** [comment]
Review status: 0 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[core/genesis.go, line 28 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/68#-L7SKn9rLAr9WdxVkj-g:-L7SLxV4iV2NqY0OK_nf:b418a0j) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/genesis.go#L28)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

I don't think Genesis should reference bcStore
</blockquote></details>

Please refer to the Initialize(), genesis structure rely on bcStore to setup genesis block.

---

*[core/genesis.go, line 49 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/68#-L7SKyfVMIdNu0V-IEq6:-L7SN1fLzda0oOPDs-Nu:bhwbm74) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/genesis.go#L49)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

do we need to add version here?
</blockquote></details>

Any purpose? If different genesis required, then define different genesis instances.

---

*[core/headerchain.go, line 16 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/68#-L7S8Op334q4LiOvKmCQ:-L7SNmjK1aGRpyfyFu1F:b-1ptnai) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/headerchain.go#L16)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

I think HeaderChain is a little wired, could we merge HeaderChain with BlockChain?
</blockquote></details>

Cannot merge, please refer to the comment of HeaderChain. HeaderChain could be used for light node, while blockchain only used for archive node.

You could refer ETH for more details.

---

*[core/headerchain.go, line 17 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/68#-L7SJWnmrmvR2KfCdwF6:-L7SOHZFx7B_VSZC3iD4:b-rk9u4w) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/headerchain.go#L17)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

seems we don't need refer bcStore.
</blockquote></details>

Required in later APIs, blockchain depend on bcStore to persist blocks.

---

*[core/store/db_store.go, line 18 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/68#-L7SB2rM3l05LJhyOrYV:-L7SOUviQfWaWQplr6eO:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/store/db_store.go#L18)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

got it, let's keep it.
</blockquote></details>

Done.

---

*[core/store/db_store.go, line 23 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/68#-L7SGDt-USV9f-oq5Hu_:-L7SP2l1WN9H9pCVsAas:bw82r3c) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/store/db_store.go#L23)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

better to add a readme file to describe database structure, such as key value patterns
</blockquote></details>

I don't think so, the Database interface indicates everything. In fact, this kind of store is not restrict to kv db, but just rely on Database interface.

---

*[core/store/db_store.go, line 89 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/68#-L7SH-WnhRCYYXUxP0Ii:-L7SPULtGhp2kXgrppZS:bmscq35) ([raw file](https://github.com/seeleteam/go-seele/blob/ef35e03f99f85edd2629fda3403d0277c5f4c661/core/store/db_store.go#L89)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

what does isHead mean?
</blockquote></details>

See the comment in interface definition. isHead indicates if the input header is the HEAD block header.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/68)*

**Comment by WTer** [comment]
Reviewed 9 of 11 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/68)*

**Pull request merged**
