### PR TITLE
Add creation of seeleservice.txPool seeleservice.chain

### PR DESCRIPTION
**Pull request by qiaozhigang**
Add creation of seeleservice.txPool seeleservice.chain
Add handshake of seele.peer

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/79)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[seele/api_test.go, line 39 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7dB3TxyMBNcK2YsW6V:-L7dB3TyLgiptd9JcMlr:b-wem8s5) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/api_test.go#L39)):*
> Fail()

change to Fatal() and you can remove the "return"

---

*[seele/seeleprotocol.go, line 128 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7dBd755L8ceWS-TE8s:-L7dBd755L8ceWS-TE8t:baave75) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/seeleprotocol.go#L128)):*
> p.peersLock.Lock()

no UnLock()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/79)*

**Comment by WTer** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[seele/api_test.go, line 29 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7dGE2IrAp-FnKNUqVj:-L7dGE2IrAp-FnKNUqVk:bixmbsp) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/api_test.go#L29)):*
> accAddr

nice to rename as acctAddr? acct is more closer to account:)

---

*[seele/config.go, line 18 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7dGUS1mOhucerYy7yB:-L7dGUS1mOhucerYy7yC:bxph83o) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/config.go#L18)):*
> local storage

need to unify to all related modules, such as log, leveldb, etc.

---

*[seele/define.go, line 22 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7dGhK6IYxvd7_0ndrR:-L7dGhK6IYxvd7_0ndrS:b-2i9o4h) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/define.go#L22)):*
> "/db/blockchain"

it's safe to use relative folder

---

*[seele/seeleservice.go, line 102 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7dFiQ0-gbr9BHHEQjv:-L7dFiQ0-gbr9BHHEQjw:bnarffb) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/seeleservice.go#L102)):*
> s.chainDB.Close()

do we need to add some retry logic for these stop and close operations to ensure resource cleaned up?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/79)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[seele/api_test.go, line 29 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/79#-L7dGE2IrAp-FnKNUqVj:-L7dIivH4R3Z8aIWeyAy:btk2627) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/api_test.go#L29)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> accAddr

nice to rename as acctAddr? acct is more closer to account:)
</blockquote></details>

yes, it's a account address

---

*[seele/api_test.go, line 39 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/79#-L7dB3TxyMBNcK2YsW6V:-L7dIqPfDgEY6IeWa84s:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/api_test.go#L39)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> Fail()

change to Fatal() and you can remove the "return"
</blockquote></details>

ok

---

*[seele/config.go, line 18 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/79#-L7dGUS1mOhucerYy7yB:-L7dJ1hlERyqhtlG78E-:b7bkoir) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/config.go#L18)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> local storage

need to unify to all related modules, such as log, leveldb, etc.

</blockquote></details>

base directory

---

*[seele/define.go, line 22 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/79#-L7dGhK6IYxvd7_0ndrR:-L7dJ4zk5FVXFNA_QPlW:bro0omp) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/define.go#L22)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> "/db/blockchain"

it's safe to use relative folder
</blockquote></details>

yes, relative to config.DataRoot

---

*[seele/seeleprotocol.go, line 128 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/79#-L7dBd755L8ceWS-TE8s:-L7dJCwn-wspWSqwqJfV:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/seeleprotocol.go#L128)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> p.peersLock.Lock()

no UnLock()
</blockquote></details>

ok

---

*[seele/seeleservice.go, line 102 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/79#-L7dFiQ0-gbr9BHHEQjv:-L7dJJ7g3NTTcSFRuove:bb7hmr8) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/seeleservice.go#L102)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> s.chainDB.Close()

do we need to add some retry logic for these stop and close operations to ensure resource cleaned up?
</blockquote></details>

how?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/79)*

**Comment by WTer** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[seele/seeleservice.go, line 102 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7dFiQ0-gbr9BHHEQjv:-L7eZSHR3uM2lodF-Btq:b7al30y) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/seeleservice.go#L102)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

how?
</blockquote></details>

just for discussion:

var err
while (i++ < 3) {
     err = s.chaindb.Close()
     if err == nil {
          break
      }
}

if (err != nil)
    log.error()

I'm not sure if it's necessary, depends on you:)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/79)*

**Comment by boqiu** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[seele/api_test.go, line 19 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/79#-L7gWV628Hl9yQzK4PsR:-L7gWV628Hl9yQzK4PsS:bd7z4hs) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/api_test.go#L19)):*
> ```Go
> 
> func getTmpConfig() *Config {
> 	rootDir, err := ioutil.TempDir("", "seeleRoot")
> ```

already defined in common pkg.

---

*[seele/define.go, line 22 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/79#-L7dGhK6IYxvd7_0ndrR:-L7gXQ2Z2s73J1rQbEc1:b-9ajn7s) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/define.go#L22)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

yes, relative to config.DataRoot
</blockquote></details>

Suggest to use go API to define the (relative) path, since Windows and Linux use different path separator.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/79)*

**Comment by tianlao** [comment]
Review status: 0 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[seele/seeleprotocol.go, line 68 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7sYZEIjQZokzS6N1hc:-L7sYZEJln5KmbHZTlA3:bu1c1d4) ([raw file](https://github.com/seeleteam/go-seele/blob/2ccab39eafb7f32ecbc55526d41aeaec92a868aa/seele/seeleprotocol.go#L68)):*
> ```Go
> 			p.handleDelPeer(delPeer)
> 		case msg := <-p.ReadMsgCh:
> 			p.handleMsg(msg)
> ```

why not use coroutine? msg from the same peer can not be handled parallel？

---

*[seele/seeleprotocol.go, line 90 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7sZOqp43A3QH2NeCZr:-L7sZOqp43A3QH2NeCZs:bhp5lj4) ([raw file](https://github.com/seeleteam/go-seele/blob/2ccab39eafb7f32ecbc55526d41aeaec92a868aa/seele/seeleprotocol.go#L90)):*
> ```Go
> 		return
> 	}
> ```

we should check whether the candidate peer already exist

---

*[seele/seeleservice.go, line 53 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7sUv1GYn9Thcr_7iap:-L7sUv1GYn9Thcr_7iaq:b2q3l6a) ([raw file](https://github.com/seeleteam/go-seele/blob/2ccab39eafb7f32ecbc55526d41aeaec92a868aa/seele/seeleservice.go#L53)):*
> ```Go
> 	s.chainDB, err = leveldb.NewLevelDB(dbPath)
> 	if err != nil {
> 		log.Error("NewSeeleService Create BlockChain err. %s", err)
> ```

close chainDB

---

*[seele/seeleservice.go, line 61 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7sUyQaGWgvVXaa8C0R:-L7sUyQbM5VkYd7mIab2:b2q3l6a) ([raw file](https://github.com/seeleteam/go-seele/blob/2ccab39eafb7f32ecbc55526d41aeaec92a868aa/seele/seeleservice.go#L61)):*
> ```Go
> 	err = genesis.Initialize()
> 	if err != nil {
> 		log.Error("NewSeeleService genesis.Initialize err. %s", err)
> ```

close chainDB

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/79)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[seele/api_test.go, line 19 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7gWV628Hl9yQzK4PsR:-L7w44JCQzphV2luXcqD:bv1fbbj) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/api_test.go#L19)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

already defined in common pkg.
</blockquote></details>

can not use that dir

---

*[seele/api_test.go, line 29 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7dGE2IrAp-FnKNUqVj:-L7w1IfuO70pHO4aOKoZ:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/api_test.go#L29)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

yes, it's a account address
</blockquote></details>

Done.

---

*[seele/define.go, line 22 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7dGhK6IYxvd7_0ndrR:-L7w15F5oBnepLo3XaIt:b-e53blb) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/define.go#L22)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Suggest to use go API to define the (relative) path, since Windows and Linux use different path separator.
</blockquote></details>

path.Join to combine two parts.
path.Join(conf.DataRoot, BlockChainDir)

---

*[seele/seeleprotocol.go, line 68 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7sYZEIjQZokzS6N1hc:-L7w1QMol2YVtUBPdBya:boktpa) ([raw file](https://github.com/seeleteam/go-seele/blob/2ccab39eafb7f32ecbc55526d41aeaec92a868aa/seele/seeleprotocol.go#L68)):*
<details><summary><i>Previously, tianlao wrote…</i></summary><blockquote>

why not use coroutine? msg from the same peer can not be handled parallel？
</blockquote></details>

not same framework with eth. Func run is for SeeleProtocol, not peer.

---

*[seele/seeleprotocol.go, line 90 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7sZOqp43A3QH2NeCZr:-L7w1flC6WhtTdxLd1GV:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/2ccab39eafb7f32ecbc55526d41aeaec92a868aa/seele/seeleprotocol.go#L90)):*
<details><summary><i>Previously, tianlao wrote…</i></summary><blockquote>

we should check whether the candidate peer already exist
</blockquote></details>

ok

---

*[seele/seeleservice.go, line 102 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7dFiQ0-gbr9BHHEQjv:-L7w3zrj1ZaGtPyrmKHh:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/seeleservice.go#L102)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

just for discussion:

var err
while (i++ < 3) {
     err = s.chaindb.Close()
     if err == nil {
          break
      }
}

if (err != nil)
    log.error()

I'm not sure if it's necessary, depends on you:)

</blockquote></details>

Done.

---

*[seele/seeleservice.go, line 53 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7sUv1GYn9Thcr_7iap:-L7w40iPOilh0TTCCq-O:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2ccab39eafb7f32ecbc55526d41aeaec92a868aa/seele/seeleservice.go#L53)):*
<details><summary><i>Previously, tianlao wrote…</i></summary><blockquote>

close chainDB
</blockquote></details>

Done.

---

*[seele/seeleservice.go, line 61 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7sUyQaGWgvVXaa8C0R:-L7w4008naEnSCmoPQcZ:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2ccab39eafb7f32ecbc55526d41aeaec92a868aa/seele/seeleservice.go#L61)):*
<details><summary><i>Previously, tianlao wrote…</i></summary><blockquote>

close chainDB
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/79)*

**Comment by boqiu** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[seele/define.go, line 22 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7dGhK6IYxvd7_0ndrR:-L7wBahAsVNACsnqUP5h:b-1iq36c) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/define.go#L22)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

path.Join to combine two parts.
path.Join(conf.DataRoot, BlockChainDir)
</blockquote></details>

please refer to filepath.Separator

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/79)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[seele/define.go, line 22 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7dGhK6IYxvd7_0ndrR:-L7wCqRaLQR5cTwWTE3G:bu7i8b1) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/define.go#L22)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

please refer to filepath.Separator
</blockquote></details>

path.Join should format file path accroding to proper separator.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/79)*

**Comment by boqiu** [comment]
Reviewed 4 of 7 files at r1, 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/79)*

**Comment by qiaozhigang** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[seele/define.go, line 22 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7dGhK6IYxvd7_0ndrR:-L7wf15CbgIsY0KS2yYs:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/define.go#L22)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

path.Join should format file path accroding to proper separator.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/79)*

**Comment by qiaozhigang** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[seele/seeleprotocol.go, line 68 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7sYZEIjQZokzS6N1hc:-L7wko-8IKnx9ZnEWtEJ:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2ccab39eafb7f32ecbc55526d41aeaec92a868aa/seele/seeleprotocol.go#L68)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

not same framework with eth. Func run is for SeeleProtocol, not peer.
</blockquote></details>

Done.

---

*[seele/seeleprotocol.go, line 90 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/79#-L7sZOqp43A3QH2NeCZr:-L7wkoUGvHdJIRRq_IBq:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2ccab39eafb7f32ecbc55526d41aeaec92a868aa/seele/seeleprotocol.go#L90)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/79)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[seele/define.go, line 22 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/79#-L7dGhK6IYxvd7_0ndrR:-L80Fflh9cVmyddA5oB7:bfxh0de) ([raw file](https://github.com/seeleteam/go-seele/blob/4bb5d922d666790e1d21c3af382bb660042edd67/seele/define.go#L22)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

Done.
</blockquote></details>

path.Join couldn't do that, use filepath.Join

---

*[seele/seeleprotocol.go, line 28 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/79#-L80GN9T18yj6LuF-7Nm:-L80GN9T18yj6LuF-7Nn:bbldvh7) ([raw file](https://github.com/seeleteam/go-seele/blob/4e89413e92c6d9408b116e6f68278b402c5d006f/seele/seeleprotocol.go#L28)):*
> ```Go
> 	p2p.Protocol
> 	peers     map[string]*peer // peers map. peerID=>peer
> 	peersCan  map[string]*peer // candidate peers, holding peers before handshaking
> ```

could you use a better way to implement it, peers and peersCan seems could merge to one

---

*[seele/seeleprotocol.go, line 32 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/79#-L80GJ170_uLcYWE9SoM:-L80GJ170_uLcYWE9SoN:bq7f0si) ([raw file](https://github.com/seeleteam/go-seele/blob/4e89413e92c6d9408b116e6f68278b402c5d006f/seele/seeleprotocol.go#L32)):*
> ```Go
> 
> 	networkID uint64
> 	txPool    *core.TransactionPool
> ```

duplicate txPool with SeeleService?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/79)*

**Pull request closed without merging**
