### PR TITLE
Add seele.peer struct

### PR DESCRIPTION
**Pull request by qiaozhigang**
Add seele.peer struct
Add simple rpc api struct, convenient for rpc test

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/60)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[seele/api.go, line 5 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tS2Vl3eWLfvK2K4aa:-L6tS2Vl3eWLfvK2K4ab:b-42ho56) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/api.go#L5)):*
> package seele
Blank line before package

---

*[seele/api.go, line 18 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tSJj6B_VXB_MGPN3L:-L6tSJj6B_VXB_MGPN3M:bpnn0jx) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/api.go#L18)):*
> ```Go
> 
> // PublicSeeleAPI provides an API to access full node-related information.
> type PublicSeeleAPI struct {
> ```

Exported type/func is public, and from your comment it's node related API.
So, why not rename to NodeAPI/NodeFacade?

---

*[seele/api.go, line 28 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tSt2GOQPJYggq9548:-L6tSt2GOQPJYggq9549:bbjx26h) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/api.go#L28)):*
> input
missed necessary comment about the data type, and not used.

---

*[seele/api.go, line 32 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tTCHjGJdyyCuCJPGs:-L6tTCHk96t_28h65LWY:bmfomp1) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/api.go#L32)):*
> ```Go
> 		return errAPIInvalidParams
> 	}
> 	*addr = api.s.coinbase
> ```

If this is not the final version, please add necessary comment about the logic.

---

*[seele/api_test.go, line 15 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tTUz-2juMFz2bnzfA:-L6tTUz-2juMFz2bnzfB:b2eikd3) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/api_test.go#L15)):*
> ```Go
> 
> func Test_PublicSeeleAPI(t *testing.T) {
> 	accAddr := common.HexToAddress("0x0548d0b1a3297fea072284f86b9fd39a9f1273c46fba8951b62de5b95cd3dd846278057ec4df598a0b089a0bdc0c8fd3aa601cf01a9f30a60292ea0769388d1f")
> ```

Use existing method? e.g. GenerateRandomAddress, see address.go under common pkg.

---

*[seele/peer.go, line 36 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tU-oBbtp66OvE7NaW:-L6tU-oBbtp66OvE7NaX:bsx58g) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/peer.go#L36)):*
> ```Go
> 	version uint   // Seele protocol version negotiated
> 	head    common.Hash
> 	td      *big.Int
> ```

total difficulty? How about add necessary comment for short name variables.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/60)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[seele/api.go, line 5 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tS2Vl3eWLfvK2K4aa:-L6uVUgG8-tiPNNjI8nO:b2nign6) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/api.go#L5)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

> package seele
Blank line before package
</blockquote></details>

yes

---

*[seele/api.go, line 18 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tSJj6B_VXB_MGPN3L:-L6uWInTkChCqfzsiIzP:b-772vce) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/api.go#L18)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Exported type/func is public, and from your comment it's node related API.
So, why not rename to NodeAPI/NodeFacade?
</blockquote></details>

Node module has its own apis too. 

---

*[seele/api.go, line 28 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tSt2GOQPJYggq9548:-L6uWadnMCsVWViz-yBO:bapjn00) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/api.go#L28)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

> input
missed necessary comment about the data type, and not used.
</blockquote></details>

yes, api function's format is defined by golang, the first argument must be exist though not necessarily.

---

*[seele/api.go, line 32 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tTCHjGJdyyCuCJPGs:-L6uXA97eAv_Otns8G91:b-uuqjjw) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/api.go#L32)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

If this is not the final version, please add necessary comment about the logic.
</blockquote></details>

for function Coinbase, this is.

---

*[seele/api_test.go, line 15 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tTUz-2juMFz2bnzfA:-L6uXKOW9RyFCVPFfphU:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/api_test.go#L15)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Use existing method? e.g. GenerateRandomAddress, see address.go under common pkg.
</blockquote></details>

ok

---

*[seele/peer.go, line 36 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tU-oBbtp66OvE7NaW:-L6uXPMbMtwLuNvCxy2h:b9v9r9d) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/peer.go#L36)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

total difficulty? How about add necessary comment for short name variables.
</blockquote></details>

td is also need? ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/60)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[seele/api.go, line 5 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tS2Vl3eWLfvK2K4aa:-L6uZONxGZLspgDyTRWY:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/api.go#L5)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

yes
</blockquote></details>

Done.

---

*[seele/api.go, line 18 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tSJj6B_VXB_MGPN3L:-L6uZNFpdOkZi_Dc7KAP:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/api.go#L18)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

Node module has its own apis too. 
</blockquote></details>

Done.

---

*[seele/api.go, line 28 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tSt2GOQPJYggq9548:-L6uZLtBvb6obPdRdBiA:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/api.go#L28)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

yes, api function's format is defined by golang, the first argument must be exist though not necessarily.
</blockquote></details>

Done.

---

*[seele/api.go, line 32 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tTCHjGJdyyCuCJPGs:-L6uZKx3eOC622aKyH5l:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/api.go#L32)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

for function Coinbase, this is.
</blockquote></details>

Done.

---

*[seele/api_test.go, line 15 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tTUz-2juMFz2bnzfA:-L6uZIUKxsiKu_g6_DfT:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/api_test.go#L15)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.

---

*[seele/peer.go, line 36 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/60#-L6tU-oBbtp66OvE7NaW:-L6uZJWx9_uh81tQN6l8:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f85ed0741a248722fe890ecdc09370f0b9903af4/seele/peer.go#L36)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

td is also need? ok
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/60)*

**Comment by boqiu** [comment]
Reviewed 5 of 8 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/60)*

**Pull request merged**
