### PR TITLE
add shard num info in genesis block

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/207)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---

*[core/genesis.go, line 47 at r1](https://reviewable.io/reviews/seeleteam/go-seele/207#-LDG7j_G0KCUMHv1r23H:-LDG7j_G0KCUMHv1r23I:b-kudsrx) ([raw file](https://github.com/seeleteam/go-seele/blob/7a8efca702c453f396f955ea7aff199e28cc1fc2/core/genesis.go#L47)):*
> ```Go
> 
> type genesisExtraData struct {
> 	ShardNumber uint
> ```

move ShardNumber to GenesisInfo, so we could set it in config.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/207)*

**Comment by boqiu** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[core/genesis.go, line 47 at r1](https://reviewable.io/reviews/seeleteam/go-seele/207#-LDG7j_G0KCUMHv1r23H:-LDGHX2c5LQTad0RrhYu:b-6p54yg) ([raw file](https://github.com/seeleteam/go-seele/blob/7a8efca702c453f396f955ea7aff199e28cc1fc2/core/genesis.go#L47)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

move ShardNumber to GenesisInfo, so we could set it in config.
</blockquote></details>

Here the shard number is to be saved in genesis block.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/207)*

**Comment by lucusfly** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---

*[core/genesis.go, line 33 at r2](https://reviewable.io/reviews/seeleteam/go-seele/207#-LDGMKKR0FzLUc7g3GMT:-LDGMKKR0FzLUc7g3GMU:b-3dfkn9) ([raw file](https://github.com/seeleteam/go-seele/blob/d325a5c43f2db4ae4278252481b7b84167a7313a/core/genesis.go#L33)):*
> ```Go
> 	header    *types.BlockHeader
> 	info      GenesisInfo
> 	extraData genesisExtraData
> ```

you could also remove it.

---

*[core/genesis.go, line 78 at r2](https://reviewable.io/reviews/seeleteam/go-seele/207#-LDGMghd0POYq4Iq7WiH:-LDGMghd0POYq4Iq7WiI:b-xjxqqs) ([raw file](https://github.com/seeleteam/go-seele/blob/7acb2d1fd4a20909513c66a36a9a0f3ec1379894/core/genesis.go#L78)):*
> ```Go
> // GetDefaultGenesis get the default genesis block.
> // This is for test only.
> func GetDefaultGenesis(accounts map[common.Address]*big.Int) *Genesis {
> ```

keep this method to avoid new an empty Genesis with difficult equal to 0.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/207)*

**Comment by boqiu** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[core/genesis.go, line 33 at r2](https://reviewable.io/reviews/seeleteam/go-seele/207#-LDGMKKR0FzLUc7g3GMT:-LDGQ83a4q2v8K2TCFlD:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/d325a5c43f2db4ae4278252481b7b84167a7313a/core/genesis.go#L33)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

you could also remove it.
</blockquote></details>

Done.

---

*[core/genesis.go, line 78 at r2](https://reviewable.io/reviews/seeleteam/go-seele/207#-LDGMghd0POYq4Iq7WiH:-LDGQ9zz2e-qmMfEvUA6:b-hhodqf) ([raw file](https://github.com/seeleteam/go-seele/blob/7acb2d1fd4a20909513c66a36a9a0f3ec1379894/core/genesis.go#L78)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

keep this method to avoid new an empty Genesis with difficult equal to 0.
</blockquote></details>

The GetDefaultGenesis() only used by UT, and GetGenesis handled such case ( 0 difficulty) already.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/207)*

**Comment by lucusfly** [comment]
Reviewed 3 of 9 files at r1, 4 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/207)*

**Pull request merged**
