### PR TITLE
Add async and once event

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/65)

### CODE REVIEW

**Comment by boqiu** [comment]
nice improvement.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[event/dispatcher.go, line 23 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/65#-L7O5i1BoIRgPz3uS1VE:-L7O5i1BoIRgPz3uS1VF:bj2cpvj) ([raw file](https://github.com/seeleteam/go-seele/blob/88e1e499d7f76d25d3aa2497a4046c0cbef86de7/event/dispatcher.go#L23)):*
> ```Go
> // their jobs.
> func (h *EventManager) Fire(e Event) {
> 	h.lock.RLock()
> ```

Use write lock since 1) do not allow 2 threads to execute once events concurrently. 2)  remobeOnceListener() is write operation.

---

*[event/dispatcher.go, line 47 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/65#-L7O6WtOE6Y7I3nI8v9l:-L7O6WtOE6Y7I3nI8v9m:b-7u3136) ([raw file](https://github.com/seeleteam/go-seele/blob/88e1e499d7f76d25d3aa2497a4046c0cbef86de7/event/dispatcher.go#L47)):*
> ```Go
> 
> // AddOnceListener register a listener which only run once
> func (h *EventManager) AddOnceListener(callback EventHandleMethod) {
> ```

How about merge AddOnceListener and AddAsyncListener together, so as to support async/once listener.

---

*[event/dispatcher.go, line 57 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/65#-L7O75g2ivSmWObqsLPi:-L7O75g2ivSmWObqsLPj:b-tm6yir) ([raw file](https://github.com/seeleteam/go-seele/blob/88e1e499d7f76d25d3aa2497a4046c0cbef86de7/event/dispatcher.go#L57)):*
> ```Go
> 
> // AddOnceListener register a listener which run async
> func (h *EventManager) AddAsyncListener(callback EventHandleMethod) {
> ```

See previous comment support aysnc and once listener.

---

*[event/dispatcher.go, line 90 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/65#-L7O7Gq5EmB51tjgWkbe:-L7O7Gq5EmB51tjgWkbf:b-2kxfms) ([raw file](https://github.com/seeleteam/go-seele/blob/88e1e499d7f76d25d3aa2497a4046c0cbef86de7/event/dispatcher.go#L90)):*
> ```Go
> }
> 
> func (h *EventManager) removeOnceListener() {
> ```

lock for thread safe

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/65#-:-L7O5WEudYg5K6heyBSw:bgo5tau)*

**Comment by lucusfly** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[event/dispatcher.go, line 23 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/65#-L7O5i1BoIRgPz3uS1VE:-L7O9YBhTv1PkOa9MukF:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/88e1e499d7f76d25d3aa2497a4046c0cbef86de7/event/dispatcher.go#L23)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Use write lock since 1) do not allow 2 threads to execute once events concurrently. 2)  remobeOnceListener() is write operation.
</blockquote></details>

Done.

---

*[event/dispatcher.go, line 47 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/65#-L7O6WtOE6Y7I3nI8v9l:-L7O9Z_rpxT6TlWTq0Ge:bx890fg) ([raw file](https://github.com/seeleteam/go-seele/blob/88e1e499d7f76d25d3aa2497a4046c0cbef86de7/event/dispatcher.go#L47)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

How about merge AddOnceListener and AddAsyncListener together, so as to support async/once listener.
</blockquote></details>

add a new method AddAsyncOnceListener

---

*[event/dispatcher.go, line 57 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/65#-L7O75g2ivSmWObqsLPi:-L7O9gDiVncUWNW5BsZz:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/88e1e499d7f76d25d3aa2497a4046c0cbef86de7/event/dispatcher.go#L57)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

See previous comment support aysnc and once listener.
</blockquote></details>

Done.

---

*[event/dispatcher.go, line 90 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/65#-L7O7Gq5EmB51tjgWkbe:-L7O9h7UYNQMT3QARSSL:b-nw0q21) ([raw file](https://github.com/seeleteam/go-seele/blob/88e1e499d7f76d25d3aa2497a4046c0cbef86de7/event/dispatcher.go#L90)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

lock for thread safe
</blockquote></details>

this is a private method, and it will be called with lock wrap

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/65)*

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[event/dispatcher.go, line 47 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/65#-L7O6WtOE6Y7I3nI8v9l:-L7OBbYGDu_rQcn8o-pw:buwne5x) ([raw file](https://github.com/seeleteam/go-seele/blob/88e1e499d7f76d25d3aa2497a4046c0cbef86de7/event/dispatcher.go#L47)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

add a new method AddAsyncOnceListener
</blockquote></details>

3 "add" methods are really redundant, the original AddListener(Listener) is good enough:)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/65)*

**Comment by boqiu** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/65)*

**Comment by boqiu** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/65)*

**Pull request merged**
