### PR TITLE
add some metric points

### PR DESCRIPTION
**Pull request by ypenghui6**
1 add disk io point
2 add seele process cpu point
3 change transmission frequency
4 add metrics writeBlock time point

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/346)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 98 files reviewed, 3 unresolved discussions (waiting on @ypenghui6, @WTer, @boqiu, and @lucusfly)

---

*[core/blockchain.go, line 222 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOi_ju7FgeMeGjlIw4:-LGOiXO81hBICFi4VbSl:bblaarl) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/core/blockchain.go#L222)):*
> ```
> int64(markTime)
> ```

markTime.Seconds()

---

*[core/blockchain.go, line 226 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOioyeC-HOOnfY7p8d:-LGOioyeC-HOOnfY7p8e:b-pki2s2) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/core/blockchain.go#L226)):*
> ```
> writeBlock
> ```

doWriteBlock

---

*[core/metric.go, line 1 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOjSnDCFueD9UeN1T0:-LGOjSnDCFueD9UeN1T1:b-w75t1z) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/core/metric.go#L1)):*
> ```Go
> package core
> ```

move this file to metric folder.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/346)*

**Comment by ypenghui6** [comment]
Review status: 0 of 98 files reviewed, 3 unresolved discussions (waiting on @lucusfly, @WTer, and @boqiu)

---

*[core/blockchain.go, line 222 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOi_ju7FgeMeGjlIw4:-LGOk0heA2mR7GMVc4T0:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/core/blockchain.go#L222)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> int64(markTime)
> ```

markTime.Seconds()
</blockquote></details>

Done.

---

*[core/blockchain.go, line 226 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOioyeC-HOOnfY7p8d:-LGOkL1F6YaTEoLR7BpC:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/core/blockchain.go#L226)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> writeBlock
> ```

doWriteBlock
</blockquote></details>

Done.

---

*[core/metric.go, line 1 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOjSnDCFueD9UeN1T0:-LGOlzYG4AqCoXICNkz9:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/core/metric.go#L1)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

move this file to metric folder.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/346)*

**Comment by boqiu** [comment]
Review status: 0 of 98 files reviewed, 9 unresolved discussions (waiting on @lucusfly, @ypenghui6, @WTer, and @boqiu)

---

*[common/constant.go, line 28 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOkoeY6g6Byt5_8M7b:-LGOkoeY6g6Byt5_8M7c:bx94ci3) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/common/constant.go#L28)):*
> ```Go
> 
> 	// CPUMetricsIntervalTime is the time of metrics monitor cpu
> 	CPUMetricsIntervalTime = time.Second
> ```

Why not name to "CPUMetricsRefreshTime" to keep consistent with the previous variable name. BTW, I think "xxxMetricsRefreshInterval" is better.

---

*[core/blockchain.go, line 220 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOmELn64J_8vVS1DYW:-LGOm8nDAlt3Ez-UcH3H:bn79tj5) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/core/blockchain.go#L220)):*
> ```Go
> 		return err
> 	}
> 	doneWriteBlockTime := time.Now()
> ```

endWriteBlockTime. BTW, I think "start" and "end" is enough.

---

*[core/blockchain.go, line 221 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOmTgv8CeQ6r3ghAbr:-LGOmTgv8CeQ6r3ghAbs:b-3slpel) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/core/blockchain.go#L221)):*
> ```Go
> 	}
> 	doneWriteBlockTime := time.Now()
> 	markTime := doneWriteBlockTime.Sub(startWriteBlockTime)
> ```

you could use time.Since(startTime) to simplify the code

---

*[core/blockchain.go, line 222 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOi_ju7FgeMeGjlIw4:-LGOn-r6BkLfMcPaIh12:b5o1bgj) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/core/blockchain.go#L222)):*
<details><summary><i>Previously, ypenghui6 (ypenghui6) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

markTime.Nanoseconds() is better

---

*[metrics/metrics.go, line 18 at r3](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOnaZtAyD9oQzRqYbK:-LGOnaZtAyD9oQzRqYbL:bcpebwy) ([raw file](https://github.com/seeleteam/go-seele/blob/d78a0bacfc5437fc710c502880d3caa52b511efe/metrics/metrics.go#L18)):*
> ```
> write.block.time
> ```

here we can follow th pkg path, e.g. core.blockchain.writeBlock.time

---

*[metrics/runtimecpu.go, line 13 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOo5WN6oETRz-CjdgK:-LGOo5WN6oETRz-CjdgL:b-ml8i8y) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/metrics/runtimecpu.go#L13)):*
> ```Go
> 
> var (
> 	metricsCpuGauge      = metrics.GetOrRegisterGauge("cpu.accout", nil)
> ```

typo: account

---

*[metrics/runtimecpu.go, line 14 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOo8I05Y2Qgs_5vm48:-LGOo8I05Y2Qgs_5vm49:b-mjazyq) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/metrics/runtimecpu.go#L14)):*
> ```Go
> var (
> 	metricsCpuGauge      = metrics.GetOrRegisterGauge("cpu.accout", nil)
> 	metricsSeeleCpuGauge = metrics.GetOrRegisterGauge("cpu.seele.accout", nil)
> ```

any difference between these 2 Gauge? suggest to add necessary comments.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/346)*

**Comment by WTer** [comment]
Review status: 0 of 98 files reviewed, 10 unresolved discussions (waiting on @lucusfly, @ypenghui6, @WTer, and @boqiu)

---

*[common/constant.go, line 18 at r3](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOrb9R0oAYeQ0NjBQq:-LGOrb9R0oAYeQ0NjBQr:b2tpisp) ([raw file](https://github.com/seeleteam/go-seele/blob/d78a0bacfc5437fc710c502880d3caa52b511efe/common/constant.go#L18)):*
> ```
> //ShardCount
> ```
add one blank between '//' and 'ShardCount'

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/346)*

**Comment by ypenghui6** [comment]
Review status: 0 of 98 files reviewed, 10 unresolved discussions (waiting on @lucusfly, @boqiu, and @WTer)

---

*[common/constant.go, line 28 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOkoeY6g6Byt5_8M7b:-LGOsjHL1CvbFkX-O5UZ:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/common/constant.go#L28)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not name to "CPUMetricsRefreshTime" to keep consistent with the previous variable name. BTW, I think "xxxMetricsRefreshInterval" is better.
</blockquote></details>

Done.

---

*[common/constant.go, line 18 at r3](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOrb9R0oAYeQ0NjBQq:-LGOsVkM0_vDa0RK0ga9:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/d78a0bacfc5437fc710c502880d3caa52b511efe/common/constant.go#L18)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> //ShardCount
> ```
add one blank between '//' and 'ShardCount'
</blockquote></details>

Done.

---

*[core/blockchain.go, line 220 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOmELn64J_8vVS1DYW:-LGP6LA14HEoyCfZz7-4:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/core/blockchain.go#L220)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

endWriteBlockTime. BTW, I think "start" and "end" is enough.
</blockquote></details>

Done.

---

*[core/blockchain.go, line 221 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOmTgv8CeQ6r3ghAbr:-LGOt5kxCxXc_koJ_GPE:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/core/blockchain.go#L221)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

you could use time.Since(startTime) to simplify the code
</blockquote></details>

Done.

---

*[metrics/metrics.go, line 18 at r3](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOnaZtAyD9oQzRqYbK:-LGP6D403lusemyNRymf:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/d78a0bacfc5437fc710c502880d3caa52b511efe/metrics/metrics.go#L18)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> write.block.time
> ```

here we can follow th pkg path, e.g. core.blockchain.writeBlock.time
</blockquote></details>

Done.

---

*[metrics/runtimecpu.go, line 13 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOo5WN6oETRz-CjdgK:-LGOrW6n2x2MPaPTUbH0:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/metrics/runtimecpu.go#L13)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

typo: account
</blockquote></details>

Done.

---

*[metrics/runtimecpu.go, line 14 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOo8I05Y2Qgs_5vm48:-LGOsLEyAPkJ50TJ8gJX:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/metrics/runtimecpu.go#L14)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

any difference between these 2 Gauge? suggest to add necessary comments.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/346)*

**Comment by lucusfly** [comment]
Reviewed 93 of 98 files at r1, 1 of 3 files at r3, 5 of 5 files at r4.
Review status: all files reviewed, 7 unresolved discussions (waiting on @boqiu and @WTer)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/346)*

**Comment by boqiu** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @WTer and @ypenghui6)

---

*[core/blockchain.go, line 222 at r2](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGOi_ju7FgeMeGjlIw4:-LGPBgSG0-5Iv3FIYlvc:b-o2myq6) ([raw file](https://github.com/seeleteam/go-seele/blob/367a6bbd3c072ddffe815889673cec9fdc5da2fa/core/blockchain.go#L222)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

markTime.Nanoseconds() is better
</blockquote></details>

Nanoseconds() return int64 value, so the type conversion is unnecessary.

---

*[metrics/runtimecpu.go, line 16 at r4](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGPCTou69WYVO2umJ9s:-LGPCTou69WYVO2umJ9t:b-shzeyf) ([raw file](https://github.com/seeleteam/go-seele/blob/e4163fdc6124b4cfde5dbb738752583a32d8df8e/metrics/runtimecpu.go#L16)):*
> ```Go
> 	metricsCpuGauge = metrics.GetOrRegisterGauge("cpu.account", nil)
> 	// metricsSeeleCpuGauge is the usage rate of the metrics current process
> 	metricsSeeleCpuGauge = metrics.GetOrRegisterGauge("cpu.seele.account", nil)
> ```

cpu.os and cpu.seele is better to describe the cpu usage of OS and seele node process.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/346)*

**Comment by ypenghui6** [comment]
Review status: 97 of 98 files reviewed, 2 unresolved discussions (waiting on @lucusfly, @WTer, and @boqiu)

---

*[metrics/runtimecpu.go, line 16 at r4](https://reviewable.io/reviews/seeleteam/go-seele/346#-LGPCTou69WYVO2umJ9s:-LGPCv43AYH5hzkuVxu-:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e4163fdc6124b4cfde5dbb738752583a32d8df8e/metrics/runtimecpu.go#L16)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

cpu.os and cpu.seele is better to describe the cpu usage of OS and seele node process.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/346)*

**Comment by boqiu** [comment]
Reviewed 93 of 98 files at r1, 3 of 5 files at r4, 2 of 2 files at r5.
Review status: all files reviewed, 1 unresolved discussion (waiting on @WTer)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/346)*

**Comment by WTer** [comment]
Reviewed 93 of 98 files at r1, 2 of 5 files at r4, 2 of 2 files at r5, 1 of 1 files at r6.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/346)*

**Pull request merged**
