### PR TITLE
add block fork support

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/107)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---

*[core/block_index.go, line 17 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9F2Sf-DSmNQM8TfzaN:-L9F2Sf-DSmNQM8TfzaO:b-2frqi3) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/block_index.go#L17)):*
> ```Go
> )
> 
> type BlockIndex struct {
> ```

add necessary comments for exported type.

---

*[core/block_index.go, line 59 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9F3fN2ETi9m7y9IM53:-L9F3fN2ETi9m7y9IM54:b6mjhmy) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/block_index.go#L59)):*
> ```Go
> 
> func (bf *BlockLeaf) GetBestStateDB() *state.Statedb {
> 	return bf.GetBestBlockIndex().state
> ```

state may be large and should not keep it in memory.

---

*[core/block_index.go, line 82 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9F4Ms_ENFUXS6UlztD:-L9F4Ms_ENFUXS6UlztE:b-a4l75o) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/block_index.go#L82)):*
> ```Go
> 		if maxTD.Cmp(index.totalDifficult) < 0 {
> 			maxTD = index.totalDifficult
> 			result = index
> ```

could cache the max td block in Add() method

---

*[core/blockchain.go, line 44 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9F8eVC42QU2VrLnl8G:-L9F8eVC42QU2VrLnl8H:bx0pcp0) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/blockchain.go#L44)):*
> ```Go
> 	genesisBlock   *types.Block
> 
> 	blockleaf *BlockLeaf
> ```

Now, use blockleaf to manage the HEAD block in fork-able chain, you could delete the usage of headerChain. But need to refactor in the case of light node. If possible, merge the fork logic into header chain.

---

*[core/blockchain.go, line 152 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9FBWBr4ZeMH0johqc9:-L9FBWBr4ZeMH0johqcA:b-efeb5t) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/blockchain.go#L152)):*
> ```Go
> 	}
> 
> 	bc.headerChain.WriteHeader(currentBlock.Header)
> ```

Cannot guarantee thread safe when update headers without lock. Composite atomic operations are not entirely atomic.

---

*[core/blockchain.go, line 154 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9F9MtN1pqTYdjEw8Aq:-L9F9MtN1pqTYdjEw8Ar:b-q53eu8) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/blockchain.go#L154)):*
> ```Go
> 	bc.headerChain.WriteHeader(currentBlock.Header)
> 	bc.blockleaf.RemoveByHash(block.Header.PreviousBlockHash)
> 	bc.blockleaf.Add(blockIndex)
> ```

if there're too many forks, maybe db + mem is better to store the different leaves.

---

*[core/headerchain.go, line 65 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9FAmDoDeiO_kH36HYF:-L9FAmDoDeiO_kH36HYG:bx0d2l1) ([raw file](https://github.com/seeleteam/go-seele/blob/dc644f0d6efa009130605c32a4894f3e53e12e32/core/headerchain.go#L65)):*
> ```Go
> }
> 
> func (hc *HeaderChain) validateNewHeader(newHeader *types.BlockHeader) (*big.Int, error) {
> ```

In light node case, will you dup the validation logic in current blockchain?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/107)*

**Comment by boqiu** [comment]
Review status: 0 of 12 files reviewed at latest revision, 7 unresolved discussions.

---

*[core/block_index.go, line 82 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9F4Ms_ENFUXS6UlztD:-L9FCnJX2bkM7JKUuqgO:bouh1rp) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/block_index.go#L82)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

could cache the max td block in Add() method
</blockquote></details>

or use max heap to record the max td block.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/107)*

**Comment by WTer** [comment]
Review status: 0 of 12 files reviewed at latest revision, 7 unresolved discussions.

---

*[core/block_index.go, line 82 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9F4Ms_ENFUXS6UlztD:-L9Y7_pNBU7ijBm2P808:by8pr1c) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/block_index.go#L82)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

or use max heap to record the max td block.
</blockquote></details>

I just suppose GetBestBlockIndex() would not be called frequently, so we can just optimize this function, no need to add extra logic to Add() that is a frequent operation.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/107)*

**Comment by WTer** [comment]
Review status: 0 of 12 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[core/block_index.go, line 42 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9YHEBe0CzPcVoOXIh_:-L9YHEBe0CzPcVoOXIha:b6pl7rr) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/block_index.go#L42)):*
> ```
> Remove
> ```
do we need to add return value to indicate if remove is successful (sometimes this index or hash 
doesn't exist)

---

*[core/block_index.go, line 93 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9Y9Edb0QY1nLcuvRPe:-L9Y9Edb0QY1nLcuvRPf:b-v430ym) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/block_index.go#L93)):*
> ```
> <=
> ```
seems '<'  is enough?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/107)*

**Comment by lucusfly** [comment]
Review status: 0 of 12 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[core/block_index.go, line 42 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9YHEBe0CzPcVoOXIh_:-L9YdHaj8x8klWGc0Skg:bubajky) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/block_index.go#L42)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> Remove
> ```
do we need to add return value to indicate if remove is successful (sometimes this index or hash 
doesn't exist)
</blockquote></details>

It will always succeed. if the key doesn't exist, it will do nothing.

---

*[core/block_index.go, line 93 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9Y9Edb0QY1nLcuvRPe:-L9Yd2Q29US63i0NfF7v:b-5maicq) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/block_index.go#L93)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> <=
> ```
seems '<'  is enough?
</blockquote></details>

no, the best block's td must bigger than all of the exist one.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/107)*

**Comment by WTer** [comment]
Review status: 0 of 12 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[core/block_index_test.go, line 24 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9YcVCX636UIOUJASZY:-L9YcVCX636UIOUJASZZ:b3gucxh) ([raw file](https://github.com/seeleteam/go-seele/blob/1af4b37512865fcafe965a6c9c03ad79daaae26c/core/block_index_test.go#L24)):*
> ```
> CRUD
> ```
you don't implement R function.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/107)*

**Comment by WTer** [comment]
Reviewed 11 of 12 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/107)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[core/block_index.go, line 59 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9F3fN2ETi9m7y9IM53:-L9Ykk4A-W2HEb1ygMi8:b-16dpmk) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/block_index.go#L59)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

Yes. I was planning to add a thread to remove very old block index and commit state with the longest chain. And I'd like to do it in another change.
</blockquote></details>

It's ok to do it later, but do not rely on a separate thread. Instead, you may design a capacity bound collection here.

---

*[core/block_index.go, line 93 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9Y9Edb0QY1nLcuvRPe:-L9Ynziq06Nhl3NSk7qG:b12n9nw) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/block_index.go#L93)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

no, the best block's td must bigger than all of the exist one.
</blockquote></details>

What if 2 blocks with the same TD?

According to the implementation of findBestBlockHash(), the best index is the FIRST block that has maximum TD.

---

*[core/block_index.go, line 35 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9Yh_IsBoS-nPImO3ZZ:-L9Yh_IsBoS-nPImO3Z_:b-kkfazx) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/block_index.go#L35)):*
> ```Go
> // BlockLeaf block leafs used for block fork
> type BlockLeaf struct {
> 	blockIndexMap cmap.ConcurrentMap //block hash -> blockIndex
> ```

Suggest to use GO built-in sync map. Anyway, if the bench mark of this concurrent map proves higher perf or provides better APIs as you desired, please go ahead.

---

*[core/block_index.go, line 48 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9Yj5yeCUNNvonQEJA0:-L9Yj5yeCUNNvonQEJA1:b2pfqjz) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/block_index.go#L48)):*
> ```Go
> 
> func (bf *BlockLeaf) Remove(old *BlockIndex) {
> 	bf.updateBestIndexWhenRemove(old)
> ```

I see lock protection when updating best index. So, I suppose you implemented thread-safe APIs. If so, 2 atomic operations cannot guarantee entirely atomic.

---

*[core/block_index.go, line 49 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9YnPfv01ZlVzhfosvh:-L9YnPfv01ZlVzhfosvi:bb70m07) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/block_index.go#L49)):*
> ```Go
> func (bf *BlockLeaf) Remove(old *BlockIndex) {
> 	bf.updateBestIndexWhenRemove(old)
> 	bf.blockIndexMap.Remove(old.currentBlock.HeaderHash.String())
> ```

I think the right logic is to remove item from map and then update best index. Please double confirm.

---

*[core/block_index.go, line 94 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9Yn1MN7RovWT8095ta:-L9Yn1MN7RovWT8095tb:bi613bh) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/block_index.go#L94)):*
> ```Go
> 	bf.lock.Lock()
> 	if bf.bestIndex != nil && bf.bestIndex.currentBlock.HeaderHash == index.currentBlock.HeaderHash {
> 		bf.bestIndex = bf.findBestBlockHash()
> ```

updateBestIndexWhenRemove comes before remove blockIndex from concurrent map. So, here findBestBlockHash() should always return current best index, right?

---

*[core/blockchain.go, line 44 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9F8eVC42QU2VrLnl8G:-L9Yon2714NFY3rTfjEm:b-w87oee) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/blockchain.go#L44)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

we don't need to consider for light node now. Will refactor it when we implement light node
</blockquote></details>

If so, you could remove the header chain in this full-node oriented blockchain.

---

*[core/blockchain.go, line 95 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9YpO0XCrz_OipxwPJi:-L9YpO0XCrz_OipxwPJj:b5lc7yn) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/blockchain.go#L95)):*
> ```Go
> 	blockIndex := NewBlockIndex(currentState, currentBlock, td)
> 	bc.blockleaf = NewBlockLeaf()
> 	bc.blockleaf.Add(blockIndex)
> ```

Only 1 leaf at the beginning? We need to serialize the leaves when write blocks.

---

*[core/blockchain.go, line 117 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9Yq8LRAMMNbXA-GgcY:-L9Yq8LRAMMNbXA-GgcZ:b-z5r7k5) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/blockchain.go#L117)):*
> ```Go
> // WriteBlock writes the block to the blockchain store.
> func (bc *Blockchain) WriteBlock(block *types.Block) error {
> 	_, err := bc.bcStore.GetBlock(block.HeaderHash)
> ```

GetBlock is heavy, suggest to add new API "HasBlock(hash)" in BlockchainStore.

---

*[core/blockchain.go, line 154 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9YrA7b9_3-CadtkaDG:-L9YrA7b9_3-CadtkaDH:b3z48a2) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/blockchain.go#L154)):*
> ```Go
> 	bc.headerChain.WriteHeader(currentBlock.Header)
> 	bc.blockleaf.RemoveByHash(block.Header.PreviousBlockHash)
> 	bc.blockleaf.Add(blockIndex)
> ```

Please pay more attention about the thread-safe. The composite of multiple thread-safe API is NOT entirely thread-safe, such bug is very dangerous and hard to find/test.

---

*[core/blockchain.go, line 155 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9Ysm070Z2R55aCqYOU:-L9Ysm070Z2R55aCqYOV:bwtpgub) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/blockchain.go#L155)):*
> ```Go
> 	bc.blockleaf.RemoveByHash(block.Header.PreviousBlockHash)
> 	bc.blockleaf.Add(blockIndex)
> ```

persist the new leaves?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/107)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[core/block_index.go, line 59 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9F3fN2ETi9m7y9IM53:-L9ZDmSU4FJW1eSdC7do:bkfq4s3) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/block_index.go#L59)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

It's ok to do it later, but do not rely on a separate thread. Instead, you may design a capacity bound collection here.
</blockquote></details>

we couldn't add a capacity here, because we need every block index inserted succeed. As I said, a thread to clear old index will be a good solution.

---

*[core/block_index.go, line 93 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9Y9Edb0QY1nLcuvRPe:-L9ZAn9hBb67hTl9RsJu:b2nhswy) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/block_index.go#L93)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

What if 2 blocks with the same TD?

According to the implementation of findBestBlockHash(), the best index is the FIRST block that has maximum TD.
</blockquote></details>

Yes

---

*[core/block_index.go, line 35 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9Yh_IsBoS-nPImO3ZZ:-L9YxRXD6MybX4SY8QkS:b-fk4m1v) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/block_index.go#L35)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Suggest to use GO built-in sync map. Anyway, if the bench mark of this concurrent map proves higher perf or provides better APIs as you desired, please go ahead.
</blockquote></details>

Yes. it has better perf and more features.

---

*[core/block_index.go, line 48 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9Yj5yeCUNNvonQEJA0:-L9ZCWmCA1QfWwGrwC1H:blo81go) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/block_index.go#L48)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

I see lock protection when updating best index. So, I suppose you implemented thread-safe APIs. If so, 2 atomic operations cannot guarantee entirely atomic.
</blockquote></details>

we just need it to be thread safe. we don't need it be atomic.

---

*[core/block_index.go, line 49 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9YnPfv01ZlVzhfosvh:-L9ZCwGhBtFSxd802DkH:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/block_index.go#L49)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

I think the right logic is to remove item from map and then update best index. Please double confirm.
</blockquote></details>

Done.

---

*[core/block_index.go, line 94 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9Yn1MN7RovWT8095ta:-L9ZEXjM1yyu_0OcVbhw:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/block_index.go#L94)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

updateBestIndexWhenRemove comes before remove blockIndex from concurrent map. So, here findBestBlockHash() should always return current best index, right?
</blockquote></details>

Done.

---

*[core/block_index_test.go, line 24 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9YcVCX636UIOUJASZY:-L9ZBEAuAhEod_KYFGg1:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/1af4b37512865fcafe965a6c9c03ad79daaae26c/core/block_index_test.go#L24)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> CRUD
> ```
you don't implement R function.
</blockquote></details>

Done.

---

*[core/blockchain.go, line 44 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9F8eVC42QU2VrLnl8G:-L9ZBGES9oQa3_3nkhDJ:b-44vdh4) ([raw file](https://github.com/seeleteam/go-seele/blob/ca9cd931e6b9931ff67b99ee107bab198de648b5/core/blockchain.go#L44)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

If so, you could remove the header chain in this full-node oriented blockchain.
</blockquote></details>

I think we could just keep it:)

---

*[core/blockchain.go, line 95 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9YpO0XCrz_OipxwPJi:-L9ZBflX81zh_chu4pIH:b-9gazxx) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/blockchain.go#L95)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Only 1 leaf at the beginning? We need to serialize the leaves when write blocks.
</blockquote></details>

actually it is block leaves. rename it

---

*[core/blockchain.go, line 117 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9Yq8LRAMMNbXA-GgcY:-L9Yx9Fs6OfElqoWHLTh:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/blockchain.go#L117)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

GetBlock is heavy, suggest to add new API "HasBlock(hash)" in BlockchainStore.
</blockquote></details>

Done.

---

*[core/blockchain.go, line 154 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9YrA7b9_3-CadtkaDG:-L9ZGo6--InTnpU5iUXz:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/blockchain.go#L154)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Please pay more attention about the thread-safe. The composite of multiple thread-safe API is NOT entirely thread-safe, such bug is very dangerous and hard to find/test.
</blockquote></details>

Done.

---

*[core/blockchain.go, line 155 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9Ysm070Z2R55aCqYOU:-L9ZCM387bHuCT18dk92:bghr1n0) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/blockchain.go#L155)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

persist the new leaves?
</blockquote></details>

leaf don't need to persist

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/107)*

**Comment by boqiu** [comment]
Review status: 7 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[core/block_index.go, line 48 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9Yj5yeCUNNvonQEJA0:-L9ZQqzU-R_Dxuis_R8H:bqp1uae) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/block_index.go#L48)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

we just need it to be thread safe. we don't need it be atomic.
</blockquote></details>

Not sure about the usage in blockchain (not used yet), but here we can easily take a very simple case to figure out the problem:

Suppose the TD of current best index is 4, and t1 add a block A with TD 5, t2 delete the same block A in t1. When t1 added the block in map, and switch to t2. Then, t2 will delete block from map, and do not update the best index. At last, thread switch back to t1, and continue to execute updateBestIndexWhenAdd(). As a result, the new block is not added in map, but the best block is changed to block A with TD 5.

---

*[core/store/db_store.go, line 91 at r4](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9ZUX3_3rDhjJ7HxLx7:-L9ZUX3_3rDhjJ7HxLx8:b-3kx66w) ([raw file](https://github.com/seeleteam/go-seele/blob/4516cc3e2150a1bde54dbef35b5da5707877c9b7/core/store/db_store.go#L91)):*
> ```Go
> func (store *blockchainDatabase) HashBlock(hash common.Hash) bool {
> 	_, err := store.db.Get(hashToHeaderKey(hash.Bytes()))
> 	return err == nil
> ```

1) should check if err equals to NotFoundErr
2) return other kinds of errors

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/107)*

**Comment by lucusfly** [comment]
Review status: 7 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[core/block_index.go, line 48 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9Yj5yeCUNNvonQEJA0:-L9ZbtAF2kykUTGKMOdI:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/373cd94a37f33248d81e7c425ba93f98cb9ddd3e/core/block_index.go#L48)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Not sure about the usage in blockchain (not used yet), but here we can easily take a very simple case to figure out the problem:

Suppose the TD of current best index is 4, and t1 add a block A with TD 5, t2 delete the same block A in t1. When t1 added the block in map, and switch to t2. Then, t2 will delete block from map, and do not update the best index. At last, thread switch back to t1, and continue to execute updateBestIndexWhenAdd(). As a result, the new block is not added in map, but the best block is changed to block A with TD 5.
</blockquote></details>

Done.

---

*[core/store/db_store.go, line 91 at r4](https://beta.reviewable.io/reviews/seeleteam/go-seele/107#-L9ZUX3_3rDhjJ7HxLx7:-L9Zczki19CEiLXaH7hx:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/4516cc3e2150a1bde54dbef35b5da5707877c9b7/core/store/db_store.go#L91)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

1) should check if err equals to NotFoundErr
2) return other kinds of errors
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/107)*

**Comment by boqiu** [comment]
Reviewed 7 of 12 files at r1, 3 of 7 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/107)*

**Comment by WTer** [comment]
Reviewed 2 of 7 files at r4, 3 of 4 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/107)*

**Pull request merged**
