### PR TITLE
Add leveldb

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/37)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 70 files reviewed at latest revision, 1 unresolved discussion.

---

*[database/leveldb/leveldb.go, line 19 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/37#-L6Me6-hJDZVnGjZ6-iX:-L6Me6-hJDZVnGjZ6-iY:b-oe5roe) ([raw file](https://github.com/seeleteam/go-seele/blob/f6700db4939ecc185077bef237ebb1cf4e9ad4c1/database/leveldb/leveldb.go#L19)):*
> ```Go
> 	db, err := leveldb.OpenFile(path, nil)
> 	if err != nil {
> 		return nil, err
> ```

nil should be db, since db will be nil if leveldb.OpenFile failed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/37)*

**Comment by WTer** [comment]
Review status: 0 of 70 files reviewed at latest revision, 2 unresolved discussions.

---

*[database/leveldb/leveldb.go, line 19 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/37#-L6Me6-hJDZVnGjZ6-iX:-L6Mf7Skv69tM5QDVKMg:b-tatwal) ([raw file](https://github.com/seeleteam/go-seele/blob/f6700db4939ecc185077bef237ebb1cf4e9ad4c1/database/leveldb/leveldb.go#L19)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

nil should be db, since db will be nil if leveldb.OpenFile failed.
</blockquote></details>

Never mind.

---

*[database/leveldb/leveldb.go, line 30 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/37#-L6MfmLzQDKeVoD3m9Y3:-L6MfmLzQDKeVoD3m9Y4:b-tcaqre) ([raw file](https://github.com/seeleteam/go-seele/blob/f6700db4939ecc185077bef237ebb1cf4e9ad4c1/database/leveldb/leveldb.go#L30)):*
> ```Go
> 
> // Close don't forget close db when not use
> func (db *levelDB) Close()  {
> ```

So sad, no standard destructor or dispose support in Go lang level

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/37)*

**Comment by WTer** [comment]
Review status: 0 of 70 files reviewed at latest revision, 3 unresolved discussions.

---

*[database/leveldb/leveldb.go, line 16 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/37#-L6Mgfs4yp97gPbLv_oV:-L6Mgfs4yp97gPbLv_oW:b-1gfkko) ([raw file](https://github.com/seeleteam/go-seele/blob/f6700db4939ecc185077bef237ebb1cf4e9ad4c1/database/leveldb/leveldb.go#L16)):*
> ```Go
> }
> 
> func NewLeveDB(path string) (*levelDB, error)  {
> ```

typo: NewLeveDB -> NewLevelDB 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/37)*

**Comment by lucusfly** [comment]
Review status: 0 of 70 files reviewed at latest revision, 3 unresolved discussions.

---

*[database/leveldb/leveldb.go, line 16 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/37#-L6Mgfs4yp97gPbLv_oV:-L6MhMd8xJFsBFS_3n2G:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f6700db4939ecc185077bef237ebb1cf4e9ad4c1/database/leveldb/leveldb.go#L16)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

typo: NewLeveDB -> NewLevelDB 
</blockquote></details>

Done.

---

*[database/leveldb/leveldb.go, line 19 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/37#-L6Me6-hJDZVnGjZ6-iX:-L6MhRdiGw1ykdWYImij:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f6700db4939ecc185077bef237ebb1cf4e9ad4c1/database/leveldb/leveldb.go#L19)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

Never mind.
</blockquote></details>

Done.

---

*[database/leveldb/leveldb.go, line 30 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/37#-L6MfmLzQDKeVoD3m9Y3:-L6MhQaCfobpthXQAckg:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f6700db4939ecc185077bef237ebb1cf4e9ad4c1/database/leveldb/leveldb.go#L30)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

So sad, no standard destructor or dispose support in Go lang level
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/37)*

**Comment by WTer** [comment]
Reviewed 69 of 70 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/37)*

**Comment by WTer** [comment]
Good.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/37#-:-L6Mix5lbRM3ReMjxrIq:b-87j110)*

**Comment by WTer** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/37)*

**Comment by WTer** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/37)*

**Pull request merged**
