### PR TITLE
add json-rpc

### PR DESCRIPTION
**Pull request by herove**
json-rpc 1.0
json-test

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/52)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[rpc/json.go, line 70 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jkOWqCT4qL-U1tE_j:-L6jkOWqCT4qL-U1tE_k:bvr43x) ([raw file](https://github.com/seeleteam/go-seele/blob/a60ab8454f89b9b0ef0d6e7e1ceb28143d0011e2/rpc/json.go#L70)):*
> ```Go
> }
> 
> func (c *jsonCodec) ReadRequestHeader(r *rpc.Request) error {
> ```

comment missed.

---

*[rpc/json.go, line 90 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jkRt6_tCFVoZJn5Ks:-L6jkRt6_tCFVoZJn5Kt:bvr43x) ([raw file](https://github.com/seeleteam/go-seele/blob/a60ab8454f89b9b0ef0d6e7e1ceb28143d0011e2/rpc/json.go#L90)):*
> ```Go
> }
> 
> func (c *jsonCodec) ReadRequestBody(x interface{}) error {
> ```

comment missed.

---

*[rpc/json.go, line 92 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jkVtET9A_nVpTHtin:-L6jkVtET9A_nVpTHtio:bybotxc) ([raw file](https://github.com/seeleteam/go-seele/blob/a60ab8454f89b9b0ef0d6e7e1ceb28143d0011e2/rpc/json.go#L92)):*
> ```Go
> func (c *jsonCodec) ReadRequestBody(x interface{}) error {
> 	if x == nil {
> 		return nil
> ```

return error? e.g. errArgNil, and it's better to put it under common/errors.go

---

*[rpc/json.go, line 108 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jksopANuvpB19LvNj:-L6jksoqVh-lQkPV8TX6:bvr43x) ([raw file](https://github.com/seeleteam/go-seele/blob/a60ab8454f89b9b0ef0d6e7e1ceb28143d0011e2/rpc/json.go#L108)):*
> ```Go
> var null = json.RawMessage([]byte("null"))
> 
> func (c *jsonCodec) WriteResponse(r *rpc.Response, x interface{}) error {
> ```

comment missed.

---

*[rpc/json.go, line 109 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jlDIxxVwzft1RDqFL:-L6jlDIxxVwzft1RDqFM:blmrsdd) ([raw file](https://github.com/seeleteam/go-seele/blob/a60ab8454f89b9b0ef0d6e7e1ceb28143d0011e2/rpc/json.go#L109)):*
> ```Go
> 
> func (c *jsonCodec) WriteResponse(r *rpc.Response, x interface{}) error {
> 	c.mutex.Lock()
> ```

Read-write lock?

---

*[rpc/json.go, line 137 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jlcb-fbSJAuAnBvNZ:-L6jlcb-fbSJAuAnBvN_:bmz9vlf) ([raw file](https://github.com/seeleteam/go-seele/blob/a60ab8454f89b9b0ef0d6e7e1ceb28143d0011e2/rpc/json.go#L137)):*
> in a go statement.
with go-routine

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/52)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jsvn0KQjR97iuj_EX:-L6jsvn0KQjR97iuj_EY:bqsj6jh) (no related file):*
json.go, json_test.go is copied from golang source code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/52)*

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

*[rpc/json.go, line 2 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jtm1ubu_sDl_481r7:-L6jtm1ubu_sDl_481r8:b424508) ([raw file](https://github.com/seeleteam/go-seele/blob/86f399381ce17da64c24affbc16cf2a0f7dc5927/rpc/json.go#L2)):*
> // Use of this source code is governed by a BSD-style

no seele license statement, is this third party code? if yes, nice to put it into vendor folder and add some wrappers.

---

*[rpc/json_test.go, line 48 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6juZwW-m5jooYLyGBM:-L6juZwW-m5jooYLyGBN:b5gale6) ([raw file](https://github.com/seeleteam/go-seele/blob/86f399381ce17da64c24affbc16cf2a0f7dc5927/rpc/json_test.go#L48)):*
> return errors.New("divide by zero")

you can refer to https://medium.com/@sebdah/go-best-practices-error-handling-2d15e1f0c5ee

there is very graceful error handler for such case: ErrZeroDivision

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/52)*

**Comment by herove** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jsvn0KQjR97iuj_EX:-L6jyMbyc420feTO_smS:b-u96atw) (no related file):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

json.go, json_test.go is copied from golang source code?
</blockquote></details>

not copy.  Jsoncodec and related function is extended. it's more suitable for our use. 
Later, we will expand to json-rpc 2.0

---

*[rpc/json.go, line 70 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jkOWqCT4qL-U1tE_j:-L6jnrT1SCnLXtte9QXv:bol5dz) ([raw file](https://github.com/seeleteam/go-seele/blob/a60ab8454f89b9b0ef0d6e7e1ceb28143d0011e2/rpc/json.go#L70)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

comment missed.
</blockquote></details>

ReadRequestBody is the implementation of the net/rpc/ServerCodec interface. the comments can be found there. And according to the convention, comment is not necessary when we can know the code logic from the function name.

---

*[rpc/json.go, line 90 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jkRt6_tCFVoZJn5Ks:-L6joWaxURGz07dJaYye:b-39w83n) ([raw file](https://github.com/seeleteam/go-seele/blob/a60ab8454f89b9b0ef0d6e7e1ceb28143d0011e2/rpc/json.go#L90)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

comment missed.
</blockquote></details>

ReadRequestBody is the implementation of the net/rpc/ServerCodec interface. 

---

*[rpc/json.go, line 92 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jkVtET9A_nVpTHtin:-L6jveuJboXSDh8qQBN1:b-xa86wp) ([raw file](https://github.com/seeleteam/go-seele/blob/a60ab8454f89b9b0ef0d6e7e1ceb28143d0011e2/rpc/json.go#L92)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

return error? e.g. errArgNil, and it's better to put it under common/errors.go
</blockquote></details>

 not error. Comments 'ReadRequestBody may be called with a nil' in ServerCodec interface. 

---

*[rpc/json.go, line 108 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jksopANuvpB19LvNj:-L6joikYUGj3ieOHHIIj:b-6z9k71) ([raw file](https://github.com/seeleteam/go-seele/blob/a60ab8454f89b9b0ef0d6e7e1ceb28143d0011e2/rpc/json.go#L108)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

comment missed.
</blockquote></details>

ReadRequestBody is the implementation of the net/rpc/ServerCodec interface.

---

*[rpc/json.go, line 109 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jlDIxxVwzft1RDqFL:-L6juxgbRx5yoHWTmM_I:btitxsy) ([raw file](https://github.com/seeleteam/go-seele/blob/a60ab8454f89b9b0ef0d6e7e1ceb28143d0011e2/rpc/json.go#L109)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Read-write lock?
</blockquote></details>

only on read and one write. mutex is better than rwmutex.

---

*[rpc/json.go, line 137 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jlcb-fbSJAuAnBvNZ:-L6jwGeFCMdunH2HEwgz:b-77v7sm) ([raw file](https://github.com/seeleteam/go-seele/blob/a60ab8454f89b9b0ef0d6e7e1ceb28143d0011e2/rpc/json.go#L137)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

> in a go statement.
with go-routine
</blockquote></details>

nice. I'll fix it.

---

*[rpc/json.go, line 2 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jtm1ubu_sDl_481r7:-L6jzccJoZSY0Gja5s-5:b59h3dk) ([raw file](https://github.com/seeleteam/go-seele/blob/86f399381ce17da64c24affbc16cf2a0f7dc5927/rpc/json.go#L2)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> // Use of this source code is governed by a BSD-style

no seele license statement, is this third party code? if yes, nice to put it into vendor folder and add some wrappers.
</blockquote></details>

third code but not copy. some function and struct is modified. The statement is also a requirement of the MIT license. go-seele/crypto/secp256k1 is the same case.

---

*[rpc/json_test.go, line 48 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6juZwW-m5jooYLyGBM:-L6jxEk5TWkfvbl8Xh4a:b-mekyg1) ([raw file](https://github.com/seeleteam/go-seele/blob/86f399381ce17da64c24affbc16cf2a0f7dc5927/rpc/json_test.go#L48)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> return errors.New("divide by zero")

you can refer to https://medium.com/@sebdah/go-best-practices-error-handling-2d15e1f0c5ee

there is very graceful error handler for such case: ErrZeroDivision

</blockquote></details>

Good suggesion. we can reffer it in our source code. 
In test file, this function is only to verify function rpc.register is as expected. The simpler the better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/52)*

**Comment by herove** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

*[rpc/json.go, line 137 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jlcb-fbSJAuAnBvNZ:-L6k0lzPpDYFt4Kn93Rh:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a60ab8454f89b9b0ef0d6e7e1ceb28143d0011e2/rpc/json.go#L137)):*
<details><summary><i>Previously, herove (Leihao Zhou) wrote…</i></summary><blockquote>

nice. I'll fix it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/52)*

**Comment by qiaozhigang** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/52)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[rpc/json.go, line 109 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jlDIxxVwzft1RDqFL:-L6kBChndx_nWafr1sON:b9ezlv5) ([raw file](https://github.com/seeleteam/go-seele/blob/a60ab8454f89b9b0ef0d6e7e1ceb28143d0011e2/rpc/json.go#L109)):*
<details><summary><i>Previously, herove (Leihao Zhou) wrote…</i></summary><blockquote>

only on read and one write. mutex is better than rwmutex.
</blockquote></details>

Do you mean only 1 thread for read and 1 thread for write? If so, mutex is ok. Otherwise, RW mutex is better for read perf.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/52)*

**Comment by herove** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[rpc/json.go, line 109 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/52#-L6jlDIxxVwzft1RDqFL:-L6kCeYpZgP20FN4uSzP:b9z3ab2) ([raw file](https://github.com/seeleteam/go-seele/blob/a60ab8454f89b9b0ef0d6e7e1ceb28143d0011e2/rpc/json.go#L109)):*
> Do you mean only 1 thread for read and 1 thread for write? 
Y

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/52)*

**Comment by boqiu** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/52)*

**Comment by WTer** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/52)*

**Pull request merged**
