### PR TITLE
fix download bugs and add more logs

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/227)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/227)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[seele/download/downloader.go, line 390 at r1](https://reviewable.io/reviews/seeleteam/go-seele/227#-LDtjdts6crmqUsFChL8:-LDtjdts6crmqUsFChL9:bmz1k50) ([raw file](https://github.com/seeleteam/go-seele/blob/a00f357e7c56a32140ba7e20de2a3bc18447f2d5/seele/download/downloader.go#L390)):*
> ```
> if len(headers) == 0
> ```

should be > 0, otherwise headers[len(headers)-1] will fail.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/227)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[seele/download/downloader.go, line 390 at r1](https://reviewable.io/reviews/seeleteam/go-seele/227#-LDtjdts6crmqUsFChL8:-LDtpvMc2xYkjB2LtEVC:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a00f357e7c56a32140ba7e20de2a3bc18447f2d5/seele/download/downloader.go#L390)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> if len(headers) == 0
> ```

should be > 0, otherwise headers[len(headers)-1] will fail.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/227)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/227)*

**Pull request merged**
