### PR TITLE
loging init module

### PR DESCRIPTION
**Pull request by yanllearnn**
log module change for all users

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/190)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[log/log.go, line 26 at r1](https://reviewable.io/reviews/seeleteam/go-seele/190#-LD0JSjz9ffLEN6LUFdc:-LD0JSjz9ffLEN6LUFdd:b8tegg6) ([raw file](https://github.com/seeleteam/go-seele/blob/ae9fc23b1652deef4cbdb8fc29c97a97c0dd3675/log/log.go#L26)):*
> ```Go
> type SeeleLog struct {
> 	log   *logrus.Logger
> 	level logrus.Level
> ```

reuse the logurs method to get/set level?

---

*[log/log.go, line 33 at r1](https://reviewable.io/reviews/seeleteam/go-seele/190#-LD0Iqo4Aglp6w7Ky3R2:-LD0Iqo4Aglp6w7Ky3R3:b-5sy8b3) ([raw file](https://github.com/seeleteam/go-seele/blob/ae9fc23b1652deef4cbdb8fc29c97a97c0dd3675/log/log.go#L33)):*
> ```
> Loging
> ```

Logging? In addition, if this is a common log instance for all modules, then the better name is Default.

---

*[log/log.go, line 35 at r1](https://reviewable.io/reviews/seeleteam/go-seele/190#-LD0JHpi9GEGpMm0pPvV:-LD0JHpi9GEGpMm0pPvW:brf00k3) ([raw file](https://github.com/seeleteam/go-seele/blob/ae9fc23b1652deef4cbdb8fc29c97a97c0dd3675/log/log.go#L35)):*
> ```Go
> var Loging *SeeleLog
> 
> func init() {
> ```

I think there should be existing method to init a log instance.

---

*[log/log_test.go, line 10 at r1](https://reviewable.io/reviews/seeleteam/go-seele/190#-LD0JZLYENrHCck2Whl4:-LD0JZLYENrHCck2Whl5:b22qhlh) ([raw file](https://github.com/seeleteam/go-seele/blob/ae9fc23b1652deef4cbdb8fc29c97a97c0dd3675/log/log_test.go#L10)):*
> ```Go
> import (
> 	"github.com/magiconair/properties/assert"
> 	"github.com/seeleteam/go-seele/common"
> ```

Suggest to use vscode to auto format the code, otherwise please use tool to format code before check-in

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/190)*

**Comment by WTer** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[log/log.go, line 32 at r1](https://reviewable.io/reviews/seeleteam/go-seele/190#-LD0KqtFAm5LJGacIFO0:-LD0KqtFAm5LJGacIFO1:b9x5ev0) ([raw file](https://github.com/seeleteam/go-seele/blob/ae9fc23b1652deef4cbdb8fc29c97a97c0dd3675/log/log.go#L32)):*
> ```
> //Loging
> ```
comments style: nice to add one blank between '//' and 'Loging'

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/190)*

**Comment by lucusfly** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/190)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[log/log.go, line 89 at r4](https://reviewable.io/reviews/seeleteam/go-seele/190#-LD1JjxA2iY_WQ717ZLt:-LD1JjxA2iY_WQ717ZLu:bh86tei) ([raw file](https://github.com/seeleteam/go-seele/blob/ccbb511bde75aab877d0f5361bff46f5852b27d1/log/log.go#L89)):*
> ```
> "log.log"
> ```

move file name to a const.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/190)*

**Comment by yanllearnn** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[log/log.go, line 26 at r1](https://reviewable.io/reviews/seeleteam/go-seele/190#-LD0JSjz9ffLEN6LUFdc:-LD5ad5f5LVD5YXuZEMc:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/ae9fc23b1652deef4cbdb8fc29c97a97c0dd3675/log/log.go#L26)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

reuse the logurs method to get/set level?
</blockquote></details>

Done.

---

*[log/log.go, line 32 at r1](https://reviewable.io/reviews/seeleteam/go-seele/190#-LD0KqtFAm5LJGacIFO0:-LD5ahkm-2uET_8V_Kl4:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/ae9fc23b1652deef4cbdb8fc29c97a97c0dd3675/log/log.go#L32)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> //Loging
> ```
comments style: nice to add one blank between '//' and 'Loging'
</blockquote></details>

Done.

---

*[log/log.go, line 33 at r1](https://reviewable.io/reviews/seeleteam/go-seele/190#-LD0Iqo4Aglp6w7Ky3R2:-LD5_vLf93shViIHyhHS:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/ae9fc23b1652deef4cbdb8fc29c97a97c0dd3675/log/log.go#L33)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> Loging
> ```

Logging? In addition, if this is a common log instance for all modules, then the better name is Default.
</blockquote></details>

Done.

---

*[log/log.go, line 35 at r1](https://reviewable.io/reviews/seeleteam/go-seele/190#-LD0JHpi9GEGpMm0pPvV:-LD5afe40xTQoCtijmLn:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/ae9fc23b1652deef4cbdb8fc29c97a97c0dd3675/log/log.go#L35)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

I think there should be existing method to init a log instance.
</blockquote></details>

Done.

---

*[log/log.go, line 89 at r4](https://reviewable.io/reviews/seeleteam/go-seele/190#-LD1JjxA2iY_WQ717ZLt:-LD5_zc8-RsWir8YERWQ:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/ccbb511bde75aab877d0f5361bff46f5852b27d1/log/log.go#L89)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> "log.log"
> ```

move file name to a const.
</blockquote></details>

Done.

---

*[log/log_test.go, line 10 at r1](https://reviewable.io/reviews/seeleteam/go-seele/190#-LD0JZLYENrHCck2Whl4:-LD5abmT5B7SSl_EH1jI:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/ae9fc23b1652deef4cbdb8fc29c97a97c0dd3675/log/log_test.go#L10)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Suggest to use vscode to auto format the code, otherwise please use tool to format code before check-in
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/190)*

**Comment by boqiu** [comment]
Reviewed 2 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/190)*

**Comment by lucusfly** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[log/log_test.go, line 31 at r6](https://reviewable.io/reviews/seeleteam/go-seele/190#-LD62yW-9WX8lJUFzEnM:-LD62yW0-dFRhoxbLXwN:blr17rk) ([raw file](https://github.com/seeleteam/go-seele/blob/201c11d25415f67a393ec270b38dc95727ac4134/log/log_test.go#L31)):*
> ```Go
> 	log.Debug("debug")
> 
> 	exist := common.FileOrFolderExists(filepath.Join(LogFolder, "test2.log"))
> ```

here we should test whether log.log exist.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/190)*

**Comment by yanllearnn** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[log/log_test.go, line 31 at r6](https://reviewable.io/reviews/seeleteam/go-seele/190#-LD62yW-9WX8lJUFzEnM:-LD63wI-4pCBNwpLXAnx:b2g7h9w) ([raw file](https://github.com/seeleteam/go-seele/blob/201c11d25415f67a393ec270b38dc95727ac4134/log/log_test.go#L31)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

here we should test whether log.log exist.
</blockquote></details>

ok,I will modify it soon

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/190)*

**Comment by WTer** [comment]
Reviewed 1 of 3 files at r4, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/190)*

**Comment by lucusfly** [comment]
Reviewed 1 of 2 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/190)*

**Pull request merged**
