### PR TITLE
Bug 1000488: support to recover inconsistent data in blockchain during init

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/307)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @boqiu, @WTer, and @lucusfly)

---

*[core/blockchain.go, line 119 at r1](https://reviewable.io/reviews/seeleteam/go-seele/307#-LFePdl7694gmP-I-nwa:-LFePdl81CXrFodu7O4B:b-8afe2p) ([raw file](https://github.com/seeleteam/go-seele/blob/7a7e30269f5cb6da55ef7ef546bb2c2be91f68b7/core/blockchain.go#L119)):*
> ```
> block chain
> ```
should be blockchain

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/307)*

**Comment by WTer** [comment]
Review status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @boqiu, @WTer, and @lucusfly)

---

*[core/blockchain_recover.go, line 49 at r1](https://reviewable.io/reviews/seeleteam/go-seele/307#-LFeRH595-IFkV8U68bh:-LFeRH595-IFkV8U68bi:bybngc1) ([raw file](https://github.com/seeleteam/go-seele/blob/7a7e30269f5cb6da55ef7ef546bb2c2be91f68b7/core/blockchain_recover.go#L49)):*
> ```Go
> 	if err = common.Deserialize(bytes, &rp); err != nil {
> 		rpLog.Warn("Failed to deserialize encoded bytes to recovery point info, %v", err.Error())
> 		rp.serialize()
> ```

why don't return err here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/307)*

**Comment by boqiu** [comment]
Review status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @WTer, @boqiu, and @lucusfly)

---

*[core/blockchain.go, line 119 at r1](https://reviewable.io/reviews/seeleteam/go-seele/307#-LFePdl7694gmP-I-nwa:-LFknMzd3EgYr4j9bNes:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/7a7e30269f5cb6da55ef7ef546bb2c2be91f68b7/core/blockchain.go#L119)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> block chain
> ```
should be blockchain
</blockquote></details>

Done.

---

*[core/blockchain_recover.go, line 49 at r1](https://reviewable.io/reviews/seeleteam/go-seele/307#-LFeRH595-IFkV8U68bh:-LFknhM6BCZdoaGjgTrL:b-y4alo0) ([raw file](https://github.com/seeleteam/go-seele/blob/7a7e30269f5cb6da55ef7ef546bb2c2be91f68b7/core/blockchain_recover.go#L49)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

why don't return err here?
</blockquote></details>

This is to avoid the recovery point info serialization corruption caused such error and block the blockchain initialization. Note, any unexpected error occurs in fault tolerant process, we should not block the prod business, just let it to behave as no data recovery mechanism.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/307)*

**Comment by WTer** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lucusfly)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/307)*

**Comment by lucusfly** [comment]
Review status: all files reviewed, 4 unresolved discussions (waiting on @boqiu)

---

*[core/blockchain.go, line 121 at r2](https://reviewable.io/reviews/seeleteam/go-seele/307#-LFoioRn8gvFSgJAO5Oq:-LFoioRn8gvFSgJAO5Or:bt1esrb) ([raw file](https://github.com/seeleteam/go-seele/blob/882c118265d713d577fd8af2f5a1a084d078aed2/core/blockchain.go#L121)):*
> ```Go
> // NewBlockchain returns an initialized blockchain with the given store and account state DB.
> func NewBlockchain(bcStore store.BlockchainStore, accountStateDB database.Database) (*Blockchain, error) {
> 	return NewBlockchainRecoverable(bcStore, accountStateDB, "")
> ```

I think we can't give a empty file name here.

---

*[core/blockchain_recover.go, line 37 at r2](https://reviewable.io/reviews/seeleteam/go-seele/307#-LFojs_X6ZIs_6iDWKcu:-LFojs_X6ZIs_6iDWKcv:b4ajzn5) ([raw file](https://github.com/seeleteam/go-seele/blob/882c118265d713d577fd8af2f5a1a084d078aed2/core/blockchain_recover.go#L37)):*
> ```
> len(file) == 0
> ```

if file is empty, save recovery info will crash, right?

---

*[core/blockchain_recover.go, line 121 at r2](https://reviewable.io/reviews/seeleteam/go-seele/307#-LFoj_T-093r604OmTLr:-LFoj_T-093r604OmTLs:b5nat5c) ([raw file](https://github.com/seeleteam/go-seele/blob/882c118265d713d577fd8af2f5a1a084d078aed2/core/blockchain_recover.go#L121)):*
> ```Go
> }
> 
> func (rp *recoveryPoint) serialize() {
> ```

suggest to use json marshal for ease read and debug.

---

*[core/blockchain_recover.go, line 175 at r2](https://reviewable.io/reviews/seeleteam/go-seele/307#-LFok6MX5AQkRpf7XJv_:-LFok6MX5AQkRpf7XJva:b8fqqzb) ([raw file](https://github.com/seeleteam/go-seele/blob/882c118265d713d577fd8af2f5a1a084d078aed2/core/blockchain_recover.go#L175)):*
> ```Go
> }
> 
> func (rp *recoveryPoint) onDeleteLargerHeightBlocks(height uint64) {
> ```

you need to consider thread safe. because write block is multi-thread.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/307)*

**Comment by boqiu** [comment]
Review status: 3 of 10 files reviewed, 4 unresolved discussions (waiting on @WTer, @boqiu, and @lucusfly)

---

*[core/blockchain.go, line 121 at r2](https://reviewable.io/reviews/seeleteam/go-seele/307#-LFoioRn8gvFSgJAO5Oq:-LFoqlbw3-G5gpXtTF94:bfp7dz6) ([raw file](https://github.com/seeleteam/go-seele/blob/882c118265d713d577fd8af2f5a1a084d078aed2/core/blockchain.go#L121)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

I think we can't give a empty file name here.
</blockquote></details>

UT will use empty string as recoveryPointFile to bypass recover().

---

*[core/blockchain_recover.go, line 37 at r2](https://reviewable.io/reviews/seeleteam/go-seele/307#-LFojs_X6ZIs_6iDWKcu:-LFowg3u5Y57T4OzjkZ4:b-wprq7u) ([raw file](https://github.com/seeleteam/go-seele/blob/882c118265d713d577fd8af2f5a1a084d078aed2/core/blockchain_recover.go#L37)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> len(file) == 0
> ```

if file is empty, save recovery info will crash, right?
</blockquote></details>

serialize() do nothing if file is empty, which is used by UT.

---

*[core/blockchain_recover.go, line 121 at r2](https://reviewable.io/reviews/seeleteam/go-seele/307#-LFoj_T-093r604OmTLr:-LFowpvg4uw9_SjwvQAc:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/882c118265d713d577fd8af2f5a1a084d078aed2/core/blockchain_recover.go#L121)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

suggest to use json marshal for ease read and debug.
</blockquote></details>

Done.

---

*[core/blockchain_recover.go, line 175 at r2](https://reviewable.io/reviews/seeleteam/go-seele/307#-LFok6MX5AQkRpf7XJv_:-LFowqun8BVTBLkQ9CwP:b-bs5s86) ([raw file](https://github.com/seeleteam/go-seele/blob/882c118265d713d577fd8af2f5a1a084d078aed2/core/blockchain_recover.go#L175)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

you need to consider thread safe. because write block is multi-thread.
</blockquote></details>

it's up to the caller to ensure the thread-safe. When write a block, the lock is held.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/307)*

**Comment by lucusfly** [comment]
Reviewed 3 of 8 files at r1, 7 of 7 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/307)*

**Pull request merged**
