### PR TITLE
fix an issue in seeleprotocol

### PR DESCRIPTION
**Pull request by sufay**
in seeleprotocol.handleMsg, we should handle the situation in which the requested tx has been removed from tx pool.

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/216)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/216)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[seele/seeleprotocol.go, line 362 at r1](https://reviewable.io/reviews/seeleteam/go-seele/216#-LD_FujO9wHPdhyHTqA-:-LD_FujO9wHPdhyHTqA0:babkdr6) ([raw file](https://github.com/seeleteam/go-seele/blob/09fd854d8a09cf6eca44c4a39ea9a9885fd7e96b/seele/seeleprotocol.go#L362)):*
> ```
> "requested transaction not found"
> ```
nice to add txHash in log:
"requested transaction %s not found", txHash.ToHex()

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/216)*

**Comment by sufay** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[seele/seeleprotocol.go, line 362 at r1](https://reviewable.io/reviews/seeleteam/go-seele/216#-LD_FujO9wHPdhyHTqA-:-LD_JzNr1VMAg0VPUuvj:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/09fd854d8a09cf6eca44c4a39ea9a9885fd7e96b/seele/seeleprotocol.go#L362)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> "requested transaction not found"
> ```
nice to add txHash in log:
"requested transaction %s not found", txHash.ToHex()
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/216)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/216)*

**Comment by lucusfly** [comment]
close it as I already fix this issue.

**Pull request closed without merging**
