### PR TITLE
Task contract simulator

### PR DESCRIPTION
**Pull request by wangff15386**
This is a contract simulator which can create a contract by the Remix-compiled binary codes and call the contract methods using the contract address and input paramaters. The test database directory default is "$HOME/seele/monitor" and the account that created the smart contract address is random. You can be specify them in the future. Finally, if possible, it can also compile the smart contracts.

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/225)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---

*[cmd/vm/main.go, line 6 at r1](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDoI9XOCdB8DPIfi_GN:-LDoI9XOCdB8DPIfi_GO:bxa32nx) ([raw file](https://github.com/seeleteam/go-seele/blob/53984fe97a8b2d8de7f2ee8134e5368ed5b42a20/cmd/vm/main.go#L6)):*
> ```Go
> 
> func main() {
> 	cmd.Execute()    
> ```

not auto formatted

---

*[cmd/vm/cmd/call.go, line 30 at r1](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDoIPrnCHhwNjFAHs0m:-LDoIPrnCHhwNjFAHs0n:bm6bjar) ([raw file](https://github.com/seeleteam/go-seele/blob/53984fe97a8b2d8de7f2ee8134e5368ed5b42a20/cmd/vm/cmd/call.go#L30)):*
> ```
>s eele-vm's
> ```

Seele contract simulator.

---

*[cmd/vm/cmd/call.go, line 38 at r1](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDoIdWN5Sh81HdYy5Nf:-LDoIdWN5Sh81HdYy5Ng:bh02j82) ([raw file](https://github.com/seeleteam/go-seele/blob/53984fe97a8b2d8de7f2ee8134e5368ed5b42a20/cmd/vm/cmd/call.go#L38)):*
> ```Go
> 	contract, err := common.HexToAddress(contractAddr)
> 	if err != nil {
> 		panic(err)
> ```

fmt.Println message, note, user friendly error message is required.

Please also use fmt.Println instead of panic for all codes under cmd pkg.

---

*[cmd/vm/cmd/call.go, line 51 at r1](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDoJ6Z8DsFxvlJ_rV3n:-LDoJ6Z8DsFxvlJ_rV3o:b-4tssj8) ([raw file](https://github.com/seeleteam/go-seele/blob/53984fe97a8b2d8de7f2ee8134e5368ed5b42a20/cmd/vm/cmd/call.go#L51)):*
> ```Go
> 
> 	// Create a call message trascation
> 	callContractTx, err := types.NewMessageTransaction(*crypto.MustGenerateRandomAddress(), contract, big.NewInt(0), big.NewInt(0), NONCE, msg)
> ```

user could be able to specify a from address in command line.

anyway, you could enhance in another pull request.

---

*[cmd/vm/cmd/call.go, line 53 at r1](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDoJSRf3Pqksqs8a04h:-LDoJSRf3Pqksqs8a04i:bpekd7y) ([raw file](https://github.com/seeleteam/go-seele/blob/53984fe97a8b2d8de7f2ee8134e5368ed5b42a20/cmd/vm/cmd/call.go#L53)):*
> ```Go
> 	callContractTx, err := types.NewMessageTransaction(*crypto.MustGenerateRandomAddress(), contract, big.NewInt(0), big.NewInt(0), NONCE, msg)
> 
> 	receipt := processContract(statedb, bcStore, callContractTx)
> ```

Since we do not use panic in command line, so here need error handling.

---

*[cmd/vm/cmd/call.go, line 56 at r1](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDoJXuyCrktdImfKS_y:-LDoJXuyCrktdImfKS_z:b-qdx1vj) ([raw file](https://github.com/seeleteam/go-seele/blob/53984fe97a8b2d8de7f2ee8134e5368ed5b42a20/cmd/vm/cmd/call.go#L56)):*
> ```Go
> 
> 	// Print the result
> 	fmt.Println("Contract call success, The result: ", string(receipt.Result))
> ```

may need decode for the receipt.Result

---

*[cmd/vm/cmd/create.go, line 23 at r1](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDoJh5T5vT9tu-dC8MG:-LDoJh5T5vT9tu-dC8MH:bbe1dy) ([raw file](https://github.com/seeleteam/go-seele/blob/53984fe97a8b2d8de7f2ee8134e5368ed5b42a20/cmd/vm/cmd/create.go#L23)):*
> ```Go
> 	NONCE uint64 = 38
> 	// STATEDBHASH statedb hash
> 	STATEDBHASH = "WFF"
> ```

1) please use a meaningful name for the key and the value.
2) define to const.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/225)*

**Comment by WTer** [comment]
Review status: 0 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[cmd/vm/cmd/call.go, line 50 at r2](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDoeeXoDho1974FQ6Fv:-LDoeeXoDho1974FQ6Fw:bcxnj0t) ([raw file](https://github.com/seeleteam/go-seele/blob/1acbcd4e12bc604247fc6367b503dcfab8657bc8/cmd/vm/cmd/call.go#L50)):*
> ```
>  trascation
> ```
typo: transaction

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/225)*

**Comment by boqiu** [comment]
Review status: 0 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[cmd/vm/cmd/create.go, line 28 at r2](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDodXD45yery_42hgcx:-LDodXD45yery_42hgcy:b-uoitmz) ([raw file](https://github.com/seeleteam/go-seele/blob/1acbcd4e12bc604247fc6367b503dcfab8657bc8/cmd/vm/cmd/create.go#L28)):*
> ```Go
> func init() {
> 	createCmd.Flags().StringVarP(&code, "create", "c", "", "create a contract")
> 	createCmd.Flags().StringVarP(&dir, "directory", "d", "$HOME/seele/monitor/", "test directory(default is $HOME/seele/monitor)")
> ```

no $HOME on windows.

---

*[cmd/vm/cmd/create.go, line 36 at r2](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDodohj9x77j2poXAZt:-LDodohj9x77j2poXAZu:boh0iyh) ([raw file](https://github.com/seeleteam/go-seele/blob/1acbcd4e12bc604247fc6367b503dcfab8657bc8/cmd/vm/cmd/create.go#L36)):*
> ```Go
> 	Use:   "create",
> 	Short: "create a contract",
> 	Long:  `All software has creates. This is seele-vm's`,
> ```

something missed?

---

*[cmd/vm/cmd/create.go, line 51 at r2](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDoe3glD4OVRFAnyjT8:-LDoe3glD4OVRFAnyjT9:bxdfcgu) ([raw file](https://github.com/seeleteam/go-seele/blob/1acbcd4e12bc604247fc6367b503dcfab8657bc8/cmd/vm/cmd/create.go#L51)):*
> ```Go
> 	// Get a directory to save the contract
> 	if dir != "$HOME/seele/monitor/" {
> 		panic(errors.New("Now the directory flag is unused"))
> ```

print error message instead panic.

---

*[cmd/vm/cmd/create.go, line 65 at r2](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDoeC1fBJxM_RygkEhR:-LDoeC1fBJxM_RygkEhS:bxdfcgu) ([raw file](https://github.com/seeleteam/go-seele/blob/1acbcd4e12bc604247fc6367b503dcfab8657bc8/cmd/vm/cmd/create.go#L65)):*
> ```Go
> 		statedb.SetNonce(from, NONCE)
> 	} else {
> 		panic(errors.New("Now the account flag is unused"))
> ```

print error message instead panic.

---

*[cmd/vm/cmd/root.go, line 24 at r2](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDoeNnkAj1W5fXtMLs2:-LDoeNnkAj1W5fXtMLs3:b-swausj) ([raw file](https://github.com/seeleteam/go-seele/blob/1acbcd4e12bc604247fc6367b503dcfab8657bc8/cmd/vm/cmd/root.go#L24)):*
> ```Go
> 	// Uncomment the following line if your bare application
> 	// has an action associated with it:
> 	//	Run: func(cmd *cobra.Command, args []string) { },
> ```

could remove these unused codes.

---

*[cmd/vm/cmd/util.go, line 23 at r2](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDoeaUnAXkdYzJMsmx2:-LDoeaUnAXkdYzJMsmx3:bz696rq) ([raw file](https://github.com/seeleteam/go-seele/blob/1acbcd4e12bc604247fc6367b503dcfab8657bc8/cmd/vm/cmd/util.go#L23)):*
> ```Go
> 	if err != nil {
> 		os.RemoveAll(dir)
> 		panic(err)
> ```

don't panic in command line

---

*[cmd/vm/cmd/util.go, line 27 at r2](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDoejjiBqByTK_mUzzE:-LDoejjiBqByTK_mUzzF:br1xn42) ([raw file](https://github.com/seeleteam/go-seele/blob/1acbcd4e12bc604247fc6367b503dcfab8657bc8/cmd/vm/cmd/util.go#L27)):*
> ```Go
> 
> 	hash := common.EmptyHash
> 	str, err := db.GetString(STATEDBHASH)
> ```

error handling

---

*[cmd/vm/cmd/util.go, line 29 at r2](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDoelWBBwY4fVHaheqf:-LDoelWBBwY4fVHaheqg:bxdfcgu) ([raw file](https://github.com/seeleteam/go-seele/blob/1acbcd4e12bc604247fc6367b503dcfab8657bc8/cmd/vm/cmd/util.go#L29)):*
> ```Go
> 	str, err := db.GetString(STATEDBHASH)
> 	if err == nil {
> 		if h, err := common.HexToHash(str); err == nil {
> ```

print error message instead panic.

---

*[cmd/vm/cmd/util.go, line 64 at r2](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDof4-RBQX8ExBG8MwC:-LDof4-RBQX8ExBG8MwD:box80a0) ([raw file](https://github.com/seeleteam/go-seele/blob/1acbcd4e12bc604247fc6367b503dcfab8657bc8/cmd/vm/cmd/util.go#L64)):*
> ```Go
> 	receipt, err := core.ProcessContract(evmContext, tx, 0, statedb, &vm.Config{})
> 	if err != nil {
> 		panic(err)
> ```

don't panic in command line.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/225)*

**Comment by WTer** [comment]
Review status: 0 of 8 files reviewed at latest revision, 16 unresolved discussions.

---

*[cmd/vm/cmd/create.go, line 28 at r2](https://reviewable.io/reviews/seeleteam/go-seele/225#-LDodXD45yery_42hgcx:-LDozyht1QsmE5CBnU75:bkome5b) ([raw file](https://github.com/seeleteam/go-seele/blob/1acbcd4e12bc604247fc6367b503dcfab8657bc8/cmd/vm/cmd/create.go#L28)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

no $HOME on windows.
</blockquote></details>

common/constant.go: defaultDataFolder or tempFolder

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/225)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/225)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/225)*

**Pull request merged**
