### PR TITLE
dynamic reward for mining

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/152)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[miner/task.go, line 59 at r1](https://reviewable.io/reviews/seeleteam/go-seele/152#-LByfxgr9Nb8DRgqlu4k:-LByfxgr9Nb8DRgqlu4l:b-ktebvs) ([raw file](https://github.com/seeleteam/go-seele/blob/393e4525219e6309913c057f7cee2d82a2d1b7aa/miner/task.go#L59)):*
> ```
> reward 
> ```
format should be "reward:"

---

*[miner/pow/reward.go, line 16 at r1](https://reviewable.io/reviews/seeleteam/go-seele/152#-LByh2bd6j67ldL1BIxH:-LByh2bd6j67ldL1BIxI:bibpinr) ([raw file](https://github.com/seeleteam/go-seele/blob/393e4525219e6309913c057f7cee2d82a2d1b7aa/miner/pow/reward.go#L16)):*
> ```
> blockNumberGeneratePerYear uint64 = 525000
> ```
just for discussion, as the consensus algorithm improvements or changes, the total generated block number also be changed, so can we set the total reward of one year as constant instead of block numbers?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/152)*

**Comment by lucusfly** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[miner/pow/reward.go, line 16 at r1](https://reviewable.io/reviews/seeleteam/go-seele/152#-LByh2bd6j67ldL1BIxH:-LByw-hi-J2RrqITyyZo:bjjc4yn) ([raw file](https://github.com/seeleteam/go-seele/blob/393e4525219e6309913c057f7cee2d82a2d1b7aa/miner/pow/reward.go#L16)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> blockNumberGeneratePerYear uint64 = 525000
> ```
just for discussion, as the consensus algorithm improvements or changes, the total generated block number also be changed, so can we set the total reward of one year as constant instead of block numbers?

</blockquote></details>

It is difficult to know when the block chain is started because genesis block don't have time info. So we use block height to define reward. After algorithm improving, we will have a more complicate table about block height mapping to reward to do it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/152)*

**Comment by lucusfly** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[miner/task.go, line 59 at r1](https://reviewable.io/reviews/seeleteam/go-seele/152#-LByfxgr9Nb8DRgqlu4k:-LByx9936UlC8RWR_Iwa:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/393e4525219e6309913c057f7cee2d82a2d1b7aa/miner/task.go#L59)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> reward 
> ```
format should be "reward:"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/152)*

**Comment by WTer** [comment]
Reviewed 5 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/152)*

**Comment by sufay** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[miner/miner.go, line 137 at r2](https://reviewable.io/reviews/seeleteam/go-seele/152#-LBz8ry5-M7k14VnjhWW:-LBz8ry5-M7k14VnjhWX:b-4inwv4) ([raw file](https://github.com/seeleteam/go-seele/blob/a99ea55f81024b5c58be8b8e94a0b4f98a45db56/miner/miner.go#L137)):*
> ```Go
> 			}
> 
> 			miner.log.Info("save block succeed and notify p2p")
> ```

saving?

---

*[miner/pow/reward.go, line 16 at r2](https://reviewable.io/reviews/seeleteam/go-seele/152#-LBzELNn0W3mdOMbOnGn:-LBzELNn0W3mdOMbOnGo:b-lfu3bn) ([raw file](https://github.com/seeleteam/go-seele/blob/a99ea55f81024b5c58be8b8e94a0b4f98a45db56/miner/pow/reward.go#L16)):*
> ```Go
> 
> 	// blockNumberGeneratePerYear block number generated per year.
> 	blockNumberGeneratePerYear uint64 = 525000
> ```

blockNumberGeneratedPerYear?

in addition, I think, anyway we should use a height-reward map, because block number generated per year is a bit varable even if consensus algorithm is fixed. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/152)*

**Comment by lucusfly** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[miner/miner.go, line 137 at r2](https://reviewable.io/reviews/seeleteam/go-seele/152#-LBz8ry5-M7k14VnjhWW:-LC1_AHQ25mDIFzfmJ0R:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a99ea55f81024b5c58be8b8e94a0b4f98a45db56/miner/miner.go#L137)):*
<details><summary><i>Previously, sufay wrote…</i></summary><blockquote>

saving?
</blockquote></details>

Done.

---

*[miner/pow/reward.go, line 16 at r2](https://reviewable.io/reviews/seeleteam/go-seele/152#-LBzELNn0W3mdOMbOnGn:-LC1Ye3G9eVMfsY7hrBi:b-kdosq7) ([raw file](https://github.com/seeleteam/go-seele/blob/a99ea55f81024b5c58be8b8e94a0b4f98a45db56/miner/pow/reward.go#L16)):*
<details><summary><i>Previously, sufay wrote…</i></summary><blockquote>

blockNumberGeneratedPerYear?

in addition, I think, anyway we should use a height-reward map, because block number generated per year is a bit varable even if consensus algorithm is fixed. 
</blockquote></details>

Yes, you are right. I am plan to refine it to map when we update consensus algorithm. And blockNumberGeneratedPerYear actually is block number for era. it is not exact equal to block number generated per year. I will rename it to blockNumberPerEra.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/152)*

**Pull request merged**
