### PR TITLE
support log rotate

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/329)

### CODE REVIEW

**Comment by boqiu** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @lucusfly, @WTer, @qiaozhigang, and @yanllearnn)

---

*[log/log.go, line 96 at r1](https://reviewable.io/reviews/seeleteam/go-seele/329#-LFyygYJ9BeSnp0gFCqD:-LFyygYJ9BeSnp0gFCqE:b1tgrnk) ([raw file](https://github.com/seeleteam/go-seele/blob/001456f6ae2aff2c0c29584c2c25143d694d4835/log/log.go#L96)):*
> ```Go
> 			rotatelogs.WithClock(rotatelogs.Local),
> 			rotatelogs.WithMaxAge(24*7*time.Second),
> 			rotatelogs.WithRotationTime(24*time.Second),
> ```

time.day

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/329)*

**Comment by lucusfly** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @lucusfly, @WTer, @qiaozhigang, and @yanllearnn)

---

*[log/log.go, line 96 at r1](https://reviewable.io/reviews/seeleteam/go-seele/329#-LFyygYJ9BeSnp0gFCqD:-LFz1_BM1cALnGQYA4sI:b-v3gwuk) ([raw file](https://github.com/seeleteam/go-seele/blob/001456f6ae2aff2c0c29584c2c25143d694d4835/log/log.go#L96)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

time.day
</blockquote></details>

There is no day in time.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/329)*

**Comment by WTer** [comment]
Reviewed 18 of 19 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @boqiu, @qiaozhigang, and @yanllearnn)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/329)*

**Comment by boqiu** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @qiaozhigang and @yanllearnn)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/329)*

**Pull request merged**
