### PR TITLE
add state independent check for txs of different shard

### PR DESCRIPTION
**Pull request by sufay**
when a tx with different shard number is sent to a node from client, a state independent check should be performed before sending it to corresponding peer sets for network performance

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/281)

### CODE REVIEW

**Comment by boqiu** [comment]
Reviewed 1 of 3 files at r4, 2 of 2 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/281)*

**Comment by boqiu** [comment]
@sufay it seems your PR still blocked by CI, suggest to close this RP and submit another one. BTW, don't forget to sync up with the latest code before any code change.

**Comment by sufay** [comment]
@boqiu another new PR also failed to get build status from CI.  I am communicating with Travis-CI support.

**Comment by boqiu** [comment]
@sufay since your PR was blocked by CI all the time, I will create a PR to fix the bug on behalf of you.

**Comment by sufay** [comment]
@boqiu OK.Thank you.

**Pull request closed without merging**
