### PR TITLE
deep test and more bugs fix. see description

### PR DESCRIPTION
**Pull request by lucusfly**
1. get current state db should create a new one
2. check tx status before add it to balance
3. suppress explosion log
4. fix miner not start issue
5. some log refine
6. get tps bug when height is 0

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/282)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @lucusfly, @WTer, @qiaozhigang, and @boqiu)

---

*[cmd/tool/cmd/sendtx.go, line 113 at r1](https://reviewable.io/reviews/seeleteam/go-seele/282#-LExaBLW3ev0QeHlRfgd:-LExaBLW3ev0QeHlRfge:b-1zww5p) ([raw file](https://github.com/seeleteam/go-seele/blob/eae3a3a7e46127cbefef4e8fb47b809535490d1f/cmd/tool/cmd/sendtx.go#L113)):*
> ```
> 			//fmt.Printf("got tx success %s from %s nonce %.0f status %s amount %.0f\n", b.tx.ToHex(), result["from"],
> 			//	result["accountNonce"], result["status"], result["amount"])
> ```
you comment them, so this code block (getTx) do nothing meaningful work?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/282)*

**Comment by lucusfly** [comment]
Review status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @lucusfly, @WTer, @qiaozhigang, and @boqiu)

---

*[cmd/tool/cmd/sendtx.go, line 113 at r1](https://reviewable.io/reviews/seeleteam/go-seele/282#-LExaBLW3ev0QeHlRfgd:-LExs77H5stMYsKSPsHS:b8t286k) ([raw file](https://github.com/seeleteam/go-seele/blob/eae3a3a7e46127cbefef4e8fb47b809535490d1f/cmd/tool/cmd/sendtx.go#L113)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> 			//fmt.Printf("got tx success %s from %s nonce %.0f status %s amount %.0f\n", b.tx.ToHex(), result["from"],
> 			//	result["accountNonce"], result["status"], result["amount"])
> ```
you comment them, so this code block (getTx) do nothing meaningful work?
</blockquote></details>

This is for test. when track some issues, I need to print this log. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/282)*

**Comment by WTer** [comment]
Reviewed 15 of 15 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @qiaozhigang and @boqiu)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/282)*

**Comment by boqiu** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @lucusfly and @qiaozhigang)

---

*[cmd/tool/cmd/sendtx.go, line 45 at r1](https://reviewable.io/reviews/seeleteam/go-seele/282#-LExaqWT2_ZUv0mj_Yj8:-LExaqWT2_ZUv0mj_Yj9:b-4jr7le) ([raw file](https://github.com/seeleteam/go-seele/blob/eae3a3a7e46127cbefef4e8fb47b809535490d1f/cmd/tool/cmd/sendtx.go#L45)):*
> ```Go
> 		balanceList := initAccount()
> 
> 		var confirmTime = 3 * time.Minute
> ```

use cmd arg to set the confirm time?

---

*[common/constant.go, line 19 at r1](https://reviewable.io/reviews/seeleteam/go-seele/282#-LExbkpV8GLI6lcBU1QH:-LExbkpV8GLI6lcBU1QI:btym5a) ([raw file](https://github.com/seeleteam/go-seele/blob/eae3a3a7e46127cbefef4e8fb47b809535490d1f/common/constant.go#L19)):*
> ```Go
> 
> // PrintExplosionLog whether print explosion log flag. Most of them are transaction track logs
> const PrintExplosionLog = false
> ```

PrintTrackLog?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/282)*

**Comment by boqiu** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @lucusfly and @qiaozhigang)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/282)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/tool/cmd/sendtx.go, line 45 at r1](https://reviewable.io/reviews/seeleteam/go-seele/282#-LExaqWT2_ZUv0mj_Yj8:-LEyXfiR18wkrS0GwE2A:by6a9h4) ([raw file](https://github.com/seeleteam/go-seele/blob/eae3a3a7e46127cbefef4e8fb47b809535490d1f/cmd/tool/cmd/sendtx.go#L45)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

use cmd arg to set the confirm time?
</blockquote></details>

confirm time should be a constant value our blockchain.

---

*[common/constant.go, line 19 at r1](https://reviewable.io/reviews/seeleteam/go-seele/282#-LExbkpV8GLI6lcBU1QH:-LEyXp-i11baFXgsSgI8:bz08p4c) ([raw file](https://github.com/seeleteam/go-seele/blob/eae3a3a7e46127cbefef4e8fb47b809535490d1f/common/constant.go#L19)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

PrintTrackLog?
</blockquote></details>

this is a switch for explosion log (the code that generate many debug logs)

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/282)*

**Pull request merged**
