### PR TITLE
add some metric points

### PR DESCRIPTION
**Pull request by ypenghui6**
add disk metric point
add cpu metric point
add net metric point

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/330)

### CODE REVIEW

**Comment by boqiu** [comment]
Reviewed 110 of 110 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @ypenghui6, @WTer, @qiaozhigang, and @lucusfly)

---

*[cmd/node/config/node1.json, line 34 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFyz-1Y5W_mWNrzFXhQ:-LFyz-1Y5W_mWNrzFXhR:b-wzv2lc) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/cmd/node/config/node1.json#L34)):*
> ```JSON
>   "metrics": {
>     "address": "127.0.0.1:8086",
>     "duration": 1,
> ```

any reason to change duration from 10 to 1? suppose it will increase the workload of node process.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/330)*

**Comment by lucusfly** [comment]
Review status: all files reviewed, 7 unresolved discussions (waiting on @ypenghui6, @WTer, and @qiaozhigang)

---

*[metrics/runtimecpu.go, line 19 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz2I4yCDDlF34zxK7t:-LFz2I4yCDDlF34zxK7u:b-ounpfo) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/metrics/runtimecpu.go#L19)):*
> ```
> *new(int64)
> ```

why not use 0?

---

*[metrics/runtimecpu.go, line 21 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz2SKtAwwcLz5m3yo3:-LFz2SKtAwwcLz5m3yo4:b-kw1xn) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/metrics/runtimecpu.go#L21)):*
> ```
> resul
> ```

result

---

*[metrics/runtimecpu.go, line 22 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz2ZSg4KVW95Ms2Rvc:-LFz2ZSg4KVW95Ms2Rvd:bjrkjry) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/metrics/runtimecpu.go#L22)):*
> ```
> i := 1
> ```

why not i := 0?

---

*[metrics/runtimecpu.go, line 25 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz2jwl3bk_4Qqpp-4E:-LFz2jwl3bk_4Qqpp-4F:bnvd8lf) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/metrics/runtimecpu.go#L25)):*
> ```Go
> 		resul = resul + out[i-1]
> 	}
> 	fmt.Printf("cup data: %v\n", resul)
> ```

remove fmt print

---

*[metrics/runtimemetrics.go, line 15 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz1zhj7OqIKRhASYnS:-LFz1zhj7OqIKRhASYnT:b7f9cuh) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/metrics/runtimemetrics.go#L15)):*
> ```
> refresh
> ```

rename to refreshTime

---

*[p2p/conn.go, line 133 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz3DpX5h8oA1SZqOQo:-LFz3DpX5h8oA1SZqOQp:b2muugu) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/p2p/conn.go#L133)):*
> ```
> headBuffLegth + headBuffLegth
> ```
size?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/330)*

**Comment by WTer** [comment]
Review status: all files reviewed, 8 unresolved discussions (waiting on @ypenghui6 and @qiaozhigang)

---

*[metrics/runtime_test.go, line 14 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz54vRECbew8qRqcfw:-LFz54vRECbew8qRqcfx:b-57tipo) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/metrics/runtime_test.go#L14)):*
> ```
> Test_getDiskRate
> ```
no NetRate?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/330)*

**Comment by ypenghui6** [comment]
Review status: 104 of 109 files reviewed, 8 unresolved discussions (waiting on @boqiu, @lucusfly, @ypenghui6, and @qiaozhigang)

---

*[metrics/runtime_test.go, line 14 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz54vRECbew8qRqcfw:-LFz5oHy9zcy7o5SiqVx:b-j1cuz) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/metrics/runtime_test.go#L14)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> Test_getDiskRate
> ```
no NetRate?
</blockquote></details>

in p2p metics

---

*[metrics/runtimecpu.go, line 19 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz2I4yCDDlF34zxK7t:-LFz4e3t-vdfjrsOcXqy:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/metrics/runtimecpu.go#L19)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> *new(int64)
> ```

why not use 0?
</blockquote></details>

Done.

---

*[metrics/runtimecpu.go, line 21 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz2SKtAwwcLz5m3yo3:-LFz5x9CCOOKH1FggBH3:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/metrics/runtimecpu.go#L21)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> resul
> ```

result
</blockquote></details>

Done.

---

*[metrics/runtimecpu.go, line 22 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz2ZSg4KVW95Ms2Rvc:-LFz5HFp84_BOQK_nBmY:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/metrics/runtimecpu.go#L22)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> i := 1
> ```

why not i := 0?
</blockquote></details>

Done.

---

*[metrics/runtimecpu.go, line 25 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz2jwl3bk_4Qqpp-4E:-LFz5G_c41tgoxr-QdDh:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/metrics/runtimecpu.go#L25)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

remove fmt print
</blockquote></details>

Done.

---

*[metrics/runtimemetrics.go, line 15 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz1zhj7OqIKRhASYnS:-LFz5T-B0uVFWHa0MWHx:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/metrics/runtimemetrics.go#L15)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> refresh
> ```

rename to refreshTime
</blockquote></details>

Done.

---

*[p2p/conn.go, line 133 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz3DpX5h8oA1SZqOQo:-LFz6xZ_5mnWrwqa7ZWa:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/p2p/conn.go#L133)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> headBuffLegth + headBuffLegth
> ```
size?
</blockquote></details>

Done.

---

*[cmd/node/config/node1.json, line 34 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFyz-1Y5W_mWNrzFXhQ:-LFz4_bU8Z9zpUPtTbRC:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/cmd/node/config/node1.json#L34)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

any reason to change duration from 10 to 1? suppose it will increase the workload of node process.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/330)*

**Comment by WTer** [comment]
Review status: 104 of 109 files reviewed, 9 unresolved discussions (waiting on @boqiu, @lucusfly, @WTer, @ypenghui6, and @qiaozhigang)

---

*[metrics/runtimedisk.go, line 22 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz7syy0yg8Azaz_LtD:-LFz7syy0yg8Azaz_LtE:b-7yx3ii) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/metrics/runtimedisk.go#L22)):*
> ```
> resul :=  disk.IOCountersStat{}
> ```
nice to add one blank line before it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/330)*

**Comment by WTer** [comment]
Review status: 104 of 109 files reviewed, 10 unresolved discussions (waiting on @boqiu, @lucusfly, @WTer, @ypenghui6, and @qiaozhigang)

---

*[metrics/runtimemetrics.go, line 48 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz8Si0-oeRc4gTfnCf:-LFz8Si0-oeRc4gTfnCg:ba9nx86) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/metrics/runtimemetrics.go#L48)):*
> ```
> time.Sleep(refresh)
> ```
this sample interval should be configurable in config file.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/330)*

**Comment by WTer** [comment]
Review status: 104 of 109 files reviewed, 11 unresolved discussions (waiting on @boqiu, @lucusfly, @WTer, @ypenghui6, and @qiaozhigang)

---

*[p2p/conn.go, line 108 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz8zO6CPHzdTYXebhh:-LFz8zO71RTTV4M6Dg5g:b-wuocz1) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/p2p/conn.go#L108)):*
> ```
> Legth
> ```
typo: Length

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/330)*

**Comment by ypenghui6** [comment]
Review status: 104 of 109 files reviewed, 11 unresolved discussions (waiting on @boqiu, @lucusfly, @WTer, and @qiaozhigang)

---

*[metrics/runtimedisk.go, line 22 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz7syy0yg8Azaz_LtD:-LFzAmZ-DixqR9nz9S9S:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/metrics/runtimedisk.go#L22)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> resul :=  disk.IOCountersStat{}
> ```
nice to add one blank line before it.
</blockquote></details>

Done.

---

*[metrics/runtimemetrics.go, line 48 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz8Si0-oeRc4gTfnCf:-LFzAnbdCUUN9maTMaXL:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/metrics/runtimemetrics.go#L48)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> time.Sleep(refresh)
> ```
this sample interval should be configurable in config file.
</blockquote></details>

Done.

---

*[p2p/conn.go, line 108 at r1](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFz8zO6CPHzdTYXebhh:-LFzC27b-JfxCGvxKa-a:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/4879610f337f939ead16e9292bb18c4a65c90778/p2p/conn.go#L108)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> Legth
> ```
typo: Length

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/330)*

**Comment by boqiu** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed, 10 unresolved discussions (waiting on @lucusfly, @WTer, and @qiaozhigang)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/330)*

**Comment by lucusfly** [comment]
Review status: all files reviewed, 5 unresolved discussions (waiting on @WTer, @ypenghui6, and @qiaozhigang)

---

*[metrics/runtimedisk.go, line 16 at r2](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFzFBFz3ZkE2hJpj7Ee:-LFzFBFz3ZkE2hJpj7Ef:b-lm3dap) ([raw file](https://github.com/seeleteam/go-seele/blob/3e9c21428194d534675f73be8db9e063c28e7314/metrics/runtimedisk.go#L16)):*
> ```Go
> 
> func getDiskRate(name string) (disk.IOCountersStat, error) {
> 	out, err := disk.IOCounters(name)
> ```

use disk.Usage()

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/330)*

**Comment by ypenghui6** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @lucusfly and @qiaozhigang)

---

*[metrics/runtimedisk.go, line 16 at r2](https://reviewable.io/reviews/seeleteam/go-seele/330#-LFzFBFz3ZkE2hJpj7Ee:-LFzHKz82Wdp6Rdc4SPw:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/3e9c21428194d534675f73be8db9e063c28e7314/metrics/runtimedisk.go#L16)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

use disk.Usage()
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/330)*

**Comment by qiaozhigang** [comment]
Reviewed 104 of 110 files at r1, 4 of 7 files at r2, 2 of 2 files at r3.
Review status: all files reviewed, 1 unresolved discussion (waiting on @lucusfly)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/330)*

**Comment by lucusfly** [comment]
Reviewed 104 of 110 files at r1, 4 of 7 files at r2, 2 of 2 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/330)*

**Comment by lucusfly** [comment]
Reviewed 2 of 2 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/330)*

**Comment by lucusfly** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/330)*

**Pull request merged**
