### PR TITLE
Task contract simulator adds account support

### PR DESCRIPTION
**Pull request by wangff15386**
1. Add three cmds that new/set/get to new a account/set the balance of the account/get the balance of the account
2. Create/Call the smart contracts support the specified account
3. Repair the error "Fatalf call has arguments but no formatting directives" in merkle\merkle_tree_test.go

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/238)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[cmd/vm/cmd/account.go, line 13 at r1](https://reviewable.io/reviews/seeleteam/go-seele/238#-LED33nN17EpL7aP1dW3:-LED33nN17EpL7aP1dW4:b-kvglv8) ([raw file](https://github.com/seeleteam/go-seele/blob/8c6397da2c3edfe67215db1f2a57841c4f29f768/cmd/vm/cmd/account.go#L13)):*
> ```Go
> 
> var (
> 	balance uint64
> ```

balance may be bigger than uint64. use string instead.

---

*[cmd/vm/cmd/account.go, line 49 at r1](https://reviewable.io/reviews/seeleteam/go-seele/238#-LED2PJhD9y7B351uAoZ:-LED2PJhD9y7B351uAo_:br6mct9) ([raw file](https://github.com/seeleteam/go-seele/blob/8c6397da2c3edfe67215db1f2a57841c4f29f768/cmd/vm/cmd/account.go#L49)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 		for {
> 			if !statedb.Exist(addr) {
> 				break
> 			}
> 			addr = *crypto.MustGenerateRandomAddress()
> 		}
> ```
</details>


This should not happen.

---

*[cmd/vm/cmd/account.go, line 107 at r1](https://reviewable.io/reviews/seeleteam/go-seele/238#-LED3Qzj3IoNL1nbrERL:-LED3Qzj3IoNL1nbrERM:bs7tvh4) ([raw file](https://github.com/seeleteam/go-seele/blob/8c6397da2c3edfe67215db1f2a57841c4f29f768/cmd/vm/cmd/account.go#L107)):*
> ```Go
> 		}
> 
> 		fmt.Println("The balance of the account is ", statedb.GetBalance(addr))
> ```

use common.BigToDecimal to change balance unit

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/238)*

**Comment by WTer** [comment]
> but 

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/vm/cmd/account.go, line 75 at r1](https://reviewable.io/reviews/seeleteam/go-seele/238#-LED4Lf75NcIXglYL3K7:-LED4Lf80VwQKT6eeOQl:b-19u4sj) ([raw file](https://github.com/seeleteam/go-seele/blob/8c6397da2c3edfe67215db1f2a57841c4f29f768/cmd/vm/cmd/account.go#L75)):*
> ```
> addr, err := common.HexToAddress(account)
> ```
need to check whether this addr is exist in db:
if statedb.Exist(addr) 

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/238#-:-LED1hfV3FOlwHmBqI8-:b-w65xwc)*

**Comment by WTer** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/vm/cmd/account.go, line 85 at r1](https://reviewable.io/reviews/seeleteam/go-seele/238#-LED4f4d0QfNNjHp_Vun:-LED4f4d0QfNNjHp_Vuo:bi40ols) ([raw file](https://github.com/seeleteam/go-seele/blob/8c6397da2c3edfe67215db1f2a57841c4f29f768/cmd/vm/cmd/account.go#L85)):*
> ```
> successful
> ```
successfully

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/238)*

**Comment by boqiu** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmd/vm/cmd/account.go, line 13 at r1](https://reviewable.io/reviews/seeleteam/go-seele/238#-LED33nN17EpL7aP1dW3:-LED8LMX2GuVpkmZ36YR:b-yciih9) ([raw file](https://github.com/seeleteam/go-seele/blob/8c6397da2c3edfe67215db1f2a57841c4f29f768/cmd/vm/cmd/account.go#L13)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

balance may be bigger than uint64. use string instead.
</blockquote></details>

Better to have, anyway, it's ok to use uint64 in simulator.

---

*[cmd/vm/cmd/account.go, line 81 at r1](https://reviewable.io/reviews/seeleteam/go-seele/238#-LED9JMoDK0ZQ2TeL_PD:-LED9JMoDK0ZQ2TeL_PE:b-nqygih) ([raw file](https://github.com/seeleteam/go-seele/blob/8c6397da2c3edfe67215db1f2a57841c4f29f768/cmd/vm/cmd/account.go#L81)):*
> ```Go
> 		}
> 
> 		if balance >= 0 {
> ```

balance of type uint64 will always be >= 0.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/238)*

**Comment by wangff15386** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[cmd/vm/cmd/account.go, line 13 at r1](https://reviewable.io/reviews/seeleteam/go-seele/238#-LED33nN17EpL7aP1dW3:-LEJYvmK5dybD2NLNgGn:b-9okz8b) ([raw file](https://github.com/seeleteam/go-seele/blob/8c6397da2c3edfe67215db1f2a57841c4f29f768/cmd/vm/cmd/account.go#L13)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Better to have, anyway, it's ok to use uint64 in simulator.
</blockquote></details>

Simulator does not need such a large balance, or I will solve it if necessary in the future.

---

*[cmd/vm/cmd/account.go, line 49 at r1](https://reviewable.io/reviews/seeleteam/go-seele/238#-LED2PJhD9y7B351uAoZ:-LEJZgkB2mFNalJN61py:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/8c6397da2c3edfe67215db1f2a57841c4f29f768/cmd/vm/cmd/account.go#L49)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> 		for {
> 			if !statedb.Exist(addr) {
> 				break
> 			}
> 			addr = *crypto.MustGenerateRandomAddress()
> 		}
> ```

This should not happen.
</blockquote></details>

Done.

---

*[cmd/vm/cmd/account.go, line 75 at r1](https://reviewable.io/reviews/seeleteam/go-seele/238#-LED4Lf75NcIXglYL3K7:-LEJZi-w5lqo82naSYyy:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/8c6397da2c3edfe67215db1f2a57841c4f29f768/cmd/vm/cmd/account.go#L75)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> addr, err := common.HexToAddress(account)
> ```
need to check whether this addr is exist in db:
if statedb.Exist(addr) 
</blockquote></details>

Done.

---

*[cmd/vm/cmd/account.go, line 81 at r1](https://reviewable.io/reviews/seeleteam/go-seele/238#-LED9JMoDK0ZQ2TeL_PD:-LEJZmpP3Rf6Sm__JPTQ:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/8c6397da2c3edfe67215db1f2a57841c4f29f768/cmd/vm/cmd/account.go#L81)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

balance of type uint64 will always be >= 0.
</blockquote></details>

Done.

---

*[cmd/vm/cmd/account.go, line 85 at r1](https://reviewable.io/reviews/seeleteam/go-seele/238#-LED4f4d0QfNNjHp_Vun:-LEJZnm08pfuGAXNJ8pE:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/8c6397da2c3edfe67215db1f2a57841c4f29f768/cmd/vm/cmd/account.go#L85)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> successful
> ```
successfully
</blockquote></details>

Done.

---

*[cmd/vm/cmd/account.go, line 107 at r1](https://reviewable.io/reviews/seeleteam/go-seele/238#-LED3Qzj3IoNL1nbrERL:-LEJZpHOCb9N9aBYOa6k:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/8c6397da2c3edfe67215db1f2a57841c4f29f768/cmd/vm/cmd/account.go#L107)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

use common.BigToDecimal to change balance unit
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/238)*

**Pull request merged**
