### PR TITLE
add state independent check for txs of different shard

### PR DESCRIPTION
**Pull request by sufay**
when a tx with different shard number is sent to a node from client, a state independent check should be performed before sending it to corresponding peer sets for network performance

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/262)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[seele/api_public.go, line 89 at r1](https://reviewable.io/reviews/seeleteam/go-seele/262#-LEg_cT9AbhpFREOPYq5:-LEg_cT9AbhpFREOPYq6:b-o15m87) ([raw file](https://github.com/seeleteam/go-seele/blob/aeee47b992ad26f10a63ed2972993b31c1a4ef7c/seele/api_public.go#L89)):*
> ```Go
> 	var err error
> 	if shard != common.LocalShardNumber {
> 	        if err = tx.ValidateWithoutState(); err == nil {
> ```

please pay attention to the indent.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/262)*

**Comment by boqiu** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/262)*

**Comment by sufay** [comment]
Review status: 1 of 2 files reviewed, all discussions resolved (waiting on @boqiu)

---

*[seele/api_public.go, line 89 at r1](https://reviewable.io/reviews/seeleteam/go-seele/262#-LEg_cT9AbhpFREOPYq5:-LEhQb3LErcALUWALEB6:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/aeee47b992ad26f10a63ed2972993b31c1a4ef7c/seele/api_public.go#L89)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

please pay attention to the indent.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/262)*

**Comment by boqiu** [comment]
Please have a double check about the merge, since another pull request had changed something in transaction.go

---

Reviewed 2 of 2 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/262#-:-LEhULJkE0cBhh4z8Krp:b1w1430)*

**Comment by sufay** [comment]
but validate method need be exported due to call in api_public.go

---

Review status: 0 of 2 files reviewed, all discussions resolved (waiting on @boqiu)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/262#-:-LEhl3riEGEOXpFPy-KU:btoauxj)*

**Comment by boqiu** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed, 2 unresolved discussions (waiting on @sufay)

---

*[core/types/transaction.go, line 223 at r4](https://reviewable.io/reviews/seeleteam/go-seele/262#-LEhouiq0-4Hca0_vF7W:-LEhouiq0-4Hca0_vF7X:bhrhzxi) ([raw file](https://github.com/seeleteam/go-seele/blob/93fdb6acd6118d9fb59c02ade0379d1f4b44e9e3/core/types/transaction.go#L223)):*
> ```Go
> 		}
> 	}
>   
> ```

please remove those 2 whitespaces. Note, we use vscode and go plugin will auto format the code style.

---

*[core/types/transaction.go, line 241 at r4](https://reviewable.io/reviews/seeleteam/go-seele/262#-LEhpDgkC1c0GP4S-UQs:-LEhpDgkC1c0GP4S-UQt:b-mje5sy) ([raw file](https://github.com/seeleteam/go-seele/blob/93fdb6acd6118d9fb59c02ade0379d1f4b44e9e3/core/types/transaction.go#L241)):*
> ```Go
> 		return ErrSigInvalid
> 	}
>   
> ```

redundant 2 whitespaces.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/262)*

**Comment by boqiu** [comment]
Review status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @boqiu and @sufay)

---

*[core/types/transaction.go, line 258 at r5](https://reviewable.io/reviews/seeleteam/go-seele/262#-LEi7M8A2C3gDXeA18O6:-LEi7M8A2C3gDXeA18O7:bqs4tfp) ([raw file](https://github.com/seeleteam/go-seele/blob/55ac6340a33ae16a9905cf8c75f2f4a158649eff/core/types/transaction.go#L258)):*
> ```Go
> 
> 	// vaildate signature
> 	if tx.Signature == nil {
> ```

dup code to valdiate signature, you could define method to validate signature.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/262)*

**Comment by sufay** [comment]
Review status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @boqiu and @sufay)

---

*[core/types/transaction.go, line 223 at r4](https://reviewable.io/reviews/seeleteam/go-seele/262#-LEhouiq0-4Hca0_vF7W:-LEiDf0cApyER16XrswN:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/93fdb6acd6118d9fb59c02ade0379d1f4b44e9e3/core/types/transaction.go#L223)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

please remove those 2 whitespaces. Note, we use vscode and go plugin will auto format the code style.
</blockquote></details>

Done.

---

*[core/types/transaction.go, line 241 at r4](https://reviewable.io/reviews/seeleteam/go-seele/262#-LEhpDgkC1c0GP4S-UQs:-LEiDm4V9QJpmI4daDAg:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/93fdb6acd6118d9fb59c02ade0379d1f4b44e9e3/core/types/transaction.go#L241)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

redundant 2 whitespaces.
</blockquote></details>

Done.

---

*[core/types/transaction.go, line 258 at r5](https://reviewable.io/reviews/seeleteam/go-seele/262#-LEi7M8A2C3gDXeA18O6:-LEiDo6q9VoNpGg6TGxW:b-earcth) ([raw file](https://github.com/seeleteam/go-seele/blob/55ac6340a33ae16a9905cf8c75f2f4a158649eff/core/types/transaction.go#L258)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

dup code to valdiate signature, you could define method to validate signature.
</blockquote></details>

I think code related to signature should be placed in validate method  because signature is a field independent to state. 
what do you think about the handling in r1 of the PR?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/262)*

**Comment by boqiu** [comment]
Review status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @boqiu)

---

*[core/types/transaction.go, line 258 at r5](https://reviewable.io/reviews/seeleteam/go-seele/262#-LEi7M8A2C3gDXeA18O6:-LEiG-re1drew7PIwEJX:b-ofzoio) ([raw file](https://github.com/seeleteam/go-seele/blob/55ac6340a33ae16a9905cf8c75f2f4a158649eff/core/types/transaction.go#L258)):*
<details><summary><i>Previously, sufay wrote…</i></summary><blockquote>

I think code related to signature should be placed in validate method  because signature is a field independent to state. 
what do you think about the handling in r1 of the PR?
</blockquote></details>

Agree with you. BTW, the newTx() need not to validate the signature, in which case we have to handle in validate() method.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/262)*

**Comment by boqiu** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed, 1 unresolved discussion (waiting on @sufay)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/262)*

**Comment by sufay** [comment]
Review status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @boqiu)

---

*[core/types/transaction.go, line 258 at r5](https://reviewable.io/reviews/seeleteam/go-seele/262#-LEi7M8A2C3gDXeA18O6:-LEjjwMw5s1aYxKOxM-F:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/55ac6340a33ae16a9905cf8c75f2f4a158649eff/core/types/transaction.go#L258)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Agree with you. BTW, the newTx() need not to validate the signature, in which case we have to handle in validate() method.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/262)*

**Comment by boqiu** [comment]
Reviewed 1 of 3 files at r7, 2 of 2 files at r8.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/262)*

**Comment by boqiu** [comment]
seems CI hung...

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/262#-:-LElY_9O9sP-1FU00CNh:b-y8j7eu)*

**Comment by sufay** [comment]
@boqiu in a fact, this PR is a reopened one, with a prior PR not checked by Travis-CI. I  will try to close this PR and rebuild an branch for a new PR.  What do you think about the CI problem?

**Comment by sufay** [comment]
@boqiu This PR has be created on a new branch, but it doesn't still work with CI.

**Comment by boqiu** [comment]
@sufay if the CI problem not resolved, you could close this PR and submit another one.

**Comment by sufay** [comment]
@boqiu I created a PR three days ago, but CI didn't report build status.  I reopen it, which failed.  
 Then I closed it, rebuilt a new branch and submitted a new PR. Unfortunately, the problem exists still.
 I submitted a new PR for another topic just now. But it is still stuck due to CI. 

I wonder whether this issue is due to CI or repo setting.

**Pull request closed without merging**
