### PR TITLE
Fee negative bug

### PR DESCRIPTION
**Pull request by gongliaoan**
1、when fee is negative，sendtx will expect.

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/203)

### CODE REVIEW

**Comment by boqiu** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/203)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[core/types/transaction.go, line 105 at r1](https://reviewable.io/reviews/seeleteam/go-seele/203#-LDF6TtV81BZF6d1dVP9:-LDF6TtV81BZF6d1dVPA:bv0e9c9) ([raw file](https://github.com/seeleteam/go-seele/blob/996e6b83611845ddfe41b9dfc1b48f559784759b/core/types/transaction.go#L105)):*
> ```
> fee.Cmp(big.NewInt(0)) < 0
> ```

fee.Sign() <= 0

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/203)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[core/types/transaction.go, line 105 at r1](https://reviewable.io/reviews/seeleteam/go-seele/203#-LDF6TtV81BZF6d1dVP9:-LDF6uc_BoYKJXFnOA_N:bw8xl6f) ([raw file](https://github.com/seeleteam/go-seele/blob/996e6b83611845ddfe41b9dfc1b48f559784759b/core/types/transaction.go#L105)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> fee.Cmp(big.NewInt(0)) < 0
> ```

fee.Sign() <= 0
</blockquote></details>

fee.Sign() < 0

---

*[core/types/transaction_test.go, line 248 at r1](https://reviewable.io/reviews/seeleteam/go-seele/203#-LDF6hYx8Xyj2x_hPO-C:-LDF6hYx8Xyj2x_hPO-D:b-c79qzx) ([raw file](https://github.com/seeleteam/go-seele/blob/996e6b83611845ddfe41b9dfc1b48f559784759b/core/types/transaction_test.go#L248)):*
> ```
> failed to create tx, fee is negative"
> ```
use a parameter

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/203)*

**Comment by gongliaoan** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[core/types/transaction.go, line 105 at r1](https://reviewable.io/reviews/seeleteam/go-seele/203#-LDF6TtV81BZF6d1dVP9:-LDGQLpqCnn6oQDHFLe6:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/996e6b83611845ddfe41b9dfc1b48f559784759b/core/types/transaction.go#L105)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

fee.Sign() < 0
</blockquote></details>

Done.

---

*[core/types/transaction_test.go, line 248 at r1](https://reviewable.io/reviews/seeleteam/go-seele/203#-LDF6hYx8Xyj2x_hPO-C:-LDGQMc75vE-3QLVA6H_:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/996e6b83611845ddfe41b9dfc1b48f559784759b/core/types/transaction_test.go#L248)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> failed to create tx, fee is negative"
> ```
use a parameter
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/203)*

**Comment by lucusfly** [comment]
Reviewed 6 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/203)*

**Pull request merged**
