### PR TITLE
add batch&database interface;add batch for leveldb implement

### PR DESCRIPTION
**Pull request by jessonzheng**
add batch&database interface;add batch for level db implement

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/55)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[database/leveldb/batch.go, line 14 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6nzH5gWyTyAFYoCM3f:-L6nzH5hezTEgMFNaQPt:b-63dxt5) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/leveldb/batch.go#L14)):*
> implenent

typo: implementation

---

*[database/leveldb/batch.go, line 31 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6nzWf1aeo94xcMeAKa:-L6nzWf1aeo94xcMeAKb:bt5lgu5) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/leveldb/batch.go#L31)):*
> b.batch.Delete(key)

the 2 blank lines around it can be removed, 
also for other functions in this file.

---

*[database/leveldb/batch_test.go, line 57 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6o-6CNQf6kY08NzOiD:-L6o-6COF0tJJi62uLI_:b3usord) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/leveldb/batch_test.go#L57)):*
> error

change to "Failed"

---

*[database/leveldb/batch_test.go, line 104 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6o-iclaGXZh_PIsPND:-L6o-iclaGXZh_PIsPNE:b-w25lhn) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/leveldb/batch_test.go#L104)):*
> value, err = db.GetString("1")

nice to add check for key "3"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/55)*

**Comment by lucusfly** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[database/leveldb/batch.go, line 17 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6o-_lDcYs6kcOxAUjI:-L6o-_lDcYs6kcOxAUjJ:b-m1f69x) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/leveldb/batch.go#L17)):*
> ```Go
> type Batch struct {
> 	db      database.Database
> 	leveldb *leveldb.DB
> ```

db and leveldb are duplicate info, we should only use one

---

*[database/leveldb/batch.go, line 23 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6nzXT8bzZwlFGmh2S9:-L6nzXT8bzZwlFGmh2SA:b-1thh0f) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/leveldb/batch.go#L23)):*
> ```Go
> // Put sets the value for the given key
> func (b *Batch) Put(key []byte, value []byte) {
> ```

remove unnecessary empty line, same as below

---

*[database/leveldb/leveldb.go, line 21 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6o-z7Fcy-zeK8vuKnT:-L6o-z7Fcy-zeK8vuKnU:btebba3) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/leveldb/leveldb.go#L21)):*
> ```Go
> 
> // NewLevelDB new database interface of level db
> func NewLevelDB(path string) (database.Database, error) {
> ```

in the leveldb folder, I think we should keep it as leveldb.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/55)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[database/database.go, line 22 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6o-sqyj_-GO7HQcS3K:-L6o-sqyj_-GO7HQcS3L:b-fpn1md) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/database.go#L22)):*
> ```Go
> }
> 
> // Batch iterface of batch for database
> ```

should be interface :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/55)*

**Comment by qiaozhigang** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/55)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[database/database.go, line 23 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6oEJ5j0xyLMZaLnkxN:-L6oEJ5j0xyLMZaLnkxO:b-fmjk6h) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/database.go#L23)):*
> ```Go
> 
> // Batch iterface of batch for database
> type Batch interface {
> ```

How about read in batch. Not sure if it is supported in levelDB, but Redis support batch read.

---

*[database/database.go, line 29 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6oCtBBeB606X8qIGaG:-L6oCtBCE0mniUeuit__:b-ys4i0x) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/database.go#L29)):*
> ```Go
> 	Rollback()
> 	Close()
> 	Database() Database
> ```

Database() and Close() is unnecessary.

---

*[database/leveldb/batch_test.go, line 57 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6o-6CNQf6kY08NzOiD:-L6oE09NWiHfQCHud46r:b-9x0uoq) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/leveldb/batch_test.go#L57)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> error

change to "Failed"
</blockquote></details>

In fact, Fatal is better, which means stop the execution immediately. Generally, the test method should return once error occurred.

---

*[database/leveldb/leveldb.go, line 21 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6o-z7Fcy-zeK8vuKnT:-L6oFrHIb7TnKI9NcaYa:b-xw6eil) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/leveldb/leveldb.go#L21)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

in the leveldb folder, I think we should keep it as leveldb.
</blockquote></details>

In fact, I prefer the original way that hide the concrete implementation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/55)*

**Comment by jessonzheng** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[database/database.go, line 22 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6o-sqyj_-GO7HQcS3K:-L6o91afXNUVc_NdWsE6:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/database.go#L22)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

should be interface :)
</blockquote></details>

Done.

---

*[database/database.go, line 29 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6oCtBBeB606X8qIGaG:-L6oJ2CNrsMWV3KvoVZl:bvtpxzg) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/database.go#L29)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Database() and Close() is unnecessary.
</blockquote></details>

delete them

---

*[database/leveldb/batch.go, line 14 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6nzH5gWyTyAFYoCM3f:-L6o9I-qcb3SDPK54-x3:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/leveldb/batch.go#L14)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> implenent

typo: implementation
</blockquote></details>

Done.

---

*[database/leveldb/batch.go, line 17 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6o-_lDcYs6kcOxAUjI:-L6oDGmMgz5EjeqOcXSg:b-spej7q) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/leveldb/batch.go#L17)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

db and leveldb are duplicate info, we should only use one
</blockquote></details>

OK.remove it

---

*[database/leveldb/batch.go, line 23 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6nzXT8bzZwlFGmh2S9:-L6o9_2pFz58Lh4bMw85:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/leveldb/batch.go#L23)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

remove unnecessary empty line, same as below
</blockquote></details>

Done.

---

*[database/leveldb/batch.go, line 31 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6nzWf1aeo94xcMeAKa:-L6o9buCASBRgEyb_t9t:bb7f2mf) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/leveldb/batch.go#L31)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> b.batch.Delete(key)

the 2 blank lines around it can be removed, 
also for other functions in this file.
</blockquote></details>

done

---

*[database/leveldb/batch_test.go, line 57 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6o-6CNQf6kY08NzOiD:-L6oAt2F5uC5wOFYbt70:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/leveldb/batch_test.go#L57)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> error

change to "Failed"
</blockquote></details>

Done.

---

*[database/leveldb/batch_test.go, line 104 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6o-iclaGXZh_PIsPND:-L6oF0qtDm2wS5nGKUbc:bb7f2mf) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/leveldb/batch_test.go#L104)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> value, err = db.GetString("1")

nice to add check for key "3"
</blockquote></details>

done

---

*[database/leveldb/leveldb.go, line 21 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6o-z7Fcy-zeK8vuKnT:-L6oA2CLaiK-BZ7YnUkf:b-jy18nw) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/leveldb/leveldb.go#L21)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

In fact, I prefer the original way that hide the concrete implementation.
</blockquote></details>

as we discussed, it should have included the interface because of "NewBatch() database.Batch" interface

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/55)*

**Comment by jessonzheng** [comment]
Review status: 1 of 5 files reviewed at latest revision, 10 unresolved discussions.

---

*[database/database.go, line 23 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6oEJ5j0xyLMZaLnkxN:-L6oKpjEWbdyNitKm-ME:b5iheb1) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/database.go#L23)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

How about read in batch. Not sure if it is supported in levelDB, but Redis support batch read.
</blockquote></details>

add them later,just use db now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/55)*

**Comment by jessonzheng** [comment]
Review status: 1 of 5 files reviewed at latest revision, 10 unresolved discussions.

---

*[database/leveldb/batch_test.go, line 57 at r3](https://reviewable.io:443/reviews/seeleteam/go-seele/55#-L6o-6CNQf6kY08NzOiD:-L6oLY9zPbKktNOpeHET:b-8ayu6x) ([raw file](https://github.com/seeleteam/go-seele/blob/a43b6ff54516925c70ea6f6bd99d4d3837645a4a/database/leveldb/batch_test.go#L57)):*
<details><summary><i>Previously, jessonzheng wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Agree

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/55)*

**Comment by lucusfly** [comment]
Reviewed 1 of 5 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/55)*

**Comment by qiaozhigang** [comment]
Reviewed 4 of 4 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/55)*

**Pull request merged**
