### PR TITLE
Task blockchain receipts

### PR DESCRIPTION
**Pull request by boqiu**
Support tx receipts in blockchain

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/165)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---

*[core/types/receipt.go, line 33 at r1](https://reviewable.io/reviews/seeleteam/go-seele/165#-LCWfywM8XbrfgoC06Ke:-LCWfywM8XbrfgoC06Kf:b-z372rj) ([raw file](https://github.com/seeleteam/go-seele/blob/d40f10d3614ef5102f57708a67f7cdef00bc7808/core/types/receipt.go#L33)):*
> ```
> Equals
> ```
nice to add unit tests for it and and another new added func ReceiptMerkleRootHash.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/165)*

**Comment by boqiu** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[core/types/receipt.go, line 33 at r1](https://reviewable.io/reviews/seeleteam/go-seele/165#-LCWfywM8XbrfgoC06Ke:-LCXJS-p3f4-ZSHAczgb:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/d40f10d3614ef5102f57708a67f7cdef00bc7808/core/types/receipt.go#L33)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> Equals
> ```
nice to add unit tests for it and and another new added func ReceiptMerkleRootHash.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/165)*

**Comment by WTer** [comment]
Reviewed 8 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/165)*

**Comment by lucusfly** [comment]
Reviewed 8 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/165)*

**Pull request merged**
