### PR TITLE
normalize code in some files

### PR DESCRIPTION
**Pull request by sufay**
normalize the code in some files:
    modify command line specification,  such as replacing [command] with [\<command\>].
    change err to err.Error() to achieve maintainability, with the possibility that we will use a custom print function which accepts an argument of string type later.
    change IsFileOrFolderExist to DoesFileOrFolderExist so as to comply with syntax.

remove the variable not used.
add and modify some comments.

@lucusfly @reedhong @chenhuaying @WTer @herove

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/133)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 24 files reviewed at latest revision, all discussions resolved.

---

*[cmd/client/cmd/getbalance.go, line 30 at r1](https://reviewable.io/reviews/seeleteam/go-seele/133#-LBABxW-7jO48-9yhU2M:-LBABxW-7jO48-9yhU2N:b-oqf7d5) ([raw file](https://github.com/seeleteam/go-seele/blob/11b7a160fbfe013b86234930a02be151e8c8ac36/cmd/client/cmd/getbalance.go#L30)):*
> ```Go
> 		client, err := jsonrpc.Dial("tcp", rpcAddr)
> 		if err != nil {
> 			fmt.Println(err.Error())
> ```

It's OK to change to err.Error(). Anyway, if a custom function is required to print error, then change the current err to err.Error() at the same time.

---

*[common/file.go, line 13 at r1](https://reviewable.io/reviews/seeleteam/go-seele/133#-LBAENrO7a0Tg4ZtKXBz:-LBAENrO7a0Tg4ZtKXC-:b-tv79g7) ([raw file](https://github.com/seeleteam/go-seele/blob/11b7a160fbfe013b86234930a02be151e8c8ac36/common/file.go#L13)):*
> ```Go
> 
> // DoesFileOrFolderExist checks if a file or folder exists
> func DoesFileOrFolderExist(fileOrFolder string) bool {
> ```

Nothing serious, 'Is' is better to indicate the bool return value.

As for the syntax, I suggest 'fileOrFolderExists'

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/133)*

**Comment by boqiu** [comment]
You're highly appreciated to correct the comments, thanks.

---

Review status: 0 of 24 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/133#-:-LBAG_hs9XdjuF2tVbwd:b-vo3wdk)*

**Comment by herove** [comment]
Reviewed 21 of 24 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/133)*

**Comment by lucusfly** [comment]
Reviewed 21 of 24 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/133)*

**Comment by boqiu** [comment]
Reviewed 21 of 24 files at r1, 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/133)*

**Comment by lucusfly** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/133)*

**Pull request merged**
