### PR TITLE
 add rpc to get pending txs

### PR DESCRIPTION
**Pull request by webbergao1**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/241)

### CODE REVIEW

**Comment by webbergao1** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[seele/api_txpool.go, line 136 at r1](https://reviewable.io/reviews/seeleteam/go-seele/241#-LEI7BDy8SLp6yVerxK9:-LEIhSed0SbiMreWykQQ:b-qssebl) ([raw file](https://github.com/seeleteam/go-seele/blob/c171ff7ab82027b77b29b2172c7a9ed4a2fdb084/seele/api_txpool.go#L136)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> transactions := make([]map[string]interface{}, txCount)
> ```
what happened if count of txs in pandingTxs is not equal to txCount?
</blockquote></details>

fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/241)*

**Comment by webbergao1** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[seele/api_txpool.go, line 131 at r2](https://reviewable.io/reviews/seeleteam/go-seele/241#-LEJeqOH5VgQxmW9m4OT:-LEKNV8I9OIBk50w6htU:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/1b10b9d8bf09fdcfc3834088ca678dc5ed833721/seele/api_txpool.go#L131)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

do you want to filter tx at PROCESSING status?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/241)*

**Comment by lucusfly** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[seele/api_txpool.go, line 133 at r3](https://reviewable.io/reviews/seeleteam/go-seele/241#-LEKSQ210ouMqD5esCdW:-LEKSQ210ouMqD5esCdX:bk3lwos) ([raw file](https://github.com/seeleteam/go-seele/blob/7b6b7a802b23377258cc0c01a1339d5c2a2520ad/seele/api_txpool.go#L133)):*
> ```
> pandingTxs
> ```

pending

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/241)*

**Comment by boqiu** [comment]
Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---

*[monitor/api.go, line 44 at r5](https://reviewable.io/reviews/seeleteam/go-seele/241#-LEMyVYj2GhNlIfZmXo2:-LEMyVYj2GhNlIfZmXo3:bufkhge) ([raw file](https://github.com/seeleteam/go-seele/blob/cc021684ee2c0d6929d5f8998c5b9792f819c0d0/monitor/api.go#L44)):*
> ```Go
> 		Client:     api.s.version,
> 		History:    true,
> 		Shard:      api.s.shard,
> ```

why remove the shard info? Won't use it anymore?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/241)*

**Comment by webbergao1** [comment]
commit again later

**Pull request closed without merging**
