### PR TITLE
support to specify payload when send tx via cmd

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/254)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[cmd/client/cmd/sendtx.go, line 48 at r1](https://reviewable.io/reviews/seeleteam/go-seele/254#-LEOTJb3A7Omxmz_pcj3:-LEOTJb3A7Omxmz_pcj4:bimogar) ([raw file](https://github.com/seeleteam/go-seele/blob/beb609e0ebebca2305d343cffb1f05468df05a70/cmd/client/cmd/sendtx.go#L48)):*
> ```
> if len(*parameter.to) > 0
> ```
so when to is nil, the toAddr will be also be nil, 

will be the following call fail?
util.Sendtx(client, key.PrivateKey, &toAddr, amount, fee, nonce, payload)

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/254)*

**Comment by WTer** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/client/cmd/sendtx.go, line 48 at r1](https://reviewable.io/reviews/seeleteam/go-seele/254#-LEOTJb3A7Omxmz_pcj3:-LEOUMqS8oexzjBUuCiW:b84t2i5) ([raw file](https://github.com/seeleteam/go-seele/blob/beb609e0ebebca2305d343cffb1f05468df05a70/cmd/client/cmd/sendtx.go#L48)):*
> ```
> tx, err = types.NewContractTransaction(*fromAddr, amount, fee, nonce, payload)
> ```

got it, I saw that, never mind.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/254)*

**Comment by WTer** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[cmd/util/utils.go, line 36 at r1](https://reviewable.io/reviews/seeleteam/go-seele/254#-LEOUqqL8y9G6i25DddN:-LEOUqqL8y9G6i25DddO:b-5msqc0) ([raw file](https://github.com/seeleteam/go-seele/blob/beb609e0ebebca2305d343cffb1f05468df05a70/cmd/util/utils.go#L36)):*
> ```
> type
> ```
nice to add ':' 
"type:"

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/254)*

**Comment by WTer** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[core/types/transaction.go, line 215 at r1](https://reviewable.io/reviews/seeleteam/go-seele/254#-LEOVeXG9cwgoVJxnvZU:-LEOVeXG9cwgoVJxnvZV:bwxr56a) ([raw file](https://github.com/seeleteam/go-seele/blob/beb609e0ebebca2305d343cffb1f05468df05a70/core/types/transaction.go#L215)):*
> ```
> if (tx.Data.To == nil || tx.Data.To.Type() == common.AddressTypeContract) && len(tx.Data.Payload) == 0
> ```

if (to == nil || to.Type() == common.AddressTypeContract) && len(payload) == 0

seems can create a private func for these logic with 2 parameters:
(to, payload)

it's nice to have. just a little friendly for unittest

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/254)*

**Comment by boqiu** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/util/utils.go, line 36 at r1](https://reviewable.io/reviews/seeleteam/go-seele/254#-LEOUqqL8y9G6i25DddN:-LEOczdI0gqBfel1MPsg:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/beb609e0ebebca2305d343cffb1f05468df05a70/cmd/util/utils.go#L36)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> type
> ```
nice to add ':' 
"type:"
</blockquote></details>

Done.

---

*[core/types/transaction.go, line 215 at r1](https://reviewable.io/reviews/seeleteam/go-seele/254#-LEOVeXG9cwgoVJxnvZU:-LEOd3GcDp_8SaJEpUPY:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/beb609e0ebebca2305d343cffb1f05468df05a70/core/types/transaction.go#L215)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> if (tx.Data.To == nil || tx.Data.To.Type() == common.AddressTypeContract) && len(tx.Data.Payload) == 0
> ```

if (to == nil || to.Type() == common.AddressTypeContract) && len(payload) == 0

seems can create a private func for these logic with 2 parameters:
(to, payload)

it's nice to have. just a little friendly for unittest
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/254)*

**Comment by WTer** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/254)*

**Pull request merged**
