### PR TITLE
update canonical height-to-hash map when bigger TD block inserted.

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/118)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[core/blockchain.go, line 371 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/118#-L9nsW49-DcyqO-g1ls_:-L9nsW49-DcyqO-g1lsa:b-faqu4w) ([raw file](https://github.com/seeleteam/go-seele/blob/c27099a1a236629c3e3d372064c6e84e6c6af61f/core/blockchain.go#L371)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 		if header, err = bc.bcStore.GetBlockHeader(headerHash); err != nil {
> 			return err
> 		}
>  
> 		if canonicalHash, err = bc.bcStore.GetBlockHash(header.Height); err != nil {
> 			return err
> 		}
> ```
</details>



better to merge this line with above duplicate code.

---

*[core/store/db_store.go, line 149 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/118#-L9nr2aS-EjdBE_L6Q_v:-L9nr2aS-EjdBE_L6Q_w:b-7ydvn9) ([raw file](https://github.com/seeleteam/go-seele/blob/c27099a1a236629c3e3d372064c6e84e6c6af61f/core/store/db_store.go#L149)):*
> ```Go
> 
> 	if isHead {
> 		batch.Put(heightToHashKey(header.Height), hashBytes)
> ```

use PutBlockHash()

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/118)*

**Comment by lucusfly** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/118)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[core/blockchain.go, line 221 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/118#-L9ntXn--R4OdQAR_dHi:-L9ntXn--R4OdQAR_dHj:b-gfkl0g) ([raw file](https://github.com/seeleteam/go-seele/blob/c27099a1a236629c3e3d372064c6e84e6c6af61f/core/blockchain.go#L221)):*
> ```
> if isHead {
> ```
nice to add comments to explain why add such logic

---

*[core/blockchain.go, line 340 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/118#-L9ntvaW8SULufTi5xP4:-L9ntvaW8SULufTi5xP5:but5yig) ([raw file](https://github.com/seeleteam/go-seele/blob/c27099a1a236629c3e3d372064c6e84e6c6af61f/core/blockchain.go#L340)):*
> ```
> Delete canonical height-to-hash entries above the new head
> ```
still not clear why do you want to delete all the nodes above new head, and how and who add these nodes?

---

*[core/blockchain.go, line 344 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/118#-L9nuOsH3KQgaaHPdZE9:-L9nuOsH3KQgaaHPdZEA:b63zt40) ([raw file](https://github.com/seeleteam/go-seele/blob/c27099a1a236629c3e3d372064c6e84e6c6af61f/core/blockchain.go#L344)):*
> ```
> return err
> ```
add error log?

---

*[core/blockchain.go, line 347 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/118#-L9nuToy4v8uIs4x9dxv:-L9nuToy4v8uIs4x9dxw:bi5q5ch) ([raw file](https://github.com/seeleteam/go-seele/blob/c27099a1a236629c3e3d372064c6e84e6c6af61f/core/blockchain.go#L347)):*
> ```
> !deleted
> ```
what's mean? failed to delete, or no such node to be deleted?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/118)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[core/blockchain_test.go, line 331 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/118#-L9nwKR50FejTd_28_et:-L9nwKR50FejTd_28_eu:b-6hqjp7) ([raw file](https://github.com/seeleteam/go-seele/blob/c27099a1a236629c3e3d372064c6e84e6c6af61f/core/blockchain_test.go#L331)):*
> ```
> (canonical)
> ```
so you mean that the chain with more nodes instead of with biggest td is canonical chain?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/118)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[core/blockchain.go, line 347 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/118#-L9nuToy4v8uIs4x9dxv:-L9nyqcL0c3NfAcew0yR:b-x9duwz) ([raw file](https://github.com/seeleteam/go-seele/blob/c27099a1a236629c3e3d372064c6e84e6c6af61f/core/blockchain.go#L347)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> !deleted
> ```
what's mean? failed to delete, or no such node to be deleted?
</blockquote></details>

got it. either no or deleted failed, but I suppose we should return instead of go ahead.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/118)*

**Comment by boqiu** [comment]
Review status: 3 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[core/blockchain.go, line 221 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/118#-L9ntXn--R4OdQAR_dHi:-L9o43oV-xxQ40kapsIK:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/c27099a1a236629c3e3d372064c6e84e6c6af61f/core/blockchain.go#L221)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> if isHead {
> ```
nice to add comments to explain why add such logic
</blockquote></details>

Done.

---

*[core/blockchain.go, line 340 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/118#-L9ntvaW8SULufTi5xP4:-L9o48394VJuF63GU4w2:b-af1ypq) ([raw file](https://github.com/seeleteam/go-seele/blob/c27099a1a236629c3e3d372064c6e84e6c6af61f/core/blockchain.go#L340)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> Delete canonical height-to-hash entries above the new head
> ```
still not clear why do you want to delete all the nodes above new head, and how and who add these nodes?
</blockquote></details>

If larger TD block inserted, need to update the height-to-hash mappings in canonical chain, which is the chain with largest TD. Here is not to delete any block, but to delete the height-to-hash mapping in canonical chain, since there is API to find a block by (canonical) height.

---

*[core/blockchain.go, line 344 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/118#-L9nuOsH3KQgaaHPdZE9:-L9o4lAJ3BzwhZvfPUoO:bf2u29h) ([raw file](https://github.com/seeleteam/go-seele/blob/c27099a1a236629c3e3d372064c6e84e6c6af61f/core/blockchain.go#L344)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> return err
> ```
add error log?
</blockquote></details>

Core pkg will not add any error log, it's up to the client to handle the concrete error, e.g. log and retry

---

*[core/blockchain.go, line 347 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/118#-L9nuToy4v8uIs4x9dxv:-L9o5FG6-e6lGcKQYypF:b-1mzxo3) ([raw file](https://github.com/seeleteam/go-seele/blob/c27099a1a236629c3e3d372064c6e84e6c6af61f/core/blockchain.go#L347)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

got it. either no or deleted failed, but I suppose we should return instead of go ahead.
</blockquote></details>

deleted, err := bc.bcStore.DeleteBlockHash(i)

deleted == true to indicate successfully delete a item.
deleted == false to indicate the item not found for the specified height i.
err != nil to indicate what went wrong for some other unexpected errors.

---

*[core/blockchain.go, line 371 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/118#-L9nsW49-DcyqO-g1ls_:-L9o5l2E3Eh-AZYkNo8E:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/c27099a1a236629c3e3d372064c6e84e6c6af61f/core/blockchain.go#L371)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> 		if header, err = bc.bcStore.GetBlockHeader(headerHash); err != nil {
> 			return err
> 		}
>  
> 		if canonicalHash, err = bc.bcStore.GetBlockHash(header.Height); err != nil {
> 			return err
> 		}
> ```


better to merge this line with above duplicate code.
</blockquote></details>

Done.

---

*[core/blockchain_test.go, line 331 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/118#-L9nwKR50FejTd_28_et:-L9o5sWa475YUGXUOvQW:b-q2uyhm) ([raw file](https://github.com/seeleteam/go-seele/blob/c27099a1a236629c3e3d372064c6e84e6c6af61f/core/blockchain_test.go#L331)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> (canonical)
> ```
so you mean that the chain with more nodes instead of with biggest td is canonical chain?
</blockquote></details>

Exactly. The concept of canonical chain comes from ETH.

---

*[core/store/db_store.go, line 149 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/118#-L9nr2aS-EjdBE_L6Q_v:-L9ntwxI61LTayqr84Qb:b-hoiq5y) ([raw file](https://github.com/seeleteam/go-seele/blob/c27099a1a236629c3e3d372064c6e84e6c6af61f/core/store/db_store.go#L149)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

use PutBlockHash()
</blockquote></details>

different data type.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/118)*

**Comment by lucusfly** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/118)*

**Comment by WTer** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/118)*

**Pull request merged**
