### PR TITLE
fix sharding problems and make node runnable

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/219)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---

*[cmd/client/cmd/cmddata.go, line 18 at r1](https://reviewable.io/reviews/seeleteam/go-seele/219#-LDilkXq4So0QXHlfQOP:-LDilkXq4So0QXHlfQOQ:b-78z6gv) ([raw file](https://github.com/seeleteam/go-seele/blob/0218dea6a5682402c33435a30be4380cdff76f30/cmd/client/cmd/cmddata.go#L18)):*
> ```Go
> 			ParamReflectType: "GetBlockByHashRequest",
> 			Method:           "seele.GetBlockByHash",
> 			UseWebsocket:     false,
> ```

Why change to false? How about other command requests?

---

*[miner/miner.go, line 245 at r1](https://reviewable.io/reviews/seeleteam/go-seele/219#-LDimhBK5ZFDxKZ9mLXp:-LDimhBK5ZFDxKZ9mLXq:bowvjen) ([raw file](https://github.com/seeleteam/go-seele/blob/0218dea6a5682402c33435a30be4380cdff76f30/miner/miner.go#L245)):*
> ```Go
> 	}
> 
> 	miner.log.Info("miner a block with coinbase %s", miner.coinbase.ToHex())
> ```

Debug level is enough, since such log generated frequently.

---

*[node/node.go, line 100 at r1](https://reviewable.io/reviews/seeleteam/go-seele/219#-LDinLIWCzThkYFCxSwe:-LDinLIX7Y2Khb5gbcqi:b95qm7) ([raw file](https://github.com/seeleteam/go-seele/blob/0218dea6a5682402c33435a30be4380cdff76f30/node/node.go#L100)):*
> ```Go
> 
> 	if specificShard > common.ShardNumber {
> 		return errors.New(fmt.Sprintf("unsupported shard number, it must in range [0, %d]", common.ShardNumber))
> ```

you could use fmt.Errorf instead

---

*[seele/seeleprotocol.go, line 317 at r1](https://reviewable.io/reviews/seeleteam/go-seele/219#-LDio5UxDVN1NIm39Ddc:-LDio5UxDVN1NIm39Ddd:b-gtsdhw) ([raw file](https://github.com/seeleteam/go-seele/blob/0218dea6a5682402c33435a30be4380cdff76f30/seele/seeleprotocol.go#L317)):*
> ```Go
> 		if peer.Node.Shard != common.LocalShardNumber {
> 			issupported := msg.Code == transactionsMsgCode
> 			if !issupported {
> ```

if msg.Code != transactionsMsgCode {
    continue
}

---

*[seele/seeleprotocol.go, line 378 at r1](https://reviewable.io/reviews/seeleteam/go-seele/219#-LDioMtaB3cVP58p2Fkc:-LDioMtaB3cVP58p2Fkd:bcoqkkb) ([raw file](https://github.com/seeleteam/go-seele/blob/0218dea6a5682402c33435a30be4380cdff76f30/seele/seeleprotocol.go#L378)):*
> ```Go
> 				shard := common.GetShardNumber(tx.Data.From)
> 				if shard != common.LocalShardNumber {
> 					break
> ```

break or just continue?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/219)*

**Comment by qiaozhigang** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/219)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[cmd/client/cmd/cmddata.go, line 18 at r1](https://reviewable.io/reviews/seeleteam/go-seele/219#-LDilkXq4So0QXHlfQOP:-LDiqmgy788WAEA-dAuB:b-emjjtw) ([raw file](https://github.com/seeleteam/go-seele/blob/0218dea6a5682402c33435a30be4380cdff76f30/cmd/client/cmd/cmddata.go#L18)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why change to false? How about other command requests?
</blockquote></details>

all should be false. these two are missing. so fix it.

---

*[miner/miner.go, line 245 at r1](https://reviewable.io/reviews/seeleteam/go-seele/219#-LDimhBK5ZFDxKZ9mLXp:-LDirk7g1uIPyxdUjo6T:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/0218dea6a5682402c33435a30be4380cdff76f30/miner/miner.go#L245)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Debug level is enough, since such log generated frequently.
</blockquote></details>

Done.

---

*[node/node.go, line 100 at r1](https://reviewable.io/reviews/seeleteam/go-seele/219#-LDinLIWCzThkYFCxSwe:-LDirspx43_uy_K9CXAc:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/0218dea6a5682402c33435a30be4380cdff76f30/node/node.go#L100)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

you could use fmt.Errorf instead
</blockquote></details>

Done.

---

*[seele/seeleprotocol.go, line 317 at r1](https://reviewable.io/reviews/seeleteam/go-seele/219#-LDio5UxDVN1NIm39Ddc:-LDirbeSAvHAkbY1MTNF:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/0218dea6a5682402c33435a30be4380cdff76f30/seele/seeleprotocol.go#L317)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

if msg.Code != transactionsMsgCode {
    continue
}
</blockquote></details>

Done.

---

*[seele/seeleprotocol.go, line 378 at r1](https://reviewable.io/reviews/seeleteam/go-seele/219#-LDioMtaB3cVP58p2Fkc:-LDircwE2i8RZ5837by2:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/0218dea6a5682402c33435a30be4380cdff76f30/seele/seeleprotocol.go#L378)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

break or just continue?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/219)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/219)*

**Pull request merged**
