### PR TITLE
apply txs when write block

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/113)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[core/blockchain.go, line 164 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9eFXPMDnJsTIQSsI2n:-L9eFXPMDnJsTIQSsI2o:b-y8tiwd) ([raw file](https://github.com/seeleteam/go-seele/blob/2678022e87d7ed672fe0f62b52d850b3807bd1a8/core/blockchain.go#L164)):*
> ```Go
> 
> 	if block.Header.StateHash.Equal(common.EmptyHash) {
> 		block.Header.StateHash = stateRootHash
> ```

miner should handle StateHash, as it is related with HeaderHash

---

*[core/blockchain.go, line 197 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9eG0chAaJL7FwwHS2F:-L9eG0chAaJL7FwwHS2G:b155g5v) ([raw file](https://github.com/seeleteam/go-seele/blob/2678022e87d7ed672fe0f62b52d850b3807bd1a8/core/blockchain.go#L197)):*
> ```
> blockStatedb.Commit(batch)
> ```

you could merge this with "stateRootHash, err := blockStatedb.Commit(nil)" upper

---

*[core/blockchain.go, line 230 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9eGHNM868Ywb0iKbny:-L9eGHNM868Ywb0iKbnz:b-9kba3l) ([raw file](https://github.com/seeleteam/go-seele/blob/2678022e87d7ed672fe0f62b52d850b3807bd1a8/core/blockchain.go#L230)):*
> ```Go
> func (bc *Blockchain) applyTxs(block, preBlock *types.Block) (*state.Statedb, error) {
> 	if len(block.Transactions) == 0 {
> 		panic("txs in block is empty.")
> ```

do not panic, this block may from a malicious peer

---

*[core/blockchain.go, line 235 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9eGRxg5EWXNqIL3mIc:-L9eGRxg5EWXNqIL3mId:bx22cre) ([raw file](https://github.com/seeleteam/go-seele/blob/2678022e87d7ed672fe0f62b52d850b3807bd1a8/core/blockchain.go#L235)):*
> ```Go
> 	minerRewardTx := block.Transactions[0]
> 	if minerRewardTx.Data == nil || minerRewardTx.Data.To == nil {
> 		panic("Tx to address in miner reward is invalid")
> ```

do not panic

---

*[core/blockchain.go, line 238 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9eHgsnEd9QRpwGkak_:-L9eHgsnEd9QRpwGkaka:b-42z0n8) ([raw file](https://github.com/seeleteam/go-seele/blob/2678022e87d7ed672fe0f62b52d850b3807bd1a8/core/blockchain.go#L238)):*
> ```Go
> 	}
> 
> 	if minerRewardTx.Data.Amount == nil || minerRewardTx.Data.Amount.Sign() < 0 {
> ```

check if reward amount is desired value.

---

*[core/blockchain.go, line 239 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9eGScn2RVytsKlHBIE:-L9eGScn2RVytsKlHBIF:bx22cre) ([raw file](https://github.com/seeleteam/go-seele/blob/2678022e87d7ed672fe0f62b52d850b3807bd1a8/core/blockchain.go#L239)):*
> ```Go
> 
> 	if minerRewardTx.Data.Amount == nil || minerRewardTx.Data.Amount.Sign() < 0 {
> 		panic("tx amount in miner reward is invalid")
> ```

do not panic

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/113)*

**Comment by lucusfly** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/113)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[core/blockchain.go, line 233 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9hN3uJ5ItdAJLiMMW7:-L9hN3uJ5ItdAJLiMMW8:bea0vah) ([raw file](https://github.com/seeleteam/go-seele/blob/2678022e87d7ed672fe0f62b52d850b3807bd1a8/core/blockchain.go#L233)):*
> ```
> block.Transactions[0]
> ```
I suppose this tx was added by miner?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/113)*

**Comment by boqiu** [comment]
Review status: 2 of 5 files reviewed at latest revision, 10 unresolved discussions.

---

*[core/blockchain.go, line 164 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9eFXPMDnJsTIQSsI2n:-L9hUwTG2pW9bh7029f9:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2678022e87d7ed672fe0f62b52d850b3807bd1a8/core/blockchain.go#L164)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

miner should handle StateHash, as it is related with HeaderHash
</blockquote></details>

Done.

---

*[core/blockchain.go, line 197 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9eG0chAaJL7FwwHS2F:-L9hV13WCHgYxCosymFv:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2678022e87d7ed672fe0f62b52d850b3807bd1a8/core/blockchain.go#L197)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> blockStatedb.Commit(batch)
> ```

you could merge this with "stateRootHash, err := blockStatedb.Commit(nil)" upper
</blockquote></details>

Done.

---

*[core/blockchain.go, line 230 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9eGHNM868Ywb0iKbny:-L9hVZrP76puonQOfqFk:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2678022e87d7ed672fe0f62b52d850b3807bd1a8/core/blockchain.go#L230)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

do not panic, this block may from a malicious peer
</blockquote></details>

Done.

---

*[core/blockchain.go, line 233 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9hN3uJ5ItdAJLiMMW7:-L9hVajs1O_G0aTLLJxo:b-1vijnd) ([raw file](https://github.com/seeleteam/go-seele/blob/2678022e87d7ed672fe0f62b52d850b3807bd1a8/core/blockchain.go#L233)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> block.Transactions[0]
> ```
I suppose this tx was added by miner?
</blockquote></details>

Exactly.

---

*[core/blockchain.go, line 235 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9eGRxg5EWXNqIL3mIc:-L9hVdGO87IBs1JEkClN:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2678022e87d7ed672fe0f62b52d850b3807bd1a8/core/blockchain.go#L235)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

do not panic
</blockquote></details>

Done.

---

*[core/blockchain.go, line 238 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9eHgsnEd9QRpwGkak_:-L9hVeuy961AErKJFW4d:bvdsgad) ([raw file](https://github.com/seeleteam/go-seele/blob/2678022e87d7ed672fe0f62b52d850b3807bd1a8/core/blockchain.go#L238)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

check if reward amount is desired value.
</blockquote></details>

Need introduce the miner engine to validate 1) nonce 2) amount

---

*[core/blockchain.go, line 239 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9eGScn2RVytsKlHBIE:-L9hVm0G2HqoezAA2MBL:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2678022e87d7ed672fe0f62b52d850b3807bd1a8/core/blockchain.go#L239)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

do not panic
</blockquote></details>

Done.

---

*[core/blockchain.go, line 247 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9hL58M5ZElzHVIOKad:-L9hVoVn83G98uBlpQea:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2678022e87d7ed672fe0f62b52d850b3807bd1a8/core/blockchain.go#L247)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> rewrad
> ```
typo: reward
</blockquote></details>

Done.

---

*[core/blockchain.go, line 251 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9hLLEDEBZG3-WKUv5L:-L9hVpen238PGU4cyIyq:b-uckuug) ([raw file](https://github.com/seeleteam/go-seele/blob/2678022e87d7ed672fe0f62b52d850b3807bd1a8/core/blockchain.go#L251)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> // process other txs
> ```
TODO optimization: parallelly handle these txs using multiple threads
</blockquote></details>

The underlying MPT is not thread-safe, so here just process the txs in sequence. Anyway, could improve the perf later.

---

*[core/blockchain.go, line 263 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9hME4j19V0xY0OddxX:-L9hWCCn6lrw_fyCQAH9:b-do7or6) ([raw file](https://github.com/seeleteam/go-seele/blob/2678022e87d7ed672fe0f62b52d850b3807bd1a8/core/blockchain.go#L263)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> fromStateObj.SubAmount(tx.Data.Amount)
> ```
do we need to modify the balance of fromAccount and toAccount?
</blockquote></details>

Of course. This method is to update the account balance/nonce.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/113)*

**Comment by WTer** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/113)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[core/blockchain.go, line 214 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/113#-L9hZSWh4edJpz139ObT:-L9h_aMP8MPN3mt1pBcV:b-vf0cit) ([raw file](https://github.com/seeleteam/go-seele/blob/486efa1a5cbb2ca7fdd8761807b167ea9ee12a91/core/blockchain.go#L214)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

why not just rollback here?
</blockquote></details>

Error may occur before batch.Commit(), and also need rollback.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/113)*

**Pull request merged**
