### PR TITLE
Task txpool processable txs

### PR DESCRIPTION
**Pull request by boqiu**
Add 2 APIs for tx pool:
1) Get tx by hash
2) Get processable txs from tx pool.

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/75)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[core/tx_collection.go, line 28 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/75#-L7Yr6t74MnT1ou4O783:-L7Yr6t74MnT1ou4O784:bjpmt8x) ([raw file](https://github.com/seeleteam/go-seele/blob/e68b43c694c99420fcb5c56dbae432416a14b1c5/core/tx_collection.go#L28)):*
> getTxs

Seems getAllTxs would be better according to your implementation.

getTxs can be implemented by passing some parameters like, range of nonce, or other conditions, I'm not sure if there is real requirement.

---

*[core/tx_pool.go, line 74 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/75#-L7YsAql5z_QiHlG2x6W:-L7YsAql5z_QiHlG2x6X:bjt0x37) ([raw file](https://github.com/seeleteam/go-seele/blob/e68b43c694c99420fcb5c56dbae432416a14b1c5/core/tx_pool.go#L74)):*
> pool.hashToTxMap[txHash]

just discussion: add a new thread-safe function pool.tryGetTxByHash().

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/75)*

**Comment by lucusfly** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[core/tx_pool_test.go, line 126 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/75#-L7Yt0o2xkf6EXx1dTL3:-L7Yt0o3GQb25XkUs2mV:b-ff997z) ([raw file](https://github.com/seeleteam/go-seele/blob/e68b43c694c99420fcb5c56dbae432416a14b1c5/core/tx_pool_test.go#L126)):*
> ```Go
> 	pool := NewTransactionPool(*DefaultTxPoolConfig())
> 	account1, txs1 := newTestAccountTxs(t, []int64{1, 2, 3}, []uint64{9, 5, 7})
> 	account2, txs2 := newTestAccountTxs(t, []int64{1, 2, 3}, []uint64{7, 9, 5})
> ```

better to add duplicate nonce test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/75)*

**Comment by boqiu** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[core/tx_collection.go, line 28 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/75#-L7Yr6t74MnT1ou4O783:-L7YtnVOwK3xur4ydV3x:b-7i7mgl) ([raw file](https://github.com/seeleteam/go-seele/blob/e68b43c694c99420fcb5c56dbae432416a14b1c5/core/tx_collection.go#L28)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> getTxs

Seems getAllTxs would be better according to your implementation.

getTxs can be implemented by passing some parameters like, range of nonce, or other conditions, I'm not sure if there is real requirement.
</blockquote></details>

This API is not used outside of this file, it's a comment internal API to get txs for further operations, e.g. sort by nonce. So, it's ok at this moment.

Anyway, if new API (e.g. getTxs(filter)) added in future, will change this one to getAllTxs().

---

*[core/tx_pool.go, line 74 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/75#-L7YsAql5z_QiHlG2x6W:-L7YuTaCozmSr80Nl7AQ:b-iup2ot) ([raw file](https://github.com/seeleteam/go-seele/blob/e68b43c694c99420fcb5c56dbae432416a14b1c5/core/tx_pool.go#L74)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> pool.hashToTxMap[txHash]

just discussion: add a new thread-safe function pool.tryGetTxByHash().
</blockquote></details>

Good idea. Let's consider to add ConcurrentMap structure in new PR, and then updates all the usage of map in the manner of thread safe.

---

*[core/tx_pool_test.go, line 126 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/75#-L7Yt0o2xkf6EXx1dTL3:-L7YuwglFTdzBN-mROhB:byfbhqs) ([raw file](https://github.com/seeleteam/go-seele/blob/e68b43c694c99420fcb5c56dbae432416a14b1c5/core/tx_pool_test.go#L126)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

better to add duplicate nonce test
</blockquote></details>

See Test_txCollection_add_txsWithSameNonce

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/75)*

**Comment by WTer** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/75)*

**Pull request merged**
