### PR TITLE
add caller for log module

### PR DESCRIPTION
**Pull request by jessonzheng**
add caller for log; Test_Log has include UT.
log output  change
from:
time="2018-03-02T11:39:42+08:00" level=debug msg="debug msg"
time="2018-03-02T11:39:42+08:00" level=info msg="info msg"
time="2018-03-02T11:39:42+08:00" level=warning msg="warn msg"
time="2018-03-02T11:39:42+08:00" level=error msg="error msg"
to:
time="2018-03-02T11:39:42+08:00" level=debug msg="debug msg" caller="log_test.go:14"
time="2018-03-02T11:39:42+08:00" level=info msg="info msg" caller="log_test.go:15"
time="2018-03-02T11:39:42+08:00" level=warning msg="warn msg" caller="log_test.go:16"
time="2018-03-02T11:39:42+08:00" level=error msg="error msg" caller="log_test.go:17"

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/45)

### CODE REVIEW

**Comment by boqiu** [comment]
Done.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[log/caller.go, line 13 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/45#-L6ZwvAP_sAU90p92T-_:-L6ZwvAP_sAU90p92T-a:bwjewko) ([raw file](https://github.com/seeleteam/go-seele/blob/55ab5b7b8cb6a08b824bbf4a1ed1304769d3f442/log/caller.go#L13)):*
> ```Go
> 
> const (
> 	depth = 9
> ```

Better to add a comment. Once log invocation stack changed, depth need to change as well.

---

*[log/caller.go, line 16 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/45#-L6ZxCXU8gs6z8Q20ZA-:-L6ZxCXU8gs6z8Q20ZA0:b-cv5z0s) ([raw file](https://github.com/seeleteam/go-seele/blob/55ab5b7b8cb6a08b824bbf4a1ed1304769d3f442/log/caller.go#L16)):*
> ```Go
> )
> 
> // CallerHook  a caller hook of logrus
> ```

2 spaces after "CallerHook", sees go plugins do not format automatically.

---

*[log/caller.go, line 28 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/45#-L6ZxnnBo_W3TBWrLOP9:-L6ZxnnBo_W3TBWrLOPA:b-4j32hi) ([raw file](https://github.com/seeleteam/go-seele/blob/55ab5b7b8cb6a08b824bbf4a1ed1304769d3f442/log/caller.go#L28)):*
> ```Go
> // Levels returns support levels
> func (hook *CallerHook) Levels() []logrus.Level {
> 	return []logrus.Level{
> ```

Const variable is better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/45#-:-L6Zw4FozlG_KvkS4tl4:b-896fix)*

**Comment by lucusfly** [comment]
nice feature!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/45#-:-L6_14-46oio5RVTAA2C:b-ne8wbb)*

**Comment by WTer** [comment]
Nice to add some unit tests for this new feature.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[log/caller.go, line 23 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/45#-L6_G9W12s5IHwlawrbY:-L6_G9W12s5IHwlawrbZ:b-pus99e) ([raw file](https://github.com/seeleteam/go-seele/blob/55ab5b7b8cb6a08b824bbf4a1ed1304769d3f442/log/caller.go#L23)):*
> return nil

why do you add this statement? seems it's unnecessary and useless, you can refine this function to remove return definition and this statement.

---

*[log/caller.go, line 28 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/45#-L6ZxnnBo_W3TBWrLOP9:-L6_HEqW9WB3Ya5Mgz7z:bf0fx5) ([raw file](https://github.com/seeleteam/go-seele/blob/55ab5b7b8cb6a08b824bbf4a1ed1304769d3f442/log/caller.go#L28)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Const variable is better.
</blockquote></details>

and also sort these log level in alphabetical order.

---

*[log/caller.go, line 42 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/45#-L6_HXAI5-Y9YBCre1-F:-L6_HXAI5-Y9YBCre1-G:b-fs4yii) ([raw file](https://github.com/seeleteam/go-seele/blob/55ab5b7b8cb6a08b824bbf4a1ed1304769d3f442/log/caller.go#L42)):*
> // not sure what the convention should be here

would be better to add a blank line before it.

---

*[log/log.go, line 87 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/45#-L6_HjT9ETWnIM53GKb2:-L6_HjT9ETWnIM53GKb3:blryzz) ([raw file](https://github.com/seeleteam/go-seele/blob/55ab5b7b8cb6a08b824bbf4a1ed1304769d3f442/log/log.go#L87)):*
> //add

add one blank between '//' and 'add'.

line -> line number.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/45#-:-L6_HzcK5E5wq5saQryb:bryreb2)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[log/caller.go, line 39 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/45#-L6_bsX57Mnp_I7Oamzs:-L6_bsX57Mnp_I7Oamzt:b-mqtv6z) ([raw file](https://github.com/seeleteam/go-seele/blob/55ab5b7b8cb6a08b824bbf4a1ed1304769d3f442/log/caller.go#L39)):*
> runtime.Caller(depth)

will be significant performance regression for logging? if yes, we should add switch to turn on/off this feature.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/45)*

**Comment by jessonzheng** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[log/caller.go, line 13 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/45#-L6ZwvAP_sAU90p92T-_:-L6bUkmQt_N9GQrnFkFZ:bb7f2mf) ([raw file](https://github.com/seeleteam/go-seele/blob/55ab5b7b8cb6a08b824bbf4a1ed1304769d3f442/log/caller.go#L13)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Better to add a comment. Once log invocation stack changed, depth need to change as well.
</blockquote></details>

done

---

*[log/caller.go, line 16 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/45#-L6ZxCXU8gs6z8Q20ZA-:-L6bXzTMR9JIQBc5oI9A:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/55ab5b7b8cb6a08b824bbf4a1ed1304769d3f442/log/caller.go#L16)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

2 spaces after "CallerHook", sees go plugins do not format automatically.
</blockquote></details>

Done.

---

*[log/caller.go, line 23 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/45#-L6_G9W12s5IHwlawrbY:-L6bQqdnELg1Ml0jTBON:bs4bf6n) ([raw file](https://github.com/seeleteam/go-seele/blob/55ab5b7b8cb6a08b824bbf4a1ed1304769d3f442/log/caller.go#L23)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> return nil

why do you add this statement? seems it's unnecessary and useless, you can refine this function to remove return definition and this statement.
</blockquote></details>

 interface is defined by logrus hook. we can't refine the function. we must implement it.

---

*[log/caller.go, line 28 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/45#-L6ZxnnBo_W3TBWrLOP9:-L6bTtZ2asbChSkdL4Vm:b-spr9jd) ([raw file](https://github.com/seeleteam/go-seele/blob/55ab5b7b8cb6a08b824bbf4a1ed1304769d3f442/log/caller.go#L28)):*
> change it to "logrus.AllLevels"  defined by logrus

---

*[log/caller.go, line 39 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/45#-L6_bsX57Mnp_I7Oamzs:-L6bYYDxxoT4C0j5hDpM:b-hasbas) ([raw file](https://github.com/seeleteam/go-seele/blob/55ab5b7b8cb6a08b824bbf4a1ed1304769d3f442/log/caller.go#L39)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> runtime.Caller(depth)

will be significant performance regression for logging? if yes, we should add switch to turn on/off this feature.
</blockquote></details>

if need,we can add this feature later by config 

---

*[log/caller.go, line 42 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/45#-L6_HXAI5-Y9YBCre1-F:-L6bUNU4GltpTQZhO7YN:bb7f2mf) ([raw file](https://github.com/seeleteam/go-seele/blob/55ab5b7b8cb6a08b824bbf4a1ed1304769d3f442/log/caller.go#L42)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> // not sure what the convention should be here

would be better to add a blank line before it.
</blockquote></details>

done

---

*[log/log.go, line 87 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/45#-L6_HjT9ETWnIM53GKb2:-L6bXewIuDxfOQ5knUy9:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/55ab5b7b8cb6a08b824bbf4a1ed1304769d3f442/log/log.go#L87)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> //add

add one blank between '//' and 'add'.

line -> line number.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/45)*

**Comment by jessonzheng** [comment]
change commit;done

---

Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/45#-:-L6b_PlwLfM1z2mmTBX2:ba57ohn)*

**Comment by boqiu** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/45)*

**Comment by WTer** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/45)*

**Comment by lucusfly** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/45)*

**Pull request merged**
