### PR TITLE
add API WriteHeader for HeaderChain

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/80)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[core/headerchain.go, line 68 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/80#-L7gfyuO6aTbg7Yq8j5Y:-L7gfyuO6aTbg7Yq8j5Z:bhjxpf3) ([raw file](https://github.com/seeleteam/go-seele/blob/79f3b4769408aea08fc2c01adda73161c24d35f4/core/headerchain.go#L68)):*
> ```Go
> // It requires the new header's parent header is the HEAD header
> // in the chain.
> func (hc *HeaderChain) WriteHeader(newHeader *types.BlockHeader) error {
> ```

how will you handle blockchain fork?

---

*[core/store/db_store.go, line 34 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/80#-L7gfbxhEed20jWF06hY:-L7gfbxhEed20jWF06hZ:b-qgio0o) ([raw file](https://github.com/seeleteam/go-seele/blob/79f3b4769408aea08fc2c01adda73161c24d35f4/core/store/db_store.go#L34)):*
> ```Go
> //   2) keyHeadBlockHash => HEAD hash
> //   3) keyPrefixHeader + hash => header
> //   4) keyPrefixTD + hash => TD
> ```

what does TD mean? better to use full name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/80)*

**Comment by boqiu** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[core/headerchain.go, line 68 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/80#-L7gfyuO6aTbg7Yq8j5Y:-L7gihEL2uvelEjO8igx:b-gg2g00) ([raw file](https://github.com/seeleteam/go-seele/blob/79f3b4769408aea08fc2c01adda73161c24d35f4/core/headerchain.go#L68)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

how will you handle blockchain fork?
</blockquote></details>

No at this iteration.

---

*[core/store/db_store.go, line 34 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/80#-L7gfbxhEed20jWF06hY:-L7glDmZEy4LFz8QUxYi:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/79f3b4769408aea08fc2c01adda73161c24d35f4/core/store/db_store.go#L34)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

what does TD mean? better to use full name
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/80)*

**Comment by lucusfly** [comment]
Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/80)*

**Comment by WTer** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[core/headerchain.go, line 68 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/80#-L7hjlGC17xdmbIGWIM-:-L7hjlGC17xdmbIGWIM0:boiyx1m) ([raw file](https://github.com/seeleteam/go-seele/blob/5f89f0a59ef20275e264ecde0aeed9f3ecb42fda/core/headerchain.go#L68)):*
> WriteHeader

Just curious, will this function be called in multi-thread env?

---

*[core/store/db_store.go, line 103 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/80#-L7hkTuv34IWiyzccVaT:-L7hkTuv34IWiyzccVaU:bnup4ld) ([raw file](https://github.com/seeleteam/go-seele/blob/5f89f0a59ef20275e264ecde0aeed9f3ecb42fda/core/store/db_store.go#L103)):*
> return batch.Commit()

do we need to log error when failed to commit?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/80)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[core/headerchain.go, line 68 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/80#-L7hjlGC17xdmbIGWIM-:-L7hwizW7AVGfwHsqpnB:bke8yel) ([raw file](https://github.com/seeleteam/go-seele/blob/5f89f0a59ef20275e264ecde0aeed9f3ecb42fda/core/headerchain.go#L68)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> WriteHeader

Just curious, will this function be called in multi-thread env?
</blockquote></details>

No, as already said in the HeaderChain' comment.

---

*[core/store/db_store.go, line 103 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/80#-L7hkTuv34IWiyzccVaT:-L7hwu7bEoLPRDlAa30W:bt68fp5) ([raw file](https://github.com/seeleteam/go-seele/blob/5f89f0a59ef20275e264ecde0aeed9f3ecb42fda/core/store/db_store.go#L103)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> return batch.Commit()

do we need to log error when failed to commit?
</blockquote></details>

do not handle the error, just return it

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/80)*

**Comment by WTer** [comment]
Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/80)*

**Pull request merged**
