### PR TITLE
loop add trustNodes

### PR DESCRIPTION
**Pull request by ypenghui6**
it will delete the staticNodes, if it false when connect to the config staticNodes. 
but,the staticNodes is the key that we can connect to public network

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/235)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[p2p/discovery/udp.go, line 420 at r1](https://reviewable.io/reviews/seeleteam/go-seele/235#-LE9PRSC-mbAGfGgMyS5:-LE9PRSC-mbAGfGgMyS6:bjghy2k) ([raw file](https://github.com/seeleteam/go-seele/blob/bd0e6dce7f647dde5aae7a6a279062cd94e26a55/p2p/discovery/udp.go#L420)):*
> ```
> addSwitch = false
> ```
add break after it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/235)*

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[p2p/discovery/udp_test.go, line 27 at r1](https://reviewable.io/reviews/seeleteam/go-seele/235#-LE9Pk9-4B59Fs7o4RS9:-LE9Pk9-4B59Fs7o4RSA:bqrnfnp) ([raw file](https://github.com/seeleteam/go-seele/blob/bd0e6dce7f647dde5aae7a6a279062cd94e26a55/p2p/discovery/udp_test.go#L27)):*
> ```
> 192.168.122.132
> ```
change to common local ip(127.0.0.1 or 0.0.0.0), otherwise will fail on other test machines.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/235)*

**Comment by lucusfly** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[p2p/discovery/server.go, line 20 at r1](https://reviewable.io/reviews/seeleteam/go-seele/235#-LE9PfJb1-9-Bd2sfSS4:-LE9PfJb1-9-Bd2sfSS5:b-kvoiko) ([raw file](https://github.com/seeleteam/go-seele/blob/bd0e6dce7f647dde5aae7a6a279062cd94e26a55/p2p/discovery/server.go#L20)):*
> ```Go
> 		for _, bn := range bootstrap {
> 			udp.addNode(bn)
> 			udp.trustNodes = append(udp.trustNodes, bn)
> ```

why not just "udp.trustNodes = bootstrap" ?

---

*[p2p/discovery/udp.go, line 419 at r1](https://reviewable.io/reviews/seeleteam/go-seele/235#-LE9PnkS13OezQRkt1ZZ:-LE9PnkS13OezQRkt1Z_:b-3vy8m1) ([raw file](https://github.com/seeleteam/go-seele/blob/bd0e6dce7f647dde5aae7a6a279062cd94e26a55/p2p/discovery/udp.go#L419)):*
> ```
> if u.trustNodes[i] == v {
> ```

== will only compare point value. we should compare its real value.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/235)*

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[p2p/discovery/udp_test.go, line 44 at r1](https://reviewable.io/reviews/seeleteam/go-seele/235#-LE9SKUhAQRiVQDQ51Wg:-LE9SKUhAQRiVQDQ51Wh:b-cc5j4h) ([raw file](https://github.com/seeleteam/go-seele/blob/bd0e6dce7f647dde5aae7a6a279062cd94e26a55/p2p/discovery/udp_test.go#L44)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	key1 := crypto.HashBytes(node1.ID.Bytes())
> 	assert.Equal(t, u.db.m[key1].UDPPort, 9000)
>  
> 	key2 := crypto.HashBytes(node2.ID.Bytes())
> 	assert.Equal(t, u.db.m[key2].UDPPort, 9888)
> ```
</details>

seems these statements are not related to the following "u.addTrustNodes()",
why do you add them?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/235)*

**Comment by ypenghui6** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[p2p/discovery/server.go, line 20 at r1](https://reviewable.io/reviews/seeleteam/go-seele/235#-LE9PfJb1-9-Bd2sfSS4:-LE9mr_J2gVCMvJVPvJJ:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/bd0e6dce7f647dde5aae7a6a279062cd94e26a55/p2p/discovery/server.go#L20)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

why not just "udp.trustNodes = bootstrap" ?
</blockquote></details>

Done.

---

*[p2p/discovery/udp.go, line 419 at r1](https://reviewable.io/reviews/seeleteam/go-seele/235#-LE9PnkS13OezQRkt1ZZ:-LE9s3Mf90qiqaoAfTS7:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/bd0e6dce7f647dde5aae7a6a279062cd94e26a55/p2p/discovery/udp.go#L419)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> if u.trustNodes[i] == v {
> ```

== will only compare point value. we should compare its real value.
</blockquote></details>

Done.

---

*[p2p/discovery/udp.go, line 420 at r1](https://reviewable.io/reviews/seeleteam/go-seele/235#-LE9PRSC-mbAGfGgMyS5:-LE9n6648JjVj2PXqwrX:b-go1qys) ([raw file](https://github.com/seeleteam/go-seele/blob/bd0e6dce7f647dde5aae7a6a279062cd94e26a55/p2p/discovery/udp.go#L420)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> addSwitch = false
> ```
add break after it?
</blockquote></details>

it control if to add the trustNodes

---

*[p2p/discovery/udp_test.go, line 27 at r1](https://reviewable.io/reviews/seeleteam/go-seele/235#-LE9Pk9-4B59Fs7o4RS9:-LE9nOdV8w9hz87eqM91:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/bd0e6dce7f647dde5aae7a6a279062cd94e26a55/p2p/discovery/udp_test.go#L27)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> 192.168.122.132
> ```
change to common local ip(127.0.0.1 or 0.0.0.0), otherwise will fail on other test machines.
</blockquote></details>

Done.

---

*[p2p/discovery/udp_test.go, line 44 at r1](https://reviewable.io/reviews/seeleteam/go-seele/235#-LE9SKUhAQRiVQDQ51Wg:-LE9nSVR6JBCbENM38Y6:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/bd0e6dce7f647dde5aae7a6a279062cd94e26a55/p2p/discovery/udp_test.go#L44)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> 	key1 := crypto.HashBytes(node1.ID.Bytes())
> 	assert.Equal(t, u.db.m[key1].UDPPort, 9000)
>  
> 	key2 := crypto.HashBytes(node2.ID.Bytes())
> 	assert.Equal(t, u.db.m[key2].UDPPort, 9888)
> ```
seems these statements are not related to the following "u.addTrustNodes()",
why do you add them?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/235)*

**Comment by lucusfly** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[p2p/discovery/udp.go, line 419 at r1](https://reviewable.io/reviews/seeleteam/go-seele/235#-LE9PnkS13OezQRkt1ZZ:-LEA-jqD1S8xk7UPG5g6:b-kk6g67) ([raw file](https://github.com/seeleteam/go-seele/blob/bd0e6dce7f647dde5aae7a6a279062cd94e26a55/p2p/discovery/udp.go#L419)):*
<details><summary><i>Previously, ypenghui6 (ypenghui6) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

actually you need compare its id, a node's shard id may be changed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/235)*

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[p2p/discovery/udp.go, line 420 at r1](https://reviewable.io/reviews/seeleteam/go-seele/235#-LE9PRSC-mbAGfGgMyS5:-LEAM6ZA1FNJkosjEhfO:b-1hi72t) ([raw file](https://github.com/seeleteam/go-seele/blob/bd0e6dce7f647dde5aae7a6a279062cd94e26a55/p2p/discovery/udp.go#L420)):*
<details><summary><i>Previously, ypenghui6 (ypenghui6) wrote…</i></summary><blockquote>

it control if to add the trustNodes
</blockquote></details>

I know. but we don't continue to go through other elements since we know u.trustNodes[i] shouldn't be added.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/235)*

**Comment by ypenghui6** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[p2p/discovery/udp.go, line 419 at r1](https://reviewable.io/reviews/seeleteam/go-seele/235#-LE9PnkS13OezQRkt1ZZ:-LECe96f87A7bjZ5jFYo:b-moa7xd) ([raw file](https://github.com/seeleteam/go-seele/blob/bd0e6dce7f647dde5aae7a6a279062cd94e26a55/p2p/discovery/udp.go#L419)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

actually you need compare its id, a node's shard id may be changed.
</blockquote></details>

OK, compare with their id

---

*[p2p/discovery/udp.go, line 420 at r1](https://reviewable.io/reviews/seeleteam/go-seele/235#-LE9PRSC-mbAGfGgMyS5:-LECewns86d-YRa2wTB0:b32w0x) ([raw file](https://github.com/seeleteam/go-seele/blob/bd0e6dce7f647dde5aae7a6a279062cd94e26a55/p2p/discovery/udp.go#L420)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

I know. but we don't continue to go through other elements since we know u.trustNodes[i] shouldn't be added.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/235)*

**Comment by lucusfly** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[p2p/discovery/udp.go, line 417 at r2](https://reviewable.io/reviews/seeleteam/go-seele/235#-LECnlxRDLnZSFbD2Scw:-LECnlxRDLnZSFbD2Scx:bcr505o) ([raw file](https://github.com/seeleteam/go-seele/blob/ed4f3cbfe266cbc23c1690a0e98b13012c789b09/p2p/discovery/udp.go#L417)):*
> ```
> 		for _, v := range copyMap {
> 			if u.trustNodes[i].ID == v.ID {
> 				addSwitch = false
> ```

I think you could leverage db.FindByNodeID method.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/235)*

**Comment by ypenghui6** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[p2p/discovery/udp.go, line 417 at r2](https://reviewable.io/reviews/seeleteam/go-seele/235#-LECnlxRDLnZSFbD2Scw:-LED4kZc3m36f3FLM4vl:b32w0x) ([raw file](https://github.com/seeleteam/go-seele/blob/ed4f3cbfe266cbc23c1690a0e98b13012c789b09/p2p/discovery/udp.go#L417)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> 		for _, v := range copyMap {
> 			if u.trustNodes[i].ID == v.ID {
> 				addSwitch = false
> ```

I think you could leverage db.FindByNodeID method.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/235)*

**Pull request merged**
