### PR TITLE
transaction and block broadcast

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/100)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---

*[seele/peer.go, line 107 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/100#-L98NRWWBgXuApTkLLCd:-L98NRWWBgXuApTkLLCe:bkx0on6) ([raw file](https://github.com/seeleteam/go-seele/blob/41d3b9e0a6426a12e45b6f5af5896578ffa4d4af/seele/peer.go#L107)):*
> ```Go
> func (p *peer) SendBlock(block *types.Block) error {
> 	return p2p.SendMessage(p.rw, blockMsgCode, common.SerializePanic(block))
> }
> ```

Any tests to cover above new added func?

---

*[seele/peerSet.go, line 18 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/100#-L98OjL_80ThnQJfq-Hy:-L98OjL_80ThnQJfq-Hz:b2nhpi3) ([raw file](https://github.com/seeleteam/go-seele/blob/41d3b9e0a6426a12e45b6f5af5896578ffa4d4af/seele/peerSet.go#L18)):*
> ```Go
> )
> 
> type peerSet struct {
> ```

UT?

---

*[seele/peerSet.go, line 31 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/100#-L98NdyVCJyvTq7i9-FR:-L98NdyVCJyvTq7i9-FS:b-823n0o) ([raw file](https://github.com/seeleteam/go-seele/blob/41d3b9e0a6426a12e45b6f5af5896578ffa4d4af/seele/peerSet.go#L31)):*
> ```Go
> 
> func (p *peerSet) Find(address common.Address) *peer {
> 	p.lock.Lock()
> ```

RLock

---

*[seele/peerSet.go, line 51 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/100#-L98O-zZAc6duz586tMS:-L98O-zZAc6duz586tMT:b7en8h8) ([raw file](https://github.com/seeleteam/go-seele/blob/41d3b9e0a6426a12e45b6f5af5896578ffa4d4af/seele/peerSet.go#L51)):*
> ```Go
> 		var k common.Address
> 		for k = range p.peers {
> 			break
> ```

How about to remove the oldest one?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/100)*

**Comment by WTer** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[seele/peer.go, line 81 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/100#-L98OvyB1IGHuvdxDq3B:-L98OvyB1IGHuvdxDq3C:b-ipbpnm) ([raw file](https://github.com/seeleteam/go-seele/blob/41d3b9e0a6426a12e45b6f5af5896578ffa4d4af/seele/peer.go#L81)):*
> ```
> return p2p.SendMessage
> ```

add tx.Hash to p.knownTxs before send this tx?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/100)*

**Comment by lucusfly** [comment]
Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[seele/peer.go, line 81 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/100#-L98OvyB1IGHuvdxDq3B:-L98VAje5dhMMKft1aVB:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/41d3b9e0a6426a12e45b6f5af5896578ffa4d4af/seele/peer.go#L81)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> return p2p.SendMessage
> ```

add tx.Hash to p.knownTxs before send this tx?
</blockquote></details>

Done.

---

*[seele/peer.go, line 107 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/100#-L98NRWWBgXuApTkLLCd:-L98VCT502WHYjLr-PrR:b-mou1p) ([raw file](https://github.com/seeleteam/go-seele/blob/41d3b9e0a6426a12e45b6f5af5896578ffa4d4af/seele/peer.go#L107)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Any tests to cover above new added func?
</blockquote></details>

They are network request, we use command line to verify it.

---

*[seele/peerSet.go, line 18 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/100#-L98OjL_80ThnQJfq-Hy:-L98_SzH7pj5_zdh2CNI:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/41d3b9e0a6426a12e45b6f5af5896578ffa4d4af/seele/peerSet.go#L18)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

UT?
</blockquote></details>

Done.

---

*[seele/peerSet.go, line 31 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/100#-L98NdyVCJyvTq7i9-FR:-L98_RLD32jCcciHD5Gh:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/41d3b9e0a6426a12e45b6f5af5896578ffa4d4af/seele/peerSet.go#L31)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

RLock
</blockquote></details>

Done.

---

*[seele/peerSet.go, line 51 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/100#-L98O-zZAc6duz586tMS:-L98_6OY1N_xcOPwKRyz:b4c0d1q) ([raw file](https://github.com/seeleteam/go-seele/blob/41d3b9e0a6426a12e45b6f5af5896578ffa4d4af/seele/peerSet.go#L51)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

How about to remove the oldest one?
</blockquote></details>

Yes. that's our improvement plan.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/100)*

**Comment by boqiu** [comment]
Reviewed 7 of 10 files at r1, 3 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/100)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[seele/peer.go, line 81 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/100#-L98OvyB1IGHuvdxDq3B:-L98uxTY9mOfqtQd03xx:b75fyvx) ([raw file](https://github.com/seeleteam/go-seele/blob/41d3b9e0a6426a12e45b6f5af5896578ffa4d4af/seele/peer.go#L81)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

moved after SendMessage successful.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/100)*

**Comment by WTer** [comment]
Reviewed 7 of 10 files at r1, 3 of 5 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/100)*

**Pull request merged**
