### PR TITLE
add monitor service

### PR DESCRIPTION
**Pull request by webbergao1**
* add monito service, implements rpc interfaces used by Monitor server

* add  miner info in node struct, hold a pointer to Miner for start or stop miner service

* add interface in SeeleProtocol

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/123)

### CODE REVIEW

**Comment by herove** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---

*[monitor/monitorservice.go, line 18 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMRAjW5ptde6D_Q-_R:-LAMRAjW5ptde6D_Q-_S:bcke5sk) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/monitorservice.go#L18)):*
> ```Go
> 
> // Service implement some rpc interfaces used by a monitor server
> type Service struct {
> ```

struct name is too easy. just personal opinion. maybe MonitorService

---

*[monitor/monitorservice.go, line 48 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMPdJQ1bnZbKTFaomt:-LAMPdJQ1bnZbKTFaomu:b8q7mkd) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/monitorservice.go#L48)):*
> ```Go
> 	s.p2pServer = srvr
> 
> 	fmt.Println("monitor rpc service start")
> ```

better to use log.

---

*[node/node.go, line 27 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMQENt4j-WJ9NbDc0w:-LAMQENu6wRxQRMcbGWl:b-wzjtxx) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/node/node.go#L27)):*
> ```Go
> 	ErrServiceStartFailed = errors.New("node service start failed")
> 	ErrServiceStopFailed  = errors.New("node service stop failed")
> 	ErrConfigIsNull       = errors.New("config info is null")
> ```

alphabetical order

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/123)*

**Comment by WTer** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/node/cmd/start.go, line 79 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMSn9W8FFeVZEPIQU4:-LAMSn9W8FFeVZEPIQU5:b-4tpin4) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/cmd/node/cmd/start.go#L79)):*
> ```
> // go on
> ```
why go on instead of return/exit?

---

*[monitor/api.go, line 12 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMT0PI5HuPQOrFnPeV:-LAMT0PJ8PVv7E4-s6A0:boqvzg3) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/api.go#L12)):*
> ```
> server
> ```
should be service.
if you want to monitor server, generally means checks its cpu/mem/disk/network metrics.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/123)*

**Comment by WTer** [comment]
nice to add unit tests

---

Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[monitor/api.go, line 24 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMTK_B5O27t2cBRTBx:-LAMTK_B5O27t2cBRTBy:b5gjf8j) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/api.go#L24)):*
> ```Go
> // NodeInfo return NodeInfo struct of the local node
> func (api *PublicMonitorAPI) NodeInfo(arg int, result *NodeInfo) error {
> ```

remove this blank line.

---

*[monitor/api.go, line 43 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMTf2G-thWeNK35qzi:-LAMTf2G-thWeNK35qzj:bl6lbd1) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/api.go#L43)):*
> ```
> var (
> ```
nice to add comments for these status.

and currently, we don't have any gas related function, why do you add such status?

---

*[monitor/api.go, line 51 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMTrDb4TgWkHGKpHHW:-LAMTrDb4TgWkHGKpHHX:b-f9sk1z) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/api.go#L51)):*
> ```
> hashrate = 10
> ```
add this magic number as constant or make it configurable.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-:-LAMUAwpDlW6czp8-53K:b-6t702d)*

**Comment by WTer** [comment]
Review status: 0 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[monitor/api.go, line 29 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMUjjwBMEBV_Abi_pg:-LAMUjjwBMEBV_Abi_ph:b-kscvf3) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/api.go#L29)):*
> ```
> Network
> ```
this name is too common, rename to NetVersion

---

*[monitor/api.go, line 55 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMVRvz5GYV-ey9NguG:-LAMVRvz5GYV-ey9NguH:b-cj5f4a) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/api.go#L55)):*
> ```
> //mining = api.s.seele.Miner().IsMining()
> ```
remove this line

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/123)*

**Comment by herove** [comment]
Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

*[cmd/node/cmd/start.go, line 76 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMVkBeCJeBOASqdr_K:-LAMVkBeCJeBOASqdr_L:brtqjmh) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/cmd/node/cmd/start.go#L76)):*
> ```Go
> 
> 		seeleNode.Start()
> 		err = seeleNode.StartMiner(seeleService)
> ```

means must start miner when start a node?

---

*[node/node.go, line 65 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMVVadCu6ZPjjxTsnp:-LAMVVadCu6ZPjjxTsnq:b91hqpx) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/node/node.go#L65)):*
> ```Go
> 
> // StartMiner create miner and begin to minning
> func (n *Node) StartMiner(service *seele.SeeleService) error {
> ```

maybe this function is placed in the wrong file.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/123)*

**Comment by webbergao1** [comment]
done add test

---

Review status: 3 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[cmd/node/cmd/start.go, line 76 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMVkBeCJeBOASqdr_K:-LAMtqfA3ePLx5109Zkx:b-d9o86h) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/cmd/node/cmd/start.go#L76)):*
<details><summary><i>Previously, herove (Leihao Zhou) wrote…</i></summary><blockquote>

means must start miner when start a node?
</blockquote></details>

In our process now, miner node should begin minning when start.
The process is old process, I just puts 'StartMiner' func into seeleNode.
I think we can put it in the configuration file or 'cmd' commond later.

---

*[cmd/node/cmd/start.go, line 79 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMSn9W8FFeVZEPIQU4:-LAN5_Eu3lP3DFdjG2Z-:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/cmd/node/cmd/start.go#L79)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> // go on
> ```
why go on instead of return/exit?
</blockquote></details>

Done.

---

*[monitor/api.go, line 12 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMT0PI5HuPQOrFnPeV:-LAN5gcE5FGCDZ6WH_eh:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/api.go#L12)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> server
> ```
should be service.
if you want to monitor server, generally means checks its cpu/mem/disk/network metrics.
</blockquote></details>

Done.

---

*[monitor/api.go, line 24 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMTK_B5O27t2cBRTBx:-LAN5ieWDWtXFnIvFtW7:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/api.go#L24)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

remove this blank line.
</blockquote></details>

Done.

---

*[monitor/api.go, line 29 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMUjjwBMEBV_Abi_pg:-LAN5kLp25IDJIplnvc5:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/api.go#L29)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> Network
> ```
this name is too common, rename to NetVersion
</blockquote></details>

Done.

---

*[monitor/api.go, line 43 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMTf2G-thWeNK35qzi:-LAN5nYQ5pwUw7m5H_FL:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/api.go#L43)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> var (
> ```
nice to add comments for these status.

and currently, we don't have any gas related function, why do you add such status?
</blockquote></details>

Done.

---

*[monitor/api.go, line 55 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMVRvz5GYV-ey9NguG:-LAN5sbOC4DFI3COjQlk:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/api.go#L55)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> //mining = api.s.seele.Miner().IsMining()
> ```
remove this line
</blockquote></details>

Done.

---

*[monitor/api_types.go, line 30 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LANF-yy9JnaxtWkF5SJ:-LANK6ZT1r4r-Fauvq9H:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/api_types.go#L30)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

we don't have gas price atually
</blockquote></details>

Done.

---

*[monitor/monitorservice.go, line 18 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMRAjW5ptde6D_Q-_R:-LAN5wK3Ay6HlJ5VnLN9:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/monitorservice.go#L18)):*
<details><summary><i>Previously, herove (Leihao Zhou) wrote…</i></summary><blockquote>

struct name is too easy. just personal opinion. maybe MonitorService
</blockquote></details>

Done.

---

*[monitor/monitorservice.go, line 48 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMPdJQ1bnZbKTFaomt:-LAN5xjS86794kATQD0m:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/monitorservice.go#L48)):*
<details><summary><i>Previously, herove (Leihao Zhou) wrote…</i></summary><blockquote>

better to use log.
</blockquote></details>

Done.

---

*[node/node.go, line 27 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMQENt4j-WJ9NbDc0w:-LAN60_UBeEmrNgP_E2L:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/node/node.go#L27)):*
<details><summary><i>Previously, herove (Leihao Zhou) wrote…</i></summary><blockquote>

alphabetical order
</blockquote></details>

Done.

---

*[node/node.go, line 65 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LAMVVadCu6ZPjjxTsnp:-LANG5Uz3qS63pliDz8K:b-9bqqoq) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/node/node.go#L65)):*
<details><summary><i>Previously, herove (Leihao Zhou) wrote…</i></summary><blockquote>

maybe this function is placed in the wrong file.
</blockquote></details>

It's ok.
Our Node is used to miner now,  so we call 'StartMiner' func through a Node and hold a pointer to the miner. 
Other modules  through Node operations miner。

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-:-LAOPCLE9Fp9np3G6tvO:b-lfnbkm)*

**Comment by lucusfly** [comment]
Review status: 3 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[monitor/api_types.go, line 30 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LANF-yy9JnaxtWkF5SJ:-LAVc7Vt06JeOr87hE26:bpy8mr1) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/api_types.go#L30)):*
<details><summary><i>Previously, webbergao1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What does Price mean? we don't have price also.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/123)*

**Comment by webbergao1** [comment]
Review status: 3 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[monitor/api_types.go, line 30 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LANF-yy9JnaxtWkF5SJ:-LAVm_Vl4QUx07sQswde:bvhzy1r) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/api_types.go#L30)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

What does Price mean? we don't have price also.
</blockquote></details>

there has also some unsure fields in the protocol structs, I will determine later. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/123)*

**Comment by lucusfly** [comment]
Review status: 3 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[monitor/api_types.go, line 30 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LANF-yy9JnaxtWkF5SJ:-LAVwO-W2rtBsT_9Lrka:b2puqkk) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/api_types.go#L30)):*
<details><summary><i>Previously, webbergao1 wrote…</i></summary><blockquote>

there has also some unsure fields in the protocol structs, I will determine later. 
</blockquote></details>

Better to remove unsure fields and add it later when you make sure.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/123)*

**Comment by webbergao1** [comment]
Review status: 3 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[monitor/api_types.go, line 30 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/123#-LANF-yy9JnaxtWkF5SJ:-LAWqqX2D7aAwcjouvkj:b74u8b5) ([raw file](https://github.com/seeleteam/go-seele/blob/a87630270246358a04a81cb9ce904ab76699a4a6/monitor/api_types.go#L30)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

Better to remove unsure fields and add it later when you make sure.
</blockquote></details>

already remove

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/123)*

**Comment by lucusfly** [comment]
Reviewed 4 of 6 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/123)*

**Pull request merged**
