### PR TITLE
pow sha3 and stop support

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/78)

### CODE REVIEW

**Comment by WTer** [comment]
nice

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[consensus/pow/sha3/sha3worker.go, line 64 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/78#-L7cQJlOncDlS9QaH8sK:-L7cQJlOncDlS9QaH8sL:bf3db87) ([raw file](https://github.com/seeleteam/go-seele/blob/b838d0cd695fed8cfc82d3c5800dc75129864d14/consensus/pow/sha3/sha3worker.go#L64)):*
> if w.isStop

do we need to init isStop to false when started? this start() only run once for the same instance.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/78#-:-L7cOeMUdePFuxcsGk75:bb7lbs2)*

**Comment by boqiu** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[consensus/pow/sha3/sha3worker.go, line 84 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/78#-L7cSggZFiDbHRgqRJB7:-L7cSgg_GKtf-AYW-ibl:bz9wjbb) ([raw file](https://github.com/seeleteam/go-seele/blob/b838d0cd695fed8cfc82d3c5800dc75129864d14/consensus/pow/sha3/sha3worker.go#L84)):*
> ```Go
> // GetResult if got error, will return the error info
> func (w *Worker) GetResult() (string, error) {
> 	if w.isStop {
> ```

From the error variable name, it seems "userStopped" is a better name. 

---

*[consensus/pow/sha3/sha3worker.go, line 116 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/78#-L7cSrBZdZko9DUu1KWM:-L7cSrBZdZko9DUu1KWN:bb17g7u) ([raw file](https://github.com/seeleteam/go-seele/blob/b838d0cd695fed8cfc82d3c5800dc75129864d14/consensus/pow/sha3/sha3worker.go#L116)):*
> ```Go
> 
> func (w *Worker) Stop() {
> 	w.isStop = true
> ```

change to atomic?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/78)*

**Comment by lucusfly** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[consensus/pow/sha3/sha3worker.go, line 64 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/78#-L7cQJlOncDlS9QaH8sK:-L7cbzCMsy0sTqqQJLJF:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/b838d0cd695fed8cfc82d3c5800dc75129864d14/consensus/pow/sha3/sha3worker.go#L64)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> if w.isStop

do we need to init isStop to false when started? this start() only run once for the same instance.


</blockquote></details>

Done.

---

*[consensus/pow/sha3/sha3worker.go, line 84 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/78#-L7cSggZFiDbHRgqRJB7:-L7ccjTj9nFgH5YEXKX7:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/b838d0cd695fed8cfc82d3c5800dc75129864d14/consensus/pow/sha3/sha3worker.go#L84)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

From the error variable name, it seems "userStopped" is a better name. 
</blockquote></details>

Done.

---

*[consensus/pow/sha3/sha3worker.go, line 116 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/78#-L7cSrBZdZko9DUu1KWM:-L7cck69D247kTHKuECH:b-a8gd9o) ([raw file](https://github.com/seeleteam/go-seele/blob/b838d0cd695fed8cfc82d3c5800dc75129864d14/consensus/pow/sha3/sha3worker.go#L116)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

change to atomic?
</blockquote></details>

I don't think it is necessary

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/78)*

**Comment by WTer** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/78)*

**Comment by boqiu** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/78)*

**Pull request merged**
