### PR TITLE
many bugs and code issues fix. see description.

### PR DESCRIPTION
**Pull request by lucusfly**
1. fix node will stop if miner is running bug
2. check transaction exist in sendtx tool
3. print more detail tps info
4. remove unused header chain
5. adjust write block order in case for inconsistent bug
6. fix wrong add nonce bug
7. added txs back when block fork to avoid tx missing bug.
8. add status info to get tx api
9. mining will continue when write block failed.

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/273)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @lucusfly, @WTer, @qiaozhigang, @boqiu, and @jessonzheng)

---

*[core/tx_pool.go, line 83 at r1](https://reviewable.io/reviews/seeleteam/go-seele/273#-LEn1nQwBvRupfWdvl6n:-LEn1nQwBvRupfWdvl6o:bcomusa) ([raw file](https://github.com/seeleteam/go-seele/blob/bdab2918b9934828ee14e2ced5069642169760a3/core/tx_pool.go#L83)):*
> ```
> chainHeaderChanged
> ```
do we need to add lock this func?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/273)*

**Comment by WTer** [comment]
Review status: 0 of 13 files reviewed, 8 unresolved discussions (waiting on @lucusfly, @WTer, @qiaozhigang, @boqiu, and @jessonzheng)

---

*[core/tx_pool.go, line 185 at r1](https://reviewable.io/reviews/seeleteam/go-seele/273#-LEn642zDQVM2FIbrqER:-LEn642zDQVM2FIbrqES:b-e6r2nw) ([raw file](https://github.com/seeleteam/go-seele/blob/bdab2918b9934828ee14e2ced5069642169760a3/core/tx_pool.go#L185)):*
> ```
> AddTransaction
> ```
there is a logic to valid txs is nil/empty in addTransactions, so do we need to add logic to check whether tx is nil?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/273)*

**Comment by lucusfly** [comment]
Review status: 0 of 13 files reviewed, 8 unresolved discussions (waiting on @lucusfly, @boqiu, @WTer, @qiaozhigang, and @jessonzheng)

---

*[core/tx_pool.go, line 83 at r1](https://reviewable.io/reviews/seeleteam/go-seele/273#-LEn1nQwBvRupfWdvl6n:-LEn66ZI0v_6naMyLTfN:bkm82b1) ([raw file](https://github.com/seeleteam/go-seele/blob/bdab2918b9934828ee14e2ced5069642169760a3/core/tx_pool.go#L83)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> chainHeaderChanged
> ```
do we need to add lock this func?
</blockquote></details>

No. The place that need lock is remove and add transaction. they already have lock.

---

*[core/tx_pool.go, line 83 at r1](https://reviewable.io/reviews/seeleteam/go-seele/273#-LEn3Rdv1xmI6qBK-V8J:-LEnGRP_CekBDyR4xtLG:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/bdab2918b9934828ee14e2ced5069642169760a3/core/tx_pool.go#L83)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

better to add UT for this method.
</blockquote></details>

Done.

---

*[core/tx_pool.go, line 85 at r1](https://reviewable.io/reviews/seeleteam/go-seele/273#-LEn02I6Em_BS58mh8s_:-LEn6StE2kUxhM_4KA4-:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/bdab2918b9934828ee14e2ced5069642169760a3/core/tx_pool.go#L85)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Hash already has a method IsEmpty()
</blockquote></details>

Done.

---

*[core/tx_pool.go, line 93 at r1](https://reviewable.io/reviews/seeleteam/go-seele/273#-LEn0DAn39sH8vfojcQ4:-LEn6oel7zOAkW954uB6:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/bdab2918b9934828ee14e2ced5069642169760a3/core/tx_pool.go#L93)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> Warn
> ```

Error?
</blockquote></details>

Done.

---

*[core/tx_pool.go, line 107 at r1](https://reviewable.io/reviews/seeleteam/go-seele/273#-LEn0nKU9tCrY8S_KWbQ:-LEn7JpfD9hlXGcncmyA:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/bdab2918b9934828ee14e2ced5069642169760a3/core/tx_pool.go#L107)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

better to add necessary comments for the reinjected txs:
1) delete committed txs in new branch from pool.
2) add committed txs back in current branch.
</blockquote></details>

Done.

---

*[core/tx_pool.go, line 129 at r1](https://reviewable.io/reviews/seeleteam/go-seele/273#-LEn2nOhDTMQUxuSehJo:-LEn7NT25YIHiUatl5cV:bd30ifx) ([raw file](https://github.com/seeleteam/go-seele/blob/bdab2918b9934828ee14e2ced5069642169760a3/core/tx_pool.go#L129)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

!=
</blockquote></details>

good catch

---

*[core/tx_pool.go, line 185 at r1](https://reviewable.io/reviews/seeleteam/go-seele/273#-LEn642zDQVM2FIbrqER:-LEn7drm4ojSuTkS-gW1:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/bdab2918b9934828ee14e2ced5069642169760a3/core/tx_pool.go#L185)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> AddTransaction
> ```
there is a logic to valid txs is nil/empty in addTransactions, so do we need to add logic to check whether tx is nil?
</blockquote></details>

Done.

---

*[core/types/block.go, line 84 at r1](https://reviewable.io/reviews/seeleteam/go-seele/273#-LEn3nrqDpzEjPRExtLv:-LEn7lwN947NSnjLXNEi:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/bdab2918b9934828ee14e2ced5069642169760a3/core/types/block.go#L84)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> block.Transactions == nil ||
> ```

redundant, len(nil) is 0
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/273)*

**Comment by boqiu** [comment]
Reviewed 10 of 13 files at r1, 3 of 3 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @lucusfly, @qiaozhigang, and @jessonzheng)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/273)*

**Comment by boqiu** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @lucusfly, @qiaozhigang, and @jessonzheng)

---

*[core/tx_pool.go, line 83 at r1](https://reviewable.io/reviews/seeleteam/go-seele/273#-LEn1nQwBvRupfWdvl6n:-LEnLO9bC-VWaLQn0dcP:b-enfv6r) ([raw file](https://github.com/seeleteam/go-seele/blob/bdab2918b9934828ee14e2ced5069642169760a3/core/tx_pool.go#L83)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

No. The place that need lock is remove and add transaction. they already have lock.
</blockquote></details>

Not safe, since this method changed the state of tx pool. (e.g. lastHeader)

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/273)*

**Comment by lucusfly** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @boqiu, @qiaozhigang, and @jessonzheng)

---

*[core/tx_pool.go, line 83 at r1](https://reviewable.io/reviews/seeleteam/go-seele/273#-LEn1nQwBvRupfWdvl6n:-LEnPRoT8oHSYFOEc93B:bwcgbcd) ([raw file](https://github.com/seeleteam/go-seele/blob/bdab2918b9934828ee14e2ced5069642169760a3/core/tx_pool.go#L83)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Not safe, since this method changed the state of tx pool. (e.g. lastHeader)
</blockquote></details>

add queue

---

*[core/tx_pool.go, line 97 at r2](https://reviewable.io/reviews/seeleteam/go-seele/273#-LEnKNZ09OX3YNm7nGqS:-LEnPWfRDQgWRkLwQbgQ:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/65d411856a177836d8681a12df707ffc3ce8797d/core/tx_pool.go#L97)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

> ```
> getRejectTransaction
> ```

getReinjectTransactions?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/273)*

**Comment by boqiu** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed, 2 unresolved discussions (waiting on @lucusfly, @qiaozhigang, and @jessonzheng)

---

*[core/tx_pool.go, line 89 at r3](https://reviewable.io/reviews/seeleteam/go-seele/273#-LEnSuvs6Sjcm6eHutpI:-LEnSuvs6Sjcm6eHutpJ:bfcyjyh) ([raw file](https://github.com/seeleteam/go-seele/blob/452c041630efe6f7f53e5937998fd0d0100d9800/core/tx_pool.go#L89)):*
> ```Go
> func (pool *TransactionPool) chainHeaderChanged(e event.Event) {
> 	newHeader := e.(common.Hash)
> 	pool.chainHeaderChangeChannel <- newHeader
> ```

if new header hash is empty, suggest not to add it into channel.

---

*[seele/seeleservice.go, line 108 at r3](https://reviewable.io/reviews/seeleteam/go-seele/273#-LEnTCwY9towIZDzwsVb:-LEnTCwY9towIZDzwsVc:bfn9l1o) ([raw file](https://github.com/seeleteam/go-seele/blob/452c041630efe6f7f53e5937998fd0d0100d9800/seele/seeleservice.go#L108)):*
> ```Go
> 	}
> 
> 	go s.txPool.MonitorChainHeaderChange()
> ```

This is only used for tx pool, suggest to move to the constructor of txpool.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/273)*

**Comment by lucusfly** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @boqiu, @qiaozhigang, and @jessonzheng)

---

*[core/tx_pool.go, line 89 at r3](https://reviewable.io/reviews/seeleteam/go-seele/273#-LEnSuvs6Sjcm6eHutpI:-LEnVLzx5nuHuGVvt0xF:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/452c041630efe6f7f53e5937998fd0d0100d9800/core/tx_pool.go#L89)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

if new header hash is empty, suggest not to add it into channel.
</blockquote></details>

Done.

---

*[seele/seeleservice.go, line 108 at r3](https://reviewable.io/reviews/seeleteam/go-seele/273#-LEnTCwY9towIZDzwsVb:-LEnVF954sjMYWzb3bQt:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/452c041630efe6f7f53e5937998fd0d0100d9800/seele/seeleservice.go#L108)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

This is only used for tx pool, suggest to move to the constructor of txpool.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/273)*

**Comment by boqiu** [comment]
Reviewed 2 of 2 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @qiaozhigang and @jessonzheng)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/273)*

**Pull request merged**
