### PR TITLE
add client api: signature

### PR DESCRIPTION
**Pull request by ypenghui6**
add client api signature, we have a AddTx RPC api, but it need a signature; so we must to provide a signature api

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/295)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ypenghui6, @WTer, @boqiu, and @lucusfly)

---

*[cmd/client/cmd/signature.go, line 91 at r1](https://reviewable.io/reviews/seeleteam/go-seele/295#-LFVPO4r5RglDvBfKxX1:-LFVPO4r5RglDvBfKxX2:b8beu9n) ([raw file](https://github.com/seeleteam/go-seele/blob/933c9c01b838b32bf1bffd5d22b8d9edc09867a5/cmd/client/cmd/signature.go#L91)):*
> ```
> os.ModeAppend
> ```
why not overwrite?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/295)*

**Comment by boqiu** [comment]
If so, we have to use client.exe to get signature, why not use client.exe to send tx instead of CURL.

Suggest to keep current API.

---

Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ypenghui6, @WTer, @boqiu, and @lucusfly)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/295#-:-LFVQzArBjTOy07V_avB:b3h3iji)*

**Comment by ypenghui6** [comment]
provide a http add tx, and we can use client sign  -k  to appoint a privatekey instead of a privatekey file

---

Review status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ypenghui6, @WTer, @boqiu, and @lucusfly)

---

*[cmd/client/cmd/signature.go, line 91 at r1](https://reviewable.io/reviews/seeleteam/go-seele/295#-LFVPO4r5RglDvBfKxX1:-LF_Yqo8E8DL2Wqq1Kxi:b-lgpu75) ([raw file](https://github.com/seeleteam/go-seele/blob/933c9c01b838b32bf1bffd5d22b8d9edc09867a5/cmd/client/cmd/signature.go#L91)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> os.ModeAppend
> ```
why not overwrite?
</blockquote></details>

change to  printf

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/295#-:-LF_ZLQW3upZlL4o3YCq:b-jzbfdr)*

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ypenghui6, @WTer, @boqiu, and @lucusfly)

---

*[cmd/client/cmd/signature.go, line 76 at r2](https://reviewable.io/reviews/seeleteam/go-seele/295#-LFaFGe1-MbFm8QWBeX0:-LFaFGe1-MbFm8QWBeX1:b-h63xho) ([raw file](https://github.com/seeleteam/go-seele/blob/2be937c9b1b9e55d9e525a522f3b17d2d499bcd3/cmd/client/cmd/signature.go#L76)):*
> ```
> tx.Sign(key)
> ```
handle errors?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/295)*

**Comment by ypenghui6** [comment]
Review status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @WTer, @boqiu, and @lucusfly)

---

*[cmd/client/cmd/signature.go, line 76 at r2](https://reviewable.io/reviews/seeleteam/go-seele/295#-LFaFGe1-MbFm8QWBeX0:-LFbBWOq2xOWUeIJdR4c:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2be937c9b1b9e55d9e525a522f3b17d2d499bcd3/cmd/client/cmd/signature.go#L76)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> tx.Sign(key)
> ```
handle errors?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/295)*

**Comment by ypenghui6** [comment]
Review status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @WTer, @boqiu, and @lucusfly)

---

*[cmd/client/cmd/signature.go, line 76 at r2](https://reviewable.io/reviews/seeleteam/go-seele/295#-LFaFGe1-MbFm8QWBeX0:-LFbBk7M0Z543C7j5GSN:b-zg906u) ([raw file](https://github.com/seeleteam/go-seele/blob/2be937c9b1b9e55d9e525a522f3b17d2d499bcd3/cmd/client/cmd/signature.go#L76)):*
<details><summary><i>Previously, ypenghui6 (ypenghui6) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It doesn't need handle, the code will not panic  if it is a right key; otherwise the code will return above . 

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/295)*

**Comment by WTer** [comment]
Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 3 of 3 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @boqiu and @lucusfly)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/295)*

**Pull request merged**
