### PR TITLE
add statedb in blockchain

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/102)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[core/blockchain.go, line 13 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/102#-L99E8XX0r0FedDY_sCJ:-L99E8XX0r0FedDY_sCK:b-mu0t41) ([raw file](https://github.com/seeleteam/go-seele/blob/22dcba4484cc3b1b6cf140e41a9353a2a4f662c5/core/blockchain.go#L13)):*
> ```Go
> 
> 	"github.com/seeleteam/go-seele/database"
> ```

remove this line

---

*[core/blockchain.go, line 32 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/102#-L99GVOaAa_CUFvaZVte:-L99GVOaAa_CUFvaZVtf:bdesn5s) ([raw file](https://github.com/seeleteam/go-seele/blob/22dcba4484cc3b1b6cf140e41a9353a2a4f662c5/core/blockchain.go#L32)):*
> ```Go
> 	mutex       sync.RWMutex
> 	bcStore     store.BlockchainStore
> 	db          database.Database
> ```

I think this db is different from bcStore's db, it is used for store state's info. could you add comments for misunderstanding?

---

*[core/blockchain.go, line 138 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/102#-L99EYeJ0gnf26H2NIIb:-L99EYeJ0gnf26H2NIIc:b-whpm69) ([raw file](https://github.com/seeleteam/go-seele/blob/22dcba4484cc3b1b6cf140e41a9353a2a4f662c5/core/blockchain.go#L138)):*
> ```Go
> 
> // GetStore returns the blockchain store instance.
> func (bc *Blockchain) GetStore() store.BlockchainStore {
> ```

I already added this method

---

*[core/blockchain_test.go, line 15 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/102#-L99EihP1g4AwI4zXJ-z:-L99EihP1g4AwI4zXJ0-:b-l6mwxj) ([raw file](https://github.com/seeleteam/go-seele/blob/22dcba4484cc3b1b6cf140e41a9353a2a4f662c5/core/blockchain_test.go#L15)):*
> ```Go
> 
> 	"github.com/seeleteam/go-seele/database"
> ```

remove

---

*[core/types/transaction.go, line 101 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/102#-L99GBv5BxVovcoFHXfj:-L99GBv5BxVovcoFHXfk:b2nh6ex) ([raw file](https://github.com/seeleteam/go-seele/blob/22dcba4484cc3b1b6cf140e41a9353a2a4f662c5/core/types/transaction.go#L101)):*
> ```Go
> 	}
> 
> 	if tx.Data.AccountNonce < accountNonce {
> ```

<=?

---

*[seele/seeleservice.go, line 77 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/102#-L99H1Hw34dOfgEBGvRG:-L99H1Hw34dOfgEBGvRH:b-8ob4vw) ([raw file](https://github.com/seeleteam/go-seele/blob/22dcba4484cc3b1b6cf140e41a9353a2a4f662c5/seele/seeleservice.go#L77)):*
> ```Go
> 	}
> 
> 	s.chain, err = core.NewBlockchain(bcStore, s.chainDB)
> ```

s.chainDB is bcStore db, right? it could not be used as state db.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/102)*

**Comment by boqiu** [comment]
Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[core/blockchain.go, line 13 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/102#-L99E8XX0r0FedDY_sCJ:-L99XhMDAKa312l4QY96:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/22dcba4484cc3b1b6cf140e41a9353a2a4f662c5/core/blockchain.go#L13)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

remove this line
</blockquote></details>

Done.

---

*[core/blockchain.go, line 32 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/102#-L99GVOaAa_CUFvaZVte:-L99MLui-oSgx-s7xg5y:b-mvhgaa) ([raw file](https://github.com/seeleteam/go-seele/blob/22dcba4484cc3b1b6cf140e41a9353a2a4f662c5/core/blockchain.go#L32)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

I think this db is different from bcStore's db, it is used for store state's info. could you add comments for misunderstanding?
</blockquote></details>

Here need not to care about the db used in bcStore, it's ok even though use the same DB. Anyway, I changed the variable name for client to better understand its usage.

---

*[core/blockchain.go, line 138 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/102#-L99EYeJ0gnf26H2NIIb:-L99Nolk4rNkDkmD-7_-:b-ypcida) ([raw file](https://github.com/seeleteam/go-seele/blob/22dcba4484cc3b1b6cf140e41a9353a2a4f662c5/core/blockchain.go#L138)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

I already added this method
</blockquote></details>

I know it, just change the method name, since it's the method of blockchain, so GetStore is enough.

---

*[core/blockchain_test.go, line 15 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/102#-L99EihP1g4AwI4zXJ-z:-L99YDyiEZf7Qep_tfG4:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/22dcba4484cc3b1b6cf140e41a9353a2a4f662c5/core/blockchain_test.go#L15)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

---

*[core/types/transaction.go, line 101 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/102#-L99GBv5BxVovcoFHXfj:-L99OAFx2j5alHMFOU6U:b-tvtfqr) ([raw file](https://github.com/seeleteam/go-seele/blob/22dcba4484cc3b1b6cf140e41a9353a2a4f662c5/core/types/transaction.go#L101)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

<=?
</blockquote></details>

No, it's <

---

*[seele/seeleservice.go, line 77 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/102#-L99H1Hw34dOfgEBGvRG:-L99YmMJ7IrdFe710wCK:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/22dcba4484cc3b1b6cf140e41a9353a2a4f662c5/seele/seeleservice.go#L77)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

s.chainDB is bcStore db, right? it could not be used as state db.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/102)*

**Comment by lucusfly** [comment]
Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[seele/seeleservice.go, line 82 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/102#-L99_rRuDLEV0NIOVkPf:-L99_rRuDLEV0NIOVkPg:br280lc) ([raw file](https://github.com/seeleteam/go-seele/blob/353154f8c840fd1495fa35e9abb8288e67e74b4e/seele/seeleservice.go#L82)):*
> ```Go
> 	bcStore := store.NewBlockchainDatabase(s.chainDB)
> 	genesis := core.DefaultGenesis(bcStore)
> 	err = genesis.Initialize(s.accountStateDB)
> ```

s.chainDB?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/102)*

**Comment by lucusfly** [comment]
Reviewed 5 of 8 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/102)*

**Comment by lucusfly** [comment]
please resolve the conflicts with master

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/102#-:-L99a2tX03LNYVI9Kd4v:b55qdwp)*

**Comment by boqiu** [comment]
resolved the conflicts with master branch.

---

Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[seele/seeleservice.go, line 82 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/102#-L99_rRuDLEV0NIOVkPf:-L99ahtT36eOGLqeTYo2:bhgtono) ([raw file](https://github.com/seeleteam/go-seele/blob/353154f8c840fd1495fa35e9abb8288e67e74b4e/seele/seeleservice.go#L82)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

s.chainDB?
</blockquote></details>

No, it's account state db, which is used to initialize the default accounts of genesis block.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/102#-:-L99bQwn96ptfQw3d0RX:b4xd8uv)*

**Comment by lucusfly** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/102)*

**Comment by WTer** [comment]
Reviewed 5 of 8 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/102)*

**Pull request closed without merging**
