### PR TITLE
add gas fee for test net

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/328)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @boqiu, @WTer, and @lucusfly)

---

*[core/evm.go, line 143 at r1](https://reviewable.io/reviews/seeleteam/go-seele/328#-LFvhOT64_4eOIzHCpRD:-LFvhOT64_4eOIzHCpRE:b-v4mz7c) ([raw file](https://github.com/seeleteam/go-seele/blob/aca16b03ef4c173a3568fcabc401534f3c955b90/core/evm.go#L143)):*
> ```
> uint64
> ```

return *big.Int

---

*[core/evm.go, line 148 at r1](https://reviewable.io/reviews/seeleteam/go-seele/328#-LFvhftCC4n5Jx2y9P0r:-LFvhftCC4n5Jx2y9P0s:bf82p1p) ([raw file](https://github.com/seeleteam/go-seele/blob/aca16b03ef4c173a3568fcabc401534f3c955b90/core/evm.go#L148)):*
> ```Go
> 	// complex contract > 16KB
> 	if codeLen > 16*1024*1024 {
> 		return 4 * common.SeeleToFan.Uint64()
> ```

The fee is too much.

---

*[core/evm.go, line 165 at r1](https://reviewable.io/reviews/seeleteam/go-seele/328#-LFviGfh6Y6yL2ikR9Lp:-LFviGfh6Y6yL2ikR9Lq:bueoz9s) ([raw file](https://github.com/seeleteam/go-seele/blob/aca16b03ef4c173a3568fcabc401534f3c955b90/core/evm.go#L165)):*
> ```Go
> }
> 
> func usedGasFee(usedGas uint64) uint64 {
> ```

better add some comments for the mapping.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/328)*

**Comment by wangff15386** [comment]
Review status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @boqiu, @WTer, and @lucusfly)

---

*[core/evm.go, line 84 at r2](https://reviewable.io/reviews/seeleteam/go-seele/328#-LFz5Atj3j8IFGw7nLUc:-LFz5Atj3j8IFGw7nLUd:b-v3qdp4) ([raw file](https://github.com/seeleteam/go-seele/blob/874cb7d5e8692e8e4e01791f813c9e0a67a02f8a/core/evm.go#L84)):*
> ```Go
> 		if receipt.Result, createdContractAddr, leftOverGas, err = evm.Create(caller, tx.Data.Payload, gas, tx.Data.Amount); err == nil {
> 			receipt.ContractAddress = createdContractAddr.Bytes()
> 		}
> ```

Why does the contract creation fee not include the used gas fee(gas - leftOverGas)?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/328)*

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @lucusfly, @boqiu, and @WTer)

---

*[core/evm.go, line 143 at r1](https://reviewable.io/reviews/seeleteam/go-seele/328#-LFvhOT64_4eOIzHCpRD:-LFzZ7bz2oOfwCoRTQeB:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/aca16b03ef4c173a3568fcabc401534f3c955b90/core/evm.go#L143)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> uint64
> ```

return *big.Int
</blockquote></details>

Done.

---

*[core/evm.go, line 148 at r1](https://reviewable.io/reviews/seeleteam/go-seele/328#-LFvhftCC4n5Jx2y9P0r:-LFzZ8IM0z3o2WWkoeAH:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/aca16b03ef4c173a3568fcabc401534f3c955b90/core/evm.go#L148)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

The fee is too much.
</blockquote></details>

Done.

---

*[core/evm.go, line 162 at r1](https://reviewable.io/reviews/seeleteam/go-seele/328#-LFz22OP29xAs1ui6ZNm:-LFzZUEv-DsCfT98bqCL:b6lb2xb) ([raw file](https://github.com/seeleteam/go-seele/blob/aca16b03ef4c173a3568fcabc401534f3c955b90/core/evm.go#L162)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> common.SeeleToFan.Uint64()
> ```
nice to add bar for free use.
</blockquote></details>

Basically, we need a min fee to avoid create too many contracts, which consume 

---

*[core/evm.go, line 165 at r1](https://reviewable.io/reviews/seeleteam/go-seele/328#-LFviGfh6Y6yL2ikR9Lp:-LFzZw_d8EAhpA8Vdfj5:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/aca16b03ef4c173a3568fcabc401534f3c955b90/core/evm.go#L165)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

better add some comments for the mapping.
</blockquote></details>

Done.

---

*[core/evm.go, line 84 at r2](https://reviewable.io/reviews/seeleteam/go-seele/328#-LFz5Atj3j8IFGw7nLUc:-LFzCBZv8YEz97_V2l18:b-cqfza5) ([raw file](https://github.com/seeleteam/go-seele/blob/874cb7d5e8692e8e4e01791f813c9e0a67a02f8a/core/evm.go#L84)):*
<details><summary><i>Previously, wangff15386 (Confucianism123) wrote…</i></summary><blockquote>

Why does the contract creation fee not include the used gas fee(gas - leftOverGas)?
</blockquote></details>

any fee policy is ok, in test net, we just ensure user cannot create too many large contract or save too many data on blockchain.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/328)*

**Comment by WTer** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed, 4 unresolved discussions (waiting on @lucusfly and @wangff15386)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/328)*

**Comment by lucusfly** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed, 1 unresolved discussion (waiting on @wangff15386)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/328)*

**Pull request merged**
