### PR TITLE
Cannot add peer to seeleprotocol if it already exists in peerSet

### PR DESCRIPTION
**Pull request by qiaozhigang**
handleAddPeer function should return error, if  peer already exists in seeleprotocol.peerSet

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/193)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[seele/seeleprotocol.go, line 258 at r1](https://reviewable.io/reviews/seeleteam/go-seele/193#-LD15hIT35jBR3okOTbA:-LD15hIUAxrZ3yRoNVOl:bgmn812) ([raw file](https://github.com/seeleteam/go-seele/blob/1a324eb43bfef2536e5cb3a749b8cb46a98c29d2/seele/seeleprotocol.go#L258)):*
> ```
> p.log.Error
> ```

Info or even debug?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/193)*

**Comment by qiaozhigang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[seele/seeleprotocol.go, line 258 at r1](https://reviewable.io/reviews/seeleteam/go-seele/193#-LD15hIT35jBR3okOTbA:-LD4fn-WEWD6OFUCVojl:b-v23wvc) ([raw file](https://github.com/seeleteam/go-seele/blob/1a324eb43bfef2536e5cb3a749b8cb46a98c29d2/seele/seeleprotocol.go#L258)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> p.log.Error
> ```

Info or even debug?
</blockquote></details>

ok, change to info

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/193)*

**Comment by lucusfly** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[p2p/peer.go, line 52 at r2](https://reviewable.io/reviews/seeleteam/go-seele/193#-LD5MWr3EtWXZpqA3dWz:-LD5MWr3EtWXZpqA3dX-:byguww9) ([raw file](https://github.com/seeleteam/go-seele/blob/da39efa3ab11c046271a2ce3f1b3854bb2f1584a/p2p/peer.go#L52)):*
> ```
> p.cap().String()
> ```

p.cap() is enough

---

*[p2p/peer.go, line 142 at r2](https://reviewable.io/reviews/seeleteam/go-seele/193#-LD5M_xg-WRCVxw0MXbb:-LD5M_xg-WRCVxw0MXbc:b-j925l9) ([raw file](https://github.com/seeleteam/go-seele/blob/da39efa3ab11c046271a2ce3f1b3854bb2f1584a/p2p/peer.go#L142)):*
> ```
> proto.cap().String()
> ```

proto.cap()

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/193)*

**Comment by boqiu** [comment]
Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/193)*

**Comment by qiaozhigang** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[p2p/peer.go, line 52 at r2](https://reviewable.io/reviews/seeleteam/go-seele/193#-LD5MWr3EtWXZpqA3dWz:-LD5ZjosCmJ_IXlEED4D:bqkjfc4) ([raw file](https://github.com/seeleteam/go-seele/blob/da39efa3ab11c046271a2ce3f1b3854bb2f1584a/p2p/peer.go#L52)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> p.cap().String()
> ```

p.cap() is enough
</blockquote></details>

p.cap() returns a Cap object, should call function String of Cap. 

---

*[p2p/peer.go, line 142 at r2](https://reviewable.io/reviews/seeleteam/go-seele/193#-LD5M_xg-WRCVxw0MXbb:-LD5_3eJ7RcwISf69c9q:bqkjfc4) ([raw file](https://github.com/seeleteam/go-seele/blob/da39efa3ab11c046271a2ce3f1b3854bb2f1584a/p2p/peer.go#L142)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> proto.cap().String()
> ```

proto.cap()
</blockquote></details>

p.cap() returns a Cap object, should call function String of Cap. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/193)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[p2p/peer.go, line 52 at r2](https://reviewable.io/reviews/seeleteam/go-seele/193#-LD5MWr3EtWXZpqA3dWz:-LD5MVz08okCccwp_9Hb:b-6bnxj3) ([raw file](https://github.com/seeleteam/go-seele/blob/da39efa3ab11c046271a2ce3f1b3854bb2f1584a/p2p/peer.go#L52)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

p.cap() returns a Cap object, should call function String of Cap. 
</blockquote></details>

it will call String of Cap automatically in format %s.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/193)*

**Comment by qiaozhigang** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[p2p/peer.go, line 52 at r2](https://reviewable.io/reviews/seeleteam/go-seele/193#-LD5MWr3EtWXZpqA3dWz:-LD6Iywx8ymR_ImMjaG-:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/da39efa3ab11c046271a2ce3f1b3854bb2f1584a/p2p/peer.go#L52)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

it will call String of Cap automatically in format %s.
</blockquote></details>

ok

---

*[p2p/peer.go, line 142 at r2](https://reviewable.io/reviews/seeleteam/go-seele/193#-LD5M_xg-WRCVxw0MXbb:-LD6J1T0D5iD_QYk9jaZ:b32wtd) ([raw file](https://github.com/seeleteam/go-seele/blob/da39efa3ab11c046271a2ce3f1b3854bb2f1584a/p2p/peer.go#L142)):*
<details><summary><i>Previously, qiaozhigang wrote…</i></summary><blockquote>

p.cap() returns a Cap object, should call function String of Cap. 
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/193)*

**Comment by lucusfly** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/193)*

**Pull request merged**
