### PR TITLE
add statedb & ut

### PR DESCRIPTION
**Pull request by jessonzheng**
add a simple statedb implement

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/90)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[core/state/statedb.go, line 41 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/90#-L8BDsbn26uSoyJXN-o0:-L8BDsbn26uSoyJXN-o1:b-83ci16) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L41)):*
> s.trie = trie

do we need to release resource associated with s.trie before assigning new trie for it?

another question, the logic of this function is nearly the same as NewStatedb, just you keep the wrapper pointer s, however, all members of s changed, so why do we need this this function?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/90)*

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[core/state/statedb.go, line 52 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/90#-L8BF8DAD88WrrTfOmhK:-L8BF8DAD88WrrTfOmhL:bt41vcw) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L52)):*
> big.NewInt(0)

nice to define it as constant, one for code clear, another avoiding allocate unnecessary memory.

---

*[core/state/statedb.go, line 59 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/90#-L8BFVb6C60e4qJCqf3F:-L8BFVb6C60e4qJCqf3G:b-gl5zbd) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L59)):*
> amount

check whether amount >= 0

for all following functions, we need to apply such check logic.

---

*[core/state/statedb.go, line 80 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/90#-L8BG4-ZCYnnSYDruATv:-L8BG4-ZCYnnSYDruATw:b2to6ls) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L80)):*
> GetNonce

seems we can add another function to return stateObjects and then caller can extract all members, amount, nonce, etc.) as needed.

---

*[core/state/statedb.go, line 97 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/90#-L8BGROe2oh7My0KHSFR:-L8BGROe2oh7My0KHSFS:bf8ub3v) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L97)):*
> Commit

do we need to make sure thread-safe for this function?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/90)*

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 13 unresolved discussions.

---

*[core/state/statedb.go, line 41 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BDsbn26uSoyJXN-o0:-L8BFFHMSaaZaqncjl1B:b32v57) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L41)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> s.trie = trie

do we need to release resource associated with s.trie before assigning new trie for it?

another question, the logic of this function is nearly the same as NewStatedb, just you keep the wrapper pointer s, however, all members of s changed, so why do we need this this function?
</blockquote></details>

+1

---

*[core/state/statedb.go, line 47 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BFY0IITZF2og48hxb:-L8BFY0IITZF2og48hxc:b-p5delm) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L47)):*
> *big.Int

(*big.Int, bool) is better to indicate the specified address not found.

---

*[core/state/statedb.go, line 80 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BFtZqGSO0FwBhYmxP:-L8BFtZqGSO0FwBhYmxQ:bfi57t6) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L80)):*
> uint64

(uint64, bool)

---

*[core/state/statedb.go, line 115 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BGD9WQBcFjzS2unix:-L8BGD9WQBcFjzS2uniy:b-dpdr5v) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L115)):*
> ```Go
> 	}
> 	object := newStateObject()
> 	val, _ := s.trie.Get(addr[:])
> ```

error handling?

---

*[core/state/statedb.go, line 119 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BGFS7_z8S_rNiEcX1:-L8BGFS7_z8S_rNiEcX2:b-t0hzwl) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L119)):*
> ```Go
> 		object.SetNonce(0)
> 		s.stateObjects[addr] = object
> 		return object
> ```

if len(val) == 0, why not return nil to indicate that the given address not found in trie?

---

*[core/state/statedb.go, line 121 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BH90Eet5Cc2t-kEua:-L8BH90Eet5Cc2t-kEub:bpv9vr0) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L121)):*
> ```Go
> 		return object
> 	}
> 	if err := rlp.DecodeBytes(val, &object.account); err != nil {
> ```

error not handled.

---

*[core/state/statedb.go, line 124 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BHvggLOnxlTVv2JFc:-L8BHvggLOnxlTVv2JFd:b-e1k8sl) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L124)):*
> ```Go
> 		return nil
> 	}
> 	s.stateObjects[addr] = object
> ```

no size limitation? Or will you add RLU here in future?

---

*[core/state/stateobject.go, line 45 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8B9Ufvjaa6vAxVj0ke:-L8B9Ufvjaa6vAxVj0kf:bv963dh) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/stateobject.go#L45)):*
> ```Go
> // GetNonce get nonce of account
> func (s *stateObject) GetAmount() *big.Int {
> 	return s.account.Amount
> ```

return new(big.Int).Set(s.account.Amount) to avoid amount changed outside of stateObject?

---

*[core/state/stateobject.go, line 50 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8B9K890oCzsuSjoOA2:-L8B9K890oCzsuSjoOA3:b-4jpr31) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/stateobject.go#L50)):*
> ```Go
> // SetAmount set amount of account
> func (s *stateObject) SetAmount(amount *big.Int) {
> 	s.account.Amount = amount
> ```

s.account.Amount.Set(amount)  to avoid amount changed outside of stateObject?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/90)*

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 14 unresolved discussions.

---

*[core/state/statedb.go, line 107 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BIjKpqRD1L7B7VZx-:-L8BIjKpqRD1L7B7VZx0:b-4d8kyp) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L107)):*
> ```Go
> 		}
> 	}
> 	return s.trie.Commit(batch)
> ```

set object.dirty to false after trie.commit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/90)*

**Comment by lucusfly** [comment]
Review status: 0 of 3 files reviewed at latest revision, 16 unresolved discussions.

---

*[core/state/statedb.go, line 17 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BRERUExAkhQndgK0G:-L8BRERUExAkhQndgK0H:bo5hnw7) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L17)):*
> accout
account

---

*[core/state/statedb.go, line 20 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BTYUGdIxxZ1gIWQN4:-L8BTYUGdIxxZ1gIWQN5:b4gppso) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L20)):*
> ```Go
> type Statedb struct {
> 	trie         *trie.Trie
> 	stateObjects map[common.Address]*stateObject
> ```

with time going on, stateObjects may get bigger and bigger, thus causes out of memory. Do you need a way to avoid it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/90)*

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 17 unresolved discussions.

---

*[core/state/statedb.go, line 6 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BbGQNvSsXexfQuBNi:-L8BbGQOCbzaiwvHma6q:b-dwq070) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L6)):*
> ```Go
>  */
> 
> package state
> ```

This is a test, @wter to verify the notify function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/90)*

**Comment by jessonzheng** [comment]
Review status: 0 of 3 files reviewed at latest revision, 17 unresolved discussions.

---

*[core/state/statedb.go, line 6 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BbGQNvSsXexfQuBNi:-L8BegqFbL3udjlJh2ED:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L6)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

This is a test, @wter to verify the notify function.
</blockquote></details>

Done.

---

*[core/state/statedb.go, line 17 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BRERUExAkhQndgK0G:-L8BYAAuHQ_cVeamCqmP:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L17)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> accout
account
</blockquote></details>

Done.

---

*[core/state/statedb.go, line 20 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BTYUGdIxxZ1gIWQN4:-L8BYNbBryPbfrsBMuI3:b-t3zix6) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L20)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

with time going on, stateObjects may get bigger and bigger, thus causes out of memory. Do you need a way to avoid it?
</blockquote></details>

Yes. add LRU feature later if needed

---

*[core/state/statedb.go, line 41 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BDsbn26uSoyJXN-o0:-L8BK-GZSe4OEOP6mCoy:b-7xf20b) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L41)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

+1
</blockquote></details>

OK,remove this func

---

*[core/state/statedb.go, line 47 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BFY0IITZF2og48hxb:-L8BdpUZslkdgoZTOsrd:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L47)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

> *big.Int

(*big.Int, bool) is better to indicate the specified address not found.
</blockquote></details>

Done.

---

*[core/state/statedb.go, line 52 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BF8DAD88WrrTfOmhK:-L8BqA6NlRFKTRHYqw-2:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L52)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> big.NewInt(0)

nice to define it as constant, one for code clear, another avoiding allocate unnecessary memory.
</blockquote></details>

Done.

---

*[core/state/statedb.go, line 59 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BFVb6C60e4qJCqf3F:-L8BqtHMpr0ZnGZCoy1d:b-ne1ufn) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L59)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> amount

check whether amount >= 0

for all following functions, we need to apply such check logic.
</blockquote></details>

add check in func (s *StateObject) SetAmount(amount *big.Int)

---

*[core/state/statedb.go, line 80 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BFtZqGSO0FwBhYmxP:-L8BdwM3b4n0VpeFOAeW:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L80)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

> uint64

(uint64, bool)
</blockquote></details>

Done.

---

*[core/state/statedb.go, line 80 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BG4-ZCYnnSYDruATv:-L8BXkHVh3g8T-PlP9eg:bkb9guv) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L80)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> GetNonce

seems we can add another function to return stateObjects and then caller can extract all members, amount, nonce, etc.) as needed.
</blockquote></details>

add func GetOrNewStateObject to return a stateobject

---

*[core/state/statedb.go, line 97 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BGROe2oh7My0KHSFR:-L8BrL0b_A5Na9P5PEZv:b-eqbgn4) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L97)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> Commit

do we need to make sure thread-safe for this function?
</blockquote></details>

let up level make sure thread-safe. add lock later if needed

---

*[core/state/statedb.go, line 107 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BIjKpqRD1L7B7VZx-:-L8BWzT1OxN9fksDghvk:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L107)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

set object.dirty to false after trie.commit
</blockquote></details>

Done.

---

*[core/state/statedb.go, line 115 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BGD9WQBcFjzS2unix:-L8Be02l_lOyIk7RqWrM:bpofyxr) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L115)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

error handling?
</blockquote></details>

not really need. just return nil ,we can't do anything if  error happen

---

*[core/state/statedb.go, line 119 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BGFS7_z8S_rNiEcX1:-L8BX1x2UpzQRYQayO3n:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L119)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

if len(val) == 0, why not return nil to indicate that the given address not found in trie?
</blockquote></details>

Done.

---

*[core/state/statedb.go, line 121 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BH90Eet5Cc2t-kEua:-L8Be_q30k42LZO-bpa_:b-5dwztf) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L121)):*
> not really need. just return nil ,we can't do anything if  error happen

---

*[core/state/statedb.go, line 124 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8BHvggLOnxlTVv2JFc:-L8BKrV7BeLnFw8oJEhP:b4h6zll) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/statedb.go#L124)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

no size limitation? Or will you add RLU here in future?
</blockquote></details>

no size limitation. add LRU feature later if needed

---

*[core/state/stateobject.go, line 45 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8B9Ufvjaa6vAxVj0ke:-L8Bs7v_xtpD2NZNIIi5:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/stateobject.go#L45)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

return new(big.Int).Set(s.account.Amount) to avoid amount changed outside of stateObject?
</blockquote></details>

Done.

---

*[core/state/stateobject.go, line 50 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/90#-L8B9K890oCzsuSjoOA2:-L8BsI8h2gWbljSJAJnT:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/53e0bed23c9810f3e9f12b18bb075891916bb01f/core/state/stateobject.go#L50)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

s.account.Amount.Set(amount)  to avoid amount changed outside of stateObject?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/90)*

**Comment by boqiu** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/90)*

**Pull request merged**
