### PR TITLE
define tx and block types

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/43)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[core/types/block.go, line 4 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6VYxKib-zGPENEz_cr:-L6VYxKib-zGPENEz_cs:b-ximrnh) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L4)):*
> ```Go
> * @file
> * @copyright defined in go-seele/LICENSE
>  */
> ```

add a blank line

---

*[core/types/transaction.go, line 13 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6VZlp1haIKxIYZvTJe:-L6VZlp1haIKxIYZvTJf:b-5vp3wm) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L13)):*
> ```Go
> 	"math/big"
> 
> 	"github.com/ethereum/go-ethereum/rlp"
> ```

please don't use rlp straightly, we have a wrap in common folder

---

*[core/types/transaction.go, line 58 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6Va86oTcXXXUSfgNWr:-L6Va86oTcXXXUSfgNWs:bt7hpzy) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L58)):*
> ```Go
> 
> // rlpEncode encodes the v using RLP and panics on error.
> func rlpEncode(v interface{}) []byte {
> ```

we already have this method in rlpwrapper.go

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/43)*

**Comment by lucusfly** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[core/types/block.go, line 15 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6VmfY503LO78kZAt3v:-L6VmfY503LO78kZAt3w:b-qt8c67) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L15)):*
> BlockHeader
do we need to add uncles?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[core/types/block.go, line 21 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6VpNNECrrosfOjHyKg:-L6VpNNF1uyBUpMGj45S:b-qwxmju) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L21)):*
> CreateTimestamp   *big.Int

why don't you use int? since int is enough for unix time.

and just curious, difficulty and height seems can be int or uint64, why do you use *big.Int?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[core/types/block.go, line 26 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6VqEOTE-7QjR3fAOrZ:-L6VqEOTE-7QjR3fAOr_:b-10mi73) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L26)):*
> Clone

just suggestion, all simple and primary members can be copies by clone:= *header,
you can refine this function to extract the logic of deep copy (2 if statements) into another function.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[core/types/block.go, line 42 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6Vqrrc4zcaxi34WQkv:-L6Vqrrc4zcaxi34WQkw:boogog8) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L42)):*
> HeaderHash   common.Hash
nice to add comments to explain how do you calc this hash? I just wonder if all members in Header will be calculated or just some selected members? 

and will you add hash for transactions?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[core/types/block.go, line 47 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6Vrg2B71XYwCqclMvE:-L6Vrg2B71XYwCqclMvF:b-kraprv) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L47)):*
> is
change to "will be" seems would align with your following "will not"

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[core/types/block.go, line 57 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6VryoB6hkpafkfObUI:-L6VryoB6hkpafkfObUJ:b-5oog6m) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L57)):*
> if len(txs) == 0

do we need to add check whether txs is nil?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[core/types/block.go, line 57 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6VryoB6hkpafkfObUI:-L6Vt5Tl9artrAfygSCi:b-trqyff) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L57)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> if len(txs) == 0

do we need to add check whether txs is nil?
</blockquote></details>

you just init Header and Transactions, but don't init HeaderHash.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[core/types/block.go, line 57 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6VryoB6hkpafkfObUI:-L6VtPrL9Ti-jDLQogzj:b-8x7gc0) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L57)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

you just init Header and Transactions, but don't init HeaderHash.
</blockquote></details>

Never mind, you already initialized the HeaderHash.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[core/types/block.go, line 74 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6VtqDcDiZ3NmpoqSJi:-L6VtqDcDiZ3NmpoqSJj:bp778ag) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L74)):*
> for _, tx := range block.Transactions

add lock would be safe

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[core/types/block_test.go, line 34 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6VuYYf4l-5DFxw2qY3:-L6VuYYf4l-5DFxw2qY4:b-lfszk8) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block_test.go#L34)):*
> header.Nonce = 2

nice to add set and check logic for Difficulty

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[core/types/transaction.go, line 27 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6VxWVh0bHfA01MmDoM:-L6VxWVh0bHfA01MmDoN:beq25gz) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L27)):*
> TransactionData

just for discussion, we need to support 1:N even M:N transactions in future, so we may make this struct more elastic to meet that requirement.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[core/types/transaction.go, line 29 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6Vy4_H7ib8Ii9aGe9Q:-L6Vy4_H7ib8Ii9aGe9R:bikpsa2) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L29)):*
> To           *common.Address
why use * for To but From without *?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[core/types/transaction.go, line 43 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6VyT363eGElp3PIKWM:-L6VyT363eGElp3PIKWN:b-4z36rd) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L43)):*
> NewTransaction

just curious, there is Clone method in BlockHeader, why not for NewTransaction?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[core/types/transaction.go, line 69 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6Vz0VF8jhJHxtZ26ao:-L6Vz0VF8jhJHxtZ26ap:b-b1mvtd) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L69)):*
>  rlpEncode(tx.Data)

tx.Data is just a pointer, I just wonder if rlpEncode will dig into it?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[core/types/transaction.go, line 79 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6VzKTf3LTwYxC5az0C:-L6VzKTf3LTwYxC5az0D:b-o4c8e1) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L79)):*
> if tx.Signature == nil

add check for tx == nil?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[core/types/transaction.go, line 89 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6Vz_6u7gFhkC74yxW9:-L6Vz_6u7gFhkC74yxWA:bx8cybu) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L89)):*
> if !tx.Signature.Verify(txDataHash) 

Just throw thought, if crypto.Keccak256Hash and Signature.Verify are time-consuming, we can do these check parallelly

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[core/types/transaction_test.go, line 20 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6W-6Fo14RKctOZsPbq:-L6W-6Fo14RKctOZsPbr:b8p7gg3) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction_test.go#L20)):*
> t.Errorf

missing return? I think we should return immediately for this error case.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[core/types/block.go, line 15 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6VmfY503LO78kZAt3v:-L6VzyKFh86V3GKGoXxE:ba729dl) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L15)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> BlockHeader
do we need to add uncles?
</blockquote></details>

Uncles is not MUST, so not included in this commit. In future, we may add it for better incentive.

---

*[core/types/block.go, line 21 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6VpNNECrrosfOjHyKg:-L6W1rXaxA4JYNFVTbiD:bbph0pk) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L21)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> CreateTimestamp   *big.Int

why don't you use int? since int is enough for unix time.

and just curious, difficulty and height seems can be int or uint64, why do you use *big.Int?
</blockquote></details>

Go system lib use int64 for unix time, but RLP cannot encode int64. So, here just followed the ETH to use bit.int.

---

*[core/types/block.go, line 26 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6VqEOTE-7QjR3fAOrZ:-L6W3uBehXIPIHcC_pdp:buz9trd) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L26)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> Clone

just suggestion, all simple and primary members can be copies by clone:= *header,
you can refine this function to extract the logic of deep copy (2 if statements) into another function.
</blockquote></details>

Unnecessary, clone is a atomic semantics.

---

*[core/types/block.go, line 42 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6Vqrrc4zcaxi34WQkv:-L6W4QZzipOJbSH2Fp1l:b-f41s0k) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L42)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> HeaderHash   common.Hash
nice to add comments to explain how do you calc this hash? I just wonder if all members in Header will be calculated or just some selected members? 

and will you add hash for transactions?
</blockquote></details>

1. Will add necessary comment for the HeaderHash property.
2. This hash is calculated based on the RLP encoded header bytes. As for transactions, their hash is calculated based on merkle tree, and the root hash resides in block header.

---

*[core/types/block.go, line 47 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6Vrg2B71XYwCqclMvE:-L6W5MGbWWJyF8khbPPv:bd51o2v) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L47)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> is
change to "will be" seems would align with your following "will not"
</blockquote></details>

No, "is" means do it in this method. Any change happens after this method, so use "will".

---

*[core/types/block.go, line 57 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6VryoB6hkpafkfObUI:-L6W5s67FtFUy11Oolat:b-jpsz6v) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L57)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

Never mind, you already initialized the HeaderHash.
</blockquote></details>

txs is not nil all the time, but of length 0.

---

*[core/types/block.go, line 74 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6VtqDcDiZ3NmpoqSJi:-L6W696psyEhVu8WWpuD:bxh09oo) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L74)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> for _, tx := range block.Transactions

add lock would be safe
</blockquote></details>

Any explicit scenario that will add/delete/update the txs array? This method come from ETH code, so I did not make it thread-safe. Anyway, I will add a comment to figure out that this is a non-thread-safe method. Once, thread-safe required in future, will change it.

---

*[core/types/block_test.go, line 34 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6VuYYf4l-5DFxw2qY3:-L6W7BwUgCwgbX_C46pS:bfo0e82) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block_test.go#L34)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> header.Nonce = 2

nice to add set and check logic for Difficulty
</blockquote></details>

Good suggestion, will test all members in header.

---

*[core/types/transaction.go, line 13 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6VZlp1haIKxIYZvTJe:-L6W7KTPb4zPieelZN4F:b-p9gujz) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L13)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

please don't use rlp straightly, we have a wrap in common folder
</blockquote></details>

thx to figure out the common method.

---

*[core/types/transaction.go, line 27 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6VxWVh0bHfA01MmDoM:-L6W7VXn_dmR7xqXK_uo:b-xl48nr) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L27)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> TransactionData

just for discussion, we need to support 1:N even M:N transactions in future, so we may make this struct more elastic to meet that requirement.
</blockquote></details>

Haha, you're right. But now it is enough at this iteration. Note, over-design is time consuming.

---

*[core/types/transaction.go, line 29 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6Vy4_H7ib8Ii9aGe9Q:-L6W7n1KklQyLCurgK3R:b5o05og) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L29)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> To           *common.Address
why use * for To but From without *?
</blockquote></details>

As comment said, to address is empty when create a contract.

---

*[core/types/transaction.go, line 43 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6VyT363eGElp3PIKWM:-L6W7yzVr5_-CGwM9c62:bdaqq25) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L43)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> NewTransaction

just curious, there is Clone method in BlockHeader, why not for NewTransaction?
</blockquote></details>

Clone is used when the input parameter is a struct. Here is not the case.

---

*[core/types/transaction.go, line 58 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6Va86oTcXXXUSfgNWr:-L6W8Dni6lqIS5l0naDb:b-5drzni) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L58)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

we already have this method in rlpwrapper.go
</blockquote></details>

thx to figure out common method.

---

*[core/types/transaction.go, line 69 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6Vz0VF8jhJHxtZ26ao:-L6W8Jk4DZelkIlewYra:b-pabw98) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L69)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

>  rlpEncode(tx.Data)

tx.Data is just a pointer, I just wonder if rlpEncode will dig into it?
</blockquote></details>

changed to use common method, it works fine as UT proves.

---

*[core/types/transaction.go, line 79 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6VzKTf3LTwYxC5az0C:-L6W8QLmVYxqr1Wre_a5:b-cw1dbw) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L79)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> if tx.Signature == nil

add check for tx == nil?
</blockquote></details>

Haha, Will you check if "this" is null pointer in C# method? 

---

*[core/types/transaction.go, line 89 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6Vz_6u7gFhkC74yxW9:-L6W8svIjtiXNiN1__SZ:bf9erh5) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L89)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> if !tx.Signature.Verify(txDataHash) 

Just throw thought, if crypto.Keccak256Hash and Signature.Verify are time-consuming, we can do these check parallelly
</blockquote></details>

this is serial logic, parallel is not allowed. 

---

*[core/types/transaction_test.go, line 20 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6W-6Fo14RKctOZsPbq:-L6W9099cEpGbLBEbJGA:b3ks2) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction_test.go#L20)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> t.Errorf

missing return? I think we should return immediately for this error case.
</blockquote></details>

W

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[core/types/transaction.go, line 79 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6VzKTf3LTwYxC5az0C:-L6WcOOP5yKpu7ZSIa-k:brblw90) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L79)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Haha, Will you check if "this" is null pointer in C# method? 
</blockquote></details>

nice, got it:)

---

*[core/types/transaction.go, line 89 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6Vz_6u7gFhkC74yxW9:-L6WcaN9D1MMhDjS7Dds:b-tatwal) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L89)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

this is serial logic, parallel is not allowed. 
</blockquote></details>

Never mind.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[core/types/transaction.go, line 18 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6X3dvU5vQFsinkyovy:-L6X3dvU5vQFsinkyovz:bse75xp) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L18)):*
> var
mice to create a single file for these errors.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[core/types/transaction.go, line 18 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/43#-L6X3dvU5vQFsinkyovy:-L6XDto57THKO1Jzt1iv:b-sl1o1n) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L18)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> var
mice to create a single file for these errors.
</blockquote></details>

Only common errors could be defined in a single file under pkg "common". But, these are specific errors about transaction, so transaction.go file is the right place for definition.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by boqiu** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[core/types/block.go, line 4 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6VYxKib-zGPENEz_cr:-L6XJpUpTvKXzNVkg3gr:b-b5c35t) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/block.go#L4)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

add a blank line
</blockquote></details>

changed.

---

*[core/types/transaction.go, line 79 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6VzKTf3LTwYxC5az0C:-L6XO79FzsAbspPZHubG:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L79)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

nice, got it:)
</blockquote></details>

Done.

---

*[core/types/transaction.go, line 89 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/43#-L6Vz_6u7gFhkC74yxW9:-L6XOAqN_QUZ7XsolQxo:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/535bd6609f3d84746b69e74c6bac505d4b39218a/core/types/transaction.go#L89)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

Never mind.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/43)*

**Comment by lucusfly** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/43)*

**Comment by lucusfly** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Comment by WTer** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/43)*

**Pull request merged**
