### PR TITLE
client add get account shard number

### PR DESCRIPTION
**Pull request by ypenghui6**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/320)

### CODE REVIEW

**Comment by lucusfly** [comment]
Review status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ypenghui6, @WTer, @boqiu, and @lucusfly)

---

*[cmd/util/getAccountShardNum.go, line 19 at r1](https://reviewable.io/reviews/seeleteam/go-seele/320#-LFtnXmz5TgKLzDJSjO2:-LFtnXmz5TgKLzDJSjO3:bqf79p5) ([raw file](https://github.com/seeleteam/go-seele/blob/08a5f20e0a486f6d055224b4a3c74187e3bd3403/cmd/util/getAccountShardNum.go#L19)):*
> ```
> getAccountShardNum
> ```

use lower case command

---

*[cmd/util/getAccountShardNum.go, line 32 at r1](https://reviewable.io/reviews/seeleteam/go-seele/320#-LFtoYtiCP-sNOP8blmz:-LFtoYtj2WJfZZfKNf1u:b8o43h6) ([raw file](https://github.com/seeleteam/go-seele/blob/08a5f20e0a486f6d055224b4a3c74187e3bd3403/cmd/util/getAccountShardNum.go#L32)):*
> ```
> HexMustToAddres
> ```

use HexToAddress and get error from return value. recover is not suggested way to handle error.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/320)*

**Comment by boqiu** [comment]
Review status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @ypenghui6, @WTer, @boqiu, and @lucusfly)

---

*[cmd/util/getAccountShardNum.go, line 15 at r1](https://reviewable.io/reviews/seeleteam/go-seele/320#-LFtoZC26ufIUm1h6N-e:-LFtoZC26ufIUm1h6N-f:brbex4t) ([raw file](https://github.com/seeleteam/go-seele/blob/08a5f20e0a486f6d055224b4a3c74187e3bd3403/cmd/util/getAccountShardNum.go#L15)):*
> ```Go
> 
> // GetAccountShardNumCmd represents the get account shard number command
> func GetAccountShardNumCmd() (cmds *cobra.Command) {
> ```

No parameter to retrieve account shard number, why not define a var for the getAccountShardNumCmd, as what did for other commands.

---

*[cmd/util/getAccountShardNum.go, line 20 at r1](https://reviewable.io/reviews/seeleteam/go-seele/320#-LFtonjh6kwIB82Fq3nj:-LFtonjh6kwIB82Fq3nk:bqqm3jh) ([raw file](https://github.com/seeleteam/go-seele/blob/08a5f20e0a486f6d055224b4a3c74187e3bd3403/cmd/util/getAccountShardNum.go#L20)):*
> ```Go
> 	var getAccountShardNumCmd = &cobra.Command{
> 		Use:   "getAccountShardNum",
> 		Short: "getAccountShardNum account with specified account",
> ```

get account shard number

---

*[cmd/util/getAccountShardNum.go, line 21 at r1](https://reviewable.io/reviews/seeleteam/go-seele/320#-LFtosdk8HKpy2S_N-Gf:-LFtosdk8HKpy2S_N-Gg:bqqm3jh) ([raw file](https://github.com/seeleteam/go-seele/blob/08a5f20e0a486f6d055224b4a3c74187e3bd3403/cmd/util/getAccountShardNum.go#L21)):*
> ```Go
> 		Use:   "getAccountShardNum",
> 		Short: "getAccountShardNum account with specified account",
> 		Long:  `getAccountShardNum account with specified account
> ```

get account shard number

---

*[cmd/util/getAccountShardNum.go, line 35 at r1](https://reviewable.io/reviews/seeleteam/go-seele/320#-LFtp6Nd9_ynORN2pvaM:-LFtp6Nd9_ynORN2pvaN:bll6jd9) ([raw file](https://github.com/seeleteam/go-seele/blob/08a5f20e0a486f6d055224b4a3c74187e3bd3403/cmd/util/getAccountShardNum.go#L35)):*
> ```Go
> 			shard := accountAddress.Shard()
> 
> 			fmt.Printf("shard number:  %d\n", shard)
> ```

1 whitespace is enough, here seems 2 whitespaces used.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/320)*

**Comment by boqiu** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 6 unresolved discussions (waiting on @ypenghui6 and @WTer)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/320)*

**Comment by lucusfly** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 6 unresolved discussions (waiting on @ypenghui6 and @WTer)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/320)*

**Comment by lucusfly** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed, 4 unresolved discussions (waiting on @boqiu and @WTer)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/320)*

**Comment by boqiu** [comment]
Reviewed 2 of 3 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WTer)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/320)*

**Pull request merged**
