### PR TITLE
add findAncestor

### PR DESCRIPTION
**Pull request by gongliaoan**
add find ancestor

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/108)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[seele/download/downloader.go, line 189 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9cSrgS4BJK51NZHgrM:-L9cSrgS4BJK51NZHgrN:bh8s07v) ([raw file](https://github.com/seeleteam/go-seele/blob/71bd0141425f57448af07b7860e467b302e09ee6/seele/download/downloader.go#L189)):*
> ```Go
> 
> // findAncestor finds the common ancestor
> func (d *Downloader) findAncestor(conn *peerConn, height uint64) (uint64, error) {
> ```

suggest to add necessary UT.

---

*[seele/download/downloader.go, line 227 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9cS_tA0g3gaMXKp7Rk:-L9cS_tA0g3gaMXKp7Rl:b-9qbujr) ([raw file](https://github.com/seeleteam/go-seele/blob/71bd0141425f57448af07b7860e467b302e09ee6/seele/download/downloader.go#L227)):*
> ```Go
> 			cmpCount++
> 			if cmpCount > MaxForkAncestry {
> 				return 0, errInvalidAncestor
> ```

A meaningful error name is appreciated, e.g. errMaxForkAncestor

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/108)*

**Comment by gongliaoan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[seele/download/downloader.go, line 227 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9cS_tA0g3gaMXKp7Rk:-L9cUtc0Bei7D_EkewQW:bb6un1j) ([raw file](https://github.com/seeleteam/go-seele/blob/71bd0141425f57448af07b7860e467b302e09ee6/seele/download/downloader.go#L227)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

A meaningful error name is appreciated, e.g. errMaxForkAncestor
</blockquote></details>

Done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/108)*

**Comment by lucusfly** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[seele/download/downloader.go, line 190 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9cua-P321fpIEfCV7y:-L9cua-P321fpIEfCV7z:b6vbf3u) ([raw file](https://github.com/seeleteam/go-seele/blob/e1efb54f2ef55167d8267b2eaea11d47a3037453/seele/download/downloader.go#L190)):*
> ```
> findAncestor
> ```
Better rename to findCommonAncestorHeight

---

*[seele/download/downloader.go, line 216 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9cshSvD0q0TXGuQNmH:-L9cshSvD0q0TXGuQNmI:b-x79tde) ([raw file](https://github.com/seeleteam/go-seele/blob/e1efb54f2ef55167d8267b2eaea11d47a3037453/seele/download/downloader.go#L216)):*
> ```
> common.Hash{}
> ```
common.EmptyHash

---

*[seele/download/downloader.go, line 217 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9ctCGv9Y5aYN48xK29:-L9ctCGv9Y5aYN48xK2A:b-o5n2ua) ([raw file](https://github.com/seeleteam/go-seele/blob/e1efb54f2ef55167d8267b2eaea11d47a3037453/seele/download/downloader.go#L217)):*
> ```Go
> 		// Get peer block headers
> 		go conn.peer.RequestHeadersByHashOrNumber(common.Hash{}, localTop, fetchCount, true)
> 		msg, err := conn.waitMsg(BlockHeadersMsg, d.cancelCh)
> ```

Here will not get the message you want. because peer has a loop to get message.

---

*[seele/download/downloader.go, line 233 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9cuHoo1ntnVCoA5NkZ:-L9cuHoo1ntnVCoA5Nk_:b4ugkxq) ([raw file](https://github.com/seeleteam/go-seele/blob/e1efb54f2ef55167d8267b2eaea11d47a3037453/seele/download/downloader.go#L233)):*
> ```Go
> 
> 		// Is ancenstor found
> 		for i := 0; i < len(headers); i++ {
> ```

if headers's height is increase. you need revert iterate headers.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/108)*

**Comment by gongliaoan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[seele/download/downloader.go, line 44 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9cVamCEfQ7InZzaT8S:-L9cu0dR7zTQI9CKCKkX:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a9a6b7310354c8b6f2d57263df4cfc2b9528ebae/seele/download/downloader.go#L44)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> errInvalidAncestor
> ```
sort all these errors in alphabetical order.
</blockquote></details>

Done.

---

*[seele/download/downloader.go, line 242 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9cqUBJAbF9wBn9iea0:-L9cuv_T0bUfWJv7W7aV:bwvmpoh) ([raw file](https://github.com/seeleteam/go-seele/blob/a9a6b7310354c8b6f2d57263df4cfc2b9528ebae/seele/download/downloader.go#L242)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> }
> ```
no default return?
</blockquote></details>

The return is in for loop, default return is unreachable 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/108)*

**Comment by qiaozhigang** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/108)*

**Comment by gongliaoan** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[seele/download/downloader.go, line 189 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9cSrgS4BJK51NZHgrM:-L9dIPYDBxUAiaStF-D4:b1m3u43) ([raw file](https://github.com/seeleteam/go-seele/blob/71bd0141425f57448af07b7860e467b302e09ee6/seele/download/downloader.go#L189)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

+1
</blockquote></details>

This is func need peer network to test, so not add UT 

---

*[seele/download/downloader.go, line 190 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9cua-P321fpIEfCV7y:-L9cw-e5EkRVONqOFkUO:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e1efb54f2ef55167d8267b2eaea11d47a3037453/seele/download/downloader.go#L190)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> findAncestor
> ```
Better rename to findCommonAncestorHeight
</blockquote></details>

Done.

---

*[seele/download/downloader.go, line 216 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9cshSvD0q0TXGuQNmH:-L9cvm6v7wtYkjusyZhz:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/e1efb54f2ef55167d8267b2eaea11d47a3037453/seele/download/downloader.go#L216)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> common.Hash{}
> ```
common.EmptyHash
</blockquote></details>

Done.

---

*[seele/download/downloader.go, line 217 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9ctCGv9Y5aYN48xK29:-L9dCC4N3tCZnnGslAjD:bfuys4e) ([raw file](https://github.com/seeleteam/go-seele/blob/e1efb54f2ef55167d8267b2eaea11d47a3037453/seele/download/downloader.go#L217)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

Here will not get the message you want. because peer has a loop to get message.
</blockquote></details>

here can get the message, request is send in RequestHeadersByHashOrNumber and call deliverMsg

---

*[seele/download/downloader.go, line 233 at r3](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9cuHoo1ntnVCoA5NkZ:-L9dENPg7nCVK0JsII-R:b-ctv6jn) ([raw file](https://github.com/seeleteam/go-seele/blob/e1efb54f2ef55167d8267b2eaea11d47a3037453/seele/download/downloader.go#L233)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

if headers's height is increase. you need revert iterate headers.
</blockquote></details>

Done. headers is decrease by height.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/108)*

**Comment by gongliaoan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[seele/download/downloader.go, line 44 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9cVamCEfQ7InZzaT8S:-L9dPFyb3q2TLo7_Wjw1:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a9a6b7310354c8b6f2d57263df4cfc2b9528ebae/seele/download/downloader.go#L44)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/108)*

**Comment by WTer** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[seele/download/downloader.go, line 189 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9cSrgS4BJK51NZHgrM:-L9dWduABi_CF87Q93YN:b-6o2s4u) ([raw file](https://github.com/seeleteam/go-seele/blob/71bd0141425f57448af07b7860e467b302e09ee6/seele/download/downloader.go#L189)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

This is func need peer network to test, so not add UT 
</blockquote></details>

you can just extract non-network logic part from this function and add unit test for it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/108)*

**Comment by qiaozhigang** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/108)*

**Comment by lucusfly** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/108)*

**Comment by gongliaoan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[seele/download/downloader.go, line 189 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9cSrgS4BJK51NZHgrM:-L9hFIpx9wFLJ2l45353:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/71bd0141425f57448af07b7860e467b302e09ee6/seele/download/downloader.go#L189)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

you can just extract non-network logic part from this function and add unit test for it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/108)*

**Comment by boqiu** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/108)*

**Comment by WTer** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[seele/download/downloader_test.go, line 150 at r6](https://beta.reviewable.io/reviews/seeleteam/go-seele/108#-L9hYVpT9MpMwA7kjajf:-L9hYVpT9MpMwA7kjajg:b3v5bpi) ([raw file](https://github.com/seeleteam/go-seele/blob/ee1ccd3d12e3765f3a55878a1f594d1712da2d8d/seele/download/downloader_test.go#L150)):*
> ```
> Test_findCommonAncestorHeight_errMaxForkAncestor
> ```
nice to add more test methods to cover most of your logic added in this change,
such as errInvalidAncestor, also including the normal cases.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/108)*

**Comment by WTer** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/108)*

**Pull request merged**
