### PR TITLE
add four rpc&cmd for block and tx pool

### PR DESCRIPTION
**Pull request by wuliaodw88**
GetBlockRlp retrieves the RLP encoded for of a single block by block height,
PrintBlock retrieves a block and returns its pretty printed form by block height,
GetTxPoolContent returns the transactions contained within the transaction pool,
GetTxPoolStatus returns the number of transaction in the pool.

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/154)

### CODE REVIEW

**Comment by lucusfly** [comment]
Please use a new branch to start a new review. there are too many stale commits in your PR.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[cmd/client/cmd/printblock.go, line 19 at r1](https://reviewable.io/reviews/seeleteam/go-seele/154#-LC1fUIxCF-8v5N6Q8_X:-LC1fUIxCF-8v5N6Q8_Y:bentabk) ([raw file](https://github.com/seeleteam/go-seele/blob/f3007bce3c5df0154273d0677e0d35633f77fb6d/cmd/client/cmd/printblock.go#L19)):*
> ```Go
> // printblockCmd represents the print block  command
> var printblockCmd = &cobra.Command{
> 	Use:   "printblock",
> ```

getblockByHeight is better

---

*[core/tx_pool.go, line 128 at r1](https://reviewable.io/reviews/seeleteam/go-seele/154#-LC1fz4lEIt0zlG1El8F:-LC1fz4lEIt0zlG1El8G:bib65du) ([raw file](https://github.com/seeleteam/go-seele/blob/f3007bce3c5df0154273d0677e0d35633f77fb6d/core/tx_pool.go#L128)):*
> ```
>  GetProcessableStatus
> ```

GetProcessableTransactionsCount()

---

*[seele/api.go, line 11 at r1](https://reviewable.io/reviews/seeleteam/go-seele/154#-LC1gDFZ4CK4HrzZWyCZ:-LC1gDFZ4CK4HrzZWyC_:b-jy64oy) ([raw file](https://github.com/seeleteam/go-seele/blob/f3007bce3c5df0154273d0677e0d35633f77fb6d/seele/api.go#L11)):*
> ```Go
> 	"math/big"
> 
> 	"github.com/davecgh/go-spew/spew"
> ```

new package?

---

*[seele/api.go, line 130 at r1](https://reviewable.io/reviews/seeleteam/go-seele/154#-LC1gYoEDrrUXA4pZJG6:-LC1gYoEDrrUXA4pZJG7:b-km0nr8) ([raw file](https://github.com/seeleteam/go-seele/blob/f3007bce3c5df0154273d0677e0d35633f77fb6d/seele/api.go#L130)):*
> ```
> spew.Sdump(block)
> ```

what's different from rpcOutputBlock?

---

*[seele/api.go, line 200 at r1](https://reviewable.io/reviews/seeleteam/go-seele/154#-LC1hPYv-_xfnc4k01GJ:-LC1hPYv-_xfnc4k01GK:b-a7kqvl) ([raw file](https://github.com/seeleteam/go-seele/blob/f3007bce3c5df0154273d0677e0d35633f77fb6d/seele/api.go#L200)):*
> ```
> rpcOutputTx(tx)
> ```

why not use tx straight?

---

*[seele/api.go, line 225 at r1](https://reviewable.io/reviews/seeleteam/go-seele/154#-LC1gySxAlvgUE3cwC2R:-LC1gySxAlvgUE3cwC2S:b-lo53oy) ([raw file](https://github.com/seeleteam/go-seele/blob/f3007bce3c5df0154273d0677e0d35633f77fb6d/seele/api.go#L225)):*
> ```
> result *map[string][]map[string]interface{}
> ```

why not use map[string]types.Transaction?

---

*[seele/api.go, line 243 at r1](https://reviewable.io/reviews/seeleteam/go-seele/154#-LC1hrei1n6rgEzKFxow:-LC1hrei1n6rgEzKFxox:bikiohk) ([raw file](https://github.com/seeleteam/go-seele/blob/f3007bce3c5df0154273d0677e0d35633f77fb6d/seele/api.go#L243)):*
> ```
> GetTxPoolStatus
> ```

actually it is count info, why not just call it GetTxPoolTXCount?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/154#-:-LC1cH2M3OJyYG-1dEkJ:bvtubrt)*

**Comment by wuliaodw88** [comment]
ok,i will use a new branch the next time

---

Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[cmd/client/cmd/printblock.go, line 19 at r1](https://reviewable.io/reviews/seeleteam/go-seele/154#-LC1fUIxCF-8v5N6Q8_X:-LC1kfPg-5wzUSPMfRbj:b-x30zfe) ([raw file](https://github.com/seeleteam/go-seele/blob/f3007bce3c5df0154273d0677e0d35633f77fb6d/cmd/client/cmd/printblock.go#L19)):*
> getblockByHeight 
getblockByHeight has already existed，and it will print a rpcblock. printblock can get all content in one block and print by go-spew

---

*[core/tx_pool.go, line 128 at r1](https://reviewable.io/reviews/seeleteam/go-seele/154#-LC1fz4lEIt0zlG1El8F:-LC31yraAxqBRjk1cFTM:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f3007bce3c5df0154273d0677e0d35633f77fb6d/core/tx_pool.go#L128)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about rename to GetStatus() and return multiple data or a struct that including some other info about tx pool.
</blockquote></details>

Done.

---

*[seele/api.go, line 11 at r1](https://reviewable.io/reviews/seeleteam/go-seele/154#-LC1gDFZ4CK4HrzZWyCZ:-LC1m1ng1ox7C_o6QDCb:bmb418c) ([raw file](https://github.com/seeleteam/go-seele/blob/f3007bce3c5df0154273d0677e0d35633f77fb6d/seele/api.go#L11)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

new package?
</blockquote></details>

no,it has already existed in vendor

---

*[seele/api.go, line 130 at r1](https://reviewable.io/reviews/seeleteam/go-seele/154#-LC1gYoEDrrUXA4pZJG6:-LC320Ag1QS3BTAhBSZ9:bxjgr5g) ([raw file](https://github.com/seeleteam/go-seele/blob/f3007bce3c5df0154273d0677e0d35633f77fb6d/seele/api.go#L130)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> spew.Sdump(block)
> ```

what's different from rpcOutputBlock?
</blockquote></details>

for debug or for public

---

*[seele/api.go, line 200 at r1](https://reviewable.io/reviews/seeleteam/go-seele/154#-LC1hPYv-_xfnc4k01GJ:-LC324_P1QKNqrbSZGlW:b-4r87mj) ([raw file](https://github.com/seeleteam/go-seele/blob/f3007bce3c5df0154273d0677e0d35633f77fb6d/seele/api.go#L200)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> rpcOutputTx(tx)
> ```

why not use tx straight?
</blockquote></details>

for public

---

*[seele/api.go, line 243 at r1](https://reviewable.io/reviews/seeleteam/go-seele/154#-LC1hrei1n6rgEzKFxow:-LC327pQ8Sp9DeEx3Nyq:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f3007bce3c5df0154273d0677e0d35633f77fb6d/seele/api.go#L243)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> GetTxPoolStatus
> ```

actually it is count info, why not just call it GetTxPoolTXCount?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/154#-:-LC1kLCKEeOgIkPckOqC:b594f4h)*

**Comment by lucusfly** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[seele/api.go, line 225 at r1](https://reviewable.io/reviews/seeleteam/go-seele/154#-LC1gySxAlvgUE3cwC2R:-LC37uiLBlduuXEiHEnJ:b-1k8vrw) ([raw file](https://github.com/seeleteam/go-seele/blob/f3007bce3c5df0154273d0677e0d35633f77fb6d/seele/api.go#L225)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> result *map[string][]map[string]interface{}
> ```

why not use map[string]types.Transaction?
</blockquote></details>

no fix?

---

*[seele/api.go, line 143 at r2](https://reviewable.io/reviews/seeleteam/go-seele/154#-LC37X7oCV7pPmCWoWAI:-LC37X7oCV7pPmCWoWAJ:b28dq4v) ([raw file](https://github.com/seeleteam/go-seele/blob/225afeb84346dff03ea545bfe4c1bcc3be593216/seele/api.go#L143)):*
> ```Go
> }
> 
> // PublicDebugAPI provides an API to access full node-related information for debug.
> ```

please move debug api to a new file

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/154)*

**Comment by wuliaodw88** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[seele/api.go, line 225 at r1](https://reviewable.io/reviews/seeleteam/go-seele/154#-LC1gySxAlvgUE3cwC2R:-LC3GoZD9DpAJc-mB9Sy:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f3007bce3c5df0154273d0677e0d35633f77fb6d/seele/api.go#L225)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

no fix?
</blockquote></details>

Done.

---

*[seele/api.go, line 143 at r2](https://reviewable.io/reviews/seeleteam/go-seele/154#-LC37X7oCV7pPmCWoWAI:-LC3Gnnf6HDaBesGn3Wp:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/225afeb84346dff03ea545bfe4c1bcc3be593216/seele/api.go#L143)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

please move debug api to a new file
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/154)*

**Comment by boqiu** [comment]
Reviewed 9 of 11 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/154)*

**Comment by lucusfly** [comment]
Reviewed 8 of 11 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/154)*

**Pull request merged**
