### PR TITLE
add event module

### PR DESCRIPTION
**Pull request by lucusfly**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/56)

### CODE REVIEW

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[event/dispatcher_test.go, line 24 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oI77GFpwUJ6y0S1Xs:-L6oI77He8mBTnmWiIqt:bjc0ay6) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher_test.go#L24)):*
> handler.AddListener(listener1) //test duplicate add

do we need to add a function .Count() for handler and check for duplicated add here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/56)*

**Comment by WTer** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/56)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[event/dispatcher.go, line 14 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oM09ZJvXN-oMrmuMz:-L6oM09ZJvXN-oMrmuN-:b-5dghp2) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L14)):*
> ```Go
> 
> // EventHandler interface defines the event handler behavior
> type EventHandler struct {
> ```

1) Figure out it is thread-safe in comment.
2) In my mind, EventHandler is a handler to handle event, and cannot to fire event. Usually, the API is as following:
    Event.Fire()
    Event.AddEventHandler

If you want to design a common event model (for different kinds of events), then how about rename EventHandler to EventManager or EventBus?

On the other hand, the Listener below looks like a "EventHandler". Anyway, Listener is ok as well.

---

*[event/dispatcher.go, line 25 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oNJtwUMTlt_INcNrK:-L6oNJtwUMTlt_INcNrL:b-x93vtg) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L25)):*
> ```Go
> 	defer h.lock.RUnlock()
> 	for _, l := range h.listeners {
> 		go l.Callable(e)
> ```

Better to add necessary comment to figure out that listeners handle event in go-routine.

---

*[event/dispatcher.go, line 36 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oLeg3l14ij1J41u3A:-L6oLeg3l14ij1J41u3B:b-9dlnza) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L36)):*
> ```Go
> 	}
> 
> 	h.lock.Lock()
> ```

Lock() at the beginning of this method, or listener may be added twice in different threads.

---

*[event/dispatcher.go, line 48 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oNaaWSqKbUMUWS4Wl:-L6oNaaWSqKbUMUWS4Wm:b-sigw0) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L48)):*
> ```Go
> 	}
> 
> 	h.lock.Lock()
> ```

Move Lock() to the beginning of this method, or it will not be thread safe.

---

*[event/dispatcher.go, line 55 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oOochg167eVUUqIrY:-L6oOochg167eVUUqIrZ:byedwsx) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L55)):*
> ```Go
> // find find listener already in the handler
> // return -1 not found, otherwise return the index of the listener
> func (h *EventHandler) find(listener Listener) int {
> ```

I see that you handle the event in different go-routine. So, the order of listeners is not important, why not use map for better add/remove/get perf?

---

*[event/dispatcher.go, line 61 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oODeNMZsjIrSq8BNr:-L6oODeNMZsjIrSq8BNs:bushcqn) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L61)):*
> ```Go
> 	defer h.lock.RUnlock()
> 	for i, l := range h.listeners {
> 		lp := reflect.ValueOf(l.Callable).Pointer()
> ```

As far as I know, interface (Listener) is pointer type, so it is unnecessary to use reflect to get the pointer value.

---

*[event/event.go, line 18 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oJtLCzKwiUIQHq-L_:-L6oJtLCzKwiUIQHq-La:b-m71zfc) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/event.go#L18)):*
> //Callable
Whitespace

---

*[event/event.go, line 19 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oKPzSPzfiBncxMiWl:-L6oKPzSPzfiBncxMiWm:b2zkhbh) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/event.go#L19)):*
> ```Go
> type Listener struct {
> 	//Callable call function
> 	Callable func(e Event)
> ```

Callable EventHandleMethod or just remove the type declaration of EventHandleMethod?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/56)*

**Comment by Sandratechy** [comment]
This project is the recommendation if users still confuse to invest their money! Good project... it looks very promising when i saw full details of this project from https://icoguide.com/en/ico/seele

**Comment by jessonzheng** [comment]
2 suggestions
1、should have singleton shared dispatcher for all modules call
2、see any events will fire all listening function whether they need this event 

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-:-L6p7ZRV8wu5UX5Vzsu1:bf3xibd)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[event/dispatcher.go, line 14 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oM09ZJvXN-oMrmuMz:-L6pFUxRKEEgY59-xBg1:byhvnup) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L14)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

1) Figure out it is thread-safe in comment.
2) In my mind, EventHandler is a handler to handle event, and cannot to fire event. Usually, the API is as following:
    Event.Fire()
    Event.AddEventHandler

If you want to design a common event model (for different kinds of events), then how about rename EventHandler to EventManager or EventBus?

On the other hand, the Listener below looks like a "EventHandler". Anyway, Listener is ok as well.
</blockquote></details>

refactor to EventManager 

---

*[event/dispatcher.go, line 25 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oNJtwUMTlt_INcNrK:-L6pFRM3yMSdIO76iyHr:burs0ww) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L25)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Better to add necessary comment to figure out that listeners handle event in go-routine.
</blockquote></details>

typo, remove go-routine call

---

*[event/dispatcher.go, line 36 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oLeg3l14ij1J41u3A:-L6pCsdW15N1W5jmzOrW:b-x47ls6) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L36)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Lock() at the beginning of this method, or listener may be added twice in different threads.
</blockquote></details>

find() already has lock

---

*[event/dispatcher.go, line 48 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oNaaWSqKbUMUWS4Wl:-L6pCws1kIB-6KIuJ0fD:b-x47ls6) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L48)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Move Lock() to the beginning of this method, or it will not be thread safe.
</blockquote></details>

find() already has lock

---

*[event/dispatcher.go, line 55 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oOochg167eVUUqIrY:-L6pD6aSZDcr6L2zGaV2:b-jj1oet) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L55)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

I see that you handle the event in different go-routine. So, the order of listeners is not important, why not use map for better add/remove/get perf?
</blockquote></details>

listeners are supposed not too many. And we don't have a better key for listener

---

*[event/dispatcher.go, line 61 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oODeNMZsjIrSq8BNr:-L6pDUPYVCsFuHkGc4PZ:bwr81v0) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L61)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

As far as I know, interface (Listener) is pointer type, so it is unnecessary to use reflect to get the pointer value.
</blockquote></details>

It doesn't compare Listener, we only compare the Callable method

---

*[event/dispatcher_test.go, line 24 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oI77GFpwUJ6y0S1Xs:-L6pDn1hVXx5joaPu2My:b-v1vj00) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher_test.go#L24)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> handler.AddListener(listener1) //test duplicate add

do we need to add a function .Count() for handler and check for duplicated add here?
</blockquote></details>

I don't think we should export Count() for wrong usage

---

*[event/event.go, line 18 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oJtLCzKwiUIQHq-L_:-L6pE5L3fEQr5r_IepVW:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/event.go#L18)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

> //Callable
Whitespace
</blockquote></details>

Done.

---

*[event/event.go, line 19 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oKPzSPzfiBncxMiWl:-L6pFJ856V8aJJb6HYsE:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/event.go#L19)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Callable EventHandleMethod or just remove the type declaration of EventHandleMethod?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/56)*

**Comment by jessonzheng** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/56)*

**Comment by WTer** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/56)*

**Comment by boqiu** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[event/dispatcher.go, line 36 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oLeg3l14ij1J41u3A:-L6tBvck--HLjWVhlcuk:b2jv6lr) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L36)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

find() already has lock
</blockquote></details>

From the code's aspect of view, it's not thread-safe.

Suppose t1 and t2 add the same listener, which does not exist. Now, t1 and t2 yield after find() and before the lock(). So, both t1 and t2 will get index -1. Later, t1 and t2 resumed and execute the append() one by one. In the end, duplicate listeners will be added.

---

*[event/dispatcher.go, line 48 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oNaaWSqKbUMUWS4Wl:-L6tCs-Curatr8_Zs6tv:btmrxoq) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L48)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

find() already has lock
</blockquote></details>

Please refer to previous comment, that avoid duplicate listeners added.

---

*[event/dispatcher.go, line 55 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oOochg167eVUUqIrY:-L6tDdgd9UdnkrMBwxIh:b-j5nrs8) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L55)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

listeners are supposed not too many. And we don't have a better key for listener
</blockquote></details>

In fact, *Listener is a good key for map. Anyway, you could keep it as it is because of limited listeners

---

*[event/dispatcher.go, line 61 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oODeNMZsjIrSq8BNr:-L6tE27ECdL9mwLz3r8e:bul0gnh) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L61)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

It doesn't compare Listener, we only compare the Callable method
</blockquote></details>

Just double confirm, if listener l1 and l2 use the same method as Callalbe, what about the reflect.Valueof(l.Callable).Pointer() values between l1 and l2?
  - If not equals, then it's ok.
  - Otherwise, find(l2) may return the index of l1

Moreover, why not consider to AddListener(*Listener), and that it's easy to compare the listener pointer address.

---

*[event/dispatcher.go, line 72 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6tEc1IRQLbPAeuEhyn:-L6tEc1IRQLbPAeuEhyo:blw82r9) ([raw file](https://github.com/seeleteam/go-seele/blob/f3d8aac187529bd46dadd6c036a73178cfb5cdce/event/dispatcher.go#L72)):*
> ```Go
> 
> // NewEventHandler creates a new instance of event handler
> func NewEventHandler() *EventManager {
> ```

NewEventManager(), also please update the comment.

---

*[event/dispatcher_test.go, line 16 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6tFIqhhbl3TfCsJMhz:-L6tFIqhhbl3TfCsJMi-:b-3f2ibg) ([raw file](https://github.com/seeleteam/go-seele/blob/f3d8aac187529bd46dadd6c036a73178cfb5cdce/event/dispatcher_test.go#L16)):*
> ```Go
> func testfun1(e Event) { fmt.Println("hello-1") }
> 
> func Test_Handler(t *testing.T) {
> ```

Test_EventManager?

---

*[event/dispatcher_test.go, line 24 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6tFU8Ar9peWWk31hoy:-L6tFU8Ar9peWWk31hoz:blui7lb) ([raw file](https://github.com/seeleteam/go-seele/blob/f3d8aac187529bd46dadd6c036a73178cfb5cdce/event/dispatcher_test.go#L24)):*
> ```Go
> 	handler.AddListener(listener1)
> 	handler.AddListener(listener2)
> 	handler.AddListener(listener1) //test duplicate add
> ```

assert the listener count is 2 to verify the dup listener case.

---

*[event/dispatcher_test.go, line 27 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6tFaXxkBR7eoWyx4kk:-L6tFaXxkBR7eoWyx4kl:bt51epm) ([raw file](https://github.com/seeleteam/go-seele/blob/f3d8aac187529bd46dadd6c036a73178cfb5cdce/event/dispatcher_test.go#L27)):*
> ```Go
> 	event := EmptyEvent
> 	fmt.Println("test 1")
> 	handler.Fire(event)
> ```

assert something?

---

*[event/dispatcher_test.go, line 32 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6tFdOEnKcXlP6wEwdX:-L6tFdOEnKcXlP6wEwdY:bt51epm) ([raw file](https://github.com/seeleteam/go-seele/blob/f3d8aac187529bd46dadd6c036a73178cfb5cdce/event/dispatcher_test.go#L32)):*
> ```Go
> 
> 	fmt.Println("test 3")
> 	handler.Fire(event)
> ```

assert something?

---

*[event/dispatcher_test.go, line 49 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6tFjhn7x4eszwZfB0z:-L6tFjhn7x4eszwZfB1-:b-tsgf7x) ([raw file](https://github.com/seeleteam/go-seele/blob/f3d8aac187529bd46dadd6c036a73178cfb5cdce/event/dispatcher_test.go#L49)):*
> ```Go
> 	handler.Fire(EmptyEvent)
> 	fmt.Println("test 2")
> 	handler.Fire(EmptyEvent)
> ```

Please use assert instead of fmt.Println

---

*[event/event.go, line 8 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6tFqwpp5nr2Hrga3OF:-L6tFqwpp5nr2Hrga3OG:b-s0g61t) ([raw file](https://github.com/seeleteam/go-seele/blob/f3d8aac187529bd46dadd6c036a73178cfb5cdce/event/event.go#L8)):*
> ```Go
> package event
> 
> var EmptyEvent interface{}
> ```

Missed necessary comment for all exported types in this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/56)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[event/dispatcher.go, line 36 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oLeg3l14ij1J41u3A:-L6t_Yrc3c_kzgtfppdt:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L36)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

From the code's aspect of view, it's not thread-safe.

Suppose t1 and t2 add the same listener, which does not exist. Now, t1 and t2 yield after find() and before the lock(). So, both t1 and t2 will get index -1. Later, t1 and t2 resumed and execute the append() one by one. In the end, duplicate listeners will be added.
</blockquote></details>

Done.

---

*[event/dispatcher.go, line 48 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oNaaWSqKbUMUWS4Wl:-L6t__-LQFDUxiXcNlJE:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L48)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Please refer to previous comment, that avoid duplicate listeners added.
</blockquote></details>

Done.

---

*[event/dispatcher.go, line 61 at r1](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6oODeNMZsjIrSq8BNr:-L6tdcSNn7OYdnRKEKu8:banble4) ([raw file](https://github.com/seeleteam/go-seele/blob/b3896fc6b97b2aff07e4085c79179502ea7a9eb3/event/dispatcher.go#L61)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Just double confirm, if listener l1 and l2 use the same method as Callalbe, what about the reflect.Valueof(l.Callable).Pointer() values between l1 and l2?
  - If not equals, then it's ok.
  - Otherwise, find(l2) may return the index of l1

Moreover, why not consider to AddListener(*Listener), and that it's easy to compare the listener pointer address.
</blockquote></details>

I want to avoid the duplicate method call in listeners. We could refine it to *Listener check if we find it is not matched with our senario.

---

*[event/dispatcher.go, line 72 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6tEc1IRQLbPAeuEhyn:-L6teFltXi0cMx7aiPz_:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f3d8aac187529bd46dadd6c036a73178cfb5cdce/event/dispatcher.go#L72)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

NewEventManager(), also please update the comment.
</blockquote></details>

Done.

---

*[event/dispatcher_test.go, line 16 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6tFIqhhbl3TfCsJMhz:-L6teG_dfEeEGUdXsdQX:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f3d8aac187529bd46dadd6c036a73178cfb5cdce/event/dispatcher_test.go#L16)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Test_EventManager?
</blockquote></details>

Done.

---

*[event/dispatcher_test.go, line 24 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6tFU8Ar9peWWk31hoy:-L6teH55eXdgq5rFU5T1:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f3d8aac187529bd46dadd6c036a73178cfb5cdce/event/dispatcher_test.go#L24)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

assert the listener count is 2 to verify the dup listener case.
</blockquote></details>

Done.

---

*[event/dispatcher_test.go, line 27 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6tFaXxkBR7eoWyx4kk:-L6teI3-nE2a_O6jXbap:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f3d8aac187529bd46dadd6c036a73178cfb5cdce/event/dispatcher_test.go#L27)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

assert something?
</blockquote></details>

Done.

---

*[event/dispatcher_test.go, line 32 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6tFdOEnKcXlP6wEwdX:-L6teIblY2Hnq3tqYV67:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f3d8aac187529bd46dadd6c036a73178cfb5cdce/event/dispatcher_test.go#L32)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

assert something?
</blockquote></details>

Done.

---

*[event/dispatcher_test.go, line 49 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6tFjhn7x4eszwZfB0z:-L6teJDgjuYjOvVdYrrL:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f3d8aac187529bd46dadd6c036a73178cfb5cdce/event/dispatcher_test.go#L49)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Please use assert instead of fmt.Println
</blockquote></details>

Done.

---

*[event/event.go, line 8 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6tFqwpp5nr2Hrga3OF:-L6teXW2HJ4jv7NbkOYM:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f3d8aac187529bd46dadd6c036a73178cfb5cdce/event/event.go#L8)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

Missed necessary comment for all exported types in this file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/56)*

**Comment by lucusfly** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[event/dispatcher.go, line 72 at r2](https://reviewable.io:443/reviews/seeleteam/go-seele/56#-L6tEc1IRQLbPAeuEhyn:-L6uTkGhvF1UTXn7Ze8e:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/f3d8aac187529bd46dadd6c036a73178cfb5cdce/event/dispatcher.go#L72)):*
<details><summary><i>Previously, boqiu wrote…</i></summary><blockquote>

event handler still exists:)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/56)*

**Comment by boqiu** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seeleteam/go-seele/56)*

**Pull request merged**
