### PR TITLE
merge two config file to one config file 

### PR DESCRIPTION
**Pull request by ypenghui6**
The two config files have a duplicate content, merge and format

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/186)

### CODE REVIEW

**Comment by lucusfly** [comment]
better to check build and test before send your PR.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[cmd/node/config/node1.json, line 6 at r1](https://reviewable.io/reviews/seeleteam/go-seele/186#-LCnVm9i5N327DF3FqEU:-LCnVm9i5N327DF3FqEV:b1afabk) ([raw file](https://github.com/seeleteam/go-seele/blob/6c6eb8650e1657afecd7daa233c6af8a1006fb54/cmd/node/config/node1.json#L6)):*
> ```
> 127.0.0.1:55027
> ```
0.0.0.0:55027

---

*[cmd/node/config/node1.json, line 10 at r1](https://reviewable.io/reviews/seeleteam/go-seele/186#-LCnW1WR0V-Tj3fTTdTl:-LCnW1WR0V-Tj3fTTdTm:b-tgg11z) ([raw file](https://github.com/seeleteam/go-seele/blob/6c6eb8650e1657afecd7daa233c6af8a1006fb54/cmd/node/config/node1.json#L10)):*
> ```
> listenAddr
> ```
address

---

*[cmd/node/config/node1.json, line 21 at r1](https://reviewable.io/reviews/seeleteam/go-seele/186#-LCnW5f5AmfCVoPun_sS:-LCnW5f5AmfCVoPun_sT:b1eonoq) ([raw file](https://github.com/seeleteam/go-seele/blob/6c6eb8650e1657afecd7daa233c6af8a1006fb54/cmd/node/config/node1.json#L21)):*
> ```
> httpAddr
> ```
address

---

*[cmd/node/config/node1.json, line 22 at r1](https://reviewable.io/reviews/seeleteam/go-seele/186#-LCnWXDl52oT5L0GiL09:-LCnWXDl52oT5L0GiL0A:b-3p8ohh) ([raw file](https://github.com/seeleteam/go-seele/blob/6c6eb8650e1657afecd7daa233c6af8a1006fb54/cmd/node/config/node1.json#L22)):*
> ```
> httpCors
> ```
crosssorgins

---

*[cmd/node/config/node1.json, line 25 at r1](https://reviewable.io/reviews/seeleteam/go-seele/186#-LCnW7ie0OWw6pdSpbkW:-LCnW7ie0OWw6pdSpbkX:b-vk4ify) ([raw file](https://github.com/seeleteam/go-seele/blob/6c6eb8650e1657afecd7daa233c6af8a1006fb54/cmd/node/config/node1.json#L25)):*
> ```
> httpWhiteHost
> ```
whitehosts

---

*[node/config.go, line 25 at r1](https://reviewable.io/reviews/seeleteam/go-seele/186#-LCnXTXg7ZETFEU456Tb:-LCnXTXg7ZETFEU456Tc:bx15poh) ([raw file](https://github.com/seeleteam/go-seele/blob/6c6eb8650e1657afecd7daa233c6af8a1006fb54/node/config.go#L25)):*
> ```
> Log log.Config
> ```

`json:"log"`

---

*[node/config.go, line 31 at r1](https://reviewable.io/reviews/seeleteam/go-seele/186#-LCnXYUk8xWRDqq9UCpB:-LCnXYUk8xWRDqq9UCpC:b-by8ci1) ([raw file](https://github.com/seeleteam/go-seele/blob/6c6eb8650e1657afecd7daa233c6af8a1006fb54/node/config.go#L31)):*
> ```
> P2P p2p.Config
> ```

`json:"p2p"`

---

*[node/config.go, line 34 at r1](https://reviewable.io/reviews/seeleteam/go-seele/186#-LCnXNTiBFzGD2y5XPHn:-LCnXNTiBFzGD2y5XPHo:b-niq33p) ([raw file](https://github.com/seeleteam/go-seele/blob/6c6eb8650e1657afecd7daa233c6af8a1006fb54/node/config.go#L34)):*
> ```
> json:"HTTPServer"`
> ```

httpServer

---

*[node/config.go, line 73 at r1](https://reviewable.io/reviews/seeleteam/go-seele/186#-LCnXlIM3futpIm9ppBM:-LCnXlIM3futpIm9ppBN:b-vqw3v1) ([raw file](https://github.com/seeleteam/go-seele/blob/6c6eb8650e1657afecd7daa233c6af8a1006fb54/node/config.go#L73)):*
> ```Go
> 
> // GetConfigFromFile unmarshals the config from the given file
> func GetConfigFromFile(filepath string) (Config, error) {
> ```

add tests for these methods.

---

*[node/config.go, line 95 at r1](https://reviewable.io/reviews/seeleteam/go-seele/186#-LCnY1myBuuUz3u1yHRI:-LCnY1myBuuUz3u1yHRJ:b9ns4p5) ([raw file](https://github.com/seeleteam/go-seele/blob/6c6eb8650e1657afecd7daa233c6af8a1006fb54/node/config.go#L95)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
> 	nodeConfig := new(Config)
> 	nodeConfig.Basic.Name = config.Basic.Name
> 	nodeConfig.Basic.Version = config.Basic.Version
> 	nodeConfig.Basic.RPCAddr = config.Basic.RPCAddr
> 	nodeConfig.HTTPServer.HTTPAddr = config.HTTPServer.HTTPAddr
> 	nodeConfig.HTTPServer.HTTPCors = config.HTTPServer.HTTPCors
> 	nodeConfig.HTTPServer.HTTPWhiteHost = config.HTTPServer.HTTPWhiteHost
>  
> 	nodeConfig.P2P, err = GetP2pConfig(config)
> 	if err != nil {
> 		return nil, err
> 	}
> ```
</details>


remove

---

*[node/config.go, line 127 at r1](https://reviewable.io/reviews/seeleteam/go-seele/186#-LCnY7s9A1d9hBfBQZjy:-LCnY7s9A1d9hBfBQZjz:b-t6lb91) ([raw file](https://github.com/seeleteam/go-seele/blob/6c6eb8650e1657afecd7daa233c6af8a1006fb54/node/config.go#L127)):*
<details><summary><i alt="summary">Quoted 21 lines of code…</i></summary>

> ```
> 	p2pConfig := p2p.Config{}
>  
> 	if len(config.P2P.StaticNodes) != 0 {
> 		for _, id := range config.P2P.StaticNodes {
> 			n, err := discovery.NewNodeFromString(id)
> 			if err != nil {
> 				return p2p.Config{}, err
> 			}
>  
> 			p2pConfig.ResolveStaticNodes = append(p2pConfig.ResolveStaticNodes, n)
> 		}
> 	}
>  
> 	key, err := crypto.LoadECDSAFromString(config.P2P.ServerPrivateKey)
> 	if err != nil {
> 		return p2pConfig, err
> 	}
>  
> 	p2pConfig.PrivateKey = key
> 	p2pConfig.ListenAddr = config.P2P.ListenAddr
> 	return p2pConfig, nil
> ```
</details>



return config.P2P

---

*[p2p/server.go, line 83 at r1](https://reviewable.io/reviews/seeleteam/go-seele/186#-LCnY_Ae1oY783Y0FleB:-LCnY_Ae1oY783Y0FleC:b-kfoubs) ([raw file](https://github.com/seeleteam/go-seele/blob/6c6eb8650e1657afecd7daa233c6af8a1006fb54/p2p/server.go#L83)):*
> ```
> 	// ServerPrivateKey private key for p2p module, do not use it as any accounts
> 	ServerPrivateKey string `json:"serverPrivateKey"`
> ```

use PrivateKey above

---

*[p2p/server.go, line 89 at r1](https://reviewable.io/reviews/seeleteam/go-seele/186#-LCnYUCfESo5NCqhb48n:-LCnYUCfESo5NCqhb48o:b-1tdydo) ([raw file](https://github.com/seeleteam/go-seele/blob/6c6eb8650e1657afecd7daa233c6af8a1006fb54/p2p/server.go#L89)):*
> ```
>  
> 	// capacity of the transaction pool
> 	Capacity uint `json:"capacity"`
> ```

capacity seems is not a part of here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/186#-:-LCnYgoCA_z8-HsM81sp:b-1i8x7t)*

**Comment by WTer** [comment]
Review status: 0 of 11 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[cmd/node/config/node1.json, line 21 at r1](https://reviewable.io/reviews/seeleteam/go-seele/186#-LCoD_lJ7V7FErUoQq1R:-LCoD_lKDzSXipUK0YZg:b-ja021g) ([raw file](https://github.com/seeleteam/go-seele/blob/6c6eb8650e1657afecd7daa233c6af8a1006fb54/cmd/node/config/node1.json#L21)):*
> ```
> 127.0.0.1
> ```

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/186)*

**Comment by WTer** [comment]
Review status: 0 of 11 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[cmd/node/config/node2.json, line 6 at r1](https://reviewable.io/reviews/seeleteam/go-seele/186#-LCoDsss1qJq_YnwX9rw:-LCoDsss1qJq_YnwX9rx:bjm2379) ([raw file](https://github.com/seeleteam/go-seele/blob/6c6eb8650e1657afecd7daa233c6af8a1006fb54/cmd/node/config/node2.json#L6)):*
> ```
> 127.0.0.1
> ```
0.0.0.0?

---

*[cmd/node/config/node2.json, line 23 at r1](https://reviewable.io/reviews/seeleteam/go-seele/186#-LCoDwZX16vmCG1hoFhE:-LCoDwZYChF6XRSsgvLo:bjm2379) ([raw file](https://github.com/seeleteam/go-seele/blob/6c6eb8650e1657afecd7daa233c6af8a1006fb54/cmd/node/config/node2.json#L23)):*
> ```
> 127.0.0.1
> ```
0.0.0.0?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/186)*

**Comment by ypenghui6** [comment]
httpServer address is 127.0.0.1, and the other is 0.0.0.0

**Pull request closed without merging**
