### PR TITLE
add payload in tx

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/106)

### CODE REVIEW

**Comment by gongliaoan** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[core/types/transaction.go, line 18 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/106#-L9Dg7Do6l9TJ3OFkABj:-L9Dg7Do6l9TJ3OFkABk:bfgxrkc) ([raw file](https://github.com/seeleteam/go-seele/blob/92092dd4ee270a146b1810ea437608f80f685010/core/types/transaction.go#L18)):*
> ```Go
> 	"github.com/seeleteam/go-seele/merkle"
> )
> ```

ci failed，please check

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/106)*

**Comment by gongliaoan** [comment]
OK

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/106#-:-L9DgFJL4WPu2gj6FocO:b32w0x)*

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[core/types/transaction.go, line 18 at r1](https://beta.reviewable.io/reviews/seeleteam/go-seele/106#-L9Dg7Do6l9TJ3OFkABj:-L9DhwwH1VtE49frlAXP:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/92092dd4ee270a146b1810ea437608f80f685010/core/types/transaction.go#L18)):*
<details><summary><i>Previously, gongliaoan wrote…</i></summary><blockquote>

ci failed，please check
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/106)*

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[core/types/transaction.go, line 46 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/106#-L9E3Hio2fK24Bye5fx_:-L9E3Hio2fK24Bye5fxa:brl3wff) ([raw file](https://github.com/seeleteam/go-seele/blob/a9274b00f0c30db530d94b6ebda89c1327cc0d6b/core/types/transaction.go#L46)):*
> ```
> Payload      []byte
> ```
this big payload will dramatically increase the total size of txs data, can we split it from TransactionData and then store separately?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/106)*

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[core/types/transaction.go, line 80 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/106#-L9E3uJj1gZxYuJNRnpt:-L9E3uJj1gZxYuJNRnpu:b48060t) ([raw file](https://github.com/seeleteam/go-seele/blob/a9274b00f0c30db530d94b6ebda89c1327cc0d6b/core/types/transaction.go#L80)):*
> ```
> len(payload) > 0
> ```
also need to double check its size <= MaxPayloadSize

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/106)*

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[core/types/transaction_test.go, line 157 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/106#-L9E6P63E58znUi_97Td:-L9E6P63E58znUi_97Te:b-xoeq4j) ([raw file](https://github.com/seeleteam/go-seele/blob/a9274b00f0c30db530d94b6ebda89c1327cc0d6b/core/types/transaction_test.go#L157)):*
> ```
> NewMessageTransaction
> ```
I just think we need to valid the  parameters, if any of them invalid, the creation will be failed and never be stored.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/106)*

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[core/types/transaction.go, line 24 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/106#-L9E5ReJ-VZmR7Ii2F25:-L9EEnjbC_aYNsul0srJ:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a9274b00f0c30db530d94b6ebda89c1327cc0d6b/core/types/transaction.go#L24)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> errPayloadOversized
> ```
nice to sort these error names in alphabetical order
</blockquote></details>

Done.

---

*[core/types/transaction.go, line 46 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/106#-L9E3Hio2fK24Bye5fx_:-L9EAGBs5o3U3-OK2bML:boy0724) ([raw file](https://github.com/seeleteam/go-seele/blob/a9274b00f0c30db530d94b6ebda89c1327cc0d6b/core/types/transaction.go#L46)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> Payload      []byte
> ```
this big payload will dramatically increase the total size of txs data, can we split it from TransactionData and then store separately?
</blockquote></details>

We can control the payload store when save block in db (contract feature in next iteration), but it's unnecessary to split the payload out of tx data.

---

*[core/types/transaction.go, line 80 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/106#-L9E3uJj1gZxYuJNRnpt:-L9EEvJhBoRn2gCHMNen:b-4jkelj) ([raw file](https://github.com/seeleteam/go-seele/blob/a9274b00f0c30db530d94b6ebda89c1327cc0d6b/core/types/transaction.go#L80)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

customer can compress the payload,
if can we also add compression logic for this payload by introducing some extra parameter, such isCompression?

</blockquote></details>

1) checked the parameter payload length that <= MaxPayloadSize.
2) As for compression, will consider it when implement smart contract in the next iteration.

---

*[core/types/transaction_test.go, line 157 at r2](https://beta.reviewable.io/reviews/seeleteam/go-seele/106#-L9E6P63E58znUi_97Td:-L9EFG_E-75_tGLu5aMF:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/a9274b00f0c30db530d94b6ebda89c1327cc0d6b/core/types/transaction_test.go#L157)):*
<details><summary><i>Previously, WTer wrote…</i></summary><blockquote>

> ```
> NewMessageTransaction
> ```
I just think we need to valid the  parameters, if any of them invalid, the creation will be failed and never be stored.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/seeleteam/go-seele/106)*

**Pull request merged**
