### PR TITLE
add api 

### PR DESCRIPTION
**Pull request by ypenghui6**
1、add  api to set miner threads 
2、add api to set  coinbase

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/280)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ypenghui6, @WTer, @boqiu, and @lucusfly)

---

*[cmd/client/cmd/miner.go, line 59 at r1](https://reviewable.io/reviews/seeleteam/go-seele/280#-LEw44CH5MIs-j3zjHwu:-LEw44CI9ORydXiImsE_:b-s29veq) ([raw file](https://github.com/seeleteam/go-seele/blob/bc7c7166fab8b21299639e03b6da512af58c3824/cmd/client/cmd/miner.go#L59)):*
> ```Go
> 		} else if *threadsNum != 0 {
> 			if *threadsNum < 0 {
> 				fmt.Printf("miner threads number greater than zero: %d\n", *threadsNum)
> ```

invalid thread number %v, it should be greater than zero.

---

*[cmd/client/cmd/miner.go, line 63 at r1](https://reviewable.io/reviews/seeleteam/go-seele/280#-LEw4Hwd0nKcVG5bfXCs:-LEw4Hwd0nKcVG5bfXCt:b9y5g72) ([raw file](https://github.com/seeleteam/go-seele/blob/bc7c7166fab8b21299639e03b6da512af58c3824/cmd/client/cmd/miner.go#L63)):*
> ```Go
> 			}
> 			client.Call("miner.setThreads", &threadsNum, &result)
> 			fmt.Printf("miner set threads succeed")
> ```

succeed to set miner thread number

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/280)*

**Comment by WTer** [comment]
Review status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ypenghui6, @WTer, @boqiu, and @lucusfly)

---

*[cmd/client/cmd/miner.go, line 57 at r1](https://reviewable.io/reviews/seeleteam/go-seele/280#-LEw9G-A3RjK0bJBBZwp:-LEw9G-A3RjK0bJBBZwq:b-wv7lsf) ([raw file](https://github.com/seeleteam/go-seele/blob/bc7c7166fab8b21299639e03b6da512af58c3824/cmd/client/cmd/miner.go#L57)):*
> ```
> *threadsNum != 0
> ```
how about when *threadsNum  ==  0?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/280)*

**Comment by ypenghui6** [comment]
Review status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @boqiu, @WTer, and @lucusfly)

---

*[cmd/client/cmd/miner.go, line 57 at r1](https://reviewable.io/reviews/seeleteam/go-seele/280#-LEw9G-A3RjK0bJBBZwp:-LEx1pfd-QxC3kc6jSKK:b-ajspb6) ([raw file](https://github.com/seeleteam/go-seele/blob/bc7c7166fab8b21299639e03b6da512af58c3824/cmd/client/cmd/miner.go#L57)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> *threadsNum != 0
> ```
how about when *threadsNum  ==  0?
</blockquote></details>

OK, change another way to aviod it

---

*[cmd/client/cmd/miner.go, line 59 at r1](https://reviewable.io/reviews/seeleteam/go-seele/280#-LEw44CH5MIs-j3zjHwu:-LEwMVGtB8rrvk9s7wv9:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/bc7c7166fab8b21299639e03b6da512af58c3824/cmd/client/cmd/miner.go#L59)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

invalid thread number %v, it should be greater than zero.
</blockquote></details>

Done.

---

*[cmd/client/cmd/miner.go, line 63 at r1](https://reviewable.io/reviews/seeleteam/go-seele/280#-LEw4Hwd0nKcVG5bfXCs:-LEwMWdt2dR_72rArXwu:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/bc7c7166fab8b21299639e03b6da512af58c3824/cmd/client/cmd/miner.go#L63)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

succeed to set miner thread number
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/280)*

**Comment by boqiu** [comment]
Reviewed 1 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @WTer and @lucusfly)

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/280)*

**Comment by lucusfly** [comment]
Review status: all files reviewed, 4 unresolved discussions (waiting on @WTer and @ypenghui6)

---

*[cmd/client/cmd/cmddata.go, line 298 at r2](https://reviewable.io/reviews/seeleteam/go-seele/280#-LExC0Hx4zkRGQWSar81:-LExC0Hy9pHmfbfXOWHG:bxkr10s) ([raw file](https://github.com/seeleteam/go-seele/blob/14e060fc4caccceb37ac43e7fea55a052ab90866/cmd/client/cmd/cmddata.go#L298)):*
> ```
> client.exe setminerthreads --t 2
> ```

client.exe setminerthreads -t 2

same as coinbase

---

*[seele/api_miner.go, line 57 at r2](https://reviewable.io/reviews/seeleteam/go-seele/280#-LExCHIM8WQJsy-4L7W7:-LExCHIM8WQJsy-4L7W8:b-rtmml9) ([raw file](https://github.com/seeleteam/go-seele/blob/14e060fc4caccceb37ac43e7fea55a052ab90866/seele/api_miner.go#L57)):*
> ```Go
> // SetThreads  API is used to set the number of threads.
> func (api *PrivateMinerAPI) SetThreads(threads *int, result *string) error {
> 	if *threads <= 0 {
> ```

threads could be zero. that means use full cores.

---

*[seele/api_miner.go, line 62 at r2](https://reviewable.io/reviews/seeleteam/go-seele/280#-LExCT_rAI7KAGgjiNB7:-LExCT_rAI7KAGgjiNB8:b-lwniwn) ([raw file](https://github.com/seeleteam/go-seele/blob/14e060fc4caccceb37ac43e7fea55a052ab90866/seele/api_miner.go#L62)):*
> ```
> *result = "succeed to set miner thread number"
> ```

this is wired. use Handler in Request to do it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/280)*

**Comment by lucusfly** [comment]
Reviewed 1 of 3 files at r1, 1 of 3 files at r2, 3 of 3 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/280)*

**Pull request merged**
