### PR TITLE
fix bugs in miner

### PR DESCRIPTION
**Pull request by sufay**
fixes:
1. as prepareNewBlock may cause an error, exception checking is necessary before changing the state of isFirstBlockPrepared. 
2. a stopped flag is used to prevent newTxCallback from invoking prepareNewBlock when the miner is stopped or unstarted
3. add the wg field. when closing a multithreading procedure, we should wait for all threads to terminate. otherwise, there exist unstable factors for a long running system.

modify some comments.

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/161)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---

*[miner/miner.go, line 48 at r1](https://reviewable.io/reviews/seeleteam/go-seele/161#-LCCxn5b76EooqWW9mP5:-LCCxn5c77tdqXhenLkA:b-nn17kg) ([raw file](https://github.com/seeleteam/go-seele/blob/36656e53159e4e8d02359dad300f8dcfba0d7721/miner/miner.go#L48)):*
> ```Go
> 	mining   int32
> 	canStart int32
> 	stopped  int32
> ```

what is stopped used for, any difference between mining and stopped?

---

*[miner/miner.go, line 250 at r1](https://reviewable.io/reviews/seeleteam/go-seele/161#-LCCyoO9CDhEAiYYqxAX:-LCCyoO9CDhEAiYYqxAY:bb4wpyx) ([raw file](https://github.com/seeleteam/go-seele/blob/36656e53159e4e8d02359dad300f8dcfba0d7721/miner/miner.go#L250)):*
> ```Go
> 		miner.log.Warn(err.Error())
> 		atomic.StoreInt32(&miner.mining, 0)
> 		return err
> ```

If error returned, then suggest to move the error handling to caller method.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/161)*

**Comment by boqiu** [comment]
Review status: 0 of 22 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[miner/miner.go, line 250 at r1](https://reviewable.io/reviews/seeleteam/go-seele/161#-LCCyoO9CDhEAiYYqxAX:-LCDeGyU3KuClj6feYCH:bwf6u48) ([raw file](https://github.com/seeleteam/go-seele/blob/36656e53159e4e8d02359dad300f8dcfba0d7721/miner/miner.go#L250)):*
<details><summary><i>Previously, sufay wrote…</i></summary><blockquote>

Done.
</blockquote></details>

did not see your change, please double confirm.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/161)*

**Comment by lucusfly** [comment]
Review status: 0 of 22 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[miner/miner.go, line 109 at r1](https://reviewable.io/reviews/seeleteam/go-seele/161#-LCD2c_a39opwRa8faIH:-LCDjwPE5z2j3bdBpymr:bdp1yvs) ([raw file](https://github.com/seeleteam/go-seele/blob/36656e53159e4e8d02359dad300f8dcfba0d7721/miner/miner.go#L109)):*
<details><summary><i>Previously, sufay wrote…</i></summary><blockquote>

i think it can go on, because prepareNewBlock can be triggered by external new tx events.
</blockquote></details>

If prepareNewBlock return error, we should restart it again, because we allow miner to generate empty block. Stop and wait for next tx events will reduce miner's reward.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/161)*

**Comment by sufay** [comment]
Review status: 0 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[miner/miner.go, line 109 at r1](https://reviewable.io/reviews/seeleteam/go-seele/161#-LCD2c_a39opwRa8faIH:-LCDxDP6DR2Ph9WdWSJ-:b9u8bhs) ([raw file](https://github.com/seeleteam/go-seele/blob/36656e53159e4e8d02359dad300f8dcfba0d7721/miner/miner.go#L109)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

If prepareNewBlock return error, we should restart it again, because we allow miner to generate empty block. Stop and wait for next tx events will reduce miner's reward.
</blockquote></details>

yes, it 's up to client's logic.  a client can restart it by its own way. if miner itself restarts, an infinite loop can happen

---

*[miner/miner.go, line 250 at r1](https://reviewable.io/reviews/seeleteam/go-seele/161#-LCCyoO9CDhEAiYYqxAX:-LCDx9d24ZEeZSty_sQl:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/36656e53159e4e8d02359dad300f8dcfba0d7721/miner/miner.go#L250)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

did not see your change, please double confirm.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/161)*

**Comment by lucusfly** [comment]
Review status: 0 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[miner/miner.go, line 109 at r1](https://reviewable.io/reviews/seeleteam/go-seele/161#-LCD2c_a39opwRa8faIH:-LCJJ_rLE3gxZNmY9Ylt:b-hmm6nu) ([raw file](https://github.com/seeleteam/go-seele/blob/36656e53159e4e8d02359dad300f8dcfba0d7721/miner/miner.go#L109)):*
<details><summary><i>Previously, sufay wrote…</i></summary><blockquote>

yes, it 's up to client's logic.  a client can restart it by its own way. if miner itself restarts, an infinite loop can happen
</blockquote></details>

a client may not know when to restart when we got error. And miner need infinite loop to keep mining.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/161)*

**Comment by sufay** [comment]
Review status: 0 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[miner/miner.go, line 109 at r1](https://reviewable.io/reviews/seeleteam/go-seele/161#-LCD2c_a39opwRa8faIH:-LCNeuFs1l3ZVlS1JETk:b-3opm4i) ([raw file](https://github.com/seeleteam/go-seele/blob/36656e53159e4e8d02359dad300f8dcfba0d7721/miner/miner.go#L109)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

a client may not know when to restart when we got error. And miner need infinite loop to keep mining.
</blockquote></details>

lucusfly,  the client can get the miner state by keeping track of miner.IsMining . maybe it's better to stay long running by an external watcher when a system level error can occur. in miner, a key failure is caused by statedb.GetCopy which is actually a fatal error .

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/161)*

**Comment by boqiu** [comment]
Reviewed 18 of 22 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/161)*

**Comment by lucusfly** [comment]
Reviewed 18 of 22 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/161)*

**Pull request merged**
