### PR TITLE
merge p2p.Config and p2p.P2PConfig

### PR DESCRIPTION
**Pull request by ypenghui6**
1、merge p2p.Config and p2p.P2PConfig  to p2p.Config
2、add Node's UnmarshalText function, to unmarsh p2p.Config.StaticNodes

---
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/212)

### CODE REVIEW

**Comment by boqiu** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[cmd/node/cmd/config.go, line 12 at r2](https://reviewable.io/reviews/seeleteam/go-seele/212#-LDLACSHChMkiEEHqjKC:-LDLACSHChMkiEEHqjKD:bxsmjsv) ([raw file](https://github.com/seeleteam/go-seele/blob/588d7603b7dd52f5d6dc047eb7aa8e4da540e8d1/cmd/node/cmd/config.go#L12)):*
> ```Go
> 	"io/ioutil"
> 	"path/filepath"
> ```

remove the blank line, and go-plugin will help to format the order of imported namespaces automatically.

---

*[p2p/discovery/node.go, line 130 at r2](https://reviewable.io/reviews/seeleteam/go-seele/212#-LDLB2eT5_kxvR4G66-F:-LDLB2eT5_kxvR4G66-G:b-4emtj1) ([raw file](https://github.com/seeleteam/go-seele/blob/588d7603b7dd52f5d6dc047eb7aa8e4da540e8d1/p2p/discovery/node.go#L130)):*
> ```Go
> }
> 
> func (node *Node) UnmarshalText(json []byte) error {
> ```

only "UnmarshalText" for Node struct? Where is "MarshalText"?

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/212)*

**Comment by ypenghui6** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/node/cmd/config.go, line 12 at r2](https://reviewable.io/reviews/seeleteam/go-seele/212#-LDLACSHChMkiEEHqjKC:-LDLDRWgDC7S6-oYwmcC:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/588d7603b7dd52f5d6dc047eb7aa8e4da540e8d1/cmd/node/cmd/config.go#L12)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

remove the blank line, and go-plugin will help to format the order of imported namespaces automatically.
</blockquote></details>

Done.

---

*[p2p/discovery/node.go, line 130 at r2](https://reviewable.io/reviews/seeleteam/go-seele/212#-LDLB2eT5_kxvR4G66-F:-LDLCWevBCmeC5Ccf5kk:b8ikiv1) ([raw file](https://github.com/seeleteam/go-seele/blob/588d7603b7dd52f5d6dc047eb7aa8e4da540e8d1/p2p/discovery/node.go#L130)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

only "UnmarshalText" for Node struct? Where is "MarshalText"?
</blockquote></details>

it receive a string

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/212)*

**Comment by boqiu** [comment]
Reviewed 1 of 8 files at r1.
Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/212)*

**Comment by ypenghui6** [comment]
Reviewed 2 of 8 files at r1, 2 of 5 files at r3, 1 of 1 files at r4.
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/node/cmd/config.go, line 112 at r4](https://reviewable.io/reviews/seeleteam/go-seele/212#-LDLOmLk15p9plSBz3CY:-LDLdHkV76cl8PQWW0xc:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2f50ac4e718c8c08ed2c0ca56c5d053dda234afd/cmd/node/cmd/config.go#L112)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> 	if cmdConfig.P2PConfig.PrivateKey != nil {
> 		return cmdConfig.P2PConfig.PrivateKey, nil
> 	}
>  
> ```

remove this check as you already check it outside.
</blockquote></details>

Done.

---

*[cmd/node/cmd/config_test.go, line 29 at r4](https://reviewable.io/reviews/seeleteam/go-seele/212#-LDLNAHJ7Lw_fPJwGuSw:-LDL_q_F7DUn8d14qaQ0:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2f50ac4e718c8c08ed2c0ca56c5d053dda234afd/cmd/node/cmd/config_test.go#L29)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> .ListenAddr, 
> ```

assert.Equal(t, len(config.P2PConfig.StaticNodes), 1)
assert.Equal(t, config.P2PConfig.StaticNodes[0].IP, "")
assert.Equal(t, config.P2PConfig.StaticNodes[0].Port, "")
</blockquote></details>

Done.

---

*[p2p/discovery/node.go, line 137 at r4](https://reviewable.io/reviews/seeleteam/go-seele/212#-LDLO2_u3chS1nRdio3c:-LDL_s4r0xsDC641xZdO:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2f50ac4e718c8c08ed2c0ca56c5d053dda234afd/p2p/discovery/node.go#L137)):*
<details><summary><i>Previously, lucusfly (lucus) wrote…</i></summary><blockquote>

> ```
> 	node.ID = n.ID
> 	node.IP = n.IP
> 	node.UDPPort = n.UDPPort
> 	node.Shard = n.Shard
> 	node.sha = n.sha
> ```

*node = *n
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/212)*

**Comment by ypenghui6** [comment]
Reviewed 2 of 2 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/212)*

**Comment by ypenghui6** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/node/cmd/config.go, line 112 at r4](https://reviewable.io/reviews/seeleteam/go-seele/212#-LDLOmLk15p9plSBz3CY:-LDLsN0tCyXfujiBbS49:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2f50ac4e718c8c08ed2c0ca56c5d053dda234afd/cmd/node/cmd/config.go#L112)):*
<details><summary><i>Previously, ypenghui6 (ypenghui6) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[cmd/node/cmd/config_test.go, line 29 at r4](https://reviewable.io/reviews/seeleteam/go-seele/212#-LDLNAHJ7Lw_fPJwGuSw:-LDLsKzl-GPddOEka4n0:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2f50ac4e718c8c08ed2c0ca56c5d053dda234afd/cmd/node/cmd/config_test.go#L29)):*
<details><summary><i>Previously, ypenghui6 (ypenghui6) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[p2p/discovery/node.go, line 137 at r4](https://reviewable.io/reviews/seeleteam/go-seele/212#-LDLO2_u3chS1nRdio3c:-LDLsMIX6aH3XOXQnwCP:b-896fix) ([raw file](https://github.com/seeleteam/go-seele/blob/2f50ac4e718c8c08ed2c0ca56c5d053dda234afd/p2p/discovery/node.go#L137)):*
<details><summary><i>Previously, ypenghui6 (ypenghui6) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/go-seele/212)*

**Pull request merged**
